### ISSUE TITLE
Graceful shutdown gotcha

### ISSUE THREAD

**Issue by tkazec** [amir20/phantomjs-node#153]
Sending `SIGTERM` to any process requiring phantom will kill it, whether or not it's caught in the main code. This seems to be a direct result of #121 and #122: phantom catches the signal and calls `process.exit()`.

I can work around this by calling `process.removeAllListeners("SIGTERM")` and then adding my listener, but it's not something I expected. Would be nice to have this either fixed or documented.

**Comment by amir20** [comment]
In the new version I don't kill anything. I wait until until phantom shuts down gracefully.
