### ISSUE TITLE
How can I set the DPI of captured screen JPEG image?

### ISSUE THREAD

**Issue by subhash-daffodil** [amir20/phantomjs-node#194]
Hi All,
I'm using phantomjs-node for generate images of webpage but all images are generating with 72 DPI which is a good quality for web but not a good quality for printing

I have tried with page.set('paperSize',{dpi:150}); but images generated with same 72 default DPI.

Please help if any one knows.
Thanks in Advance.
Subhash

**Comment by amir20** [comment]
This should be working now.
