### ISSUE TITLE
phantomjs processes left laying around

### ISSUE THREAD

**Issue by cottrelld** [amir20/phantomjs-node#198]
Sometimes when rendering pages, if the phantomjs process takes a long time to render for any reason or the user clicks away, the phantomjs process stays lying around, consuming file descriptors.  If you kill that process, it then brings down the whole node process.  

I call ph.exit() upon page rendering, and as long as everything is ok the process gets cleaned up, but the left over processes are an issue.  Is there any way to handle this case?

Thanks!

**Comment by dlykissas** [comment]
@kalvinarts Does this work? I really like phantom.js for node.js and I am using it. But I have a huge issue with shim.js running after everything is supposed to have terminated. It hogs between 98% and 99% CPU of my small VPS. Also, can you explain your code a bit for me? Especially what 'cb' does.

**Comment by kalvinarts** [comment]
I don't really know anything about how phantomjs works internally... my code symply kills the real phantoms process behind phantoms-node.

cb is a callback you can pass to my function wich is passed to the exec. When exec ends running the kill command calls the callback.

(http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback)[You can read the child_process exec documentation here]

**Comment by MartijnR** [comment]
Am experiencing the same issue. Am running small node-commander app every hour as a cron job. One phantomjs/shim.js process keeps running at 100% CPU load.

**Comment by conrado** [comment]
:+1:

**Comment by dchrostowski** [comment]
I seem to be experiencing the same thing, and wanted to offer some insight.  It appears that when using phantomjs-node quite heavily, I'm left with a few rogue phantomjs processes. 
```
$ ps aux | grep phantomjs
dan      19781  0.0  1.0 1635460 44316 ?       Sl   03:09   0:00 phantomjs --proxy=http://120.195.203.33:80 /home/dan/mfeddie_dev/node_modules/phantom/shim.js 52835 127.0.0.1
dan      20784  0.0  1.0 1635448 43544 ?       Sl   04:11   0:00 phantomjs --proxy=http://58.246.96.211:8080 /home/dan/mfeddie_dev/node_modules/phantom/shim.js 34301 127.0.0.1
dan      23936  0.0  1.0 1635648 44984 ?       Sl   04:17   0:00 phantomjs --proxy=http://109.196.127.35:8888 /home/dan/mfeddie_dev/node_modules/phantom/shim.js 43639 127.0.0.1
dan      24931  0.0  1.0 1635688 44944 ?       Sl   03:18   0:00 phantomjs --proxy=http://120.195.199.49:80 /home/dan/mfeddie_dev/node_modules/phantom/shim.js 41298 127.0.0.1
dan      26511 97.8  5.6 2059748 230360 ?      Rl   03:21  76:47 phantomjs --proxy=http://54.167.134.138:3128 /home/dan/mfeddie_dev/node_modules/phantom/shim.js 33692 127.0.0.1
dan      27213  0.0  1.0 1635524 44728 ?       Sl   04:23   0:00 phantomjs --proxy=http://120.195.207.54:80 /home/dan/mfeddie_dev/node_modules/phantom/shim.js 36941 127.0.0.1
dan      27504  0.0  1.1 1635564 45644 ?       Sl   03:23   0:00 phantomjs --proxy=http://97.77.104.22:80 /home/dan/mfeddie_dev/node_modules/phantom/shim.js 43210 127.0.0.1
dan      30345  4.6  1.9 1836140 80752 ?       Sl   04:29   0:28 phantomjs --proxy=http://178.23.150.58:8080 /home/dan/mfeddie_dev/node_modules/phantom/shim.js 59835 127.0.0.1
```
Let this go on long enough and you've got a memory leak that is wreaking havoc on your system until it finally crashes your machine.  As a quick and dirty fix, I just used a cron job that executed `pkill phantomjs` every few hours.  This was effective, but would cause whatever headless crawl jobs running at the time to die.

So I tried doing what @kalvinarts  suggested; simply manually killing the phantom process with a system call.  But I still got rogue processes.  What the hell is going on here?  I started logging the phantomjs pid every time I called `phantom.create()`, `ph.exit()` and/or `exec('kill '+ph.process.pid', cb)`.  After checking the logs, I discovered that the rogue pids did not match up with the ones that I logged. Some of these phantomjs procs had managed to escape my wrath.

Some further research led to me typing in this useful command into my shell:
```
$ ps -eo pid,ppid,command,etime | grep phantom
19781     1 phantomjs --proxy=http://12    01:42:59
20784     1 phantomjs --proxy=http://58       41:15
23936     1 phantomjs --proxy=http://10       34:51
24931     1 phantomjs --proxy=http://12    01:33:40
26511     1 phantomjs --proxy=http://54    01:30:40
27213     1 phantomjs --proxy=http://12       28:24
27504     1 phantomjs --proxy=http://97    01:28:35
30345     1 phantomjs --proxy=http://17       22:25
30624 16786 grep --color=auto phantom         00:00
```

This displays the `process id`, `parent process id`, `command`, and `elapsed time` of the rogue phantomjs processes.  Notice that the `parent pid` is 1.  According to [this] (https://www.win.tue.nl/~aeb/linux/lk/lk-10.html#ss10.1), having a parent pid of 1 on UNIX systems indicates that this process was orphaned.  So I guess phantomjs spawns child procs?  

I need to investigate further, but I just wanted to put this out there.  Maybe it will be helpful to someone.

**Comment by kalvinarts** [comment]
As I said, I don't have any idea how pantomjs works internally, and I gave up on it some time ago using other solutions.

Here we are dealing with some kind of zombie process and 'kill' command by default sends TERM signal wich can be blocked if the program handles it.

Maybe using KILL signal instead wich can't be blocked will make the hack.

UNTESTED:
```coffeescript
exec = require('child_process').exec

terminatePH = (ph, cb) ->
    ph.exit()
    exec 'kill -KILL '+ph.process.pid, cb
```
I don't have time to take a look at phantomjs code but it might be with taking a look on how phantomjs handles system signals.

**Comment by dchrostowski** [comment]
Well I tried kill -9 too, but still got rogue procs.  I was logging the pid on `create()` and `exec('kill....`.  Everything that was created was also killed.  But there are PhantomJS procs which I never "created".  These will either show a parent pid of 1 (if nodejs was terminated) or the nodejs process itself.

Looking at the process tree, I think a PhantomJS process spawns 8 threads (maybe?).  I was wondering if it's possible for one of these child threads becomes orphaned and then get treated as a process.  I'm no expert on UNIX processes and threads, but I think that's one possible explanation.

 I would say that this is most likely a PhantomJS problem, but I could be wrong.  I don't have much time to read over the PhantomJS code either.  Here's my new hacky fix:

1. Keep track of phantom pids in a global array by adding and removing pids at `create()` and `exit()`
2. Parse stdout from `exec(ps -eo uid,ppid,pid,command | grep phantomjs)`
3. For each phantom pid, check its parent pid against the nodejs pid. (To make sure we're targeting the correct phantomjs procs.)
4. Kill with extreme prejudice if a parsed pid is not in the global array.
5. Maybe check phantom's parent pid against 1 in case of nodejs crashing and restarting.

I'll follow up with my results.

**Comment by amir20** [comment]
This shouldn't happen anymore with v2 if you call `phantom.exit()`. In all my testing, everything was cleaned up.

**Comment by Unf-Sander** [comment]
Using v2.1.1, problem still occurs. There are a couple of phantomjs processes laying around. (phantom.exit() is being called)

**Comment by strengthening** [comment]
I tried  phantom.exit() phantom.kill() . Using v2.1.1 ,the phantomjs processes haven't disappear as usual..

**Comment by amir20** [comment]
Can you show the code @strengthening? Something that is simple and that I can locally. It might be worth trying to debug with `DEBUG=true` to see if PID is missing. We really got to fix this. I just can't reproduce it.

**Comment by alexrockt** [comment]
I've the same problem (PhantomJS 2.1.1 on a BananaPi) but I also can't reproduce it. The script works fine for days and suddenly my server is crashing due to memory issues. 

This is my script, runs every 5 minutes via cron. I was using it on a Raspberry Pi before with a precompiled PhantomJS binary that worked for over one year straight without any problems. For the BananaPi I had to compile the binary myself, which might be the reason, but sometimes there are no problems for 1-2 weeks, but then suddenly no processes are killed.

```javascript

var page = require('webpage').create();

page.viewportSize = {
	width: 1280,
	height: 2000
};

page.clipRect = {
	top: 0,
	left: 0,
	width: 1280,
	height: 2000
};

d = new Date();
dMonth = d.getMonth()+1;
dDate = d.getDate();
dYear = d.getFullYear();

dHour = d.getHours() < 10 ? "0" + d.getHours() : d.getHours();
dMinutes = d.getMinutes() < 10 ? "0" + d.getMinutes() : d.getMinutes();

df = dYear + '-' + dMonth + '-' + dDate + '-' +dHour + '-' + dMinutes;

page.open('SOME_URL', function() {
  page.render('/root/tools/screenshots/'+df+'.png');
  page.close();
  phantom.exit();
});

```

**Comment by Treeeater** [comment]
I have the same problem as everyone else here had. I am using phantomjs 2.1.1, also can't reproduce the problem consistently. For me however I use 100 workers, each opens up a phantomjs page and then closes it after page loads or 4 minutes, whichever comes first. 

After 2 hours of execution, I found 47 zombie processes, with ppid of 1. The 'non-zombie processes' have a correct ppid of its parent node process. 

Unfortunately I cannot post my code due to certain reasons, so this may not be very helpful, but I can verify that the zombie process is indeed a problem that the owner may want to look deeper into.

**Comment by ClickerMonkey** [comment]
The current work around I'm using is to set a maximum execution time on the process. In my tests this has killed lingering processes. I'm using PhantomJS for PDF generation and if the PDF isn't generated in X minutes I kill the process. I get rogue processes when a user closes the tab where the PDF is being generated.

```javascript
var MAXIMUM_EXECUTION_TIME = 5 * 60 * 1000;
setTimeout(function() {
  phantom.exit();
}, MAXIMUM_EXECUTION_TIME);
```
