### ISSUE TITLE
Node-Webkit support

### ISSUE THREAD

**Issue by acicali** [amir20/phantomjs-node#200]
I was able to successfully use this module while testing with Node, but it consistently crashes under Node-Webkit.  I know this is not phantomjs-node-webkit, but it would be great if it also worked with Node-Webkit.

**Comment by TrejGun** [comment]
+1

**Comment by amir20** [comment]
Hi @TrejGu, @KalenAnson and @acicali. What isn't exactly working? 

I did 

```html
<!DOCTYPE html>
<html>

<head>
  <title>Hello World!</title>
</head>

<body>
  <h1>Loading stackoverflow screenshot...</h1>
  <script>
    var phantom = require('phantom');
    phantom.create().then(function(ph) {
      ph.createPage().then(function(page) {
        page.open('https://stackoverflow.com/').then(function(status) {
          console.log(status);
          page.renderBase64('PNG').then(function(data) {
            var image = new Image();
            image.src = 'data:image/png;base64,' + data;
            document.body.innerHTML = '';
            document.body.appendChild(image);
          });
          page.close();
          ph.exit();
        });
      });
    });
  </script>

</body>

</html>
```

with `nw` and it has worked every time.  Is this something that was fixed on version 2.0.0-alpha?

**Comment by amir20** [comment]
Can I close this since no one has expressed any interest?

**Comment by KalenAnson** [comment]
I say shoot it

**Comment by amir20** [comment]
OK, above it shows that it does work when I try it with `node-webkit`. If someone finds a specific bug then let's reopen.
