### ISSUE TITLE
Optional host/interface to go along with the port.

### ISSUE THREAD

**Issue by jawsome** [amir20/phantomjs-node#205]
It appears that the port is the only value accepted. I'd like to be able to specify which host it's listening on. 

https://github.com/sgentle/phantomjs-node/blob/master/phantom.js#L16
I think, this is it:
```
  startPhantomProcess = function(binary, port, args) {
    return spawn(binary, args.concat([__dirname + '/shim.js', port]));
  };

```

**Comment by amir20** [comment]
`2.0.0-alpha` doesn't use sockets anymore. So closing.
