### ISSUE TITLE
how is onConfirm handled?

### ISSUE THREAD

**Issue by reinpk** [amir20/phantomjs-node#216]
in order to confirm/cancel a confirmation popup, the function set to phantomjs's `onConfirm` needs to return true: http://phantomjs.org/api/webpage/handler/on-confirm.html

supposedly this is handled in:
+ node-phantom: https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#onconfirm
+ phantom-proxy: https://github.com/sheebz/phantom-proxy#special-events

i've tried passing in functions that `return true;` to `phantom` but the confirm return value is always `false` on the page.

how is the onConfirm return value handled with `phantom`? is there a way to `return true` to the confirm event?

**Comment by amir20** [comment]
Closing because this is really old.

**Comment by FernandoGOT** [comment]
Did someone resolved this problem?
i saw that there is [onConfirm](http://phantomjs.org/api/webpage/handler/on-confirm.html) but show to use it?
