### ISSUE TITLE
I got an TypeError: Cannot read property '_session' of null

### ISSUE THREAD

**Issue by VanMess** [amir20/phantomjs-node#222]
I had get an error like this:

e:\Projects\cuckoo\node_modules\phantom\node_modules\shoe\index.js:10
        var _didTimeout = stream._session.didTimeout
                                ^
TypeError: Cannot read property '_session' of null
    at Server.handler (e:\Projects\cuckoo\node_modules\phantom\node_modules\shoe\index.js:10:33)
    at Server.EventEmitter.emit (events.js:95:17)
    at App.emit (e:\Projects\cuckoo\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\sockjs.js:182:27)
    at Session.emit_open (e:\Projects\cuckoo\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\transport.js:107:23)
    at process._tickCallback (node.js:415:13)

This exception would occur after a short time when I start my server application to load and some performance test , so do you have any clue about this? Wait your response online , TKS.

**Comment by frankred** [comment]
Same with me:

```
[ 'TypeError: Cannot read property \'_session\' of null',
     '    at Server.handler (C:\\workspace-js\\cme-content-crawler-suppilo-nodejs\\node_modules\\phantom\\node_modules\\shoe\\index.js:10:33)',
     '    at Server.emit (events.js:107:17)',
     '    at App.emit (C:\\workspace-js\\cme-content-crawler-suppilo-nodejs\\node_modules\\phantom\\node_modules\\shoe\\node_modules\\sockjs\\lib\\sockjs.js:182:27)',
     '    at Session.emit_open (C:\\workspace-js\\cme-content-crawler-suppilo-nodejs\\node_modules\\phantom\\node_modules\\shoe\\node_modules\\sockjs\\lib\\transport.js:107:23)',
     '    at process._tickCallback (node.js:355:11)' ]
```

**Comment by amir20** [comment]
Gonna close this in favor of the new version. If it's still broken, reopen and I can probably get you a fix.
