### ISSUE TITLE
Provide a way to stop the child process

### ISSUE THREAD

**Issue by callumlocke** [amir20/phantomjs-node#225]
If I do `ph.process.kill()`, it breaks [this assertion](https://github.com/sgentle/phantomjs-node/blob/d81a65b4d315a8833fd7a3749b4072d4c9fd55ae/phantom.coffee#L90):

```coffee
console.assert not signal?, "signal killed phantomjs: #{signal}"
```

I know the child process automatically gets killed when my process exits, but sometimes I want to exit it manually.

**Comment by JakubSK** [comment]
process is undefined on my ph object...

**Comment by tdj-br** [comment]
Hi, if you define a callback onExit when creating the phantom, it will not quit the main process.

  phantom.create(phantomCallback, {onExit: fnExit});
