### ISSUE TITLE
Sometimes shim.js is left running, hogs CPU time

### ISSUE THREAD

**Issue by dlykissas** [amir20/phantomjs-node#239]
My code runs phantom.js via this node.js script every 2 minutes, does some stuff and then exits ["ph.exit()"]. Problem is that sometimes "shim.js" is left running, and using up to 99% of CPU time as exposed by "ps -eo pcpu,pid,user,args | sort -k1 -r | head -10" and various other tools. Now I have seen another similar issue open here ("phantomjs processes left laying around #198"), but since it does not mention "shim.js" by name, I thought I should open a new one.

**Comment by sdimkov** [comment]
+1 on this issue. I also experience it.

**Comment by amir20** [comment]
I haven't seen this error happen. In fact I stress tested and it looks like no instances are left behind.
