### ISSUE TITLE
Proxy is being ignored

### ISSUE THREAD

**Issue by benzmuircroft** [amir20/phantomjs-node#246]
var phantom = require('../node_modules/phantom');
    phantom.create(function(browser){
        browser.createPage(function(page){
            browser.set('proxy','98.239.198.83:21320');
            browser.setProxy('98.239.198.83','21320','http', null, null, function(){
                page.open('http://example.com/req.php', function() {
                     //I save php $_SERVER to a text pad
                     });});});});

I still see my own ip as the REMOTE_ADDR header, the proxy is not used.

Here are more ways that I have tried: http://stackoverflow.com/questions/28571601/how-do-i-set-proxy-in-phantomjs

**Comment by rodrigogs** [comment]
+1

**Comment by huyvn** [comment]
You can try adding the proxy in parameters when starting phantom
```
phantom.create({
    parameters: {
        proxy: 'your proxy'
    }
}, function(browser) {
    ...
}
```

**Comment by pelallemant** [comment]
+1 for huyvn, it should solve your problem. I used a proxy with phantomjs few days ago, and it's not `{ proxy }` but `{ parameters: proxy }` so your syntax should have been `browser.set('settings.proxy')`.

But you can't change the proxy once the page is created, so `browser.set('proxy','98.239.198.83:21320'); ` nor `browser.set('settings.proxy','98.239.198.83:21320');` won't work. You have to specify it in the phantom.create call.

**Comment by rodrigogs** [comment]
KUDOS for huyvn! It works.

Anyway... It's very bad documented.

**Comment by voidmonk** [comment]
Can't get the proper `setProxy` call to work. @amir20 has #214 been released?

Both `phantom.setProxy(....)` and `instance.setProxy(....)` throw an error: `setProxy is not a function`

**Comment by amir20** [comment]
Yes it was merged. There are test cases so you can take a look to see how it is used.

**Comment by voidmonk** [comment]
@amir20 Thanks, I had a look at the `setProxy` test in [page_spec.js](https://github.com/amir20/phantomjs-node/blob/master/src/spec/page_spec.js#L574), but unfortunately it doesn't look explanatory.

Phantomjs seems to allow proxy use in two ways: 1) `--proxy:host:port` switch with `--proxy-auth:username:password` switch, or 2) `phantom.setProxy(host, port, type, username, password)` call.

The test case has `page.setProxy('host:port')` which is not consistent and also unclear about how to specify other parameters (type, username, password).
