### ISSUE TITLE
Second page.evaluate is slow

### ISSUE THREAD

**Issue by johntitus** [amir20/phantomjs-node#248]
I was investigating an [issue](https://github.com/segmentio/nightmare/issues/123) for another project, and I believe there is a problem with either phantomjs-node, or PhantomJS itself, when multiple page.evaluates are called.

I've created a [gist](https://gist.github.com/johntitus/8bb14c69f89e5241057f) with some demonstration code.

If you execute the file with `DEBUG=phantom node file.js`, you should see something like this:

```
opened github?  success
  phantom starting evaluate +0ms
  phantom back from evaluate +4ms
  phantom sending letter m +1ms
  phantom done with letter m +0ms
  phantom sending letter y +1ms
  phantom done with letter y +0ms
  phantom sending letter u +1ms
  phantom done with letter u +0ms
  phantom sending letter s +0ms
  phantom done with letter s +1ms
  phantom sending letter e +0ms
  phantom done with letter e +1ms
  phantom sending letter r +0ms
  phantom done with letter r +1ms
  phantom sending letter n +0ms
  phantom done with letter n +1ms
  phantom sending letter a +1ms
  phantom done with letter a +1ms
  phantom sending letter m +0ms
  phantom done with letter m +1ms
  phantom sending letter e +1ms
  phantom done with letter e +0ms
  phantom starting evaluate +0ms
  phantom back from evaluate +22s  <-- called before second 'type' starts
  phantom sending letter m +1ms
  phantom done with letter m +0ms
  phantom sending letter y +0ms
  phantom done with letter y +2ms
  phantom sending letter p +0ms
  phantom done with letter p +0ms
  phantom sending letter a +0ms
  phantom done with letter a +1ms
  phantom sending letter s +0ms
  phantom done with letter s +0ms
  phantom sending letter s +0ms
  phantom done with letter s +0ms
  phantom sending letter w +1ms
  phantom done with letter w +0ms
  phantom sending letter o +0ms
  phantom done with letter o +0ms
  phantom sending letter r +0ms
  phantom done with letter r +1ms
  phantom sending letter d +0ms
  phantom done with letter d +0ms
  phantom rendering screenshot +1ms
  phantom done rendering +0ms
```

I'm not sure how to test is this is due to phantomjs-node, or PhantomJS itself.

Specs for me: (However, this issue has been reported by multiple people)
phantomjs-node: 0.7.2,
phantomjs --version = 2.0.1 (but happened with the 1.9x line of PhantomJS too)
Ubuntu linux

**Comment by johntitus** [comment]
I created a pure PhantomJS script to mimic the above, and it doesn't have the same slowdown issue.

https://gist.github.com/johntitus/1cbdaa5f0f3a9afbe35f

**Comment by johntitus** [comment]
After going down the rabbit hole, it looks like it's an issue with shoe.  Shoe calls sock.js, which has an option called `heartbeat_delay` which defaults to 25000 ms, but is configurable. However, shoe doesn't expose option.

If I change the default `heartbeat_delay` to 200 ms, the above test works just fine.

I'm not sure if shoe is supported anymore, as it looks like the last update was over 2 years ago.  There is an open [pull request](https://github.com/substack/shoe/pull/19) which might resolve this issue.

It may be faster to just fork shoe and enable that pull request.

**Comment by trsrm** [comment]
This issue still exists.

**Comment by amir20** [comment]
Should be fixed now.
