### ISSUE TITLE
Wrong path for injectJs()

### ISSUE THREAD

**Issue by roadhump** [amir20/phantomjs-node#260]
I have file structure similar to 
```
- lib
-- inject
--- inject.js
-- scrape.js
- app.js
```

Then I call

app.js
```
var scrape = require('./lib/scrape');
```

scrape.js
```
page.injectJs('./inject/inject.js');
```

And it doesn't work. It works only if I set path to `inject.js` from root, that seems totally non-intuitive

scrape.js
```
page.injectJs('./lib/inject/inject.js');
```

**Comment by amir20** [comment]
This makes sense why it doesn't work. All of this is passed to phantomjs via command line. You should use `__dirname` when you can.
