### ISSUE TITLE
Using aws lambda

### ISSUE THREAD

**Issue by Tarang** [amir20/phantomjs-node#276]
AWS Lambda doesn't allow port binding (from https://forums.aws.amazon.com/thread.jspa?messageID=597671).

While I can't get a specific error from Lambda, are there options that can work on Lambda?

It is possible to bind to `/tmp` using a unix pipe. Can this module work with this somehow?

**Comment by whiteadam** [comment]
+1 Might not make total sense, but I'm interested in this too. Triggering tests on a "serverless" infra would be sweet.

**Comment by wonderdogone** [comment]
+1, and raised my eyebrows

**Comment by amir20** [comment]
2.0.0-alpha doesn't use sockets anymore. Everything is communicated over pipes.
