### ISSUE TITLE
stdout optional console message

### ISSUE THREAD

**Issue by Tarang** [amir20/phantomjs-node#283]
https://github.com/sgentle/phantomjs-node/blob/master/phantom.js#L124

Is it possible to make the above line run optionally? It would help clean up logs should it not be wanted.

Would be ok creating a pull request if the idea if welcomed.

**Comment by amir20** [comment]
Pull requests are welcomed!  I prefer some kind of logging solution to tune and filter log levels instead though. 

Sent via my iPhone

**Comment by Tarang** [comment]
@amir20 Perhaps for this a default 'login hook' may do? By default its set to a method to stream it to `console.log`, on the other hand it can be changed to something else that can tune and filter via a hook of some sort:

page.onstdout = function() ....

**Comment by amir20** [comment]
In `2.0.0-alpha`, I added a new logging hook.
