### ISSUE TITLE
page.render() callback provides no error information on failure

### ISSUE THREAD

**Issue by noah-sis** [amir20/phantomjs-node#290]
I tried running page.render() to save a page to a .pdf document, and all is fine and good if it succeeds. However, I tried writing to a read-only directory (just to test my error handling), and there was no hint of a failure within the code. The callback passed to render() was called with no arguments, exactly as it would have been called if the file write had been successful. Here's what the code looks like:

```
page.render(".../some/file.pdf", function(arg){
	if(!arg){
		console.log("File was successfully saved as a PDF");
		// ...
	}
}
```

Regardless of whether or not the file is created, I always see "File was successfully saved as a PDF" in the console.

For now, I can check to make sure that the file is written after render() finishes, but is there any way to get a "status" argument (like page.open() has) for the page.render() method?

Node v0.12.1
phantomjs-node 0.7.2

Thanks in advance for your help and great work on this fantastic tool!

**Comment by FelixAkk** [comment]
+1

On example case to produce this, is specifying a output render path with a filename extension ot her than `.pdf`. Simply omitting the extension will even crash it.

**Comment by amir20** [comment]
I have changed this behavior to make it more clear. You can do `catch()` from promise.
