### ISSUE TITLE
Crash @ efinancialcareers.com

### ISSUE THREAD

**Issue by aaawtest** [amir20/phantomjs-node#295]
The following NodeJS script crashes on Ubuntu 14.04.2 LTS 64-bit. The same script runs fine on Mac OS X with same phantomjs and node versions. Any help is much appreciated. Thanks in advance!

phantomjs: 2.0.1-development
node: v0.12.6

NodeJS Script:

```
var phantom = require('phantom');
var url ='http://efinancialcareers.com'
phantom.create(function (ph) {
  ph.createPage(function (page) {
    page.open(url, function (status) {
      console.log(status)
    })
  })
})
```

Crash message: (Dump file: https://goo.gl/adNmoh )
```
phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at
<http://phantomjs.org/crash-reporting.html> and file a bug report at
<https://github.com/ariya/phantomjs/issues/new>.
Please attach the crash dump file:
  /tmp/00c01522-9fb8-1d61-4ae2d788-14dc532c.dmp


assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: signal killed phantomjs: SIGSEGV
    at Console.assert (console.js:106:23)
    at ChildProcess.<anonymous> (/home/user/tmp/tmp/repro/node_modules/phantom/phantom.js:152:21)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

**Comment by Maskime** [comment]
Hi,

I'm having the same issue.
Just to confirm that we have the same problem, did you try to launch phantomjs alone ?
when I do I get :
```$ phantomjs
[1]    90175 killed     phantomjs```
I suspect that you are using a pre-build version and not one that was compilated from the source ?

**Comment by aaawtest** [comment]
Hi @Maskime,

I did build phantomjs from source following the steps at http://phantomjs.org/build.html

Running phantomjs standalone works fine without any problem. It just crashes for the case I mentioned above.

**Comment by felixcrive** [comment]
Hi, I am having the same issue with a webpage

Debug: internal, implementation, error 
    AssertionError: signal killed phantomjs: SIGSEGV
    at Console.assert (console.js:87:23)
    at ChildProcess.<anonymous> (/Users/fcguerrero/Public/work/MakeMyDeal/sherlock/node_modules/phantom/phantom.js:165:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)


Is this a known issue ? Thanks.

**Comment by nachomunoz** [comment]
also interested in this issue

**Comment by amir20** [comment]
Is this still an issue?
