### ISSUE TITLE
Add childFramesCount and childFramesName

### ISSUE THREAD

**Issue by rclai** [amir20/phantomjs-node#297]
Add more frame-related shims [here](https://github.com/sgentle/phantomjs-node/blob/120559bb051578f07316d5ee552fc702a1885073/shim.coffee#L72) like `childFramesCount` and `childFramesName`.

I'd like a way to check whether the frame index or name is valid before diving into the frame the same way CasperJS does [here](https://github.com/n1k0/casperjs/blob/376d85fceb5eca63596e12e2ef6072a72422ed9b/modules/casper.js#L2359-L2365).

**Comment by rclai** [comment]
Shouldn't this be a `request` rather than a `question`?

**Comment by amir20** [comment]
Should work with `page.property('childFramesCount')`
