### ISSUE TITLE
Is there a drawback to always pass weak = false for `dnodeOpts`?

### ISSUE THREAD

**Issue by jiahaog** [amir20/phantomjs-node#318]
I've noticed that for windows, it is advised to pass the following as an argument to `phantom.create`

```javascript
{
  dnodeOpts: {
    weak: false
}
```

Is there any drawback to passing that as an argument to phantom.create all the time, even on darwin and linux systems?

**Comment by jazzzz** [comment]
Actually, I found out that due to a leak in dnode, Phantomjs-node leaks less with `weak = false ` in `dnodeOpts` (see substack/dnode#179).

**Comment by jiahaog** [comment]
Hmm, so wouldn't it be better to set `weak = false` all the time by default in Phantomjs-node so that windows users do not have to go through the additional overhead of setting that?

**Comment by amir20** [comment]
Could someone test the new version with windows?

**Comment by amir20** [comment]
It works on windows. I tried it last night.
