### ISSUE TITLE
phantom.create with {"port": 12345} return null ph oncallback

### ISSUE THREAD

**Issue by berytung** [amir20/phantomjs-node#342]
phantom.create("--web-security=no", "--ignore-ssl-errors=yes", {"port": 12345}, function (ph) {
    ph.createPage(function (page) {
       ^
TypeError: Cannot call method 'createPage' of null

This code worked yesterday, and this morning suddenly give an error. Anyone has same problem?

**Comment by amir20** [comment]
This was fixed with v1 a while back I think. Should be fixed now with 2.0.0-alpha also.
