### ISSUE TITLE
page.open failure, no callback launched

### ISSUE THREAD

**Issue by pelallemant** [amir20/phantomjs-node#343]
Hi,

When I request some webpage, it happens sometimes (rarely) that page.open(url, callback); doesn't call callback, and in the shell we have written: "phantomjs stdout: Syntax Error: Parse error".

It may occur when the page isn't received entirely.

Best regards.

**Comment by katrotz** [comment]
Same here, the page open callback is not called phantomjs-node@0.8.4, phantomjs@1.9.19

**Comment by amir20** [comment]
Try with 2.0.0-alpha
