### ISSUE TITLE
several page loaded at the same time

### ISSUE THREAD

**Issue by pelallemant** [amir20/phantomjs-node#344]
Hi.

If we open several pages at the same time, the callbacks are executer totally randomly. Sometimes I have 10 callback executed, sometimes 2, sometimes 8 then 1. 

Best regards.

**Comment by amir20** [comment]
Hey @pelallemant,

This is a known bug. Unfortunately, there hasn't been a solution. I haven't digged through the code but I believe there is something wrong with the callbacks.

**Comment by SgtPooki** [comment]
I am seeing this as well in a scenario where I continuously execute the same page after x time until the page is done doing it's loading stuff. (Is there a better way to handle this..?)

Right now, i'm solving the issue by wrapping the page.execute in a function(let's call it wrapper) that is re-called inside my debounced callback(lets call it callback) if the page isn't done reloading.

**Comment by amir20** [comment]
Can you try 2.0.0-alpha

**Comment by amir20** [comment]
I tried this and it looks to be fixed.
