### ISSUE TITLE
Add support of Phantom 2.0.0

### ISSUE THREAD

**Issue by slavaparfenov** [amir20/phantomjs-node#345]
getting this error using simple script from readme

```
phantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.
```

no errors with Phantom 1.9.8 using the same script

**Comment by dmmmdfll** [comment]
I just got that same error.  [The error is related to ajax it seems.](http://stackoverflow.com/questions/15913170/phantom-js-synchronous-ajax-request-network-err-xmlhttprequest-exception-101)

I no longer got the error with 

    options = { 'web-security': 'no'};
    phantom.create({parameters: options}, function() {};

**Comment by nathanmarks** [comment]
@dmmmdfll did it work with 1.9.8?

**Comment by dmmmdfll** [comment]
@nathanmarks Yes. I had the expected result in 1.9.8. It seems it was purely related to web security.

**Comment by nathanmarks** [comment]
What exactly were you trying with 2.0.0? I'm using this module with v2 right now.

**Comment by thoop** [comment]
It seems like it's only newer compiled versions of 2.0 that are having this issue. I'm using and older compile of v2 as well and it works fine. I'm trying to see if I can figure out what's going on here too.

**Comment by dmmmdfll** [comment]
@nathanmarks If I do not set web-security to no then phantom.create (ph) -> throws an error:
    
    hantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.


    phantom stdout:   file:///home/ubuntu/js/nodejs-equalizer/node_modules/phantom/shim.js:7608 in send
    file:///home/ubuntu/js/nodejs-equalizer/node_modules/phantom/shim.js:7608 in _start
    file:///home/ubuntu/js/nodejs-equalizer/node_modules/phantom/shim.js:7635

This works as expected:

    Phantom = require 'phantom'
    parameters = {
        parameters: {
            'web-security': 'no',
            'load-images': 'no',
            'local-to-remote-url-access': 'yes',
            'ignore-ssl-errors': 'yes',
            'proxy': '10.0.1.235:8118',
        }
    }
    ph = null
    phantom.create parameters, (_ph) ->
      ph = _ph
      ph.exit()

**Comment by amir20** [comment]
After doing some debugging, I am pretty convinced that this is related to opening a dnode server so that the client can communicate. I am thinking of rewriting and not use dnode. But I haven't found anything else.

**Comment by thoop** [comment]
Defaulting to web-security=no is pretty insecure :(

**Comment by amir20** [comment]
Yea except phantom node doesn't work without it. So until I figure how to communicate between processes without dnode, this will have to do as a hack. :/

Sent via my iPhone

**Comment by amir20** [comment]
Support added with the new version.
