### ISSUE TITLE
phantom stdout: SyntaxError: Parse error

### ISSUE THREAD

**Issue by zhuyingda** [amir20/phantomjs-node#346]
I have the PhantomJs 1.9.8 and I write this code to run 'phantom' module:

var phantom = require('phantom');

phantom.create(function (ph) {
    ph.createPage(function (page) {
        page.onResourceRequested(
            function(requestData, request) { request.abort(); },
            function(requestData) { console.log(requestData.url) }
        );
        page.open("http://www.google.com", function (status) {
            console.log("opened  ", status);
            page.evaluate(function () { return document.title; }, function (result) {
                console.log('Page title is ' + result);
                //ph.exit();
            });
        });
    });
});

but I got a lot of  " phantom stdout: SyntaxError: Parse error ".
I run the phantomjs to do something like this, it works fine.

**Comment by amir20** [comment]
Going to close this since I just published `2.0.0-alpha`. Please try again. Reopen a new ticket with new version.
