### ISSUE TITLE
scrollPosition not scrolling

### ISSUE THREAD

**Issue by antolovich** [amir20/phantomjs-node#347]
A couple months ago I created a script that scrolled through an infinite scroll script.  Today, I started working on the project that used it before, but the `page.set('scrollPosition')` function no longer modifies the scroll position.  A section of my code is listed below. When I used it last, it worked flawlessly; however, now when I run the script, it no longer scrolls the page. It gets stuck in an infinite loop and `scrollHeight` remains the same initial page pixel height.  If the page cannot be scrolled (meaning there are no more entries than are shown on the page), the script exits just fine.

When I test this manually in my browser, the page scrolls properly. When I reach the end of the infinite scroll, no more DOM elements have the .moreToScroll class, so it doesn't seem to be a problem with the logic of using the querySelector as the turnary condition.

I'm using phantom v2.0.0, phantomjs-node v0.8.3, node v0.12.4.

```
var async = require('async');
var scrollHeight;
async.doWhilst(
	function(cb) {
		page.evaluate(function() {
			return document.querySelector('.moreToScroll') ? document.body.scrollHeight : 0;
		}, function(result) {
                        scrollHeight = result;
			page.set('scrollPosition', {
				top: scrollHeight,
				left: 0
			}, function() {
				setTimeout(function() {
					cb();
				}, 1000);
			});
		});
	},
	function() {
		return !!scrollHeight;
	},
	function() {
		page.evaluate(function() {
				return document.querySelectorAll('.entry').length;
			},
			function(result) {
				console.log(result);
			});
	});

**Comment by amir20** [comment]
Is this still a bug?

**Comment by amir20** [comment]
No response from owner so closing...

**Comment by antolovich** [comment]
Yes, this is still an issue with version 0.8.3.  I am currently changing my code to work with the new 2.0.0 that you released today, and will test it out and see if it still a problem.

**Comment by amir20** [comment]
OK let me know! I should be able to help you more with this version. Since I wrote it, I understand a lot better what is needed.

**Comment by antolovich** [comment]
I am still having the same issue using v2.0.0.  Here is the updated section of my code to work with v2.0.0:

```
var scrollHeight;

async.doWhilst(

	function(innerCB) {

		page.evaluate(function() {
				return document.querySelector('.has-more-items') ? document.body.scrollHeight : 0;
			})
			.then(function(result) {

				scrollHeight = result;
				
				console.log('Scrolling ' + scrollHeight + 'px');

				page.property(
						'scrollPosition', {
							top: scrollHeight,
							left: 0
						})
					.then(function() {
						setTimeout(function() {
							innerCB();
						}, 1000);
					});
			});
	},
	function() {
		return scrollHeight;
	},
	function(err, result) {

		page.evaluate(function() {
				var something = 'evaluate DOM';
				return something;

			})
			.then(function(result) {
				console.log(result);
			});

	});
```

**Comment by amir20** [comment]
Just curious, does this work with `phantomjs` directly?

**Comment by antolovich** [comment]
I have never worked directly with `phantomjs`.  I do know that sometime in the last couple months of 2015 that it worked correctly.  I put the project on hold until mid-January, and when I started working on it again it no longer worked.  I can try working with `phantomjs` directly and seeing if it still works later this week.

**Comment by amir20** [comment]
If you can get me a `phantomjs` script that works, then I can make sure to figure out why it doesn't work. This could be a bug with phantomjs and nothing to do with this package. I can't tell until we try it with both.

**Comment by antolovich** [comment]
Sounds good.  I'll report back with the results that i get from using `phantomjs` directly

**Comment by antolovich** [comment]
I wrote up a phantom script, and unfortunately it does not work.  Looks like this may be a problem with phantom itself.

**Comment by antolovich** [comment]
Not an issue with phantomjs-node

**Comment by amir20** [comment]
That's unfortunate. :( Thanks for the update. Glad to hear `phantomjs-node` works.

**Comment by shiguofu2012** [comment]
I have the same problem ,I donot know how to scroll to the bottom of the page.

**Comment by mike-aungsan** [comment]
@shiguofu2012 did you get it working? I just start using phantom a few days ago. Trying to scroll to the bottom but has no luck..

**Comment by antolovich** [comment]
@mike-aungsan 

I ended up using jQuery inside the evaluate instead of using the built in `scrollPosition`. 

```
var height =  $("selector").height();
`$("selector").scrollTop(height);`
```

The selectors you use depend on what DOM element you want to get the height of, and what DOM element does the actual scrolling.

**Comment by mike-aungsan** [comment]
Many Thanks.
