### ISSUE TITLE
How to use it with phantomjs 2.0?

### ISSUE THREAD

**Issue by abhilashsajeev** [amir20/phantomjs-node#349]
I would like to use phantomjs 2.0 insted of phantom 1.9.8. Is it possible with current version?

**Comment by dmmmdfll** [comment]
@abhilashsajeev Yes. It is possible. See [this issue](https://github.com/sgentle/phantomjs-node/issues/345) for possible caveats.

**Comment by abhilashsajeev** [comment]
I am trying to use it with node.

in options adding 'phantomPath':require('phantomjs2.0').path
shows unsupported parameter.
How should I point local instance to ```phantom.create``` function

**Comment by dmmmdfll** [comment]
@abhilashsajeev Use the binary parameter and pass the path to the phatnomjs 2.0.0 binary:

    # coffeescript
    phantom.create binary: '/path/to/phantomjs2', (ph) ->

    // javascript
    (function() {
      phantom.create({
        binary: '/path/to/phantomjs2'
      }, function(ph) {});

    }).call(this);

**Comment by abhilashsajeev** [comment]
I have removed global installation of phantomjs 1.9.8 and used the binary command.
now it shows this error
```
phantomjs-node: You don't have 'phantomjs' installed
```

**Comment by dmmmdfll** [comment]
Then the value you passed for the binary parameter is probably not a path to phantomjs. Replace the `'/path/to/phantomjs'` with the path to your ❝custom package phantomjs2.0❞.

**Comment by dmmmdfll** [comment]
Check my code [here](https://gist.github.com/dmmmdfll/dcaa99040717e8b5a405) where I have two different paths to two different versions of phantomjs.

**Comment by abhilashsajeev** [comment]
@dmmmdfll Sorry Man. That was another error caused by some unwanted return statement in my code. But your suggestion binary: //path name. Helped me so much now I am able to run phantomjs2.0. Cheers. It would be nice to include the parameters in the documentation. 
Thank you very much for speedy reply.

**Comment by dmmmdfll** [comment]
You're welcome. Glad I could help. I struggled for a while with that one, too.

**Comment by dmmmdfll** [comment]
Do you have to include the '--web-security=no' parameter like I do on my setup?

**Comment by abhilashsajeev** [comment]
I have used that already in my config. 
It would be great help if you could update this in the documenation. 
:smile:

**Comment by dmmmdfll** [comment]
I would like to contribute. What is the best way to contribute? I am rather new the contribution process.

Are you referring to the [PhantomJS documentation](http://phantomjs.org/api/) or to the [phantomjs-node documentation](https://github.com/sgentle/phantomjs-node)?

**Comment by abhilashsajeev** [comment]
https://github.com/sgentle/phantomjs-node

**Comment by amir20** [comment]
This should be fixed now.
