### ISSUE TITLE
Transfer of repository to Amir's account

### ISSUE THREAD

**Issue by sgentle** [amir20/phantomjs-node#351]
Hi all,

I figured I would document this publicly in case anyone gets curious. As is hopefully obvious I haven't really touched this project since 2013, when Amir kindly offered to take over. Since then he's been working tirelessly to maintain the project while it sat under my GitHub account, completely ignored by me.

So really, this project has been Amir's for a long time, and I'm much happier knowing it is attached to his name in recognition of all the work he's done. Maintaining a project is not easy, and Amir's done a great job.

Thanks, Amir!

**Comment by amir20** [comment]
Thanks Sam! There is a little clean up I need to do. But so people have had some great pull requests.
