### ISSUE TITLE
Running within a Docker container

### ISSUE THREAD

**Issue by PaulTondeur** [amir20/phantomjs-node#353]
When running phantom within a docker container I get the following error:

```
NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests
```

When running this directly on my machine or when running phantomjs directly (within a Docker container) I won't get this error. It turns out that I have to create a phantomjs instance with disabled web security:

```
phantom.create(callback,{parameters:{'web-security':'no'}})
```

I don't know why I have to configure phantom this way while in a Docker container, but it took me quite some hours to figure out. 

I'm reporting here in the hope this will save others time in the future and maybe to get a reply by someone who knows why this happens as I don't think it is a bug with this project.

**Comment by jordancrawfordnz** [comment]
I'm having the exact same issue. I didn't used to get this on my local install but since upgrading my local phantomJS to the latest version it also happens on my machine too (outside of Docker).

The page I'm loading doesn't seem to have any security errors in the Chrome dev console so I'm not sure why this happens in the first place.

**Comment by jordancrawfordnz** [comment]
https://github.com/amir20/phantomjs-node/issues/345 Seems to just be related to the new version.

**Comment by amir20** [comment]
I had the same problem too. It made me go crazy but I had to add `--web-security=no`. I really want to know how to fix it because it has been on my mind for a while now!

**Comment by PaulTondeur** [comment]
Thanks for the reply and linking to the other issue.

I tried out several versions in the 2.x series, but they all had this same problem while running within a Docker container. Locally I have the same versions installed on my mac and everything seems to work fine without the `--web-security=no` argument.
