### ISSUE TITLE
Adopt phantomjs-prebuilt

### ISSUE THREAD

**Issue by cdaniel** [amir20/phantomjs-node#355]
Phantomjs now has a node wrapper that installs platform specific libraries if they are not present.

It would be awesome to make phantomjs-node use those libraries as it would completely remove the need of manually installing phantomjs.

**Comment by mastayoda** [comment]
+1 for this. It will be great if there is not need to have phantomjs installed already. phantmjs-prebuild is awesome, it should be easy to just point this module to that binary(i.e. include it as a dependent module)

**Comment by amir20** [comment]
Agreed. If you look at package.json there is  ` "phantomjs": "~1.9.7-5"` in `devDependencies`. So it's already there. It's just a matter of moving to just `dependencies`. @cdaniel want to issue a pull request?

**Comment by amir20** [comment]
Looks like the bin path needs to be changed to `phantomjs.path`. If you make that change then that would be great. Otherwise, I have been doing a lot of work on this package. I should be able to get it in later this week.

**Comment by cdaniel** [comment]
I've created a pull request, although apparently not in this bug https://github.com/amir20/phantomjs-node/pull/357
