### ISSUE TITLE
Unable to render one page after first one got closed

### ISSUE THREAD

**Issue by janober** [amir20/phantomjs-node#361]
Hi,

just gave the new version (2.0.0-alpha.1) a spin and I am somehow totally unable to render a page after the first one got closed.

So I want to use the same PhantomJS instance and render multiple pages with it. But somehow after one page got closed I am unable to create another page. Here a simple example:

```
var phantom = require('phantom');

phantom.create().then(function(ph) {

  console.log('Render first');
  ph.createPage().then(function(page) {
    page.open('https://stackoverflow.com/').then(function(status) {
      console.log('done1: ' + status);
      page.close();
    });
  });

  setTimeout(function() {
    console.log('Render second');
    ph.createPage().then(function(page) {
      page.open('https://stackoverflow.com/').then(function(status) {
        console.log('done2: ' + status);
        page.close();
        ph.exit();
      });
    });
  }, 3000);

});
```

Output will be:
```
Render first
done1: success
Render second
```
and then it simply sits there. Any idea what is going on there?

**Comment by amir20** [comment]
This makes sense. I only allow one page instance per process. Short term solution would be to not call `page.close()`. 

Now for the real bug. According to the documentation, `page.close()` cleans up memory. It sounded optional to dispose the page. 

I can fix this by creating a new page per session. Do you think that your use case is common?

**Comment by janober** [comment]
Ah interesting, in the old version I always did it that way.

I am not sure if I understand correctly. So I should not be able to open multiple pages at the same time?

I would have expected that it is a common usecase. I use PhantomJS to create a screenshot of the page and parse its content. Each node-instance is supposed to open only one PhantomJS instance (to save resources) but multiple pages at the same time.
So what I should do is to actually open multiple PhantomJS instances at the same time with one page each?

**Comment by amir20** [comment]
I think the use case I had in mind was `phantom.create()` -> `createPage()` -> `do one task` -> `phantom.exit()`. 

I want to keep it consistent with phantom. So what is the right way to do it? Is the phantom way to open multiple page with one instance? If so, I am willing to make that change. 

My only concern is performance. PhantomJS can process only ONE message at any given time.  So multithread with the same instance won't work. That's why I wanted to keep the above design. An example could be, if one page is opening a new page, then the second page cannot do any tasks until the first page has returned the callback to client. 

If you think the above is still safe, I can issue a pull request to allow multiple page instances.

**Comment by janober** [comment]
To be honest I do not know that much about PhantomJS and how it works or should work. For me it was simply important to get many pages crawled fast with as less resources as possible. So I use very small instances (512 MB RAM with 1 core). Always multiples pages get crawl at once because it take always anyway a while to return the page in which I can already process the result of the previous one. So I always have 3-5 open at the same time.

Sorry, not sure if I understand the multithread issue. If I open 5 pages at the same time and the 5th loads faster than the previous 4 I would not be able to get the source code or create a screenshot of the 5th till I processed the other ones first?

**Comment by amir20** [comment]
Ah I see then. You are doing crawling. In that case, you should definitely spin new instances of phantom to do your crawling. Creating phantom instances is cheap. 

The problem with the new version is that it can process only one message at one time.  The old version used sockets so it could handle more. But it wasn't efficient and didn't work in cluster. 

For now, just spin up multiple instances per thread. It will be faster and safer.

**Comment by janober** [comment]
Ah great thanks a lot for that information!

Had actually multiple PhantomJS instances before and just changed it to a single one a week ago. So I guess I then simply reverse that ;-)

So from my side this issue can be changed unless other people have the same problem for better reasons.

**Comment by amir20** [comment]
I think I'll fix it so that you can do `page.close()` and then open a new `page`. That seems to be a bug. But for your use case, it won't improve performance.

**Comment by amir20** [comment]
Bug should be fixed now. This is the new output I get:

```
$ node bug.js 
Render first
done1: success
Render second
done2: success
```

In regards to performance, you should probably still spin new instances of phantom. 

And as always, thanks for trying the new version!

**Comment by janober** [comment]
Wow thanks that was fast! I changed my code already to use different phantom instances.

Thanks for the great support and creating that great module in the first place!
