### ISSUE TITLE
Use this with mocha-phantomjs

### ISSUE THREAD

**Issue by dschinkel** [amir20/phantomjs-node#364]
Does it make sense to use this bridge WITH another middleware like mocha-phantomjs?  Or is mocha-phantomjs another bridge as well?

**Comment by amir20** [comment]
I am not too familiar with `mocha-phantomjs` so I don't know what you would do with it.

**Comment by amir20** [comment]
This package is a node client. So you would write javascript code in a file. ie.

```
var phantom = require('phantom');

phantom.create().then(function(ph) {
  ph.createPage().then(function(page) {
    page.open('https://stackoverflow.com/').then(function(status) {
      console.log(status);
      page.property('content').then(function(content) {
        console.log(content);
        page.close();
        ph.exit();
      });
    });
  });
});
```
and run it with `node example.js`. This package is not a command line tools.

**Comment by dschinkel** [comment]
what do you mean by "node client"?  it's a bridge right?  when you run it with node example.js you are able to run mocha tests around the code above too?  and then see those tests results in the terminal?  Like can I wrap that code above into a test is what I'm asking

**Comment by amir20** [comment]
Yes it is a bridge in node to work with phantom. You use it with `mocha` or any other test framework. Again, I am not too familiar, `mocha-phantomjs`. If you can write js code, then you can use this.

**Comment by dschinkel** [comment]
So lets say I have the following my-spec.js: 

'use strict';

var expect = require('chai').expect,
    phantom = require('phantom'),
    status,
    page,
    pageStatus;

before(function() {
    phantom.create().then(function(ph) {
        ph.createPage().then(function(page) {
            page.open('https://stackoverflow.com/').then(function(status) {
                pageStatus = status
            })
        });
    });
})

describe('can get an instance of a phantom js page', function() {
    it('should have a page to work with', function() {
        // use the page instance here in my test
    })
})

so how would I run this from the command-line?

**Comment by amir20** [comment]
I have no idea. It depends on your test framework. I think this is a question for stackoverflow. 

For this project I use jasmine and gulp. You can read the source if it helps.

**Comment by dschinkel** [comment]
I am just trying to understand if anyone out there is using this like I'm trying here and why it would be failing like this? if I have your bridge in my require and using that to call commands on it, why would it fail? At the top of my spec is phantom = require('phantom')

**Comment by dschinkel** [comment]
I'm using mocha-casper now.
