### ISSUE TITLE
Confusing evaluate() behavior

### ISSUE THREAD

**Issue by lmanzke** [amir20/phantomjs-node#365]
Passing a function to the page.evaluate() function results in the loss of the argument.
That is due to JSON.stringify seemingly converting a function into null. (phantom.js around line 100 -> executeCommand)

Node version: v5.6.0 (strict)
PhantomJS Version: v2.1.1

### Expected behavior

Passing a function to page.evaluate() returns the evaluation of that function.

### Actual behavior

Null is returned. The evaluation function argument does not get through to phantom. Passing the function as a string works though. That is not a nice workaround though.

Sample code:
`   describe('index page', () => {

    it('should have the correct title', function (done) {
        phantom.create().then(function (ph) {
            ph.createPage().then(function (page) {

                page.open('http://localhost:3000').then(function (status) {
                    page.evaluate("function() {return document.title}").then(function (title) {
                        expect(title).to.equal('Title');
                    }).then(done, done);
                });
            });
        });
    });
});   `

This works, but if you remove the quotes around the function passed to evaluate, it fails.

**Comment by amir20** [comment]
I'll take a look at this today. But it's strange because I have a test which return an actual function. :( I'll update you when I get a chance after my meetings.

**Comment by lmanzke** [comment]
Maybe the behavior of JSON.stringify has changed recently?

**Comment by lmanzke** [comment]
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify says:

> If undefined, a function, or a symbol is encountered during conversion it is either omitted (when it is found in an object) or censored to null (when it is found in an array).

I think that is the case here.

**Comment by amir20** [comment]
I use a variant of that function `JSON.stringify(command, (key, val) => typeof val === 'function' ? val.toString() : val) `  where it does `function.toString()` so it has been working. I need to bring the test case locally to see what's going on...

**Comment by amir20** [comment]
I just did this locally

```js
it('#evaluate(function(){return document.title}) executes correctly', function*() {
        let page = yield phantom.createPage();
        yield page.open('http://localhost:8888/test.html');
        let response = yield page.evaluate(function () {
            return document.title
        });
        expect(response).toEqual('Page Title');
    });
```

And it worked just fine. I also have node `5.6.0`. I am going to try with a different page next.

**Comment by amir20** [comment]
@lmanzke I copied your code exactly and it worked just fine. 

```
~/D/test_phantom $ cat bug.js
var phantom = require('phantom');

phantom.create().then(function(ph) {
    ph.createPage().then(function(page) {
        page.open('https://www.google.com/').then(function(status) {
            page.evaluate(function() {
                return document.title
            }).then(function(title) {
                console.log(title)
                ph.exit();
            });
        });
    });
});
~/D/test_phantom $ node bug.js 
Google
~/D/test_phantom $ 
```

**Comment by amir20** [comment]
Couple of questions. 

1. What OS are you running? 
2. Can you run my tests locally by doing `npm test` 
3. Last try running your test with `DEBUG=true`.

**Comment by amir20** [comment]
@lmanzke any update?

**Comment by lmanzke** [comment]
@amir20 My OS is Ubuntu 14.04.
WIll try the test suite...

**Comment by lmanzke** [comment]
Test suite runs fine. May be the buggy behavior is related to me using wallaby.js as test runner. Will try to investigate that further. I already tried the debug output - Using it I tracked down the "function loss" to the JSON.stringify call in phantom.js:100.

**Comment by amir20** [comment]
`JSON.stringify()` in debug is a little misleading because I don't pass the json through the same function I pasted above. It will probably not print the function correctly. I just issued a fix for that.

**Comment by amir20** [comment]
I installed ubuntu on Vagrant and ran the same file above. It worked just fine. I think at this point it is something your doing. I am going to close the ticket. I am curious what the problem is so please update if you find out.
