### ISSUE TITLE
Can not define commandline parameters

### ISSUE THREAD

**Issue by janober** [amir20/phantomjs-node#366]
In the old version I could define commandline parameters like "ignore-ssl-errors" by supplying them them to the create method , in version 2 I am somehow unable to do the same.

### Expected behavior

phantom.create({'ignore-ssl-errors': 'yes', 'ssl-protocol': 'TLSv1'})
or
phantom.create({parameters:{'ignore-ssl-errors': 'yes', 'ssl-protocol': 'TLSv1'}})

to start PhantomJS with that parameters.

### Actual behavior

Does simply not do anything. Promise gets never resolved.

**Comment by amir20** [comment]
This should already work. I added this feature a while ago. Try doing `phantom.create(['--ignore-ssl-errors=yes', '--ssl-protocol= TLSv1'])`. 

I should probably update documentation. 


Close bug if it works.

**Comment by amir20** [comment]
I updated documentation to include this. See https://github.com/amir20/phantomjs-node/commit/d804ab145bf0dbbd3e2d3b3c82137c930e6c61c0#diff-04c6e90faac2675aa89e2176d2eec7d8R47

Let me know if it doesn't work, and if it does...please close.

**Comment by janober** [comment]
Great, thanks a lot works perfectly.
