### ISSUE TITLE
Doesn't re-evaluate DOM changes

### ISSUE THREAD

**Issue by AnthonyCalandra** [amir20/phantomjs-node#369]
### Expected behavior

1. Create phantom instance.
2. Create page.
3. Wait for dynamic element to load to read its contents.
4. Create an interval and evaluate the page for the element's contents every `t` milliseconds.
5. Every evaluation returns the element's **new** contents.

```
$ node script.js
0
1
2
^C
```

### Actual behavior

1. Create phantom instance.
2. Create page.
3. Wait for dynamic element to load to read its contents.
4. Create an interval and evaluate the page for the element's contents every `t` milliseconds.
5. Every evaluation returns the **old** element's contents.

```
$ node script.js
[empty string]
[empty string]
[empty string]
^C
```

### Steps to reproduce the behavior

Some code would really help with this report.
**script.js:**
```js
'use strict';
let phantom = require('phantom');
const JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js';
const SITE_URL = 'http://localhost:8000/example.html';

function isVisible() {
  return $('#ajax').is(':visible');
}

function listen(page) {
  setInterval(() => {
    page.evaluate(function() {
      var time = $('#ajax').text();
      return time;
    }).then((buffer) => {
      // `buffer` doesn't seem to change after first evaluation.
      console.log(buffer);
    });
  }, 1000);
}

phantom.create().then((ph) => {
  // See: https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js
  function waitFor(testFx, onReady, timeOutMillis) {
    let maxtimeOutMillis = timeOutMillis ? timeOutMillis : 3000;
    let start = new Date().getTime();
    let condition = false;
    let interval = setInterval(() => {
      if ((new Date().getTime() - start < maxtimeOutMillis) && !condition) {
        condition = testFx();
      } else {
        if (!condition) {
          ph.exit(3);
        } else {
          onReady();
          clearInterval(interval);
        }
      }
    }, 250);
  }

  ph.createPage().then((page) => {
    let res = new Promise((resolve, reject) => {
      page.open(SITE_URL).then((status) => {
        status === 'success' ? resolve() : reject();
      });
    });
    res.then(() => {
      page.includeJs(JQUERY_URL).then(() => {
        waitFor(
          () => page.evaluate(isVisible),
          () => listen(page)
        );
      });
    });
  });
});
```
**example.html:**
```html
<!doctype html>
<html>
<head></head>
<body>
  <span id="ajax"></span>
  <script>
    window.onload = function() {
      var i = 0;
      var t = setInterval(function() {
        document.getElementById('ajax').innerHTML = i++;
      }, 1000);
    };
  </script>
</body>
</html>
```
As you can tell by the code, I should be able to read `#ajax`'s new value during each page evaluation -- however I continuously get an empty string (the original value). It appears as if the DOM isn't being updated by the JavaScript.

If I run this using `phantomjs` from the console directly with a similar script:
```js
'use strict';
var JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js';
var SITE_URL = 'http://localhost:8000/example.html';
var page = require('webpage').create();

page.onConsoleMessage = function(msg, lineNum, sourceId) {
  console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};

function isVisible() {
  return $('#ajax').is(':visible');
}

function waitFor(testFx, onReady, timeOutMillis) {
  var maxtimeOutMillis = timeOutMillis ? timeOutMillis : 3000;
  var start = new Date().getTime();
  var condition = false;
  var interval = setInterval(function() {
    if ((new Date().getTime() - start < maxtimeOutMillis) && !condition) {
      condition = testFx();
    } else {
      if (!condition) {
        phantom.exit(3);
      } else {
        onReady();
        clearInterval(interval);
      }
    }
  }, 250);
}

function listen(page) {
  setInterval(function() {
    var buffer = page.evaluate(function() {
      var time = $('#ajax').text();
      return time;
    });
    console.log(buffer);
  }, 1000);
}

page.open(SITE_URL, function(status) {
  page.includeJs(JQUERY_URL, function() {
    waitFor(
      function() { return page.evaluate(isVisible); },
      function() { listen(page); }
    );
  });
});
```
It works.

### Environment

Mac OSX Yosemite. Reproducible on PhantomJS `2.1.1` and `1.9.2`.

**Comment by amir20** [comment]
Well this is an interesting one. Let me look at it.

**Comment by amir20** [comment]
@AnthonyCalandra nice find! It took me forever to figure out what is going on... I think I know what is going on. `stdin.readLine()` in phantomjs blocks the thread so no javascript executes. Therefore, `setInterval` is blocked and never gets executed. 

This is going to take me a little while to fix it. I think `phridge` fixes this by sending a heartbeat every few milliseconds so that other js pages have a chance to execute.  Maybe this will fix it. I am going to try this and see if it works. I'll also try `phridge` to see if that works. 

Thanks for reporting this.

**Comment by AnthonyCalandra** [comment]
Hi @amir20, thanks for taking a look. I would like to comment on about this statement: `Therefore, setInterval is blocked and never gets executed.` Is this the same `setInterval` in my code? I would like to clarify that the interval does indeed run every `t` milliseconds regularly, but it's the `buffer` that doesn't give me my expected value -- meaning that the page isn't updating somehow.

**Comment by amir20** [comment]
No, I mean the `setInterval` in `example.html` doesn't run. I did 

```html
<script>
    window.onload = function() {
      var i = 0;
      var t = setInterval(function() {
        console.log('updating ajax');
        document.getElementById('ajax').innerHTML = i++;
      }, 1000);
    };
</script>
```
and `console.log` never executes. So that tells me that the javascript is never executing.

**Comment by AnthonyCalandra** [comment]
@amir20 I might have just fixed this... Stay tuned.

**Comment by amir20** [comment]
Me too. I just added #370. What's your fix look like? I'll probably merge the better one. :)

**Comment by amir20** [comment]
About to release new build

**Comment by amir20** [comment]
@AnthonyCalandra thanks for the fix. I published `2.0.0-alpha.5.

**Comment by AnthonyCalandra** [comment]
Glad to hear! Thanks.

**Comment by amir20** [comment]
Also @AnthonyCalandra you should change `condition = testFx();` to `testFx().then(c => condition = c);`

**Comment by AnthonyCalandra** [comment]
@amir20 Good catch. :+1:
