### ISSUE TITLE
Node application exits cleanly when incorrectly passing parameters to phantom

### ISSUE THREAD

**Issue by antolovich** [amir20/phantomjs-node#374]
### Expected behavior

When passing parameters to phantom.create() without putting them into an array first, phantomjs-node should throw an error.

### Actual behavior

When passing parameters to phantom.create() without putting them into an array first, the node application exits with no error.

### Steps to reproduce the behavior

```
var phantom = require('phantom');

phantom
     .create('--web-security=false')
     .then...
```
### Environment

- OS: Ubuntu 14.04
- Node version (`node -v`): v0.12.4
- package version: 2.0.0

**Comment by amir20** [comment]
Yea, probably a bug. Want to send a pull request? :)
