### ISSUE TITLE
Use phantomjs-node with mocha

### ISSUE THREAD

**Issue by Daxtek** [amir20/phantomjs-node#381]
Hi, i'm trying to use phantomjs-node with mocha to do some tests

```
var phantom = require('phantom');
phantom.create().then(function(ph) {
  	ph.createPage().then(function(page) {
	    page.open('http://localhost:8900').then(function(status) {
	      	console.log(status);
                 if ( status === "success" ) {
		      page.injectJs("../node_modules/mocha/mocha.js");
		      page.injectJs("../node_modules/chai/chai.js");

		      //inject your test reporter
		      page.injectJs("testMocha/reporter.js");

		      //inject your tests
		      tests.forEach(function(test) {
		         page.injectJs(test);
		      })

		       page.property('evaluate').then(function() {
		          window.mocha.run();
		        });
		    }else{
		      ph.exit();
		    }
		});
	});
});
```
If i do it without phantomjs-node i'm able to run my tests lunching the file with

`phantomjs myFile.js`

, but i need phantomjs-node to do otherthings needed for my tests. Do you have any idea on how to run mocha with phantomjs-node ?

I lunch the file with 
`node myFile.js`

Thanks in advance.

### Environment

- OS: Ubuntu 15.10
- Node version (`node -v`): 4.2.3

**Comment by amir20** [comment]
Sorry. I don't use mocha. I don't know what you're asking. Please read the guides. Issues are not to ask questions. Try stackoverflow.

**Comment by Daxtek** [comment]
For those who see that, i have found an answer to my problem, you can see that here : http://stackoverflow.com/questions/35581464/use-phantomjs-node-with-mocha
