### ISSUE TITLE
What is the way to set the content using html string?

### ISSUE THREAD

**Issue by jdnichollsc** [amir20/phantomjs-node#382]
### Expected behavior

Hi man, thanks for this package... but the package need more code examples. Can you share an example to set the content using a html string?

### Actual behavior

page.property('plainText', template.html).then(function () {
     res.status(200).send(page.renderBase64());
});

page.renderBase64() return => Error: write EPIPE

### Environment

- OS: Windows
- Node version (`node -v`): v4.2.4
- package version: phantom@2.0.1

**Comment by amir20** [comment]
Read the phantom [help pages](http://phantomjs.org/api/webpage/property/content.html). Setting content is done via `page.content = '<html>,....</html>';` and that's documented already. So you would use `page.property('content', html)`. 

> Setting the property will effectively reload the web page with the new content.

**Comment by jdnichollsc** [comment]
Thanks! :dancers:
