### ISSUE TITLE
Getting data in event-callbacks

### ISSUE THREAD

**Issue by janober** [amir20/phantomjs-node#383]
Is there a way to get data in and out of an even-callback? So if I for example want to pass in a value and depending on that save the resources that did timeout in "onResourceError".

Someting like it go implemented in version 1:
https://github.com/amir20/phantomjs-node/pull/229
but no matter what I tried in PhantomJS 2 (setting data on the page-object, using closures, ...) I was totally unable to get it working. Neiter was I able to pass any value in nor was I able to get any data out of it.

Thanks!

**Comment by amir20** [comment]
Well this is an interesting one. I think it's worth adding. But just to be clear, #229 only let's you pass data IN  callbacks. It doesn't let you get data OUT. Correct? Because I remember merging that. 

Also, I won't be able to add this for a couple days. But if you want to send me a pull request I can merge it.

**Comment by janober** [comment]
Ah yes thats true. That the referenced pull request did just allow to send data in and not oud did not not really come across in my description. Actually hoped that getting data out was maybe already possible and I was maybe just not able to figure out how.

Would love to give back at least a little bit and send that pull request but right now is really land under and I will so not be able to. Sorry.

**Comment by amir20** [comment]
You can get data out. But it's a hack. Look at #378. I haven't documented it because it feels really dirty to return objects on the `window`. 

I'll add the parameters next week. Too many meeting for me to get a chance to add this.

**Comment by janober** [comment]
Ah yes does not seem like the prettiest thing ;-)

Thanks a lot! Wish you a nice evening!

**Comment by amir20** [comment]
@janober can you try with #383? 

```js
var phantom = require('phantom');

phantom.create().then(function(ph) {
    ph.createPage().then(function(page) {
        var test = 123;
        var property2 = 'foobar';

        page.property('onResourceRequested', function(requestData, request, a, b, c) {
            console.log(requestData.id, a, b, c);
        }, test, property2, {fooBar: true});

        page.open('http://amirraminfar.com', function(status) {
            ph.exit();
        });
    });
});

```

**Comment by amir20** [comment]
I tested this when I got home. It should work for you. So I released a new version.

**Comment by janober** [comment]
Wow that was fast. Just tried it and it worked great. Thanks a lot!
