### ISSUE TITLE
Access document when evaluating page

### ISSUE THREAD

**Issue by csysmans** [amir20/phantomjs-node#384]
Hi,

It's unclear to me how I can access the document variable when executing the "evaluate" method:

`
page.evaluate().then(function(){
    console.log(document);
});	
`

Any help would be much appreciated.

**Comment by amir20** [comment]
You have to pass a function to evaluate. 

```js
page.evaluate(function(){
    return document.getElementById('foo').innerHTML
}).then(function(html){
    console.log(html);
})
```

**Comment by amir20** [comment]
Added an example https://github.com/amir20/phantomjs-node/commit/5caf024e4cf03729e4b68570d41c1b3530bec490
