### ISSUE TITLE
Supply data into a document

### ISSUE THREAD

**Issue by TWKDreamState** [amir20/phantomjs-node#390]
### Expected behavior

I am trying to render a document to a PDF. I wish to be able to supply some data from a database (several svg's) to the document and put them in to a bootstrap div. Previously, I could supply the data into page.evaluate as follows (although it wasn't always perfect) ..

```javascript 
page.evaluate(function (reportData) {
    for (var graph of reportData) {
        if (graph.number <= 5) {
            var svg = document.getElementById("svg" + graph.number);
            svg.innerHTML = graph.svg;
         }
    }
}, reportData)
```

### Actual behavior

page.evaluate no longer accepts data. What is the recommended way for me to achieve the above? Many thanks in advance.

**Comment by amir20** [comment]
This is possible. I added this support a while back. Look at the docs and most recent pull requests. 

I am traveling and can't look right now. The syntax should be similar.

**Comment by amir20** [comment]
Did you get a chance to try this out?

**Comment by amir20** [comment]
Actually, I realized I did this only for properties. I should make it so that it works for evaluate too.

**Comment by TWKDreamState** [comment]
Many thanks. I did look through the PR's and then thought that onRequestResources might be the way but it didn't work out - possibly my misunderstanding but I couldn't access it from the evaluate. If it is useful to make evaluate accept parameters as before that would be brilliant. I've tried to figure other ways to do this, but the data is intended to remain private before the PDF creation and only available from the server. I'm using Meteor.

**Comment by amir20** [comment]
@TWKDreamState I wrote a test to fix it. But somehow, the tests still pass. 

```js

fit('#evaluate(function(){...}, param1, param2) executes and passes parameters correctly', function*() {
        let page = yield phantom.createPage();
        let data = 'monkeys are cool';
        let response = yield page.evaluate(function (testdata) {
            return 'test.' + testdata;
        }, data);
        expect(response).toEqual('test.monkeys are cool');
    });
```

It turns out, phatomjs' #[evaluate](http://phantomjs.org/api/webpage/method/evaluate.html) supports this already. So I can't reproduce this. It looks to be working.

**Comment by TWKDreamState** [comment]
Thank you for this - I'll have another go as I would prefer to use version 2! I was having other issues with various other bits of the code (resolved now - seems using for (var graph of reportData) instead of for (var i =0; var < reportData.length; i++) caused some issues) so I'm not sure what I have and haven't done!! Will report back shortly.

**Comment by TWKDreamState** [comment]
OK. I can confirm it does work (so I guess my code was at fault), however, it's creating a completely different PDF output from version 1 (which rendered correctly). Things seem to be all over the place. Another issue for after I've had some sleep :) Thanks for your help.

**Comment by amir20** [comment]
OK Good luck and just remember this is just a wrapper around phantomjs. Perhaps v2 of phantomjs did something.
