### ISSUE TITLE
Page object needs aditional methods

### ISSUE THREAD

**Issue by ZiggyQubert** [amir20/phantomjs-node#391]
The page object is missing a number of methods that phantomjs exposes on its page object

### Expected behavior

the following should be available on the page object (taken from the phantom documentation http://phantomjs.org/api/webpage/)
- evaluateAsync
- evaluateJavaScript
- getPage
- goBack
- goForward
- go
- reload
- setContent - added as part of #393 
- switchToFocusedFrame
- switchToFrame
- switchToMainFrame
- switchToParentFrame
- uploadFile

Edited to remove depricated methods from the list

**Comment by amir20** [comment]
You are welcome to add them. But some of those are just properties. 

Send a pull request. And add tests!

Sent via my iPhone

**Comment by amir20** [comment]
@ZiggyQubert I don't think it makes sense to add every method. Which ones do you want the most? Since I am traveling maybe you add them.

**Comment by gerotakke** [comment]
I've added setContent in https://github.com/amir20/phantomjs-node/pull/393 — you can't replace it with .property('content') because it can set the URL as well and .property('url') is read only.

**Comment by ZiggyQubert** [comment]
@amir20 I can certainly add some of the methods, there are a few that I need, seams like a good idea to mirror phantoms api where possible though

**Comment by ZiggyQubert** [comment]
Submitted a pull request for the sendEvent method, I'll submit another when I have tests written for a number of the other methods

**Comment by amir20** [comment]
Thanks @ZiggyQubert I see it. I merged the other pull request. Nicely done.

**Comment by amir20** [comment]
I am going to close this, and we should add a new pull request as it we need per method.
