### ISSUE TITLE
'Promise' is not defined in lib/index.js

### ISSUE THREAD

**Issue by stephengardner** [amir20/phantomjs-node#392]
```javascript
"use strict";

var _phantom = require("./phantom");

var _phantom2 = _interopRequireDefault(_phantom);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/**
 * Retuns a new instance of Phantom class
 * @param args
 * @returns {Promise}
 */
module.exports.create = function (args) {
  return new Promise(function (resolve) {
    return resolve(new _phantom2.default(args));
  });
};
```

`Promise` is not defined, throws error

**Comment by amir20** [comment]
You're probably using and old version of node. 

Sent via my iPhone

**Comment by amir20** [comment]
I don't see the node version in the bug. I support version 4.x or later. Probably need to update.

**Comment by Buom01** [comment]
Same probleme here with node v0.10.41
Tested with the main demo:
```javascript
var phantom = require('phantom');

phantom.create().then(function(ph) {
  ph.createPage().then(function(page) {
    page.open('https://stackoverflow.com/').then(function(status) {
      console.log(status);
      page.property('content').then(function(content) {
        console.log(content);
        page.close();
        ph.exit();
      });
    });
  });
});
```

Output:
```bash
[bastien@bastien-pc test_phantom]$ node index.js 

/home/bastien/node_apps/test_phantom/node_modules/phantom/lib/index.js:15
  return new Promise(function (resolve) {
             ^
ReferenceError: Promise is not defined
    at Object.module.exports.create (/home/bastien/node_apps/test_phantom/node_modules/phantom/lib/index.js:15:14)
    at Object.<anonymous> (/home/bastien/node_apps/test_phantom/index.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by amir20** [comment]
@Buom01 I am not sure why you are surprised that this doesn't work. Like I said, the older version of node isn't supported. I am not sure when `Promise` was introduced.

**Comment by amir20** [comment]
Looks like `Promise` got added in `0.12`. There is a shim that fixes it. You can include https://github.com/paulmillr/es6-shim in your npm project and it should work. It doesn't make sense for this project to include because if there is a bug in the shim(s) then I don't see a new getting into supporting it. 

Hopefully this works out for people. 

* Related question on [stackoverflow](http://stackoverflow.com/questions/21564993/native-support-for-promises-in-node-js).

**Comment by Buom01** [comment]
Big thank :+1:

**Comment by amir20** [comment]
I upped the engine version in efd7e5e7e9c1476ac2b8536d56bf4a5b7305aec3.

**Comment by HugoPoi** [comment]
Not for production use but this works with node `0.10.25`
```
Promise = require('es6-promise').Promise;
var phantom = require('phantom');
```
and launch script with `node --harmony yourscript.js`
