### ISSUE TITLE
A better way for handling events?

### ISSUE THREAD

**Issue by jrust** [amir20/phantomjs-node#395]
I'm upgrading to v2 and finding it very hard to get around the limitation that no variables or memory can be shared with event callbacks.  Two big issues are surfacing:

1. In order for me to capture a screenshot I'm finding myself passing a large number of variables to the callback. 
2. It's causing me to have copy/paste functions that used to be shared (e.g. cleanup and logging functions).  copy/paste is a workaround for a few small functions, but anything larger like log4js or lodash is not possible. 

To try and summarize: because of the lack of shared variables it is very difficult to do anything besides the most basic because closures don't work and any library  fails because all of its dependencies are not in phantomjs memory.

Is there a better way or a pattern I'm missing?

**Comment by jrust** [comment]
One other thing I've found is that trying to debug problems inside the callbacks is very difficult because the error seems completely swallowed.  For example, if I call an undefined function in the callback the function terminates, but I couldn't find any way to get insight into the error.

**Comment by amir20** [comment]
So there is multiple questions here. 

1. In version 1, nothing was ever shared. This behavior was never changed in v2. I am not sure if I am misunderstanding this or you were using it incorrectly. But all phantomjs clients I have seen pass a block of code to `phantomjs` process and cannot share variables. So I can't help you there. 
2. What do you mean `log4js` can't be used anymore? Can you explain? 
3. So if you wrap your code in `then(function(){.....})` and then not provide a `catch`, all exceptions will be swallowed. This is how `Promise` works. You have to write correct code and has nothing to do with this package.

**Comment by jrust** [comment]
Sorry, I'm having trouble describing it accurately.  Here is an example of what I'm trying to do:

```javascript
const log4js = require('log4js');
const Jimp = require('Jimp');
const outputFile = 'foo.png';

function loadAndCapture(page) {
  page.property('onCallback', (_saveScreenshot, _page) => { _saveScreenshot(_page) }, saveScreenshot, page)
    .then(() => page.open(url))
    .catch(e) => log4js.debug(e));
}

function saveScreenshot(page) {
  logTime('taking screenshot');
  page.render(outputFile).then(() => Jimp.read(outputFile).resize());
}

function logTime(msg) {
  log4js.debug(`took ${process.hrtime} for ${msg}`);
}
```

I have confirmed that the `onCallback` function is being called, but after that it silently dies because phantom does not know about `logTime`, `log4js`, or `Jimp`.  And even if I try to pass all those as arguments to `saveScreenshot` it still fails.  For example, even if I just simplify it to this it shows the first console message, but not the second, because the `_log4js` call dies with some unknown error:

```javascript
page.property('onCallback', (_log4js) => { 
  console.log('test1'); // Shows up
  console.log(_log4js); // Logs Object
  _log4js.debug('test2');
  console.log('test2'); // Never shows up
}, log4js);
```

Code was very similar to v2, but used `page.set('onCallback', () => saveScreenshot(page);`

**Comment by amir20** [comment]
You cannot pass functions as parameters to `phantomjs-node`. That won't work. You can pass data around. What you're trying to do is essentially not possible with any client that I know of. See #292 for more context on why this is not possible. This never worked in v1 so I don't understand what you are asking here about the difference of v1 or v2. v1 worked over tcp. 

I also don't understand why you are using `onCallback` to open a page. Do you know what `[onCallback](http://phantomjs.org/api/webpage/handler/on-callback.html)` does?  If you want just a screenshot then I don't see why you are making it so complicated. 

Sorry I can't help more. You might want to jump on stackoverflow and ask.

**Comment by jrust** [comment]
Thanks for the links, those are helpful.  I'm using onCallback because it's an angular app and I need to know when it finishes loading.  After reading and more investigation it appears the crucial difference is that somehow the callback function in v1 knew of the enclosing scope.  This works in v1:

```javascript
page.set('onCallback', function() { foo(); });
function foo() {
  console.log('callback done');
}
```

While this does not in v2:
```javascript
page.property('onCallback', function() { foo(); });
function foo() {
  console.log('callback done');
}
```

I'll keep poking around the code, but hopefully this example helps clarify for you or others that notice the change.
