### ISSUE TITLE
images are not loading

### ISSUE THREAD

**Issue by TrejGun** [amir20/phantomjs-node#396]
Thanks for this great lib! its very useful)

however i think i have found a bug
here is example script

```js
import os from "os";
import path from "path";
import {create} from "phantom";


async function render(url) {
	const phantom = await create([
		"--ignore-ssl-errors=true",
		"--load-images=true",
		"--local-to-remote-url-access=true"
	]);

	const page = await phantom.createPage();

	page.property("onResourceRequested", requestData => {
		console.log(requestData.url);
	});

	page.property("onConsoleMessage", message => {
		console.log(message);
	});

	const template = `<img src="${url}" width="200" height="200" style="border: 1px solid black"/>`;

	await page.property("content", template);

	const abs = path.join(os.tmpdir(), "test.pdf");

	await page.render(abs).then(() => {
		console.log("PDF Rendered", abs);
	});

	page.close();
	phantom.exit();
}

render("https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png")
	.then(r => {
		console.log("ok");
		console.log(r);
		process.exit(0);
	})
	.catch(e => {
		console.log("error");
		console.error(e);
		process.exit(0);
	});

```

it should render pdf with image
but instead it does nothing

if i change --load-images=false it saves empty pdf
i guess it should not silently fail on render but show at least any error message like 'unable to retrieve external resource' or that ever

- OS: mac
- Node version (`node -v`):
➜  common git:(master) ✗ node -v
v5.7.0
➜  common git:(master) ✗ npm -v
3.7.3
- package version: 2.0.3

**Comment by amir20** [comment]
@TrejGun 

Interesting. I just pass everything directly to phantom. I don't do anything special. So if phantom is not creating an error then this should could happen. I am going to try it locally and see what's going on. 

How are you running it? I noticed you used `await` and `async` so I want to make sure I run it the same way.

**Comment by TrejGun** [comment]
i'm running it with babel

```bash
NODE_ENV=test DEBUG=true node_modules/.bin/babel-node test.js
```

i tried generators first but decided i don't need `co`

PS firewall doesn't show a request to wiki so its definitely on my side

**Comment by amir20** [comment]
@TrejGun I found the problem. According to [this post](http://stackoverflow.com/questions/19103268/phantomjs-setcontent-not-working-when-html-has-assets), you have to use `onLoadFinished`. 

So doing something like this in phantomjs work...

``js
var webPage = require('webpage');
var page = webPage.create();
page.content = '<img src="https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png" width="200" height="200" style="border: 1px solid black"/>';

page.onLoadFinished = function(status) {
    page.render('test.pdf');
    phantom.exit();
};
```

I am not sure how to do this in `phantomjs-node`. I can't really trigger callbacks in node. Somehow, I have to figure out how to pass call backs. I have an idea where I mentioned in #292. Maybe something like `page.register('onLoadFinsihed', function(){ node js })`. 

I am open to ideas. What do you think? If we can brainstorm together maybe we can come up with a clean way to do this.

**Comment by amir20** [comment]
I think the only way I can think of implementing this is introducing an `event` method that could look like this: 

```js
page.event('onLoadFinished', function(){
  page.render(...);
  phantom.exit();
});
```
The above event could be executed in NodeJS. But there could be up to a `100ms` delay because phantomjs is blocking and I have implemented a heartbeat every 100ms to check for events. 

I feel this is really hack. What do you think @TrejGun? Is it worth implementing?

**Comment by TrejGun** [comment]
I tried to investigate how this can be fixed

looks like `onLoadFinished` works pretty much same as `onResourceRequested`
so you can set it 

```js
    page.property("onLoadFinished", () => {
        console.log('onLoadFinished');
    });
```

but this doesn't print `onLoadFinished` at all, so i don't know :(
if your idea with heartbeat works i'd like to give it a chance

**Comment by amir20** [comment]
That should work actually. I am guessing phantom exits before it has a chance to write anything to console though. 

I am thinking of two different ways:

1. Create a wrapper around events like I said above (kinda hacky, and requires the heartbeat trigger)
2. Create a method like `page.fromHtml("<div>fooBar</div>").then(function(){})` which would internally call `setContent` and `onLoadFinished`. This goes against this module being a thin wrapper. 

I don't know what's best. What is your use case exactly? Are you trying to just load page with some image? Could you maybe create a simple web server that does that for you. Like `page?imageUrl=http://test.com/image.png` instead?

**Comment by TrejGun** [comment]
really hacky :(

1) lets imagine i want to listen to `onLoadFinished` so i wrap command and execute my callback in nodejs but this event will be fired only once and there are events which can be fired multiple times. so this is not a solution but a patch

2) still requires code from **1** but if it can be work as a plugin it would be perfect

my use case is to print branded docs from generated html. its really simple - only one image. 
as the result added `delay(3000)` for now which is not perfect but does the trick

**Comment by amir20** [comment]
If I am implement it correctly it should work in 1 and fired multiple times. I would make it so that event callbacks just stick around for ever. 

I am leaning to 1 because 2 is really adding extra logic on top of phantomjs which I don't think the package should be doing. 

I am glad you found a short term solution. I can probably working on it Friday and see how far I get.

**Comment by justusmaier** [comment]
What's the current state on this? I'm generating a multipage PDF template with EJS and
I want to include lots of small SVG images.
The only way I currently see is to inline my SVGs, else I have to switch to another module.

I tried the sleep(3000) [setTimeout] approach without success.
```javascript
    return co(function*() {
        var templateFileName = __dirname + '/templates/' + data.template + '.html';
        var template =
            yield fs.readFile(templateFileName);

        var content = data.content;
        content.IMAGE_DIR = imageDir;
        content.__ = i18n.__.bind(i18n);
        content.utils = {
            time: timeUtil
        };
        var html = ejs.render(template.toString(), content, {
            filename: templateFileName
        });

        // create phatom instance
        var ph =
            yield phantom.create(['--load-images=true', '--local-to-remote-url-access=true']);

        try {
            // create phantom page
            var page =
                yield ph.createPage();

            var outObj = ph.createOutObject();
            outObj.urls = [];
            page.property('onResourceRequested', function(requestData, networkRequest, out) {
                out.urls.push(requestData.url);
                console.log('resource requested');
            }, outObj);

            // set page properties
            yield page.property('paperSize', {
                format: 'A4',
                orientation: 'portrait',
                margin: '1cm'
            });
            yield page.property('zoomFactor', 1);
            yield page.property('content', html);
            yield sleep(5000);

            var renderingFileName = renderDir + data.filename;
            // make sure folders exist
            yield fs.mkdirs(path.dirname(renderingFileName));
            // render pdf
            yield page.render(renderingFileName);
            winston.info('pdf created', renderingFileName);
            // after call to page.open()
            var urls =
                yield outObj.property('urls');
            console.log('urls', urls);

            // read file
            var file =
                yield fs.readFile(renderingFileName);

            // save file to filestorage
            var fileUrl =
                yield filestorage.put(file, data.filename);
            winston.info('new file [%s] stored', fileUrl);

            // clean up intermediate file
            yield fs.unlink(renderingFileName);

            return true;
        } catch (e) {
            winston.error(e);
            throw e;
        } finally {
            ph.exit();
        }
```

**Comment by TrejGun** [comment]
if you know how many images is there you can do
```
 outObj.urls = [];
            page.property('onResourceRequested', function(requestData, networkRequest, out) {
                out.urls.push(requestData.url);
                console.log('resource requested');
            }, outObj);
if ( outObj.urls === count ) { ... loaded }
```

**Comment by justusmaier** [comment]
Nice idea, but that part sadly isn't working either, I always get an empty url array..

**Comment by amir20** [comment]
The solution you have should work. I am not certain why you are getting an empty array. Might be worth digging more in. 

There is something going on here which I can't debug this week. If you want to try to figure out what is broken, then we can create an issue. I am away from home for the next seven days. Thanks @TrejGun for responding to this thread.

**Comment by amir20** [comment]
So I think #454 should be fixing this. At least allow you to run code in nodejs.

**Comment by justusmaier** [comment]
Thank you! This is fixed for me.
After I updated to 2.1.1 it still wasn't working for me, because I was missing the "file://" prefix in my IMG_DIR.
Now it works without any additional sleep or waiting explicitly for resources.

**Comment by justusmaier** [comment]
```javascript
            // create phantom page
            var page =
                yield ph.createPage();

            var urls = [];
            page.on('onResourceRequested', function(requestData, networkRequest) {
                urls.push(requestData.url);
                console.log('resource requested', requestData.url);
            });

            // set page properties
            yield page.property('paperSize', {
                format: 'A4',
                orientation: 'portrait',
                margin: '1cm'
            });
            yield page.property('zoomFactor', 1);
            yield page.property('content', html);

            // wait for images to be loaded
            while (imageCount < urls.length) {
                yield sleep(100); // wait a phantom heartbeat (100ms)
            }
            yield sleep(100); // wait an additional phantom heartbeat

            var renderingFileName = renderDir + data.filename;
            // make sure folders exist
            yield fs.mkdirs(path.dirname(renderingFileName));
            // render pdf
            yield page.render(renderingFileName);
            winston.info('pdf created', renderingFileName);

            /* useful to debug and find image count console.log('urls', urls.map(function(url) {
                var parts = url.split('/');
                return parts[parts.length-1];
            }), urls.length); */

            // read file
            var file =
                yield fs.readFile(renderingFileName);
```

**Comment by TrejGun** [comment]
Does this work for you?

**Comment by justusmaier** [comment]
yeah kinda.. here's a litte tweaking and breakout.
Note that this solution requires the resource count known and fix.
```javascript
             let sleepCounter = 0, maxSleep = imageCount + 50; // maxSleep will be at least 5s
             // wait for images to be loaded
             while (urls.length < imageCount) {
                 sleepCounter++;
                 if (sleepCounter > maxSleep) {
                     throw new Error('Image loading timeout');
                 }
                 winston.info('loaded %d/%d images for PDF', urls.length, imageCount);
                  // as long as there are remaining images to be loaded
                 yield sleep(100); // wait a phantom heartbeat (100ms)
             }
```

**Comment by iursevla** [comment]
Is this working  now?
In my case it renders the PDF without the images.
