### ISSUE TITLE
Use it with phantomjs 1.9.x

### ISSUE THREAD

**Issue by stereoit** [amir20/phantomjs-node#397]
Hello, is it possible to use the v2 version with older phantomjs? There is some strange regression with Linux and DPI and page size on phantomjs v2 branch.

I've tried to replace the binaries in the `phantomjs-prebuilt`, it almost works, but the images are missing.

**Comment by amir20** [comment]
I think you should try downgrading the npm package to `phantomjs@1.9.x`. `phantomjs-prebuilt` was called `phantomjs` before 2.0. If you do that and recompile then it should work. I haven't personally tried it.

**Comment by stereoit** [comment]
Ok, I've figured out:

v2 and issue with 72*96dpi I sort of can handle with:
```
// fix DPI issue on Linux and Phantomjs
page.evaluate(function(){
  document.body.style.zoom = 0.75;
})
```

The v1 was working fine, it just probably handles loading of background-images compared to v2. So the trick is likely to be to use setTimeout. Please close this question.
