### ISSUE TITLE
page.setContent cannot stop.

### ISSUE THREAD

**Issue by waitingduck** [amir20/phantomjs-node#399]
### Expected behavior

I was trying to set a custom html and javascript code using setContent

This should start my script and return status.
### Actual behavior

However, page has never stop and in DEBUG mode I got 
```
debug: Parsing:
 {
   "id":"163337ff0325b6c157f493cf7f5ed426",
   "target":"phantom",
   "name":"noop",
   "params":[],
   "deferred":{
      "resolve":"function () { [native code] }",
      "reject":"function () { [native code] }"
  }
}
```
with different id every time.

### Steps to reproduce the behavior

code is here

```
phantom.create(['--web-security=no']).then( function(ph){
   ph.createPage().then( function(page) {
      page.setContent('<!DOCTYPE html><html><head></head><body style="margin: 0px; padding: 0px"><div>' + somescript + '</div></body></html>',
      renderConfig.headers.Referer).then( function(status) {
         if (status === 'success') {
            //do something
         } else {
            //do something
           page.close();
           ph.exit();
         }
      });
   });
});
```
### Environment

- OS: CentOS
- Node version (`node -v`): v5.6.0
- package version: v2.0.3
- phantomJS version: v2.1.1

Any idea happens here? Thanks in advance.

**Comment by amir20** [comment]
So this is a little my fault. I didn't actually release the latest version with `setContent`. Oops. :) That has been fixed. However, I did add a test to phantom and noticed that `phantomjs` doesn't throw an error. 

```js
var webPage = require('webpage');
var page = webPage.create();
page.setContent('<!DOCTYPE htddml><ddhtml><head></hddead><body style="margin: 0px; padding: 0px"><div></div></body></html>', 'http://testtest.com')
page.render('test.png');
phantom.exit();
```

`phantomjs` doesn't return an error. `test.png` does get created though. 

I have released `2.0.4` so `setContent` should be working as expectantly. One note, `then` for `setContent` doesn't return `status`. It's just a pass-thru to phantomjs.

**Comment by x3au** [comment]
Not sure if I am missing something but seeing this issue again. 
Windows 7
phantomjs version - 2.1.1
phantomjs-node version - 2.0.10

Thanks!

Here is console output:
_debug: Starting C:\source\product.results.test\JS\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe --web-se
curity=no C:\source\product.results.test\JS\node_modules\phantom\lib\shim.js
debug: Sending: {"id":"737b806324ed6a267660af400b0b1e43","target":"phantom","name":"createPage","params":[],"deferred":{
"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"737b806324ed6a267660af400b0b1e43","target":"phantom","name":"createPage","params":[],"deferred":{
"resolve":"function () { [native code] }","reject":"function () { [native code] }"},"response":{"pageId":"737b806324ed6a
267660af400b0b1e43"}}
debug: Sending: {"id":"03af5a4aaaff351329940e523594f7c0","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"03af5a4aaaff351329940e523594f7c0","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"8491919d3ab9bfebefd194e3959f3cb8","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"8491919d3ab9bfebefd194e3959f3cb8","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"9848a6f913981291699662a2fff7096f","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"9848a6f913981291699662a2fff7096f","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"39b145b512ecc4759aea970828290c62","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"39b145b512ecc4759aea970828290c62","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"cfd98f2ff5dab8dcf7284864129513fa","target":"phantom","name":"noop","params":[],"deferred":{"resol
ve":"function () { [native code] }","reject":"function () { [native code] }"}}_

**Comment by amir20** [comment]
I am not sure if I understand the problem. Seeing `noop` is expected because the process goes in to a special event listening mode to allow phantomjs to trigger events. Otherwise it will block.

**Comment by x3au** [comment]
Got it, I just tried the code shown above with DEBUG on and saw these messages in the log so thought this could be the issue recurring again. Thanks!
