### ISSUE TITLE
Silent render error

### ISSUE THREAD

**Issue by isuttell** [amir20/phantomjs-node#400]
I'm working on creating a PDF from some HTML I've generated locally. However, the `render` function silently fails depending on the `content`.

### Expected behavior

The expected behavior is for the `render` function to throw an error when it doesn't succeed.

### Actual behavior

The actual behavior is that when I include 
````
<base href="http://localhost:3000/">
````
in the HTML the render fails but doesn't throw an error. I've figured out that I can fix it by changing it to:
```
<base href="/">
```
I'm guessing is this a phantomjs error, however, I would still expect phantom to throw an error if it doesn't work. It doesn't even create a pdf.

### Environment

- OSX 10.11
- node: 4.2.1
- phantom: 2.0.2

**Comment by amir20** [comment]
This is probably related to #399? 

Can you provide an example script to reproduce?

**Comment by amir20** [comment]
So this is a little my fault. I didn't release the latest version. I just did release `2.0.4` so it should have `setContent` working. If you were using that, it should be working. 

Sadly, as you suggested, it is just a pass-thru to phantomjs. I don't think phantomjs will create an error for bad html. With version `2.0.4` it should at least work like you expected it.

**Comment by amir20** [comment]
I'll leave this open as favor to #399. If the new version doesn't work then let me know.

**Comment by amir20** [comment]
Also remember to always have `catch`. Because otherwise you won't see errors. Specially in `createPage()`'s catch. If you make a mistake in `then`, it would be silent unless you have `catch`.
