### ISSUE TITLE
onResourceRequested no fire

### ISSUE THREAD

**Issue by waitingduck** [amir20/phantomjs-node#401]
### Expected behavior

```
page.property('onResourceRequested', function(request) {
   //do something
   console.log('send requested');
 }).then(function() {
   console.log('success set onResourceRequested');
});
```

### Actual behavior

Should print send requested when requesting.

### Steps to reproduce the behavior

Code is here
```
page.property('onResourceRequested', function(request) {
   console.log('onResourceRequested: ' );
   console.log( request );
}).then(function() {
   console.log('success set onResourceRequested');
});

page.property('onResourceReceived', function(res) {
   console.log('onResourceReceived: ' + res.stage );
   if (res.stage === 'start') {
      harResources[res.id].startReply = res;
   }
   if (res.stage === 'end') {
      harResources[res.id].endReply = res;
   }
}).then(function() {
   console.log('success set onResourceReceived');
});

page.setContent('<!DOCTYPE html><html><head></head><body style="margin: 0px; padding: 0px"><div>'  + renderConfig.tag +  '</div></body></html>', renderConfig.headers.Referer)
.then( function() {
   console.log('start on load success');
   setTimeout(function() {
      onLoadSuccess();
   }, 10000);
});
```

Base on this code, I got a lot of onResourceReceived but no onResourceRequested. Like this
info: onResourceReceived: end
info: onResourceReceived: end
info: onResourceReceived: start
info: onResourceReceived: end
info: onResourceReceived: end
### Environment

- OS: CentOS
- Node version (`node -v`): v5.6.0
- package version: v2.0.4
- phantomJS version: v2.1.1

Any suggestion of this situation? Thanks in advance!

**Comment by amir20** [comment]
```js
import {
    create
} from "phantom";

function sleep(ms = 0) {
    return new Promise(r => setTimeout(r, ms));
}

(async function() {
    const phantom = await create(["--ignore-ssl-errors=true", "--local-to-remote-url-access=true"]);
    const page = await phantom.createPage();
    await page.property("onResourceRequested", requestData => console.log('requesting', requestData.url));

    let url = "https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png";
    const template = `<img src="${url}" width="200" height="200" style="border: 1px solid black"/>`;
    await page.property("content", template);
    await sleep(2000);
    phantom.exit();
    console.log("done!");
}());
```

It works for me. Could it be that `<!DOCTYPE html><html><head></head><body style="margin: 0px; padding: 0px"><div>` doesn't actually have any resources loading?

**Comment by waitingduck** [comment]
Hey, I found why it is not working...

Sorry, it is my fault that the onResourceRequested call back function is broken and that why it seems it has never fire. Please close it. Thank you!

**Comment by rafaelrferreira** [comment]
Hi, i am having the same problem. What was your solution @waitingduck? onResourceReceived is working but onResourceRequested its not firing.

Look what i tried:

page.property("onResourceRequested", requestData => console.log('requesting', requestData.url));

page.property('onResourceRequested', function(requestData, networkRequest) {
     console.log(requestData.url);
});

No one above seems to work =(

Thanks!

**Comment by waitingduck** [comment]
Hi, @rafaelrferreira 

This is my way to use onResourceRequested. Hope this will help you.

```
page.property('onResourceRequested', function (request) {
   console.log( request.url );
}).then(function() {
   console.log('success set onResourceRequested');
});
```

**Comment by rafaelrferreira** [comment]
Nice @waitingduck ! It worked properly! ^^ 

Thanks a lot!
