### ISSUE TITLE
Close Phantom Process from onResourceRequested

### ISSUE THREAD

**Issue by Sinistralis** [amir20/phantomjs-node#403]
```
phantom.create().then(function (ph) {
        ph.createPage().then(function(page) {
            
            page.property('onResourceRequested', function(requestData, networkRequest) {
                //some logic
               ph.exit();
            })
           
            page.open('url') .then(function(status) {
        
                page.evaluate(function(args) {
                    //some logic
                }, args);
            });
        })
    });
```

Given the above, what is the correct way to kill ph from inside that promise? I cannot for the life of me figure out a way to do this. I also tried passing ph into the promise but that causes a circular structure error.

Ideally, I would be able to attach some kind of event to the page being closed that the node-side can listen to, so I can kill the process from that, but that event didn't seem to exist.

**Comment by Saredon** [comment]
Try this:
```javascript
page.property('onResourceRequested', function(requestData, networkRequest) {
    //some logic
}).then(function(){
    ph.exit();
});
```

**Comment by Sinistralis** [comment]
Wouldn't this cause the first request to exit the process?  What if I want to conditionalize the exit?

**Comment by Sinistralis** [comment]
Wouldn't this cause the first request to exit the process? What if I want to conditionalize the exit?  I also feel like this would fire once the event was attached. I'll try it when I get a chance but I'm not sure it's what I need.

**Comment by Sinistralis** [comment]
Tried it and the .next is fired after the event is added as opposed to after each time it's fired.

**Comment by amir20** [comment]
You can't do that. In the README file 

> It is important to understand that the function above executes in the PhantomJS process. PhantomJS does not share any memory or variables with node. So using closures in javascript to share any variables outside of the function is not possible. 

That `function` is actually executed in phantomjs process. You can't share node variable instances. To exit, use the promise from `page.open`. There isn't any other way that I know around this. 

I have spent a lot of time trying to figure this out but it's really complicated to communicate back to Node. If you search through the issues, you can see a lot of people have asked the same question.

**Comment by Sinistralis** [comment]
That's why I ask if there is a way we can have a callback for when the page instance is closed. It would provide a way to handle this case.

**Comment by amir20** [comment]
Interesting. What do you mean when the page is closed? What is your use case? I am curious to know why you need to know when the page is closed and you can't just do:

```js
page.open(url).then(function(status){
  // page finished and call exit
}
```

**Comment by Sinistralis** [comment]
I am looking for a specific network request to determine when to close.

My use case is, when a specific URL is is requested, grab data from it so I can compare it against other criteria.

So I need phantomjs to run beyond the page.open so it can get resources, and then only close it after it submits a form and redirects to a new location (thus requesting resources). Once it gets the resource I want, I then want to exit phantom with that resource so I can perform additional logic on it.

**Comment by amir20** [comment]
Hmm OK. You should look at #378. I know it's totally a hack. Everybody wants to send data back from PhantomJs but that's just not possible because data gets executed in a different process. :( 

With the solution I provided you could do something like: 

```js
page.property('onResourceRequested', function(requestData, networkRequest) {
   if(criteria){
      FOO_FOUND = true'
});

// later on

phantom.windowProperty('FOO_FOUND').then(function(FOO_FOUND){
   if(FOO_FOUND) phantom.exit();
});
```

Obviously this is a hack and I didn't hack it for those reasons. 

I am open to suggestions on how to fix this. There was a little conversation regarding this in #396 and #292.

If you have any better ideas than me, I'd be more than happy to talk about it.

**Comment by Sinistralis** [comment]
This is incredibly hacky, but it solves our problem. Thanks for the tip. Going to make sure to document the hell out of this on our end.

**Comment by Sinistralis** [comment]
Closing issue

**Comment by amir20** [comment]
You're welcome. I have looked at all kinds of implementation node-phantomjs bridge and I haven't been able to find a decent solution that is not confusing as hell. I am open to ideas. Good luck....
