### ISSUE TITLE
Promises should avoid callback hell...

### ISSUE THREAD

**Issue by ryanshawty** [amir20/phantomjs-node#404]
Promises were introduced to try and fix callback (among other reasons) the example in the README.md should be changed to better represent this.

```js
phantom.create().then(function(ph) {
  ph.createPage().then(function(page) {
    page.open('https://stackoverflow.com/').then(function(status) {
      console.log(status);
      page.property('content').then(function(content) {
        console.log(content);
        page.close();
        ph.exit();
      });
    });
  });
});
```

to something like:

```js

phantom.create().then(function(ph) {
  return ph.createPage();
}).then(function(page){
  return page.open('https://stackoverflow.com/');
}).then(function(status){
  console.log(status);
  return page.property('content')
}).then(function(content){
  console.log(content);
  page.close() // Make these in scope somehow 
  ph.exit(); 
});
```

**Comment by amir20** [comment]
I agree it should be switched to that but `page` and `ph` do need to be somehow in scope. Your way doesn't allow that. Also remember that people who are migrating from 1.x to 2.x would be very confused with this style. 

I actually prefer to put `async` `await` and `yield` instead. 

Something like 
```js
(async function() {
    const phantom = await create(["--ignore-ssl-errors=true", "--local-to-remote-url-access=true"]);
    const page = await phantom.createPage();
    await page.property("onResourceRequested", requestData => console.log('requesting', requestData.url));

    let url = "https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png";
    const template = `<img src="${url}" width="200" height="200" style="border: 1px solid black"/>`;
    await page.property("content", template);
    await sleep(2000);
    phantom.exit();
    console.log("done!");
}());
```

But for most people who don't really know js, I think that's too much.

**Comment by ryanshawty** [comment]
Fair point. a

await and async probably are even further of though seeing as they are ES7

**Comment by brandon93s** [comment]
I tend to hoist `page` and `ph` out to local variables to get over the scoping issues. It isn't perfect, but gets the job done. 

```javascript
let _ph, _page;

phantom.create().then(ph => {
  _ph = ph;
  return _ph.createPage();
}).then(page => {
  _page = page;
  return _page.open('https://stackoverflow.com/');
}).then(status => {
  console.log(status);
  return _page.property('content')
}).then(content => {
  console.log(content);
  _page.close() // Make these in scope somehow 
  _ph.exit(); 
});
```

**Comment by amir20** [comment]
I plan to put some example pages soon. I'll use @brandon93s's as an example for one of the example. 

Is it just me or is that harder to read though?

**Comment by ryanshawty** [comment]
IMO it's a lot easier to read as you've only got one level of indentation.
As long as you know how promises work that is.

On Sunday, 13 March 2016, Amir Raminfar <notifications@github.com> wrote:

> I plan to put some example pages soon. I'll use @brandon93s
> <https://github.com/brandon93s>'s as an example for one of the example.
>
> Is it just me or is that harder to read though?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amir20/phantomjs-node/issues/404#issuecomment-195883792>
> .
>


-- 
Ryan Shaw

**Comment by amir20** [comment]
I added some examples and update the `README` file to reflect these changes.
