### ISSUE TITLE
Phantom Spawning Orphaned Process

### ISSUE THREAD

**Issue by brandon93s** [amir20/phantomjs-node#409]
### Expected behavior
Module spawns a single phantomjs process when `phantom.create()` is invoked. 

### Actual behavior
Moudle spawns two phantomjs processes when `phantom.create()` is invoked. One of these processes is used by the module, the other is orphaned.

### Steps to reproduce the behavior

```javascript
var phantom = require('phantom');
phantom.create().then(function (ph) {
    console.log('phantom process started');
});
```

### Environment

- OS: Windows 10 
- Node version (`node -v`): 4.4.0 & 5.8.0
- package version: 2.0.4

### Screenshot 

![orphaned process](http://i.imgur.com/9oRWbki.png)

### Explanation 

The child_process module normalizes arguments and [adds the filename as the first argument of the arguments array](https://github.com/nodejs/node/blob/master/lib/child_process.js#L340). Because of this, the following ends up getting executed (windows):

```
C:\ProgramData\chocolatey\bin\phantomjs.exe C:\ProgramData\chocolatey\bin\phantomjs.exe 'C:\Source\quick projects\phantom-test\node_modules\phantom\lib\shim.js'
```

Executing this same command directly in cmd or powershell results in the same scenario of one active process running the shim and a second orphaned process not running anything.

**Comment by brandon93s** [comment]
### UPDATE

This appears to be a phantomjs 2.1.1 bug. Downgrading to 2.0.0 alleviates this issue. I will be opening an issue with phantomjs.

**Comment by amir20** [comment]
Still...thanks for filing it. I don't use Windows so I haven't been able to reproduce it. Do try to make sure you call `ph.exit()`.
