### ISSUE TITLE
outObject not firing appropriately  

### ISSUE THREAD

**Issue by DarrylD** [amir20/phantomjs-node#410]
Not sure if I'm using this correctly, but the `outObj.property('url')` is supposed to resolve after the condition is met? Excuse my ignorance but, am I doing something wrong?

```
var outObj = ph.createOutObject();

page.property('onResourceRequested', function(requestData, out) {
    var match = requestData.url.split('testing');

    if (match.length > 1) {
        out.url = requestData.url;
    }
}, outObj)

//based on the doc
outObj.property('url').then(function(){
    // not called when condition above is met
});
```

**Comment by amir20** [comment]
Sounds like a bug. Can you show me more of the code? Where do you call `page.open`?

**Comment by amir20** [comment]
Also, why did you remove the issue template? I need to know the versions.

**Comment by amir20** [comment]
I think I found your problem. Your parameters are wrong for `onResourceRequested`. You should do

`page.property('onResourceRequested', function(requestData, networkRequest, out) {})`

**Comment by DarrylD** [comment]
Hey, 

Sorry about that, using package 2.0.6 and v5.5.0 node.

But I added the `networkRequest ` and the same issues happens. It fire, but it happens on initiation, not resolving when the `out.url` is defined in the condition. 

Conceptually, am I correct on how this should happen?

**Comment by amir20** [comment]
I can't reproduce it. There is also a test that makes sure it works nightly. So I am guessing there is something you are missing. Are you sure `out.url = requestData.url` is actually being executed? Try putting some `console.log`s to debug. 

Try giving a gist or pasting the whole code. Conceptually, yes it should work. But so do a lot of things. :-1:

**Comment by amir20** [comment]
Here is the working code for me

```js

var phantom = require('phantom');
var co = require('co');

co(function*() {
    try {
        var ph = yield phantom.create();
        var page = yield ph.createPage();

        var outObj = ph.createOutObject();

        yield page.property('onResourceRequested', function(requestData, networkRequest, out) {
            out.lastUrl = requestData.url;
        }, outObj);

        var status = yield page.open('https://www.google.com/');

        var lastUrl = yield outObj.property('lastUrl');

        console.log('lastUrl', lastUrl);
        ph.exit();
    } catch (e) {
        console.log(e)
    }
});

```

**Comment by DarrylD** [comment]
Here is a gist of what's not working for me:

**Comment by amir20** [comment]
Your parameters for `page.property('onResourceRequested', function(requestData, networkRequest, out)` is still wrong.

**Comment by DarrylD** [comment]
Sorry, just fixed and tested it. Same issue.

**Comment by amir20** [comment]
I see your problem. `outObj.property('url').` is called before `page.open`. Of course that's not going to work. I also don't know what you expect to happen with `seconObj`. That object doesn't do anything. See the example I posted for an example.

**Comment by DarrylD** [comment]
You're awesome man... Again excuse my ignorance, much thanks!!
