### ISSUE TITLE
Incorrect page.evaluate behavior

### ISSUE THREAD

**Issue by BPkazemi** [amir20/phantomjs-node#414]
### Expected behavior

``page.evaluate`` should return the contents of the selector to the promise handler.

### Actual behavior

Any use of a selector causes evaluate to "hang". The handler is never called.

### Steps to reproduce the behavior
Running the below prints "response: true", so the DOM element is being found.
```
var phantom = require('phantom');

phantom.create().then(function(ph) {
    ph.createPage().then(function(page) {
        page.open('http://stackoverflow.com').then(function(status) {
            console.log('page opened.');
            if (status == 'success') {
                page.evaluate(function() {
                    return document.querySelector('div#footer') ? true : false;
                }).then(function(fulfilled) {
                    console.log('response:', fulfilled);  // "response: true"
                    page.close();
                    ph.exit();
                }, function(reject) {
                    console.log('rejected:', reject);
                });
            }
        });
    });
});
```

However, trying to return the element itself fails:
```
page.evaluate(function() {
    return document.querySelector('div#footer');
}).then(function(fulfilled) {
    console.log('response:', fulfilled);  // Never called
    page.close();
    ph.exit();
}, function(reject) {
    console.log('rejected:', reject);
});
```
### Environment

- OS: OS X Yosemite 10.10.5
- Node version (`node -v`): 5.4.0
- package version: 2.0.6
- Fresh install from ``npm install phantom``

``page.evaluate`` is an oft-used command, so I'm surprised to see this failing. Am I missing something here?

**Comment by amir20** [comment]
The return object is serialized to JSON and returned to node. `document.querySelector('div#footer')` doesn't make sense to be serialized so it won't work. You have to return simple objects not a DOM object.
