### ISSUE TITLE
Header / Footer content problem - ph.callback is undefined

### ISSUE THREAD

**Issue by aeksco** [amir20/phantomjs-node#415]
Hey folks! I'm having an issue with getting header content to render properly. It appears to be a result of ```ph.callback``` being undefined. My code is as follows:

```coffee
phantom = require 'phantom'

phantom.create().then (ph) ->
  ph.createPage().then (page) ->

    page.open('http://www.google.com').then (status) ->

      paperSizeOptions =
        format: 'A4'
        orientation: 'portrait'
        border: '1cm'
        header:
          height: '2cm'
          contents: ph.callback( (pageNum, numPages) ->
            return '<h1>Hello world!</h1>'
          )

      page.property('paperSize', paperSizeOptions).then ->
        page.render('/path/to/file/test_output.pdf').then ->
          page.close()
          ph.exit()
```

Because ```ph.callback``` is undefined, this code isn't functional as long as the  ```header``` object is defined on ```paperSizeOptions```.

It is worth noting that if I don't supply a ```contents``` attribute, the page  *does* render and the header has the correct height. Here's my output with a header height of ```10cm``` without any content:

![test_output](https://cloud.githubusercontent.com/assets/4616233/13824798/0798a624-eb86-11e5-8396-bd6be58782c1.png)

I've also noticed that in ```/lib/phantom.js``` a number of methods are exposed, i.e. ```createPage```:

```javascript
key: "createPage",
value: function createPage() {
    var _this2 = this;

    return this.execute('phantom', 'createPage').then(function (response) {
        return new _page2.default(_this2, response.pageId);
    });
}
```

However, there is no ```callback``` method exposed - is this on purpose?

Any help would be very appreciated - I have not been able to get this working and it's becoming a blocker to pushing a big feature to our application. Thanks!

**Comment by amir20** [comment]
Read other issues before posting :) 

https://github.com/amir20/phantomjs-node/issues/411#issuecomment-197401282

This feature is not supported. Easy to add but I won't be able to any time soon.

**Comment by amir20** [comment]
If you are comfortable writing js code, I can give you direction on how to add this support.

**Comment by aeksco** [comment]
@amir20 Thanks for the prompt reply! I'd be happy to implement this feature as it's pretty essential to shipping a new feature. Where would be the best place to start?

**Comment by amir20** [comment]
There is a probably a bunch of ways around this. I see two ways: 

The easiest way to do this is to first create a noop function in `phantom.js` that basically does nothing. 
```
function callback(obj) {return obj}
```
This is so that it is easy to use for people who have no idea what `phantomjs-node` does. They can still do `phantom.callback(...)`

Then in `shim.js` you should look for `content` key and call `phantom.callback(value['content'])`.  Probably somewhere on line `30`. 

At a high level that should work. I haven't written it so I am just guessing. 

The second way would be to somehow make `phantom.callback` in node do something special so that `shim.js` could convert to actual `phantom.callback`. You could make it something like 

```
function callback(obj) {
    return phantom_callback(obj){
      return obj;
   }
}
```
And then you could search for `phantom_callback` and replace with calling `phantom.callback`. I think this is a little harder. 

Up to you which one you try. 

Let me know how it goes! Either way, it shouldn't be more than 5 lines of code. :)

**Comment by RemekConsulting** [comment]
+1

**Comment by aeksco** [comment]
@amir20 I've been wrestling with it quite a bit and I'm not making great progress.

I added a ```callback``` method to the Phantom object defined in ```phantom.js``` that returns the user-supplied callback sent in with ```header.contents```:

```
paperSizeOptions =
  ...
  header:
    height: '2cm'
    contents: ph.callback( (pageNum, numPages) ->
      return '<h1>Hello world!</h1>'
    )
```

From looking at the ```property``` function defined in the ```commands``` object in ```shim.js```, it looks like this may not be the best place to invoke this callback as it would need to be parsed out of ```command.params```. I tried adding a ```callback``` function to the ```commands``` object - I was able to hit that function and invoke the callback, but the ```pageNum``` and ```numPages``` parameters were undefined. Regardless of how the function was executed, the ```returnValue``` property in the object returned by ```Phantom.callback(function)``` was always ```null```.

From what I can see I shouldn't need to modify ```shim.js``` at all - if I'm understanding the purpose of that code correctly it looks like it proxies methods from ```phantimjs-node``` to ```phantomjs-prebuilt```. If a command for ```callback``` is not defined in ```shim.js```, it *should* reference the vanilla implementation in ```phantomjs-prebuilt```.

I've been able to get this working with no trouble at all using vanilla PhantomJS - why does it seem so unreasonably difficult to get this working with ```phantomjs-node```? This is unfortunately an absolute show-stopping issue that may prohibit my team from continuing to use this library - any thoughts on how to resolve this sometime soon?

**Comment by amir20** [comment]
Sorry you are struggling. 

The underlying issue is that phantomjs and node are two DIFFERENT processes. That has to make sense before working on this module. Everything that you do in node, is proxied to phantomjs via systemout and sysin. 

This module is a client. It can't have access to the same methods that Phantom has because there is no shared memory. 

You do have to modify `shim.js` because that's the file that gets executed with the messages that come from PhantomJS. 

I wanted to point out that this an open source project. I don't get paid for this project nor do I expect to. There will always be features that are missing because as you have noticed 95% of things get proxied but somethings need to be handled differently. 

So I think what's going on is that you have to REALLY understand advanced js to be able to do this. It's really another few lines of code in shim.js.

Short term you can just write in in vanilla phantomjs and invoke it using `spawn`. Or wait until end of this week when I have some free time to implement it. 

Sorry I can't help more. This is my part hobby and not job.

**Comment by aeksco** [comment]
@amir20 Thanks for the run down - I understand your situation completely, and despite this single issue the library has been working out very nicely for us. Conceptually it's making more sense - I think I'm close to having a functional implementation, though after several hours I'm a touch burned out on it. I'll take a look at it again in the morning with come coffee and a fresh pair of eyes. Thanks again for your prompt replies - I really appreciate the help getting this problem worked out :)

**Comment by amir20** [comment]
@aeksco it's your lucky day. I got home a little early and added this functionality in #416.

**Comment by amir20** [comment]
#416 is merged. `2.0.7` should be live soon.

**Comment by amir20** [comment]
@aeksco I expected you to be very excited? :P Did you try this?

**Comment by RemekConsulting** [comment]
Hi Amir, I tried this on my system but it's still throwing the same error.

`
phantom.create(['--ignore-ssl-errors=yes', '--ssl-protocol=any', '--web-security=no']).then(function(ph) {

		ph.createPage().then(function(page) {

			page.property('paperSize', {
				format:			"A4",
				margin:			"1cm",
				orientation:	'portrait',
				header: {
					height:		"1.2cm",
					contents:	phantom.callback(function (pageNum, numPages) {
 						return "<h1>Header <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
					})
				},
				footer: {
					height:		"1.2cm",
					contents:	phantom.callback(function (pageNum, numPages) {
 						return "<h1>Footer <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
					})
				}
`
I checked the node_module and it's the latest version 2.0.7 so I'm on the latest version.

**Comment by amir20** [comment]
you should do `ph.callback`

**Comment by RemekConsulting** [comment]
I tried that and that doesn't work either :(

**Comment by amir20** [comment]
Can you give me your whole code?

**Comment by RemekConsulting** [comment]
Here you are, and the entry from the log:

```
phantom.create(['--ignore-ssl-errors=yes', '--ssl-protocol=any', '--web-security=no']).then(function(ph) {

		ph.createPage().then(function(page) {

			page.property('paperSize', {
				format:			"A4",
				margin:			"1cm",
				orientation:	'portrait',
				header: {
					height:		"1.2cm",
					contents:	ph.callback(function (pageNum, numPages) {
 						return "<h1>Header <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
					})
				},
				footer: {
					height:		"1.2cm",
					contents:	ph.callback(function (pageNum, numPages) {
 						return "<h1>Footer <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
					})
				}
			}).then(function() {

				page.open(pageURL).then(function(status) {

					page.render('..' + printResponse.reportFile).then(function(finished) {
						console.log('rendering ' + pageURL + ' done');
						ph.exit();
						callback(printResponse);
					}).catch(function(error) {
						console.log("There was an error with rendering the page", error);
					});

				}).catch(function(error) {
					console.log("There was an error opening the page", error);
				});

			}).catch(function(error) {
				console.log("There was an error setting page properties", error);
			});

		}).catch(function(error) {
			console.log("There was an error creating the page", error);
		});

	}).catch(function(error) {
		console.log("There was an error creating the ph instance", error);
	});
```

```
There was an error creating the page [TypeError: ph.callback is not a function]
```

**Comment by amir20** [comment]
Hmm I wonder if I messed up something and deployed the wrong version. Let me try locally.

**Comment by RemekConsulting** [comment]
Ok. I can pull from NPM but I am sadly "under qualified" to build the module from source. Haven't made it that far in the manual yet ;)

**Comment by aeksco** [comment]
@amir20 Saw your comment last night! I've been caught up all day running errands - apologies for the radio silence!

SUPER excited to test this - at first glance it does look like you may have deployed the wrong version as everything is different from what I was looking at yesterday :scream: 

Similarly to @RemekConsulting I'm having issues pulling / building from NPM (glad it's not just me). It appears that NPM still pulls down a branch with a ```lib``` directory, though the master branch here contains a ```src``` directory instead.

**Comment by amir20** [comment]
Yea, it wasn't deployed correctly. I am using travis to do deploys and not sure what happened.

**Comment by RemekConsulting** [comment]
No problem. We really appreciate your reactivity. Without this feature our application would not be close to where we want it so we really appreciate your work in getting it implemented!

**Comment by amir20** [comment]
Try again with `2.0.8`. I think i just goofed up with my deployment. And you're welcome. It feels good to be appreciated.

**Comment by RemekConsulting** [comment]
Confirmed working exactly as intended. You are the man!!! Thanks so much for this, you have made our reports complete :)

**Comment by aeksco** [comment]
Also confirmed working! Our reporting is in great shape - if you're open to it @amir20 I'd love to add an example or two detailing PDF report generation - seems to be a pretty standard use case. At your convenience comment and let me know - I'd be thrilled to find some way to contribute to the project :)

**Comment by amir20** [comment]
Sure. Send pull request in `examples`.
