### ISSUE TITLE
Multiple property notifications

### ISSUE THREAD

**Issue by rscreene** [amir20/phantomjs-node#417]
### Expected behavior

I have the following code:
```
phantom.create().then(function (myPh) {
  ph = myPh;
  return ph.createPage();
}).then(function (myPage) {
  page = myPage;

  outObj = ph.createOutObject();

  return page.property("onResourceRequested", function (requestData, networkRequest, out) {
    console.log("--URL", requestData.url);
    out.url = requestData.url;
  }, outObj);
}).then(function (status) {
  return page.open("https://yahoo.com");
}).then(function (status) {

  outObj.property('url').then(function (url) {
    console.log("++URL=", url);
  });
});
```

I would like the outObj.property function to be executed every time the onResourceRequested callback is invoked.

### Actual behavior

The outObj.property function is executed just the once.  Presumably because the promise has been satisfied.  Is there something I'm missing that will allow me to have the function called repeatedly (or have I made a mistake in the code!).  I tried to create a new promise in the handler but this feels wrong and just seems to repeat the function for the same URL!

Output extract:
```
...
info: --URL https://geo.query.yahoo.com/v1/public/yql?yhlVer=2&yhlClient=rapid&yhlS=2023392312&yhlCT=2&yhlBTMS=1458208550151&yhlClientVer=3.29.1&yhlRnd=xwLQjuutmTimntIg&yhlCompressed=3
info: ----------------PROPERTY [object Object]
++URL= https://geo.query.yahoo.com/v1/public/yql?yhlVer=2&yhlClient=rapid&yhlS=2023392312&yhlCT=2&yhlBTMS=1458208550151&yhlClientVer=3.29.1&yhlRnd=xwLQjuutmTimntIg&yhlCompressed=3
info: --URL https://uk.yahoo.com/_td_api/resource/today/id/today;ids=%5B%22id-1021577%22%2C%22id-1021554%22%2C%22id-1021553%22%2C%22id-1021552%22%2C%22id-1021542%22%5D;startIndex=45;ui=%7B%22viewer_off_network%22%3Atrue%2C%22viewer%22%3Afalse%2C%22pcsExclusions%22%3Afalse%7D?_appletType=today&_p=p1&authed=0&bucket=903&crumb=&default_appletinit=viewport&default_page=p1&device=desktop&enable_dd=&guid=&lang=en-GB&locdrop_crumb=&mcCrumb=&region=GB&rid=75vdkolbekvp4&site=fp&ssl=1&ucsCrumb=&woeid=44418
info: --URL https://geo.query.yahoo.com/v1/public/yql?yhlVer=2&yhlClient=rapid&yhlS=2023392312&yhlCT=2&yhlBTMS=1458208550574&yhlClientVer=3.29.1&yhlRnd=rhBX67F060zi0s1C&yhlCompressed=3
info: --URL https://s.yimg.com/zz/combo?kx/yucs/uh3s/uh/414/js/uh-min.js&kx/yucs/uh2/common/145/js/jsonp-super-cached-min.js&kx/yucs/uh3s/uh/379/js/escregex-min.js&kx/yucs/uh3s/uh/376/js/persistence-min.js&kx/yucs/uh3s/uh/401/js/menu_group_plugin-min.js&kx/yucs/uh3s/uh/430/js/menu-plugin-min.js&kx/yucs/uh3s/uh/429/js/menu_handler_v2-min.js&kx/yucs/uh3s/uh/376/js/gallery-jsonp-min.js&kx/yucs/uh3s/uh/408/js/logo_debug-min.js&kx/yucs/uh3/uh/js/958/localeDateFormat-min.js&kx/yucs/uh3s/uh/409/js/timestamp_library-min.js&kx/yucs/uh3s/uh/376/js/usermenu_v2-min.js&kx/yucs/uh3/signout-link/10/js/signout-min.js&kx/yucs/uhc/rapid/49/js/uh_rapid-min.js&kx/yucs/uhc/meta/66/js/meta-min.js&kx/yucs/uh3/disclaimer/388/js/disclaimer_seed-min.js&kx/yucs/uh3s/top-bar/137/js/top_bar_v2-min.js&kx/yucs/uh3s/top-bar/139/js/home_menu-min.js&kx/yucs/uh3s/search/369/js/search-min.js
info: --URL https://s.yimg.com/dh/ap/default/140317/pc_flags_sprite_0317_Regular_630pm.png
...
```

### Environment

- OS: OSX 10.10
- Node version (`node -v`): v0.12.0
- package version: 2.0.6

**Comment by amir20** [comment]
That is not possible with this module. The communication is not bidirectional. Only node can ask for things from phantomjs. I don't think the documentation suggests you can do that? 

You could try doing a different thing. It sounds like you are trying to collect all URLs. Use an array instead and collect all the URLs in `out`. Something like `out.urls.push(requestData.url)`. 

Doing things like this is cleaner.

**Comment by rscreene** [comment]
Thanks for the quick response @amir20 

It's a shame it doesn't work like that - it would have saved lots of work at my end :-).  (The documentation doesn't imply this but I thought I'd ask anyway).

The snippet I posted was just a simple example of the problem I was facing - I want to trap callbacks in the browser throughout the lifetime of the page.  So, I'm afraid you're workaround won't really work.

I think I'm going to have to model some sort of request/response mechanism.

Thanks for your help!

**Comment by amir20** [comment]
OK that makes sense. Pull requests are welcomed! #396 is another issue you should look at. There are ways to have phantom send messages to node, and I thought of doing it, but all of them are hacky and will probably break. So I gave up and decided to keep it simple. 

Good luck!
