### ISSUE TITLE
onConsoleMessage and onError do not work

### ISSUE THREAD

**Issue by roadhump** [amir20/phantomjs-node#420]
### Expected behavior

I want to get console messages of page by `page.property('onConsoleMessage')` and thrown errors by `page.property('onError')`.

### Actual behavior

It looks like that callbacks inside `onConsoleMessage` and `onError` do not work now.

### Steps to reproduce the behavior

Here is a code 

```js
const phantom = require('phantom');

phantom.create()
.then((phantomInstance) => phantomInstance.createPage())
.then((page) => {

    page.property('onConsoleMessage', (msg) => {
        console.log('phantomjs page console message', msg);
    });

    page.property('onError', (msg) => {
        console.log('phantomjs page error', msg);
    });

    return page;

})
.then((page) => {

    return page.open('http://google.com/').then(() => page);

})
.then((page) => {

    return page.evaluate(function() {

        console.log('HELLO FROM CONSOLE');

        throw 'SOMETHING';

        return 'something';

    }).then((res) => {

        console.log('result', res);

        return page;

    });

});
```

Now I see `result null` in console, when I expect to get `phantomjs page console message HELLO FROM CONSOLE` and `phantomjs page error SOMETHING`.

Also, if I comment `page.property('onError')`, output will be 

```
info: SOMETHING
info:
info:   :5 in anonymous
info:   :10
result null
```

### Environment

- OS: Mac OS 10.11.3
- Node version (`node -v`): v5.8.0
- package version: 2.0.9

**Comment by amir20** [comment]
I haven't had a chance to look at this. Any update? I don't know what is the problem.  Any debugging information?

**Comment by waitingduck** [comment]
Maybe here
```
.then((page) => {

    page.property('onConsoleMessage', (msg) => {
        console.log('phantomjs page console message', msg);
    });

    page.property('onError', (msg) => {
        console.log('phantomjs page error', msg);
    });

    return page;

})
```
you return page before set onConsoleMessage and onError?

**Comment by roadhump** [comment]
@waitingduck I don't think that problem is here, the same way I added 
```
    page.property('onResourceReceived', (msg) => {
        console.log('received');
    });
```
and it worked fine, print to console.

**Comment by harianus** [comment]
@roadhump When you don't use arrow functions, your example works fine here. So maybe just use regular functions for now?

**Comment by amir20** [comment]
Interesting. I always compile so I never tried this. It makes sense though because I serialize and it needs a function.

**Comment by amir20** [comment]
Closing since the issue was found.
