### ISSUE TITLE
How injectJs in version 2.0

### ISSUE THREAD

**Issue by JeStasG** [amir20/phantomjs-node#421]
Hello!
Please tell me how to make [injectJs](http://phantomjs.org/api/webpage/method/inject-js.html) Since, according to the documentation:

> The page object that is returned with #createPage is a proxy that sends all methods to phantom. Most method calls should be identical to PhantomJS API. You must remember that each method returns a Promise.

I do the following:

```
phantom.create().then(function(ph) {
    ph.createPage()
    .then(function(page) {
        page.open('http://mail.ru')
        .then(function(result){
            console.log(result);
        })
        .then(page.injectJs('http://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js')
            .then(function (result) {
              console.log("Loaded jQuery!");
              console.log(result);   
            }))
        .then(page.evaluate(function(){
                return jQuery.fn.jquery;
            }).then(function(version){
                console.log(version);
            }));
        ph.exit();
    });
});

```
script connection does not happen ....
Thank you!

**Comment by amir20** [comment]
```js
.then(page.injectJs('http://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js')
            .then(function (result) {
              console.log("Loaded jQuery!");
              console.log(result);   
            }))
``` 

The above is not right. 

You should do 
```.then(function(){
   // code goes here
}
```

**Comment by JeStasG** [comment]
Thank you, but
```
.then(function(){
            page.injectJs('https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js')
        })
```
not working.

**Comment by amir20** [comment]
I know it works because it is tested. Look at https://github.com/amir20/phantomjs-node/blob/master/src/spec/page_spec.js#L140

**Comment by amir20** [comment]
I just realized you are using `injectJs` to include a full url. You should use `includeJs` instead. Read the docs carefully.

**Comment by JeStasG** [comment]
Thank you! I am sorry for carelessness!

**Comment by carinlynchin** [comment]
I'm confused...just learning..where are you getting "then" from? i have looked at the api and I don't see it in there...
