### ISSUE TITLE
fs.write is note working in phantomjs-node 

### ISSUE THREAD

**Issue by Sahilgoyal190** [amir20/phantomjs-node#427]
I am trying to modify a phantomjs script to a phantomjs-node script for production scaling, and I am not able to grab and save the HTML content with fs.write(). Does phantomjs-node support this feature or any alternative for this?

**Comment by amir20** [comment]
`fs.write` should work. In fact, I use it in one of my tests. So I don't think this is related to this module.

**Comment by Sahilgoyal190** [comment]
Thanks For the reply, I got the page workaround for fs.write as fs.writeFile in node.js, but I am not able to find a way to wait for all the ajax request get complete before dumping the content. Does Phantom support page.onCallback mthod like Phantomjs

**Comment by rathahin** [comment]
In angular application, I add the line window.callPhantom() once the data are bind with DOM. Apparently, I can get callback, but I cannot pass the content of page. 

```
page.property('onCallback', () => {
	console.log('Angular DOM Ready');
	console.log(sitepage.property('content'));
	
	// respond final html
	res.send(sitepage.property('content'));

	// create snapshot of current page
	sitepage.render('page.png');

	// close
	sitepage.close();
	phInstance.exit();
});
```
I can see the output
`Angular DOM Ready`

But next output never shown.

I think the callback function might be in difference process. Is there any work around to make the callback function able to access sitepage and res object?

Thank you very much.

**Comment by amir20** [comment]
As you have guessed it, `onCallback` does work but it won't tricker code back in NodeJs. This is because there are two different processes. There is no way that I know to fix this. You could use `#createOutObject()` and sleep for 1sec. That seems to have worked a few folks.

**Comment by rathahin** [comment]
`Thank you very much. I would appreciate your time.`
