### ISSUE TITLE
How to evaluate a page using awaitFor to load dynamic contents

### ISSUE THREAD

**Issue by loretoparisi** [amir20/phantomjs-node#431]
### Expected behavior
It's not clear to me respect version 0.7.2, how phantom will load dynamic contents (dynamically loaded by JavaScript).

The Promise chain `then` 

```javascript
.then((content) => {
              sitepage.close();
              phInstance.exit();
              if(done) done( content );
          })
```

will return the page `html`. How to evaluate the page to get dynamic contents?

### Actual behavior
In the past I was using some technique like this to be sure the the page DOM elements were loaded at some point:

```javascript
var Parser = {
  parse : function(page) {

  	var onSuccess = function (page) { // page loaded
        var json=page.evaluate(function() {
          	return document.body.innerText;
      	});
      }
    var onError = function (page,elapsed) { // error

    }
    waitFor({
      	debug: false,
     	 	interval: Settings.parserPageRetryInterval,
      	timeout: Settings.parserPageTimeout,
      	check: function (page) {
      		return page.evaluate(function(func) {
          		return func(document);
          	}, function(dom) {
          		return true;
          	});
      	},
      	success: onSuccess,
      	error: onError
  	},page);

  }
} // Parser
```

where the function `waitFor` was

```javascript
/**
* Recursive Await
*/
function waitFor (config,page) {
    config._start = config._start || new Date();
		var elapsed = new Date - config._start
    if (config.timeout && elapsed > config.timeout) {
        if (config.error) config.error(page, elapsed);
        if (config.debug) console.log('timedout ' + elapsed + 'ms');
        return;
    }
		if (config.check(page)) {
        if (config.debug) console.log('success ' + elapsed + 'ms');
        return config.success(page);
    }
		setTimeout(waitFor, config.interval || 0, config, page);
}
```

so that in the callback `onLoadFinished` I was calling it:

```javascript
var onLoadFinished = function(status) {
	Parser.parse(Context.page);
};
```

Now it's not clear to me how to achieve the same result to evaluate the page, and where.
### Environment

- OS:
- Node version (`node -v`): v4.2.6
- package version: ^2.0.10

**Comment by loretoparisi** [comment]
I'm not sure if this is a possible solution, by the way a first attempt was this one

```javascript
phantom.create(self.options.commandline)
.then((instance) => {
})
...
.then((content) => {

              sitepage.evaluate(function() {
                  return document.body.innerHTML;
              }).then(function(html) {
                  sitepage.close();
                  phInstance.exit();
                  if(done) done( content );
              });


          })
```

**Comment by loretoparisi** [comment]
So,
I have a better understanding of the new patterns, so I think it should work like

```javascript
sitepage.evaluate(function() {
                return document.querySelectorAll('.content > ul');
              }).then(function(html) {
                  console.log("LOADED %s",html);
                  sitepage.close();
                  phInstance.exit();
                  if(done) done( content );
              });
```

This means that the `then` part is waiting contents from that selector `document.querySelectorAll('.content > ul')` to load right?

**Comment by amir20** [comment]
I am not too familiar with `waitFor` so I can't 100% say I know what you are doing. But you would want to do `document.querySelectorAll('.content > ul').innerHTML`. You can't return DOM objects to NodeJS since it would need to be serialized. 

I don't see where the `content` is defined. So I am not sure how what you are trying to do. Try pasting the whole example and maybe I can help then. Also did you do `page.property('content')` some where and I just missed it?

**Comment by loretoparisi** [comment]
@amir20 This is the whole example:

https://gist.github.com/loretoparisi/e14908c5bbfd42d0a2f616c191797add

Normally when in `phantomjs` script I would do

```javascript
page.open(url, function (status) {
    // Check for page load success
    console.log("Page status:" + status);
    if (status !== "success") {
        console.log("Unable to access network");
    } else {
        // Wait for 'signin-dropdown' to be visible
        waitFor(function() {
            return page.evaluate(function() {
                return document.querySelectorAll('.content > ul > li').length>1;
            });
        },
        function() {
            var content = page.content;

        });
    }
  });
````

using the `waitFor` function. I have mentioned this issue here as well https://github.com/ariya/phantomjs/issues/14166

**Comment by amir20** [comment]
So this should still work. Instead of using `page.content` try using `page.property('content')`. That's pretty clear in the documentation. I have tested this functionality with `waitFor` so I know it works. Make sure to use promises.

**Comment by amir20** [comment]
I think you're problem might also be here `return document.body;` since that returns a dom object. I don't think that's what you want.

**Comment by loretoparisi** [comment]
@amir20  I want to check some generic / specific condition for a DOM element in the `body` like:

```javascript
return page.evaluate(function() {
                var elCond=document.querySelectorAll('.content > ul > li').length>1;
                return elCond;
            });
```

that returns `true` when there are some of those `li` elements in this examples.
In `phantomjs` this will then return the bool as result of the `page.evaluate`.
But when in node I have a `then`

```javascript
sitepage.evaluate(function() {
                var elCond=document.querySelectorAll('.content > ul > li').length>1;
                return elCond;
              }).then(function(html) {
                  sitepage.close();
                  phInstance.exit();
                  if(done) done( content );
              });
```

so, question is, the `then` will be executed/chained in the same way so when the condition `elCond` is `true`?

And if so, how can I then use a `waitFor` approach that basically check the `page.evaluate` to exit the timeout handler, and returns the `success` block?

**Comment by amir20** [comment]
I don't think I understand your question. In the `then` block, the value `elCond` is returned. But you put `html`. I don't get it. I could take a look at it later next week when I have some free time. Could you try to simplify your code and paste it. It's a lot of code to go through.

**Comment by YagoGG** [comment]
I think I've got the same problem, if I understood well.

@loretoparisi, just correct me if I'm wrong and I'll create a different issue if we're talking about different things.

For example, using the following code for the function `waitFor()`, taken from [this](https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js) PhantomJS example:
```javascript
function waitFor(testFx, onReady, timeOutMillis) {
    var maxtimeOutMillis = timeOutMillis ? timeOutMillis : 3000, //< Default Max Timout is 3s
        start = new Date().getTime(),
        condition = false,
        interval = setInterval(function() {
            if ( (new Date().getTime() - start < maxtimeOutMillis) && !condition ) {
                // If not time-out yet and condition not yet fulfilled
                condition = (typeof(testFx) === "string" ? eval(testFx) : testFx()); //< defensive code
            } else {
                if(!condition) {
                    // If condition still not fulfilled (timeout but condition is 'false')
                    console.log("'waitFor()' timeout");
                    phInstance.exit(1);
                } else {
                    // Condition fulfilled (timeout and/or condition is 'true')
                    console.log("'waitFor()' finished in " + (new Date().getTime() - start) + "ms.");
                    typeof(onReady) === "string" ? eval(onReady) : onReady(); //< Do what it's supposed to do once the condition is fulfilled
                    clearInterval(interval); //< Stop this interval
                }
            }
        }, 250); //< repeat check every 250ms
};
```

If I try to do the following:
```javascript
// Open the site

page.evaluate(function() {
  // Something that will take a while to load...
});

waitFor(function() {
  return sitepage.evaluate(function() {
    return document.getElementById('loading').style.visibility === "hidden";
  });
}, function() {
  sitepage.render(savePath);
  console.log('Screenshot taken.');
  sitepage.close();
  phInstance.exit();
});
```

My objective is to wait for `#loading` to become `hidden`, because that means the webpage I want to render is completely loaded.

However, the result is like if the screenshot was taken immediately, without waiting for `#loading` to disappear.

**Comment by loretoparisi** [comment]
@YagoGG Yes, exactly, I think with the `then` pattern, things became a bit confusing ( I was using `phantomjs-node` since first release...). So, at the end I had to move back to `phantomjs` and use `spawn` to run it, this solved all those issues, of course, this is not the solution, so I'm keeping `phantomjs-node` in a module, waiting for a solution.

@amir20 first thank you for your support!
So, according to what you say if I do

```javascript
sitepage.evaluate(function() {
                return document.querySelectorAll('.content > ul > li').length>1;
              }).then(function(cond) {
                  sitepage.close();
                  phInstance.exit();
                  if(done) done( content );
              });
```

This will ends having `cond` in the `then` callback with the bool result of the evaluated condition, right?
If so, using the `waitFor` should work, without having any `then` condition so that:

```javascript
waitFor(function() {
  return sitepage.evaluate(function() {
    return document.querySelectorAll('.content > ul > li').length>1;
  }); // <--- Any then here
}, function() {
  // fired when the condition on the `querySelectorAll` has been satisfied
},7000); // timeout after 7 sec.
```

**Comment by amir20** [comment]
I think I am understanding the problem. Thanks for simplifying it. `waitFor` expects to return a value. But `evaluate` returns a `Promise`. So that's why it is not working. This is not a problem of the module but rather problem with `waitFor`. Since everything is executed asynchronously then you have to wait for the value. 

I think what you want is more of a function like this: 

```js
function waitUntil(asyncTest) {
    return new Promise(function(resolve, reject) {
        function wait() {
            console.log('loop...')
            asyncTest().then(function(value) {
                console.log('value', value)
                if (value === true) {
                    resolve();
                } else {
                    setTimeout(wait, 100);
                }
            }).catch(function(e) {
                console.log('Error found. Rejecting.', e);
                reject();
            });
        }
        wait();
    });
}
```

Then you could do 

```js
waitUtil(function() {
    return sitepage.evaluate(function() {
        return document.querySelectorAll('.content > ul > li').length > 1;
    })
}).then(function(){
  // evaluate is true
})
```

I only tested this quickly. You probably want to implement `maxTries` or something similar.

**Comment by amir20** [comment]
If that does work, I really recommend using something like [es7/babel](http://masnun.com/2015/11/11/using-es7-asyncawait-today-with-babel.html) to just use `await` and loop until value is true. That's much cleaner IMO.

**Comment by YagoGG** [comment]
Works like a charm! You can't imagine for how long I've been bumping my head to find a solution for this. :sweat_smile: 

Thanks a lot, man!

**Comment by loretoparisi** [comment]
That's awesome! @amir20 , we have it! I'm going to refer this in https://github.com/ariya/phantomjs/issues/14166 where I have open an issue to support the promise in `waitFor`.

**Comment by amir20** [comment]
You're welcome @loretoparisi  and @YagoGG

**Comment by x3au** [comment]
Would be great if you could provide a gist showing the waitUntil in use. I have a similar need and so trying to figure out the right approach.

Thanks!

**Comment by x3au** [comment]
I am seeing that I cannot pass the selector as a parameter to querySelectorAll call above. Something like:
https://gist.github.com/x3au/929a15aa9f0f4c200ce66e63b3a75d86

The parameter "sel" isn't translated to actual passed value.

Any ideas?

**Comment by loretoparisi** [comment]
@x3au I think I'm having the same issue as well:

This is a simple crawler example that should use the `waitUntil` with promise pattern

https://gist.github.com/loretoparisi/0da825688a000492c657290d7afacb5e

**Comment by Openappdev** [comment]
I personally want to thank you @amir20 with **waitUntil** func. You save my project. Wish you the best in all your projects :).

**Comment by mbret** [comment]
To everyone trying to use waitFor function, this cannot works as evaluate() returns a promise. Your condition will always be true as Function is "true". Use waitUntil
