### ISSUE TITLE
error on createPage()

### ISSUE THREAD

**Issue by tasoss** [amir20/phantomjs-node#432]
###Info
The same code runs under slackware(linux distribution) and windows 10.
I have installed centos with the minimal packages needed.
Then i tried to run my program and i get the error displayed below.
I have used console.log to see where the error occurs.

phantom.create().then(function (ph) {
---> this is printed
	ph.createPage().then(function (page) {
---->this is not printed...

### Expected behavior
createPage() Should work

### Actual behavior

[tasoss@localhost tenbet]$ node main.js 

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)

### Environment

- OS:CentOS Linux release 7.2.1511 (Core) 
- Node version (`node -v`):v4.4.2
- package version: phantom@2.0.10

**Comment by amir20** [comment]
Can you try just running a simple `phantomjs` example? I don't use CentOS. More of an Ubuntu guy. So I don't think I can help or debug. If `phantomjs` doesn't work then you know something is up with the binary.

**Comment by amir20** [comment]
Closing but will reopen if related to module.

**Comment by codyhanson** [comment]
When this happened to us we were missing a required font package on CentOS that PhantomJS was complaining about. I believe it was the `fontconfig` package. But you can try running Phantom on its own, and see what the specific error is.

Ubuntu must come pre-shipped with this package.

**Comment by amir20** [comment]
> Ubuntu must come pre-shipped with this package.

😆 

One day I will ship everything as docker images.

**Comment by tasoss** [comment]
yes i think this was the problem.i should have mentioned it!thanks!
