### ISSUE TITLE
How to hide phantomjs.exe window

### ISSUE THREAD

**Issue by jmartindivmedianet** [amir20/phantomjs-node#434]
### Expected behavior

phantomjs.exe windows normally don't appear when run from a node.js script.

### Actual behavior

Now that I'm running the node.js script (that spawns the phantomjs instances) from pm2, each phantomjs.exe instance's window opens up, stays visible and is listed in the (Windows!) Task Manager as a separate process.
Not sure if this is a phantom, node, pm2 or bat file issue!
UPDATE: it's not a bat file level issue, as running 'pm2 start server.js' from the console opens up the phantomjs windows, too.  Appears to be a pm2 issue, just wondering if anyone has any recommendations.  Thanks a lot.

### Steps to reproduce the behavior

1. write node.js js script (call it 'server.js', for example) to spawn one or more phantomjs's.
2. write bat file to run a 'pm2 start server.js'
3. run bat file

### Environment

- OS: Windows 7
- Node version (`node -v`): v4.4.1
- package version:

**Comment by amir20** [comment]
I really doubt this is related to the driver. Probably worth mentioning on phantomjs project instead.

**Comment by amir20** [comment]
Try reproducing it without this module, and if it happens, then it is definitely related to phantomjs.
