### ISSUE TITLE
How to Obtain onResourceRequested callback in value in the node environment

### ISSUE THREAD

**Issue by ickeep** [amir20/phantomjs-node#436]
### Actual behavior
![image](https://cloud.githubusercontent.com/assets/9164133/14338606/d16194ea-fcaa-11e5-9fb6-ec24a06c453e.png)

- OS:OS X 10.11.4 (15E65)
- Node version (`node -v`):4.41
- package version:  "phantom": "^2.0.10",

**Comment by amir20** [comment]
You should use `createOutObject()`. See the documentation.
