### ISSUE TITLE
How to set paperSize?

### ISSUE THREAD

**Issue by fbernhard** [amir20/phantomjs-node#437]
We are using the latest master branch after having migrated from a 1.x version. 

We try to set the paperSize like this, but it never produces an A4 PDF. 

```
page.set('settings.paperSize',
	{
		format: 'A4',
		orientation: 'portrait',
		margin: '1cm'
	}).then(function(){
		page.render("/tmp/test.pdf").then(function()
		{
			page.close().then([...]);
		});
	});
``` 

Thanks for your help!

- OS: CentOS 7
- Node version (`node -v`): v4.4.2
- package version: 2.0.10

**Comment by TWKDreamState** [comment]
I am happy to share my code that works if it helps? You need to use ...

_page.property('paperSize', {format: 'A4', orientation: 'portrait'})

Just a heads up. I did have to build the phantom binary myself with some alterations to enable a dpi setting otherwise the PDF output ends up all over the place depending on what OS/screen size you are using! You might come across this issue [https://github.com/ariya/phantomjs/issues/12685](url)

`
        phantom.create(['--ignore-ssl-errors=yes']).then(ph => {
            _ph = ph;
            return _ph.createPage();
        }).then(page => {
            _page = page;
            return _page.property('onConsoleMessage', function (msg) {
                console.log(msg);
            });
        }).then(() => {
            console.log('Setting paperSize');
            return _page.property('paperSize', {format: 'A4', orientation: 'portrait'})
        }).then(() => {
            console.log('paperSize set successfully');
            console.log('Setting viewportSize');
            return _page.property('viewportSize', {width: 1920, height: 1080});
        }).then(() => {
            console.log('viewportSize set successfully');
            console.log('Setting DPI');
            return _page.property('dpi', 130)
        }).then(() => {
            console.log('DPI set successfully');
            console.log('Opening report');
            return _page.open('http://phantomjs.org');
        }).then(status => {
            console.log(status);
            console.log('Preparing to render document');
            return _page.render(<insert file path here>);
        }).then(() => {
            console.log('Rendering completed');
            console.log('Phantom process completed successfully');
            _page.close();
            _ph.exit();
        });
`

**Comment by fbernhard** [comment]
Fantastic @TWKDreamState, it works like this. Thanks a lot!

**Comment by amir20** [comment]
Thanks @TWKDreamState for the help!
