### ISSUE TITLE
Using phantomjs 1.9.x binary with phantom 2.x

### ISSUE THREAD

**Issue by undeadlock** [amir20/phantomjs-node#440]
Due to a few environmental issues, I couldn't get phantomjs 2.1.1 to run on my machine, so I'm trying to use phantomjs 1.9.x.
I tried passing binary in the options:
`phantom.create([], {port: 12345, binary: "path to 1.9.x binary")`. This resulted in an `EPIPE` error.
It worked fine when I manually copied phantomjs 1.9.x binary into `phantomjs-prebuilt` folder, but I'd like to know if there's a way to pass custom binary path as an option to phantom?

### Environment

- OS: RHEL 5.5
- Node version (`node -v`): 4.4.1
- package version: 2.0.10

**Comment by amir20** [comment]
That's not supported. I removec `binary` feature because a lot of tests depend on the latest version.

**Comment by amir20** [comment]
I think your best bet is going to build locally by changing the phantomjs dependency in `package.json`

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.

**Comment by undeadlock** [comment]
Thanks, I couldn't find time to post an update. Unfortunately, none of the older versions of `phantomjs-prebuilt` is fetching 1.9.x of phantomjs for me to build locally. I guess for now, I will go with manually copying the phantomjs binary into nodemodules.
