### ISSUE TITLE
ph.addCookie() in 2.x?

### ISSUE THREAD

**Issue by pmpbar** [amir20/phantomjs-node#441]
I am sorry to not follow the guideline, this is just a question about the new API. In the old one there was an addCookie function. Is this still available in the new version? The process just hangs without error. What does the new method look like?

**Comment by amir20** [comment]
Look in the tests https://github.com/amir20/phantomjs-node/blob/dbc79bd9971ac446d57374c0542298fe759b8f44/src/spec/page_spec.js#L183

**Comment by pmpbar** [comment]
Thank you!! Sorry to open the issue, did not see them!
