### ISSUE TITLE
How to generate pdf file output?

### ISSUE THREAD

**Issue by symonny** [amir20/phantomjs-node#443]
Hey there,

I have updated to the new version and I'm not sure how to get the pdf filled with a provided html content. Please let me know what should I correct below.
Thanks in advance.  
   
    `var createPDF = function(options, html, filePath, callback) {
        var phInstance = null;
        var sitepage = null;
        phantom.create().then(function (ph) {
            phInstance = ph;
            return phInstance.createPage();
        }).then(function(page){
            console.log('page');
            sitepage = page;
            var paperSize = {
                format: 'letter',
                orientation: 'portrait',
                margin: {left: "1.25cm", right: "1.25cm", top: "1.25cm", bottom: "1.25cm"}
            };
                page.setting('javascriptEnabled');
                page.property('paperSize', paperSize);
                page.property('viewportSize',  {width: 704, height: 1054}); 
                page.property('zoomFactor', 0.9);
                page.property('content', html);
        }).then(function(status){
            console.log(status);
                return sitepage.property('content');
        }).then(function(content){
            console.log(content);
            sitepage.render(filePath, {format: 'pdf', quality: '100'}).then(function(res){
                /* var outObj = phInstance.createOutObject();
                 sitepage.property('onResourceRequested', function(requestData, networkRequest, debug, out) {
                 if(debug){
                 out.url = requestData.url;
                 }
                 }, process.env.DEBUG, outObj);

                 outObj.property('url').then(function(url){
                 console.log(url);
                 });*/
                setTimeout(function () {
                     sitepage.close();
                     phInstance.exit();
                    return callback(null, filePath);
                }, 25000);
            }).catch(function (err){
                console.log(err);
                sitepage.close();
                phInstance.exit();
            });

        }).catch(function(err){
            console.log(err);
            phInstance.exit();
        });
    };`

**Comment by amir20** [comment]
That's a lot of code to figure out what you are doing wrong. This is not a bug, so I'll point you the right direction. https://github.com/amir20/phantomjs-node/blob/master/src/spec/page_spec.js#L284 there are some example there you can use. You basically should use `page.setContent`.

If you find any bugs, then feel free to open a bug.
