### ISSUE TITLE
createOutObject returns undefined from onResourceReceived

### ISSUE THREAD

**Issue by Shtirlits** [amir20/phantomjs-node#445]
### Expected behavior

I need to get data from the request's response (just to keep it simple I'm expecting to get  `1`)

### Actual behavior

Instead of `out here: 1` I see `out here: undefined` and bunch of expected `resource received` in the console.
For some reason it returns `out here: undefined` even earlier, than `data.out = 1` is called (`out here: undefined` comes before the very first `resource received`)

    out here: undefined
    info: resource received
    info: resource received
    info: resource received
    info: resource received
    info: resource received
    info: resource received
    info: resource received
    ...

### Steps to reproduce the behavior
```coffee
outObj = @ph.createOutObject()
@page.property 'onResourceReceived', (response, data) ->
  console.log 'resource received'
  data.out = 1
, outObj
outObj.property('out').then (out) ->
  console.log 'out here: ' + out
```

### Environment

- OS: Ubuntu 15.04 x64
- Node version (`node -v`): v5.10.1 (npm v3.8.3) (via nvm)
- package version: 2.0.10

**Comment by amir20** [comment]
Hmm, you seem to be doing everything right. It's been a while since I have read coffeescript. Can you `console.log data`. I want to make sure that it is a valid object. Also, I assume you have a call to `page.open` and you just didn't show it? A complete example would be helpful so I can run it.

**Comment by Shtirlits** [comment]
Here is `data`:

```
out here: undefined
info: resource received
info: {"target":"OutObject$d51aea3727ef232c64bdba26abb5fe40"}
info: resource received
info: {"target":"OutObject$d51aea3727ef232c64bdba26abb5fe40","out":1}
info: resource received
info: {"target":"OutObject$d51aea3727ef232c64bdba26abb5fe40","out":1}
info: resource received
info: {"target":"OutObject$d51aea3727ef232c64bdba26abb5fe40","out":1}
...
```

Tell me if you still need complete example - I'll create it

**Comment by Shtirlits** [comment]
Example:

```coffee
phantom = require 'phantom'

class Browser
  constructor: ->
    phantom
      .create()
      .then (ph) =>
        @ph = ph
        @ph
          .createPage()
          .then (page) =>
            @page = page
            @attachEventHandlers()
            @navigate()

  attachEventHandlers: ->
    outObj = @ph.createOutObject()
    @page.property 'onResourceReceived', (response, data) ->
      console.log 'resource received'
      console.log JSON.stringify data
      data.out = 1
    , outObj
    outObj.property('out').then (out) ->
      console.log 'out here: ' + out

  navigate: ->
    @page
      .open('http://google.com')


new Browser()
```

**Comment by amir20** [comment]
So this makes sense. `out` will be undefined because you are trying to get the property before any page has been opened. `outObj.property('out')` should be moved to _after_ `page.open` has executed.
