### ISSUE TITLE
Seems like '--remote-debugger-port' option is not supported.

### ISSUE THREAD

**Issue by nuh-temp** [amir20/phantomjs-node#447]
### Expected behavior

I'd like to debug my app by using PhantomJS's option '--remote-debugger-port'.

### Actual behavior

process gets stuck after calling:
phantom.create(['--load-images=no', '--remote-debugger-port=9000'])

### Environment

- OS: Ubuntu 14.04
- Node version (`node -v`): v4.4.1
- package version: "phantom": "^2.0.10"

**Comment by amir20** [comment]
I don't know much about that. Everything is passed to `phantomjs` as is.
