### ISSUE TITLE
Batch screenshots

### ISSUE THREAD

**Issue by holographix** [amir20/phantomjs-node#448]
Hi, I am desperately trying to process something like 200 screenshots in a single shot, 
my first attempt was to follow the guidelines with a simple script invoked 200 times,

        phantom.create()
          .then(function(instance) {
              console.log("1 - instance")
              phInstance = instance;
              return instance.createPage();
          })
          .then(function(page) {
              console.log("2 - page")
              sitepage = page;
            return page.open(url);
          })
          .then(function(status) {
                console.log("3 - render")
                sitepage.property('clipRect', {top: 0, left: 0, width:3000,height:890}).then(function() {
                  sitepage.render(fname).then(function(finished) { 
                    console.log("\t\t\t---> finished");
                    sitepage.close();
                    phInstance.exit();
                    callback({msg: 'ok'})
                    phantom.exit();
                    return;
                  });
                });
          })
 
this approach kinda works, but it's really overwhelming for the cpu,
the problem is related to the fact that this way of doings things leads to 200 phantom processes that quickly eats up all the memory.

A more profitable way of doing so, would be to create a single phantom instance and then drive it to open 
one page at the time and render it, something that could be done with a phantom script, like so:

      var content, counter, f, fs, grab_screen, img, lines, next_screen, page, system, url;
      page = require('webpage').create();
      system = require('system');
      fs = require('fs');
      content = '';
      lines = [];
      url = '';
      img = '';
      counter = 0;

      page.viewportSize = {
        width: 1200,
        height: 800
      };

      page.settings.userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36';

      f = fs.open("sites.txt", "r");

      content = f.read();

      lines = content.split("\n");

      grab_screen = function() {
        var site;
        site = lines[counter];
        url = 'http://' + site + '/';
        img = 'screens/' + site + '.png';
        console.log("Grabbing screen for: " + url);
        return page.open(url, function(status) {
          return window.setTimeout(function() {
            page.render(img);
            counter++;
            return next_screen();
          }, 200);
        });
      };

      next_screen = function() {
        console.log("On to " + counter + " ...");
        if (counter < lines.length) {
          return grab_screen();
        } else {
          return phantom.exit();
        }
      };

      next_screen();

so I was wondering how to achieve that with phantomjs-node.
Thanks in advance.

Aaron.

### Environment
- OS: Max OSX - el cap
- Node version (`node -v`): 0.12.7
- package version: 2.0.10

**Comment by amir20** [comment]
If your goal is to execute all pages in parallel then I don't think any architecture will work. That's a lot of work on the CPU. And you will probably run out of memory first. 

You should be able to create on `phantom` instance and open & close multiple pages. I have tested it and it was able to do a lot at the same time as long as you limit it to 10 per second. This is a classic consumer / producer problem. 

Let me know how it works out. Hopefully, it works out for you.

**Comment by amir20** [comment]
Also upgrade nodejs if you can. It would help a lot.

**Comment by skysilence** [comment]
hi, @amir20 
as you said, it takes a lot of CPU and memory,I had two problems as blow:
1、I tested in diff machine with limit phantom num blow 200, but in some can start 60 phantom instances and some be 80 and some be 140 and some be 200, CPU and momery of all are not overload,what's the problem can lead to this, how can i use the cpu and momery more effective?
2、base on step 1, all of them I can consume 10 per second,no matter 80 or 200 phantom instances, is there some settings I didnot cover? 
how it works? 
Thanks in advance.
