### ISSUE TITLE
Page field not working ? 

### ISSUE THREAD

**Issue by jaumard** [amir20/phantomjs-node#453]
### Expected behavior

I'm trying to export a page to PDF file in A4 format. 

### Actual behavior

Nothing is generate and no errors. If I don't do `page.property ` pdf is generate but not in A4.

### Steps to reproduce the behavior
Example for google page : 
```
phantom.create().then(function (ph) {
    ph.createPage().then((page) => {
      page.property('paperSize', {
        width: '8.5in',
        height: '11in',
        header: {
          height: "1cm",
          contents: phantom.callback(function (pageNum, numPages) {
            return "<h1>Header <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
          })
        },
        footer: {
          height: "1cm",
          contents: phantom.callback(function (pageNum, numPages) {
            return "<h1>Footer <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
          })
        }
      }).then(() => {
        page.open("http://www.google.com").then((status) => {

          page.render('google.pdf').then(function () {
            console.log('Page Rendered');
            ph.exit();
          })
        }).catch(err => console.log(err))
      }).catch(err => console.log(err))
    }).catch(err => console.log(err))
  })
```
### Environment

- OS: OSX
- Node version (`node -v`): 4.4.2
- package version: 2.0.10

**Comment by amir20** [comment]
There is a test where it's almost identical to what you are doing here https://github.com/amir20/phantomjs-node/blob/master/src/spec/page_spec.js#L70. 

So it should work. I am guessing some error is being thrown and it's not being caught properly. Hm.....

**Comment by amir20** [comment]
It works for me locally. Make sure `phantom` is the instance of phantom that `phantom.create()` returns...
