### ISSUE TITLE
Trouble including Javascript files

### ISSUE THREAD

**Issue by ngzhongcai** [amir20/phantomjs-node#464]
Hi Amir, 

Thank you for this library. I am trying to generate Google Charts onto a PDF.
Using your library, I tried to "includeJS". 
Not sure if I am using it correctly.

```
page.open("test.html").then(function(err) {
    page.includeJS("https://www.gstatic.com/charts/loader.js").then(function() {
```

**Comment by ngzhongcai** [comment]
Similarly, how will you use "onLoadFinished"

**Comment by ngzhongcai** [comment]
I am using it as such...
```
page.open("test.html").then(function(err) {
	page.set("onLoadFinished").then(function() {
```

**Comment by ngzhongcai** [comment]
My own issue....
Needed to set time delay for page to render properly

**Comment by ngzhongcai** [comment]
Thanks Amir!

**Comment by amir20** [comment]
Nice.

**Comment by amirmog** [comment]
@ngzhongcai  Would you describe abit more how you fixed it?
Thanks

**Comment by ngzhongcai** [comment]
`age.open("report.html").then(function(err) {
					page.evaluateJavaScript("function() { google.charts.load('current', {'packages':['corechart']}); }").then(function() {
						setTimeout(function () {
							page.evaluate(function(instance) {
								render(instance);
							}, instance).then(function() {

**Comment by ngzhongcai** [comment]
report.html
```
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	... ...
</head>
```

**Comment by amirmog** [comment]
Thanks alot but I'm still unclear on how to properly use ``` includeJS ```
any full code snippet that works would be helpful.

Thanks

**Comment by ngzhongcai** [comment]
Didn't get to use `includeJS` eventually.
Instead I just embed the required JS file inside the HTML head.
See the 2 snippets.

**Comment by ngzhongcai** [comment]
Not sure if this is the right way to use PhantomJS. But in anycase, above snippets worked for me. I used page.evaluateJavaScript to invoke the JS function within the embeded JS file. And then a subsequent settimeout delay for the previous JS function to render the Google Charts properly before I PDF it.

**Comment by amirmog** [comment]
Great. And how does the ``` setTimeout ``` guarantee that the Google Charts is loaded before it is used?

**Comment by amir20** [comment]
@amirmog I am not sure what you are doing wrong but the following works for me. 

```js
var phantom = require('phantom');

phantom.create().then(function(ph) {
    ph.createPage().then(function(page) {

        page.includeJs('http://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js')
            .then(function(result) {
                console.log("Loaded jQuery!");
                console.log(result);
                ph.exit();
            });
    });
});
```

```
$ node bug.js
Loaded jQuery!
http://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js
```

**Comment by amirmog** [comment]
@amir20 Thanks alot, that works like a charm.

I try to use the jQuey object to detect when the page is fully loaded but I have no idea whether I'm doing it correctly or not.

`phantom.create().then(function(ph) {
    ph.createPage().then(function(page) {
        page.open('http://stackoverflow.com').then(function(status) {
            console.log(status);
            page.includeJs('http://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js')
                .then(function(result) {
                    console.log("Loaded jQuery!");
                    console.log(result);

                    page.evaluate(function(){
                        return jQuery;
                    }).then(function(jQuery){
                        console.log('------- jQuery obj is accessible here.', jQuery);
                        jQuery(page).ready(function() {
                            console.log('-------- Page is ready now.');
                            console.log( jQuery('html') );
                        });
                    });

                    ph.exit();
                });
        })
    });
});`

``` console.log('-------- Page is ready now.'); ``` and ``` console.log( jQuery('html') ); ```  never get called.

Any ideas what I'm doing wrong?
Thanks.

**Comment by amir20** [comment]
You can't return jquery. You can only return HTML or string. So you should do `return `jQuery('html')` in `evaluate`.

**Comment by amirmog** [comment]
Thank you very much @amir20 and @ngzhongcai 
It worked like a charm.
