### ISSUE TITLE
Scraping dynamic page

### ISSUE THREAD

**Issue by jgranduel** [amir20/phantomjs-node#465]
Hi !

I want to get the whole content of a site. I cannot use curl for instance, as the page is dynamic (made with angularJS) and should be rendered before being downloaded.
At the end, I've been able to do it with phantomJS (v-2.1.1). It requires using page.evaluate.

```
var url = "http://site/to/download"

var page = require('webpage').create();
page.open(url, function(status) {
    if (status === 'success') {
        var html = page.evaluate(function() {
            return document.documentElement.outerHTML;
        });
        console.log(html)
    }
    phantom.exit();
});
```

I want to stick with node, so I installed phantomjs-node. But I cannot make it work (I can download the original page, not the rendered one). What's the way to do it with phantomjs-node and Promises? If possible, could you add this kind of scraping example into your own examples, beside simple.js ?

Thanks in advance,

**Comment by amir20** [comment]
There is a lot of examples in issues that have talked about this. This should work. Just use `evaluate`. I won't go in to detail on how to do it because I think the source is pretty clear. Try it and if it doesn't work post what you have tried.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com or the [slack](https://phantomjs-node.herokuapp.com) chat room. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future.

**Comment by jgranduel** [comment]
Thank you for your answer.
Sorry for not posting in the right place, I hadn't found the places where to ask questions. Maybe it should be in the Readme? "I won't go in to detail on how to do it because I think the source is pretty clear" is pretty severe for new learners who have read the examples, but not all issues, I admit. 
Thanks anyway for this useful project.

**Comment by amir20** [comment]
@jgranduel  there is a slack room that you can join to ask questions.
