### ISSUE TITLE
phantom not working on EC2

### ISSUE THREAD

**Issue by kaustubh56** [amir20/phantomjs-node#469]
Hi,

I developed a code using this node phantom module.
The code runs successfully without any errors on my local system.
I deployed my code on amazon's EC2 instance, and phantom stopped working.
No errors are thrown, it just stops further execution when trying to create a phantom instance.

Are there any steps I need to perform separately on the EC2 instance to get phantom to work?

Edit 1:
I already tried rebuilding the prebuilt binary (npm rebuild).

Package versions I tried it with : 2.1.0, 2.1.1, 2.1.2
node version: 6.0.0

**Comment by amir20** [comment]
Does `phantom` binary work without `node`? If it doesn't then you probably need to figure out that out first. Also, look at #314. Next time search issues before opening issues.
