### ISSUE TITLE
Can't catch error after phantom is killed

### ISSUE THREAD

**Issue by Shtirlits** [amir20/phantomjs-node#470]
### Expected behavior

I'm searching the way to catch the error which is thrown while trying to use phantom after killing it. May be there is some kind of http://phantomjs.org/api/phantom/handler/on-error.html (if it is helpful) which is not referenced in the docs?

### Actual behavior

If I try to use `phantom` after doing `phantom.exit()` I receive 
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at Pipe.onread (net.js:550:26)
```

As you can see in the following code, I'm trying to catch the error in several places, but it does not work

### Steps to reproduce the behavior

```javascript
var phantom = require('phantom'),
    ph = null,
    sitepage = null,
    navigate;

try {
  phantom.create()
    .then(function(phInstance){
      ph = phInstance;
      ph.createPage().then(function(page){
        sitepage = page;
        navigate();
      })
    })
    .catch(function(e){
      console.log('PHANTOM.CATCH CAUGHT AN ERROR');
      console.log(e);
    });

  navigate = function () {
    sitepage
      .open('http://google.com')
      .then(function(){
        ph.exit();
        sitepage.evaluate(function(){
          console.log(11);
        })
      })
      .catch(function(e){
        console.log('PAGE.CATCH CAUGHT AN ERROR')
        console.log(e)
      })
  }
}
catch (e) {
  console.log('TRY/CATCH CAUGHT AN ERROR');
  console.log(e);
}
```

### Environment

- OS: Ubuntu 15.04 x64
- Node version (`node -v`): node v5.10.1 (npm v3.8.3)
- package version: 2.1.2

**Comment by amir20** [comment]
Hmm interesting. This error is being thrown INSIDE phantomjs. So I am not even sure if it is possible to capture it. Do you only care about catching `#exit()` or any error?

**Comment by Shtirlits** [comment]
Well, my main concern is catching `#exit()` error. But now I can see, that if I for example throw from here:
```javascript
      ph.createPage().then(function(page){
        sitepage = page;
        throw new Error('Custom Error');
        navigate();
      })
```
nothing happens.
The same is for this:
```javascript
  navigate = function () {
    throw new Error('Custom Error');
    sitepage
      .open('http://google.com')
```
Not sure if this is connected somehow, but looks weird to me as well.

**Comment by amir20** [comment]
I am not sure what you are doing. But when I do 

```js
var phantom = require('phantom');

phantom.create()
   .then(function(phInstance){
     throw Error("error here. boo.");
   })
   .catch(function(e){
     console.log('PHANTOM.CATCH CAUGHT AN ERROR');
     console.log(e);
   });
```

I do see 
```
PHANTOM.CATCH CAUGHT AN ERROR
Error: error here. boo.
    at Error (native)
    at /Users/amir.raminfar/Desktop/test_phantom/errors.js:5:12
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:445:3
```

**Comment by Shtirlits** [comment]
Yep, from there I'm seeing it too.

But from here:
```javascript
  var phantom = require('phantom'),
  phantom.create()
    .then(function(ph){
      ph.createPage().then(function(page){
        throw Error("error here. boo.");
        navigate();
      })
    })
    .catch(function(e){
      console.log('PHANTOM.CATCH CAUGHT ERROR');
      console.log(e);
    });
```

It throws nothing

**Comment by amir20** [comment]
That's obvious. You need to have a `catch` for `#createPage()`'s Promise. You probably want to chain it instead. If you get on the slack page, it would be easier. But you want do chaining of promise calls. Which is on the README.
