### ISSUE TITLE
Catching child process errors in phantom

### ISSUE THREAD

**Issue by btofel** [amir20/phantomjs-node#471]
Hi guys!

Is there any way to catch errors emitted by phantom instances from the node script that spawned the instances?

I tried to use the following:
`var phantom = require('phantom');
function getPageContent(url) {

    let phInstance = null;
    let results = [];

    return new Promise(
        function (resolve) {

                let openedPage = null;

                phantom.create(['--load-images=false', '--disk-cache=true'])
                    .then(instance => {

                        instance.process.on('uncaughtException', err=> {
                            console.log("I'm HIT!");
                            console.log(err);
                        });
                        phInstance = instance;
                        console.log(`PID: ${phInstance.process.pid}`);
                        phInstances.push(instance);
                        return instance.createPage();

                    }).then(page => {`

Process PID is printed so I assume that the process, in which phantom is running is exposed. But setting the `process.on('uncaughtException)'` has no effect.

How do I know? Well... when the instance is running and I (p)kill it, it throws `error: uncaughtException: read ECONNRESET`, which melts the node script. I'm pretty sure I'm doing something wrong and it should be possible to have catch all uncaught errors thrown by phantomjs child process. Can you point me in the right direction, please?

Or what I'm trying to do is impossible and the only way to make it work would be to add this handler inside 'phantomjs-node' code?

**Comment by amir20** [comment]
I don't think you are using `uncaughtException` correctly. I read the [doc](https://nodejs.org/api/process.html#process_event_uncaughtexception). It is only triggered when an exception happens in the current process in node. Phantom is a different process. 

Look at `phantom.js`. You probably want `this.process.stderr.on` or something like that.

**Comment by btofel** [comment]
Yeap, `process.on` refers to the current process in node. I was hoping that `instance.process.on('uncaughtException', err=> {
                        console.log("I'm HIT!");
                        console.log(err);
                    });` would set the handler on the child process, not on the current process, just like `instance.process.pid` return id of the child process, not of the current one. But obviously that's not working.

> Look at phantom.js. You probably want this.process.stderr.on or something like that. 

Are you suggesting that I should put the snippet to handle `uncaughtException` inside `phantom.js`? If so that's the solution I'd best avoid as I'd have to modify the file every time I update the version. Or did I get you wrong?

Thanks for a reply, by the way :-)

**Comment by amir20** [comment]
I don't think `uncaughtException` will ever work since that will only work inside a node process. You would have to catch something else like `error` or `stderr`. 

Also, `process` is public so you should be able to do `instance.process.stdout`. 

I am starting to think you are going the wrong direction for this. What are you really trying to do? I have already implemented `try...catch` so that promise's `catch` should work. Am I missing something else that you want? What is your use case?

**Comment by btofel** [comment]
:-)

Basically what I'm doing is scrapping thousands of pages using X concurrent phantom instances (usually 10), which are spawned using a random delay and who have a set timeout for opening the website (10 seconds usually as well). So depending on network conditions, number of spawned instances, timeout and delay values some phantom instances fail to open a page within the timeout. I close them using `.exit()` method and requeue the url. Usually `.exit()` works fine, but sometimes at the end of the scrapping phase I know there are some phantom instances, which failed to exit (`ps aux | grep phantomjs`) so I use 'pkill' to get rid of them. And that sometimes causes ERRCONSET error, which I'd like to catch, because after scrapping there are other operations, which I need to perform.

**Comment by amir20** [comment]
So instead of fixing the real problem, you want to catch the errors. 🐱 Shouldn't you figure out why `.exit()` doesn't work all the time? Right now, I send a message which causes phantom to exit. Sounds like instead, `exit()` should send the message AND do `process.kill`. That sounds like the right solution. Doing `ps aux` just sounds hacky to me.

**Comment by btofel** [comment]
Well... I just assumed that sometimes phantom becomes irresponsive and since I've seen people complaining about it here and there, well... I just figured that that's what I have to work with :-) I am not a fan of changing 3rd party libraries on my own as that is not maintainable in the long run.

Yeah, `ps aux` is hacky and OS-dependent, so definitely not the best solution (but better than leaking phantom instances, I assume).

`Process.kill()` seems like a better solution (thanks for pointing it out!), especially that I can easily put my hands on the `PID` of the child processes. Well... at least if it will work. If I send `SIGTERM` and phantom closes, then all good. But if it doesn't I'll need to send `SIGKILL` anyway and still could get `ERRCONSET` error in result.

**Comment by amir20** [comment]
>  I am not a fan of changing 3rd party libraries on my own as that is not maintainable in the long run.

I actually was suggesting you send a pull request so that I can merge it. ;)

**Comment by btofel** [comment]
Ha! Not the worst idea, I'll do that!

**Comment by amir20** [comment]
Any update on this?

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.
