### ISSUE TITLE
Planning to close the slack room

### ISSUE THREAD

**Issue by amir20** [amir20/phantomjs-node#472]
The slack chatroom [#phantomjs-node](https://phantomjs-node.herokuapp.com/) has been open for almost a month. During this time, I have only gotten four people interested. A lot of people ask random questions on issues that are better suited on slack. I am unable to get people to use slack. 

I plan to close the room in one week if there is no interest. It costs $7/month which is no big deal but no reason to keep it open if no one uses it. 

Ideas welcomed to make more people go on slack.

**Comment by fabiofumarola** [comment]
yes probably you can move to gitter
