### ISSUE TITLE
my customHeaders works, but I can not get excepted data!

### ISSUE THREAD

**Issue by swumao** [amir20/phantomjs-node#473]
### Expected behavior

I use phantomjs to get ajax data of a website written with laravel framework.

there is my code to set the customHeaders, token[1] is laravel's csrf _token.
```js
.then(content =>    {
   var patt1=new RegExp(/(?:content=")[a-z|A-Z|0-9]+(?=">)/);
   var token = patt1.exec(content);
   token = token.toString().split('"');
   sitepage.customHeaders = {
        'X-CSRF-TOKEN' : token[1],
        'Accept' : 'application/json',
        'X-Requested-With' : 'XMLHttpRequest'
    };
  return sitepage.open(server, 'POST', data);
  })
.then(status => {
     console.log(status);
     console.log(sitepage);// I can see the customHeaders here!
     return sitepage.property('content');
})
```
But when I run this code, laravel seems consider that I am do a csrf request!

And I print the cookies, It also looks normal!
 
### Actual behavior
I have a test code and can works correctly run with phantomjs not the nodejs.
```js
function post(server, data, callback) {
    page.open(server, 'post', data, callback);
}
// This function just for get the msg!
page.onConsoleMessage = function(msg) {
    var url = 'https://gamedataquery.sdo.com/ajax/getpaypoint';
    var data = 'date=2016-05-13+~+2016-05-20&area=(177)%E7%BB%8F%E5%85%B8%E5%9B%9E%E5%BD%92%E4%BA%8C%E5%8C%BA+-+all';
    page.customHeaders = {
        'X-CSRF-TOKEN' : msg,
        'Accept' : 'application/json',
        'X-Requested-With' : 'XMLHttpRequest'
    };
    post(url, data, function(status){
        console.log(status);
        console.log('----------------------------------------------\n');
        console.log(page.plainText);
    });
};

```
### Steps to reproduce the behavior

1. I don't know...

### Environment

- OS:Windows7
- Node version (`node -v`):6.2.0
- package version: 2.1.7

**Comment by amir20** [comment]
I have never used laravel framework. But you should use property to set customHeaders.

**Comment by swumao** [comment]
@amir20 Could you tell me how to use `property` to set a value? Please show me a sample example.

I have fixed this problem use phantom-prebuilt package.But I am still interested in this project.

**Comment by amir20** [comment]
I haven't tested it but something like `page.property('customHeaders', { ... })` should work. This is also in the README file. Please read it.
