### ISSUE TITLE
papersize  invalid

### ISSUE THREAD

**Issue by ibeeger** [amir20/phantomjs-node#474]
is my code  papersize invalid 

<pre>
var sitepage = null;
		var phInstance = null;
		phantom.create()
		    .then(function(ph){
		        phInstance = ph;
		        console.log(phInstance);
		        return phInstance.createPage();
		    })
		    .then(function(page){
		    	console.log(page);
		    	sitepage = page;
		    	sitepage.viewportSize = { width: 1200, height: 1570 };
		    	sitepage.paperSize = {
		    		 width: 1200, 
		    		 height: 1570,
					margin: 50,
					header: {
						height: 50,
						contents: phInstance.callback(function(pageNum, numPages){
							return  ;
						})
					},
					footer: {
						height: 50,
						contents:  phInstance.callback(function(pageNum, numPages) {
							return  
						})
					}
			 }
		        return sitepage.open(url);
		    })
		    .then(function(status){
		        if (status !="success") {
		        	process.send(null);
		        	return;
		        };
		        return sitepage.render(result.path,{format:type});
		    })
		    .then(function(content){
		    	process.send(null)
		        sitepage.close();
		        phInstance.exit();
		    })
		    .catch(error => {
		        console.log(error);
		        phInstance.exit();
		    });
</pre>

**Comment by amir20** [comment]
Please read the README. That's not how you set `paperSize`.
