### ISSUE TITLE
Css Printing Rules

### ISSUE THREAD

**Issue by salcam** [amir20/phantomjs-node#476]
### Expected behavior

I'm expected that a long text, auto breaking page. If I print the HTML page, the result is correct (3 pages), but if I convert in PDF with phantomJS, all zoom out in one page.

### Actual behavior

The HTML rendered in one page and when printing zoom out all

### Steps to reproduce the behavior

1. Create a page with css rules (
    ```
@page {
        size: A4;
        margin: 190mm 132mm 367mm 190mm;
    }
    
    @media print {
        html,
        body {
            width: 210mm;
            height: 297mm;
        }
    }
```
) and long paragraph (more than one page)
2. Run phantomjs on server with previous page

### Environment

- OS: OSx (El Captain)
- Node version (`node -v`): 6.2.0
- package version: 2.1.2

**Comment by amir20** [comment]
This seems to be related to `phantomjs` and not this module. I suggest trying it without node.

**Comment by salcam** [comment]
Thanks for response!

I've tested all with `phantomjs` and, with correct settings, all works! 

Now I've copied this settings in node, but doesn't works as I'm expext. This is my code (node):

`phantom.create().then(ph => {
        _ph = ph;
        return _ph.createPage();
    }).then(page => {
        _page = page;

        _page.paperSize = {
            format: 'A4',
            margin: {
                top: '1.9cm',
                left: '1.9cm',
                right: '1.32cm',
                bottom: '1.32cm'
            },
            footer: {
                height: '1cm',
                contents: _ph.callback(function (pageNum, numPages) {
                    return "<p style='text-align:center;'><span style='margin-left:auto;margin-right:auto;font-size:10px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;>- " + pageNum + " -<span></p>";
                })
            }
        };
        return _page.open('http://www.google.com');
    }).then(status => {
        if (status != 'success')
            return;

        return _page.render(pathFile);
    }).then(content => {
        var stat = fs.statSync(pathFile);
        fs.readFile(pathFile, function (err, data) {
            res.setHeader('Content-Length', stat.size);
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', 'inline; filename=report.pdf');
            res.send(data);
        });

        _page.close();
        _ph.exit();
    }).catch(err => {
        console.log(err);
        phInstance.exit();
    });`

**Comment by amir20** [comment]
Wait that's not how you set paperSize. You have to use property method. Look at the readme

**Comment by salcam** [comment]
Ok ok... Now works!

For the future:

I've replaced:

`_page.paperSize = {};`

with:

`page.property('paperSize', {...});`

Thank you! And sorry to don't understand README

**Comment by amir20** [comment]
@salcam I added a warning so this is more obvious. See 5d7d7ec103c4c68e27d12948b3b126d63586a955

**Comment by amir20** [comment]
Related https://github.com/amir20/phantomjs-node/pull/477

**Comment by salcam** [comment]
It's perfect!!! Thanks a lot
