### ISSUE TITLE
evaluate returns only null or Promise { <pending> }

### ISSUE THREAD

**Issue by lehtu** [amir20/phantomjs-node#479]
I have tried this many different ways and I'm always getting null or Promise { <pending> }
```
var element = sitepage.evaluate(function(x, y) {
 	return document.elementFromPoint(x, y).outerHTML;
}, x, y);
```

It should return HTML element from given location. 

Here is where I'm trying to achive this:
```
var phantom = require('phantom');
var sitepage;
var url = "http://amazon.com";
var ph;

phantom.create().then(function(phantomObj){
	ph = phantomObj;
	return ph.createPage();
}).then(function(page){
	var pageWidth = parseInt("1920px", 10);
	var pageHeight = parseInt(pageWidth * 3/4, 10);
	sitepage = page;
	sitepage.property('settings', {loadImages: false});    // * problem was caused by this line
	sitepage.property('viewportSize', { width: pageWidth, height: pageHeight });
	return sitepage.open(url);
}).then(function(status){
	if (status == "success") {
		var x = 888;
		var y = 777;

		var element = sitepage.evaluate(function(x, y) {
		 	return document.elementFromPoint(x, y).outerHTML;
		}, x, y);
		
		return element;
	}

	return '404';
}).then(function(content){
	console.log(content);

	sitepage.close();
	ph.exit();		
}).catch(function(error) {
	console.log(error);
	ph.exit();
});
```
Here is the example from README:
```
page.evaluate(function() {
    return document.getElementById('foo').innerHTML;
}).then(function(html){
    console.log(html);
});
```

Even if I try to return document.title or somehting else, still getting null or Pormise { <pending> }.

I have also tried that example found in README, but still no success. Or maybe I'm not using it right.. 

Any ideas, or is there anyone who got this working?

### Environment

- OS: OSX
- Node version: v4.4.4
- package version: 2.1.3

**Comment by amir20** [comment]
This is the right place to ask questions like this. I'll check it tonight when I get home.

**Comment by lehtu** [comment]
Okay, I solved the original issue and it was caused by this line `sitepage.property('settings', {loadImages: false});` (marked by * in issue). That line didn't cause error, but by removing that line I accidentally noticed that my code started working. Not sure if this should be a new issue?

**Comment by amir20** [comment]
You have to use a different method to set settings. See readme. 

Sent via my iPhone

**Comment by amir20** [comment]
Ok now that I am home. You need to use `page.setting(key)`
