### ISSUE TITLE
Is it possible to read and use *pages* property?

### ISSUE THREAD

**Issue by altieres** [amir20/phantomjs-node#481]
### Expected behavior

```
page.property('pages')
````

should return a new Page object which I can work on.

### Actual behavior

I get a json with "objectName: 'WebPage'" and some details about the page loaded.

There is a way to work with the open pages?

### Steps to reproduce the behavior

1. Load some page containing a link with target
2. Simulate a click on the link

**Comment by amir20** [comment]
I am not sure what you are saying. Steps say `Simulate a click on a link` but you are talking `pages.property('pages')`. It's unclear what you are asking.

**Comment by altieres** [comment]
Hi, Amir! Thanks for your reply.

If I'm clicking on a link with target="_blank" and another window is opened, I can get this throught page.pages on native phantom, but I don't know how to this with phantomjs-node.

Please see this attachment:

[problem-sample.zip](https://github.com/amir20/phantomjs-node/files/303775/problem-sample.zip)

Thanks, Altieres.

**Comment by amir20** [comment]
That's not supported. It returns the object, but phantomjs serializes it to json which node doesn't understand. It would probably be possible to add this support. Pull requests welcomed.

**Comment by altieres** [comment]
Ok, thanks!
