### ISSUE TITLE
IncludeJs and Alert

### ISSUE THREAD

**Issue by hugocar** [amir20/phantomjs-node#482]
Hi,

It seems that includeJs is opening an alert on the phantom runtime

```
        page.on('onInitialized',false,function () {
          if (page.includeJs('https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js'))
            console.log("jQuery injected");
          else
            console.error("jQuery injection failed");
        });
        page.on('onAlert',false,function (msg) {
          console.log(msg)
        })
```

### Expected behavior

No alert are expected

### Actual behavior

One onAlert event is fired and this is the message of the alert :
> https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js

### Steps to reproduce the behavior

Set the event handlers described above.
Load a page

**Comment by amir20** [comment]
What does this do in vanilla phantomjs?

**Comment by hugocar** [comment]
My bad,
Trying to reproduce it in phantom, I realized that unlike the method injectJs, the method inludeJs accept a callback argument.

Correct syntax would be

```
page.on('onInitialized',false,function () {      
         page.includeJs('https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js',function(){
            console.log("jQuery injected");
         });
});
```
