### ISSUE TITLE
doesn't work if node binary is called nodejs

### ISSUE THREAD

**Issue by dsvensson** [amir20/phantomjs-node#483]
If node is not called 'node', but in my case 'nodejs', phantom will fail to install.

    > phantomjs-prebuilt@2.1.7 install /home/blabla/bleble/node_modules/phantomjs-prebuilt
    > node install.js
    
    sh: 1: node: not found

npm config content:

    $ nodejs node_modules/.bin/npm config list
    ; cli configs
    user-agent = "npm/3.9.5 node/v0.10.29 linux x64"
    
    ; node bin location = /usr/bin/nodejs
    ; cwd = /home/blabla/bleble
    ; HOME = /home/blabla
    ; "npm config ls -l" to show all defaults.

I would expect it would use the same binary that called npm.

The workaround mentioned here seems like work that can be automated:
https://www.npmjs.com/package/phantomjs#im-on-debian-or-ubuntu-and-the-installer-failed-because-it-couldnt-find-node

**Comment by amir20** [comment]
Hmm this seems to be a problem with `phantomjs-prebuilt`. I don't support version < 3. There is a few missing features that you would need to have a polyfill. Since there is a workaround, and even they say they don't recommend it, then I am going to mark this as won't fix.
