### ISSUE TITLE
renderBuffer fails

### ISSUE THREAD

**Issue by stephenwithav** [amir20/phantomjs-node#484]
`page.renderBuffer` fails.

Modifying your example from #386 returns no output:

```
// bug.js
var input = '<h1>Hello word</h1>'
var output = 'file.pdf'

var phantom = require('phantom');

phantom.create([
  '--ignore-ssl-errors=yes',
  '--load-images=yes',
  '--local-to-remote-url-access=yes'
]).then(function(ph) {
  ph.createPage().then(function(page) {
    page.property('content', input).then(function() {
      page.renderBuffer('png', -1)
        .catch(function() {
          console.log('error');
          ph.exit();
        })
        .then(function() {
          console.log('success');
          ph.exit();
        });
    });
  });
});
```

It also fails after adding `renderBuffer` to `methods` in `page.js`.
### Expected behavior

`renderBuffer` should return a promise that provides a `Buffer`.
### Actual behavior

Node hangs, producing no output.

If I add `renderBuffer` to `methods`, this is the output:

``` error
success undefined
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1007:11)
    at Pipe.onread (net.js:563:26)
```
### Environment
- OS: Debian Jessie
- Node version (`node -v`): 6.2.1
- package version: 2.1.5

**Comment by elias-winberg** [comment]
The PhantomJS docs are slightly ahead, and [the pull request that adds 'page.renderBuffer'](https://github.com/ariya/phantomjs/pull/13345) hasn't been merged yet.

**Comment by stephenwithav** [comment]
Thank you, @elias-winberg.  That makes perfect sense.

**Comment by amir20** [comment]
Thanks @elias-winberg. That's right. Let's keep this open. We can have a PR to add this method.

**Comment by yhBluescape** [comment]
If possible may I know when will the PR plan to? We really need this method,...

By the way we haven't full support phantomjs object API, is it?

Thanks,

**Comment by amir20** [comment]
Someone needs to provide a PR for it. Wait for the PhantomJS API to get merged. Then released. Honestly, that's probably going to take a while. Since it depends on upstream changes, I wouldn't know.

**Comment by yhBluescape** [comment]
Thanks for the response,
If possible may I know what do you mean the PhantomJs  API merger ? The following API?

👍 http://phantomjs.org/api/webpage/method/render-buffer.html

var server = require('webserver').create();

var listening = server.listen(8001, function(request, response) {
	var url = "http://phantomjs.org", format = 'png', quality = -1;

	var page = require('webpage').create();

	page.viewportSize = {
		width: 800,
		height: 600
	};

	page.open(url, function start(status) {

		// Buffer is an Uint8ClampedArray
		var buffer = page.renderBuffer(format, quality);

		response.statusCode = 200;
		response.headers = {
			"Cache": "no-cache",
			"Content-Type": "image/" + format
		};
		page.close();

		// Pass the Buffer to 'write' to send the Uint8ClampedArray to the client
		response.write(buffer);
		response.close();
	});

});

**Comment by amir20** [comment]
Look above at @elias-winberg comment please.

**Comment by yhBluescape** [comment]
Thanks for the reply so fast,

 @elias-winberg comment is page#reload().  Does this mean page.renderBuffer depend on page#reload()?

Another funny things:
I could find any code with renderBuffer on PhantomJs src, plus the following sample is not run,... http://phantomjs.org/api/webpage/method/render-buffer.html 
Is the possible PhantomJs haven't implement the API?

**Comment by yhBluescape** [comment]
I fund that renderBuffer is in doc first, the PhantomJs haven't merge renderBuffer it yet,...
That is very rare open source , doc first ,...
https://github.com/ariya/phantomjs/issues/14285

**Comment by amir20** [comment]
Heads up, I am closing this bug as there is no actionable item for me.
