### ISSUE TITLE
Is is possible to change the key inside of a page property which is also an object?

### ISSUE THREAD

**Issue by legendtang** [amir20/phantomjs-node#490]
Look at https://github.com/ariya/phantomjs/blob/master/examples/netsniff.js:

```javascript
            page.onResourceReceived = function (res) {
                if (res.stage === 'start') {
                    page.resources[res.id].startReply = res;
                }
                if (res.stage === 'end') {
                    page.resources[res.id].endReply = res;
                }l
            };
```

How to change `page.resources[res.id]` using `page.property()`?

**Comment by amir20** [comment]
You can use `property` but I am not sure if it would work in `onResourceReceived`. Maybe someone else can help because I am not sure what you are trying to do.

**Comment by elias-winberg** [comment]
Try this:

```js
page.on('onResourceReceived', true, function (res) {
    if (res.stage === 'start') {
        this.resources[res.id].startReply = res;
    }
    if (res.stage === 'end') {
        this.resources[res.id].endReply = res;
    }
});
```

**Comment by legendtang** [comment]
@elias-winberg Thank you! I believe your way is working, and `this` should appear in docs example.

But here is what I find. Have a look at https://github.com/ariya/phantomjs/blob/master/examples/netsniff.js#L129

```JavaScript
    page.open(page.address, function (status) {
        var har;
        if (status !== 'success') {
            console.log('FAIL to load the address');
            phantom.exit(1);
        } else {
            page.endTime = new Date();
            page.title = page.evaluate(function () {
                return document.title;
            });
            har = createHAR(page.address, page.title, page.startTime, page.resources);
            console.log(JSON.stringify(har, undefined, 4));
            phantom.exit();
        }
    });
```

If we change to `phantom-node`, the code should be like this:

```js
        .then(page => {
            /* do something  */

            return page.open('http://www.yahoo.com')
        })
        .then(function(status) {
            var har;
            if (status !== 'success') {
                console.log('FAIL to load the address');
                phInstance.exit(1);
            } else {
                this.endTime = new Date();
                this.title = this.evaluate(function () {
                    return document.title;
                });
                har = createHAR(this.address, this.title, this.startTime, this.resources);
                console.log(JSON.stringify(har, undefined, 4));
                phInstance.exit();
            }
        })
```

However, in `page#open`, there is no reference to `WebPage` at all, `this` is `undefined`.

**Comment by amir20** [comment]
@legendtang, `#on` methods are bounded to `page` objects and that's why `this.resouces` work. But other methods are not bounded to `page`. That's why open doesn't work. It wouldn't be hard to add it but I wonder if it makes sense to do that because in vanilla phantomjs, it is also not bounded to this. 

Either way, we should figure out what you think should be done so that I can close or keep this ticket open.

**Comment by legendtang** [comment]
@amir20 Thank your for the explanation. I migrate to `child_process` with vanilla phantomjs eventually. I think `phantomjs-node` should find a proper way to fully support vanilla usage.

**Comment by amir20** [comment]
The goal of this module is not to support 100% vanilla phantomjs. That would be replicating every single phantomjs functionality which would be very difficult. That would be recreating phantomjs which isn't the goal. If you can get away using child_process then you should. But the goal of this module is to allow people communicate back and fourth between phantomjs and node easy. An example could be if you are trying to show a progressbar and you need to have hooks in nodejs to update the status. You can't do that with child_process.

**Comment by legendtang** [comment]
@amir20 That's excactly why I use `phantomjs-node` as a first choice before. I know a fully integration is not your goal. Like that example, my aim is to collect and to deal with the output with the property of page, and maybe to send back to phantomjs. Now using `child_process` I have to listen on process output add cut those strings down to what I want. And sometimes, you know, `child_process` would give half or two-combined lines (`\r\n`) which are very difficult to deal with that case. Well, I still like the ticket to be open with title changes. At least I think `page` should be bounded to more use cases

**Comment by amir20** [comment]
It sounds like you are trying to solve a lot of problems that were solved in this module. I spend at least a couple hours fixing `\r\n` in pipe. Could I somehow excited you to fix the problem in this module instead? It sounds like you are investing a lot of time in a solution that you are going to use, but giving back to an open source project could improve this for others and yourself in the future. 

Regardless of what you end up doing, thanks for the feedback. If there was an easy way to just support all vanilla features in regards to this particular ticket then I would gladly take a PR and help you merge it.
