### ISSUE TITLE
[Suggestion] Process Safety

### ISSUE THREAD

**Issue by zovt** [amir20/phantomjs-node#495]
Currently using this library for a program I'm working on. It involves a lot of PhantomJS pooling, and handling errors on pages.

Usually when an error is handled, the phantom worker calls `phantomInstance.exit()`. This works fine most of the time, however. it seems that if something inside the instance is still doing work e.g. a page, an ECONNRESET error is thrown. It would be lovely if we could solve that issue. I'll work on getting a minimal working example created, and would love to help solve this issue.

**Comment by zovt** [comment]
Seems that an update has solved this. I'll keep monitoring the server logs and will reopen this if this becomes an issue again.

**Comment by zovt** [comment]
Going to reopen this since I have a MWE done:

```
const phantom = require('phantom');

let page;
let ph = [];
for (let i = 0; i < 10; i++) {
	phantom.create()
		.then((res) => {
			ph[i] = res;
			setTimeout(() => {
				ph[0].exit(); // crash
			}, 4000);
			return ph.createPage();
		})
		.then((p) => {
			page = p;
			return page.open('https://google.com');
		})
		.then(() => {
			page.evaluate(function () {
				while (true) { };
			}).then(() => { console.log('hello'); });
			page.open('https://reddit.com');
		});
	console.log('helo');
}
```

**Comment by zovt** [comment]
I have a feeling that this (and a related error of externally causing the phantom process to exit causing ECONNRESET errors) are due to the heartbeat trying to read a closed socket. Not entirely sure though

**Comment by amir20** [comment]
I used to force the process to be [killed](https://github.com/amir20/phantomjs-node/pull/477/commits/2adfef51009fa46efdc12002a3453d072f1d0254) but it broke Travis tests so I reverted it. 

You can try adding it back in to see if it solves the problem.

Regarding what you were saying about the heartbeat, it is definitely possible that this is happening. I just got your example running locally. Let me try it out and see where the error is actually being thrown. 

Just to be clear, what is the expected or preferred behavior?

**Comment by amir20** [comment]
@zovt when I run your example, nothing happens. It just hangs. How are you running it? Are you getting an error?

**Comment by zovt** [comment]
here's a better example:
```
const phantom = require('phantom');
const exec = require('child_process').exec;
const longjohn = require('longjohn');

let page;
let ph;

phantom.create()
	.then((p) => {
		ph = p;
		exec('killall phantomjs');
	})
	.then(() => ph.createPage())
	.then((p) => { page = p; })
	.then(() => {
		console.log('opening page');
		return page.open('google.com');
	})
	.then(() => {
		page.render('test.png').catch((e) => {
			console.log("failed to render" + e);
			throw e;
		});
		page.evaluate(function() { while(true) { console.log("blah"); }; })
			.catch((e) => {
				console.log('failed to eval' + e);
				throw e;
			});
	})
	.catch((e) => {
		console.log(`!!! Child process error: ${e} !!!`);
		console.log(e.stack);
	})
	.then(() => {
		console.log('end');
	});
console.log('hello');
```
I've created a patch that I'll make a PR for. It catches errors on the stdin (which is what was throwing them errors) and then rejects all of the commands in the map.
