### ISSUE TITLE
Design pattern to use to loop over a series of pages?

### ISSUE THREAD

**Issue by giacecco** [amir20/phantomjs-node#503]
This is not a bug but a request for advice. What design pattern do you suggest to use phantomjs-node to interpret multiple pages within the same session, e.g. in the classic case where the results of a search are split over several pages, and I would lose the "session" if I instantiated a new phantomjs for each page? 

The promises-based syntax is confusing me, and I would welcome your suggestions.

**Comment by amir20** [comment]
It depends how scalable you want it to be. If this is a small project and you are just trying to get results then you have two options. 

1) Create multiple phantom processes and then call `async.parallel` to wait for all. This obviously heavy and it might take a lot of memory depending how many pages you have. This has been tested so I know it works. Look in the example directory `cluster.js`
2) Create one instance of phantom and then open each page sequentially or in parallel. I haven't tested this, but given that it uses unique ids for different pages, it should work. Theoretically. :) 

The above is the easy way of course. 

The more scalable way which I would recommend if you plan to do this _a lot_ is to have a simple queuing system. Something like this:

1) Have a consumer batching process which looks for items on a queue and process each one. 
2) Wait a new session opens, put all these pages on to the queue
3) You can return immediately and then use AJAX to check the status of the jobs. You can show progress bar and whatever. 
4) Is your load going to triple? Just create more batch process machines to consume the queue faster. 

Hopefully this all makes sense. You also might want to try stackoverflow.

**Comment by giacecco** [comment]
Thanks @amir20 . 

Why do you say (1) would work? Wouldn't the different phantomjs instances be independent? I could not share the session created by the very first search.

(2) is what I was thinking of, too, but how do you make a loop of ```.then()_```?

Load is not going to be massive in my case, but I would like to design the thing properly anyway.

**Comment by amir20** [comment]
I thought you meant the session of the user who is requesting. I am guessing you mean the session in phantomjs. You are right that the different process would be independent. You would have to use cookies like this [example](http://stackoverflow.com/questions/14824798/phantomjs-and-sessions) if you want to really share sessions. I am just not sure how to get the first page's cookies out. 

For (2), you wouldn't loop and look for all promises. You can either block for all promises using `Promise.all` which I wouldn't recommend because it could take a while. Or return immediately and then in your front-end (or whatever UI) use AJAX requests to update status on progress.

**Comment by giacecco** [comment]
Thanks a lot. I guess I am still too new to promises to understand your advice on (2), unfortunately. If you have no time to give me more hints, just close the issue and I'll study what is needed. Thanks!

My script is silent, so no need to care to the front-end, just need to go through ~40 results pages, collect the results and write them somewhere for post-processing.

**Comment by amir20** [comment]
Unfortunately, I don't have any sample code to share. The idea behind promises are that you can join them all and block. Here is a good example https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all. 

I am going to close the issue but will try to respond if you respond. Good luck.
