### ISSUE TITLE
Example script from README.md throws TypeError: bad argument

### ISSUE THREAD

**Issue by Grayda** [amir20/phantomjs-node#506]
### Expected behavior

Example mentioned in README.md should run

### Actual behavior

Example doesn't run, with the script returning

> TypeError: Bad argument
>     at TypeError (native)
>     at ChildProcess.spawn (internal/child_process.js:278:26)
>     at exports.spawn (child_process.js:367:9)
>     at new Phantom (C:\xampp\htdocs\sizer\node_modules\phantom\lib\phantom.js:97:49)
>     at C:\xampp\htdocs\sizer\node_modules\phantom\lib\index.js:16:20
>     at Object.module.exports.create (C:\xampp\htdocs\sizer\node_modules\phantom\lib\index.js:15:10)
>     at Object.<anonymous> (C:\xampp\htdocs\sizer\index.js:5:9)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:456:32)

### Steps to reproduce the behavior

1. Create a new folder, `npm init` to get it set up
2. Run `npm install --save phantom`
3. Create a new file called index.js, copy and paste the whole example under the [Super Easy To Use](https://github.com/amir20/phantomjs-node#super-easy-to-use) section in there
4. Make sure phantomjs is installed (I used `npm install -g phantomjs-prebuilt`)
5. Run `node index.js`

### Environment

- OS: Windows 10, x64
- Node version (`node -v`): node 6.1.0
- package version: 2.1.12

**Comment by amir20** [comment]
When you do `phantomjs -v` does it work? I don't have Windows so I can't really debug this.

**Comment by amir20** [comment]
@Grayda I installed a new [image](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) to Virtualbox. Installed NPM and ran the example from README.  I was able to follow your instructions and get stackoverflow output. 

I am not sure what's going on. See if `phantomjs` works without node.

**Comment by Grayda** [comment]
`phantomjs` worked fine, as I was able to modify my script to run without using your library, so no issues there I think. 

Not sure of exact version (not on that PC at the moment), but it's the most recent version of phantomjs-prebuilt, which is 2.1.7

**Comment by amir20** [comment]
Hmm bummer. Closing.

**Comment by amir20** [comment]
@Grayda try this. Run with `DEBUG=true node /path/to/file.js` and paste what it outputs.

**Comment by Grayda** [comment]
I'll give it a shot when I get back to the machine I was on. 

I did notice that your code doesn't seem to be at fault (there's no mention of your library in the stack trace), but I'll give it a shot anyway and see. Hopefully it's an easy fix.

**Comment by amir20** [comment]
Cool. Btw, I spent a lot of time trying to figure out how to do `DEBUG=true` in Windows. I was able to install `cross-env` with `npm install -g cross-env` and then doing `cross-env DEBUG=true node file.js` and it works. You should see something like

```
C:\Users\IEUser\Desktop\test>cross-env DEBUG=true node index.js
debug: Starting C:\Users\IEUser\Desktop\test\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe C:\Users\IEUser\Desktop\test\node_modules\phantom\lib\shim.js
debug: Sending: {"id":"ffd1f6c82c92112f81ba43060a56cf7b","target":"phantom","name":"createPage","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"ffd1f6c82c92112f81ba43060a56cf7b","target":"phantom","name":"createPage","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"},"response":{"pageId":"ffd1f6c82c92112f81ba43060a56cf7b"}}
```

**Comment by Grayda** [comment]
You can also do `set DEBUG=true && node file.js`to set environment variables in Windows. 

I'll post some output later this afternoon (about 2-3 hours until I finish work)

**Comment by Grayda** [comment]
Righto, got home, ran `phantomjs -v`, got `2.1.1`. Set `DEBUG=true`, ran my script, and got:

`debug: Starting null C:\xampp\htdocs\sizer\node_modules\phantom\lib\shim.js`

So I followed it back, and found that

`var phantomPath = typeof config.phantomPath === 'string' ? config.phantomPath : _phantomjsPrebuilt2.default.path;`

In `lib/phantom.js` on line 89 returns `null`, so looks like the path to phantomJS is not being detected correctly. That might be an upstream issue, but I haven't had enough time to check it out fully yet

**Comment by amir20** [comment]
Well at least now we are getting somewhere! That line was changed recently in a pull request to allow changing `phantomPath`.  Either it introduced a bug or as you suspected it is related to `phantomjs-prebuilt`. 

I think the easiest way to debug this is open up node and doing:

```require('phantomjs-prebuilt').path```

If that doesn't work then something is up with your machine and phantomjs.

**Comment by elias-winberg** [comment]
https://github.com/Medium/phantomjs/issues/533 might be related? The installation of `phantomjs-prebuilt` is most likely unsuccessful.

**Comment by amir20** [comment]
Nice find @elias-winberg. I think we should add `if(path == null) throw Error()` statement so that this is more clear in the future. I don't see a solution though in that ticket. :(

**Comment by elias-winberg** [comment]
@Grayda try this:

```bash
$ cd node_modules/phantomjs-prebuilt
$ node install.js
```

**Comment by Grayda** [comment]
@elias-winberg Nope, not running out of memory, but running the install script for phantomjs-prebuilt fixed the issue. Now my script runs, no problems at all!

**Comment by amir20** [comment]
OK closing then.
