### ISSUE TITLE
page.on(...) does not work.

### ISSUE THREAD

**Issue by prashantjain68** [amir20/phantomjs-node#509]
Why does this code break or hangs my application ...
```
                page.on("onConsoleMessage", function () {
                    //ignore the trash coming from the page
                });
                page.on("onError", function () {
                    //ignore the trash coming from the page
                });  
```
### Expected behavior
Console messages and JavaScript errors should be handled through these functions.

### Actual behavior
After executing the first line, control does not come back to my app and my nodejs app hangs.

### Steps to reproduce the behavior

        phantom.create(['--ignore-ssl-errors=yes', '--load-images=no']).then(me.busyCounter.callback(function(ph) {
            me.phamtonInstance = ph;
            ph.createPage().then(me.busyCounter.callback(function(page) {
                me.phantomPage = page;

                //spoof as a real browser
                // page.settings.userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36';
                page.setting("javascriptEnabled", true);
                page.setting("loadImages", false);
                page.setting("resourceTimeout", 60000);
                page.on("onConsoleMessage", function () {
                    //ignore the trash coming from the page
                });
                page.on("onError", function () {
                    //ignore the trash coming from the page
                });                 
            }));
        }));

### Environment
nodejs

- OS:
OSX

- Node version (`node -v`):
v4.0.0

- package version: 
v2.0.9

**Comment by amir20** [comment]
```js
var phantom = require("phantom");
phantom.create(['--ignore-ssl-errors=yes', '--load-images=no']).then(function(ph) {
    ph.createPage().then(function(page) {
        page.on("onConsoleMessage", function() {
            //ignore the trash coming from the page
        });
        page.on("onError", function() {
            //ignore the trash coming from the page
        });

        page.open('http://stackoverflow.com/').then(function() {
            console.log('done');
            ph.exit();
        })
    });
});
``` 

seems to work for me.

**Comment by prashantjain68** [comment]
I finally updated to 2.1.7 and it is working now.

thanks
