### ISSUE TITLE
How to check response.statusCode at the callback when page.open()

### ISSUE THREAD

**Issue by lcoder** [amir20/phantomjs-node#510]
![image](https://cloud.githubusercontent.com/assets/5225853/17047640/a5d7bb18-5012-11e6-9bdd-db186e319e31.png)

**Comment by elias-winberg** [comment]
[You have to listen to the `onResourceReceived` event to get the HTTP status code.](http://stackoverflow.com/questions/30221204/how-can-i-see-the-http-status-code-from-the-request-made-by-page-open)

**Comment by amir20** [comment]
Thanks @elias-winberg

**Comment by lcoder** [comment]
非常感谢！完美解决了我的疑问。😄

**Comment by kdekooter** [comment]
How would this SO code translate to phantomjs-node? A code sample would be highly appreciated!
