### ISSUE TITLE
phantomjs hangs or no response

### ISSUE THREAD

**Issue by prashantjain68** [amir20/phantomjs-node#511]
After making the call 
me.phantomPage.open(trackingRequestParams.url).then(function(status) { ... }
the callback should be invoked.

[Describe expected behavior here]
callback should be invoked with the status

### Actual behavior
callback not being invoked

[Describe observed behavior here]
hangs

### Steps to reproduce the behavior
In functionA, I have code ...
        phantom.create(['--ignore-ssl-errors=yes', '--load-images=no']).then(me.busyCounter.callback(function(ph) {
            me.phamtonInstance = ph;
            ph.createPage().then(me.busyCounter.callback(function(page) {
                me.phantomPage = page;

                //spoof as a real browser
                // page.settings.userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36';
                page.setting("javascriptEnabled", true);
                page.setting("loadImages", false);
                page.setting("resourceTimeout", 60000);
                page.on("onConsoleMessage", function () {
                    //ignore the trash coming from the page
                });
                page.on("onError", function () {
                    //ignore the trash coming from the page
                });                 
                page.on("onAlert", function () {
                    //ignore the trash coming from the page
                });                 
            }));
        }));

In functionB ...
        me.phantomPage.close();
        me.logScrapeBegin(record, shipping_number, callback, trackingRequestParams.url);        
        me.phantomPage.open(trackingRequestParams.url).then(function(status) {
            if (status === "success") {
                me.onPhantomJSPageReady(record, shipping_number, callback, trackingRequestParams.url);
            } else {
                console.log("Error occurred");
            }
        });

The  me.phantomPage.open(...) line is invoked but the callback is never called.

### Environment
nodejs version: v4.0.0
phantom module version: 2.1.7
phantomjs: 2.1.1

- OS: OSX
- Node version (`node -v`): v4.0.0
- package version: 2.1.7

**Comment by prashantjain68** [comment]
Interesting thing is that this worked yesterday but something went wrong today.

**Comment by prashantjain68** [comment]
and I keep getting these messages from phantomjs when running with DEBUG=true ...

debug: Parsing: {"id":"a16e51c634e32634df3828810f8fde7d","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"af817ffcafb6f0fbae95a72b775a490b","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"af817ffcafb6f0fbae95a72b775a490b","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"ff22fcc3fc3ef514cd5e489ce05a1ce5","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"ff22fcc3fc3ef514cd5e489ce05a1ce5","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"7cca217b2193d4caae55c46e8ab0d49c","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"7cca217b2193d4caae55c46e8ab0d49c","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"0c578e18521703ca3195c1b7b870f5a4","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"0c578e18521703ca3195c1b7b870f5a4","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"2695ec8790b4bed12ca493c0338edc46","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"2695ec8790b4bed12ca493c0338edc46","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Sending: {"id":"7fc92f4770572cf02b08d1f398ba9578","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}
debug: Parsing: {"id":"7fc92f4770572cf02b08d1f398ba9578","target":"phantom","name":"noop","params":[],"deferred":{"resolve":"function () { [native code] }","reject":"function () { [native code] }"}}

**Comment by amir20** [comment]
Can you give me a gist so I can locally? I can't make sense of your code. Like I don't know what `me.busyCounter.callback` is?

**Comment by prashantjain68** [comment]
sorry about that. Let me give you something better

**Comment by prashantjain68** [comment]
Amir, I dont know how to create a gist. But here are the 2 functions. I will create a gist if you are unable to use them. AND thanks a mil for your help.

    doBegin() {
        var me = this;

        phantom.create(['--ignore-ssl-errors=yes', '--load-images=no']).then(function(ph) {
            me.phamtonInstance = ph;
            ph.createPage().then(function(page) {
                me.phantomPage = page;

                //spoof as a real browser
                // page.settings.userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36';
                page.setting("javascriptEnabled", true);
                page.setting("loadImages", false);
                page.setting("resourceTimeout", 60000);
                page.on("onConsoleMessage", function () {
                    //ignore the trash coming from the page
                });
                page.on("onError", function () {
                    //ignore the trash coming from the page
                });                 
                page.on("onAlert", function () {
                    //ignore the trash coming from the page
                });    

                me.scrapePhantomJS();
            });
        });

        super.doBegin();
    }


    scrapePhantomJS() {
        var me = this,
            trackingRequestParams = "http://track.dtdc.com/ctbs-config-admin/customerInterface.tr?submitName=showCITrackingDetails&cType=Consignment&cnNo=M38395233";

        me.phantomPage.close();
        me.phantomPage.open(trackingRequestParams).then(function(status) {
            if (status === "success") {
                // me.phantomPage.injectJs('./public/libs/jquery-2.2.2.min.js').then(me.busyCounter.callback(function() {
                //     me.onPhantomJSPageReady(record, shipping_number, callback, trackingRequestParams.url);
                // }));
                console.log("Page sucessfully loaded");
            } else {
                console.log("Error occurred");
            }
        });
    }

**Comment by amir20** [comment]
sorry I still can't run it. I think it's part of a bigger script that you are not sharing. Give me a file that I can run with `node <file.js>`. 

On a different note, why do you `close()` the page and then open a new page. That doesn't look right.

**Comment by prashantjain68** [comment]
[phantomDebug.js.txt](https://github.com/amir20/phantomjs-node/files/380334/phantomDebug.js.txt)

Amir,
The reason I close is because I reuse the same page to load multiple web pages for scrapping. I read that closing releases the memory of the previous page. I could be wrong here so please advise the best practice.

I even commented the .close but still doesnt work and it is very difficult to debug all this.

**Comment by prashantjain68** [comment]
BTW, I have attached a fully working file.

**Comment by amir20** [comment]
The problem is what I expected...

I changed your code to 

```js
phantomPage.open(url).then(function(status) {
        console.log('status = ' + status);
    }).catch(function(e){
      console.log(e);
    });
```

With the output

```
Error: undefined is not an object (evaluating 'target[command.params[0]]')
    at Liner.<anonymous> (/Users/amirraminfar/Workspace/phantomjs-node/examples/node_modules/phantom/lib/phantom.js:115:37)
    at emitOne (events.js:96:13)
    at Liner.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Liner.Readable.push (_stream_readable.js:135:10)
    at Liner.Transform.push (_stream_transform.js:128:32)
    at Array.forEach (native)
    at Liner.transform [as _transform] (/Users/amirraminfar/Workspace/phantomjs-node/examples/node_modules/linerstream/index.js:20:9)
    at Liner.Transform._read (_stream_transform.js:167:10)
    at Liner.Transform._write (_stream_transform.js:155:12)
```

Like I was saying. You can't close a page and the expect to open it again. You have to do `createPage` again. I changed your code to:

```js
var scrapePhantomJS = function() {
    var url = "http://track.dtdc.com/ctbs-config-admin/customerInterface.tr?submitName=showCITrackingDetails&cType=Consignment&cnNo=M38395233";
    // phantomPage.close();
    phantomPage.open(url).then(function(status) {
        console.log('status = ' + status);
    }).catch(function(e){
      console.log(e);
    });
}
```

Which prints
```
$ node phantomDebug.js                                                
status = success
```

It takes a really long time though. I looked at the `url` and it is very slow. The page takes over 5 seconds to load.

**Comment by prashantjain68** [comment]
Amit, thank you very much for the support. I know this is managed by one person which is you. But you are very responsive and helpful.

Thanks

**Comment by prashantjain68** [comment]
I meant Amir.
