### ISSUE TITLE
phantomjs-node works fine locally but won't run on PaaS Openshift Nodejs Catridge

### ISSUE THREAD

**Issue by samtran123** [amir20/phantomjs-node#512]
I have my phantomjs-node works fine on local Mac server. But when it won't run on Openshift or produce any error. It just runs like there is no phantom code in the server. Even the most simple codes from [phantomjs-node example](https://github.com/amir20/phantomjs-node/tree/master/examples) won't run. I have tried many ways including:
 - [manually install phantomjs on Openshift](https://blog.openshift.com/screen-scraper-as-a-service/) and pass the path to phantom 
`var phantomjsPath = '/var/lib/openshift/579977de2d52715ddc000001/app-root/data/phantomjs/bin/phantomjs';
phantom.create([], {phantomPath: phantomjsPath}).then(function(ph) { ...}`
- or using path from phantom-prebuilt node_modules installed via npm
`var phantomjsPath = '/var/lib/openshift/579977de2d52715ddc000001/app-deployments/current/repo/node_modules/phantom/node_modules/phantomjs-prebuilt/bin/phantomjs';`

code I tried works fine on local but won't work on Openshift:
`console.log('phantom start');

var phantom = require("phantom");

 var util = require("util");
    console.log(util.inspect(phantom, {showHidden: false, depth: null}));
console.log("phantom: %j", phantom);
console.info('phantom: ' + phantom);

console.log('phantom after require phantom');

var _ph, _page, _outObj;
console.log('phantom after initialize _ph, _page, _outObj');

phantom.create([], {phantomPath: phantomjsPath}).then(function(ph) {
console.log('phantom after phantom.created');
  
    _ph = ph;
    return _ph.createPage();
console.log('phantom after reuturn createPage');
  
}).then(function(page) {
    _page = page;
    return _page.open('https://example.com/');
}).then(function(status) {
    console.log(status);
    return _page.property('content')
}).then(function(content) {
    console.log(content);
    _page.close();
    _ph.exit();
});

console.log('phantom end');`

It will log out:
`// phantom start
// { create: [Function] }
// phantom: {}
// phantom: [object Object]
// phantom after require phantom
// phantom after initialize _ph, _page, _outObj
// phantom end
`

I have googled and tried almost every tricks on stackoverflow but haven't got any results. Thing is it won't show a error. Which is harder to investigate.

Much appreciate if you guys can help me out. And great works so far, guys.

- OS: Local: Mac El Captian, Server: Openshift Nodejs 0.10
- Node version (`node -v`): 5.9.0
- package version: npm version: 3.7.3
- phantomjs-node version: 2.0.x

**Comment by amir20** [comment]
Your code is not very clear for me to understand what is going. But Openshift has been a big topic. I would first check to see if `phantomjs -v` actually works. If it doesn't, then that's your problem and you need to fix it. You may have to install dependencies. I can't help you there because I have never used OpenShift.  

If it does work, then re-run with `DEBUG=true` so I can see the path to where PhantomJs is installed. 

If you are familiar with Docker then here is a file that I know works. 

```
FROM ubuntu:15.10
MAINTAINER Amir Raminfar <findamir@gmail.com>

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_5.x | bash -
RUN apt-get install -y nodejs build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev

RUN npm install phantom co

COPY simple.js simple.js
```

**Comment by samtran123** [comment]
Phantom does get installed and run on openshift. I could shh to openshift and check version, run demo file, echo "hello ghost" on phantom cli. It even can capture screen shoot follow [this tutorial](https://blog.openshift.com/screen-scraper-as-a-service/). I could download the photo and verify it works. However, when integrate with Nodejs, nothing happens. The preceding code is from your repo example. This is my code:
`
//SERVER machine path to phantomjs
var phantomjsPath = '/var/lib/openshift/579977de2d52715ddc000001/app-root/data/phantomjs/bin/phantomjs';

console.log('before phantom');
crawlBac(phantomjsPath);
console.log('after phantom');

function crawlBac(phantomjsPath){ //open phantomjs and crawlBac
  var phantom = require('phantom');
  var url = 'http://www.minhngoc.net.vn/xo-so-truc-tiep/mien-bac.html';
  var _ph, _page, _outObj;

phantom.create([], {phantomPath: phantomjsPath}).then(function(ph) {
  _ph = ph;
  return _ph.createPage();
}).then(function(page) {
  _page = page;
  return _page.open(url);
}).then(function(status) {
  console.log('**Open status for: ' + url + ' : ' + status);
    
  var container = [];
  
  var runJob = schedule.scheduleJob('*/3 * * * * *', function() { //schedule job
  
    _page.evaluate(function() {
		var dai = document.querySelector('#box_tructiepkqxs > div.box_kqxs.box_kqxstt_mienbac > div.content > div > table > tbody > tr > td > table > tbody > tr:nth-child(1) > td.ngay > div > span.tinh_loai_ve > a').innerText;
		var selector = "";
		switch(dai) {
			case "Bắc Ninh": selector = 48; break;
			case "Hà Nội": selector = 46; break;
			case "Hải Phòng": selector = 49; break;
			case "Nam Định": selector = 50; break;
			case "Quảng Ninh": selector = 47; break;
			case "Thái Bình": selector = 51; break;
			default: throw new Error ('Selector does not have this dai: ' + dai);
		};
    return [
			{
				mien: "Bắc",
				dai: document.querySelector('#box_tructiepkqxs > div.box_kqxs.box_kqxstt_mienbac > div.content > div > table > tbody > tr > td > table > tbody > tr:nth-child(1) > td.ngay > div > span.tinh_loai_ve > a').innerText,
				//ngay: document.querySelector('#box_tructiepkqxs > div.box_kqxs.box_kqxstt_mienbac > div.top > div > div > div > div.title').innerText,
				dacBiet: document.querySelector('#giaidb_' + selector).innerText,
				nhat: document.querySelector('#giai1_' + selector).innerText,
				nhi1: document.querySelector('#giai2_1_' + selector).innerText,
				nhi2: document.querySelector('#giai2_2_' + selector).innerText,
        
//				ba1: document.querySelector('#oclock').innerText,
				ba1: document.querySelector('#giai3_1_' + selector).innerText,
        
				ba2: document.querySelector('#giai3_2_' + selector).innerText,
				ba3: document.querySelector('#giai3_3_' + selector).innerText,
				ba4: document.querySelector('#giai3_4_' + selector).innerText,
				ba5: document.querySelector('#giai3_5_' + selector).innerText,
				ba6: document.querySelector('#giai3_6_' + selector).innerText,
				tu1: document.querySelector('#giai4_1_' + selector).innerText,
				tu2: document.querySelector('#giai4_2_' + selector).innerText,
				tu3: document.querySelector('#giai4_3_' + selector).innerText,
				tu4: document.querySelector('#giai4_4_' + selector).innerText,
				nam1: document.querySelector('#giai5_1_' + selector).innerText,
				nam2: document.querySelector('#giai5_2_' + selector).innerText,
				nam3: document.querySelector('#giai5_3_' + selector).innerText,
				nam4: document.querySelector('#giai5_4_' + selector).innerText,
				nam5: document.querySelector('#giai5_5_' + selector).innerText,
				nam6: document.querySelector('#giai5_6_' + selector).innerText,
				sau1: document.querySelector('#giai6_1_' + selector).innerText,
				sau2: document.querySelector('#giai6_2_' + selector).innerText,
				sau3: document.querySelector('#giai6_3_' + selector).innerText,
				bay1: document.querySelector('#giai7_1_' + selector).innerText,
				bay2: document.querySelector('#giai7_2_' + selector).innerText,
				bay3: document.querySelector('#giai7_3_' + selector).innerText,
				bay4: document.querySelector('#giai7_4_' + selector).innerText,
				uniqueId: document.querySelector('#box_tructiepkqxs > div.box_kqxs.box_kqxstt_mienbac > div.content > div > table > tbody > tr > td > table > tbody > tr:nth-child(1) > td.ngay > div > span.tinh_loai_ve > a').innerText + document.querySelector('#box_tructiepkqxs > div.box_kqxs.box_kqxstt_mienbac > div.top > div > div > div > div.title').innerText
			}
		];
}).then(function(title) { //collected result will be stored in 'title' variable
    
    //put all collected giai into a same array
    documentCollectedResults(title, container);
     
    console.log('most reliable container[0].ba1 is: ' + mode(container[0].ba1));
    console.log('container[0].ba1 is: ' + container[0].ba1);
  
    //choose result has highest or greater than 3 occurance to prepare for pushing to db
    var final = finalize(container);
    
    console.log('final.length: ' + final.length);
    
    //put selected results to db
    toDb(final);
    
    //printBac: print raw collected result each time 
    printBac(title);
    
  });
}); //schedulte runJob
  function stopRunJob(){
    runJob.cancel(); //stop capturing data on phantom browser
    _page.close(); //close phantom browser
    _ph.exit(); //exit phantom instance
    console.log('*** runJob done');
  };
  setTimeout(stopRunJob, 120000); //crawl for 25mins = 1,500,000 miliseconds
});  //end page.open => then
}; //end function crawlBac
`

When I run it on my Mac, it produces:

`
Server is listening on 127.0.0.1:8080
before phantom
after phantom
Connected correctly to DB
**Open status for: http://www.minhngoc.net.vn/xo-so-truc-tiep/mien-bac.html : success
colRes[j].uniqueId: Hà NộiTRỰC TIẾP XỔ SỐ MIỀN BẮC - 28/07/2016
container.length: 1
most reliable container[0].ba1 is: 
container[0].ba1 is: 66587
final.length: 1
******************************************
          Truc Tiep Xo So Mien Bac        
dai: Hà Nội
giai DB: 03248
giai nhat: 74117
giai nhi: 29171 47822
giai ba: 66587 08301 80145 75388 97944 85768
giai tu: 1437 3299 1093 3787
giai nam: 8821 3813 1504 7528 7141 0799
giai sau: 076 949 706
giai bay: 26 10 69 46
uniqueId: Hà NộiTRỰC TIẾP XỔ SỐ MIỀN BẮC - 28/07/2016
******************************************
duplicate record found, updating that record...
done
`

But on openshift server it only gives:

`
DEBUG: Sending SIGTERM to child...
DEBUG: Running node-supervisor with
DEBUG:   program 'server.js'
DEBUG:   --watch '/var/lib/openshift/579977de2d52715ddc000001/app-root/data/.nodewatch'
DEBUG:   --ignore 'undefined'
DEBUG:   --extensions 'node|js|coffee'
DEBUG:   --exec 'node'
DEBUG: Starting child process with 'node server.js'
DEBUG: Watching directory '/var/lib/openshift/579977de2d52715ddc000001/app-root/data/.nodewatch' for changes.
Server is listening on 127.0.0.1:8080
before
after
Connected correctly to DB
Connected: 1 connected


`



I haven't used Docker before, but I will look at it. I assume that I will have to wrap up all my code with Docker and deploy it along with wrapper to Openshift?

**Comment by samtran123** [comment]
I found a working example with [phridge](https://github.com/demille/screenshot-service.git). Looking closer to their dependancies, [phantomjs-node](https://github.com/amir20/phantomjs-node) and [phridge](https://www.npmjs.com/package/phridge) both use [phantom-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) or [phantomjs](https://www.npmjs.com/package/phantomjs) as executable file. So I think there should be a way to make phantomjs-node works with openshift...

**Comment by amir20** [comment]
There is a bug with `phantomjs-prebuilt` Can you try with `phantomjs-prebuilt@2.1.9`?

**Comment by samtran123** [comment]
I'll try 2.1.9 and let you know.

**Comment by amir20** [comment]
Also, I don't have Openshift. So this is really hard for me to test.

**Comment by samtran123** [comment]
Update: 2.1.9 still doesn't work. But i found [phridge](https://www.npmjs.com/package/phridge) can work with the same code I developed with [phantomjs-node](https://github.com/amir20/phantomjs-node). I think we can close this issue for now. Thank you for your accompany!

**Comment by amir20** [comment]
I guess I was hoping we can figure out why this isn't working. But I give up. :)
