### ISSUE TITLE
 Recovery console messages and errors

### ISSUE THREAD

**Issue by cissok** [amir20/phantomjs-node#513]
### Hello,

I wish my script shows me the console messages and the execution of Javascript errors on my page.

Can you tell me if I use the right methods  ?

`
            page.property('onError', (msg) => {
                console.log('msg onError -> ' msg);
            });
`
`
            page.property('onConsoleMessage', (msg) => {
                console.log('msg onError -> ' msg);
            });
`

### Environment

- OS: OSX 10.11.6
- Node version : v4.4.7

**Comment by amir20** [comment]
Try
 ```page.property('onError', function(msg) { console.log('msg onError -> ' msg); }); ```

because I am pretty sure you can't do `=>` unless you compile to es6
