### ISSUE TITLE
Page Send Event

### ISSUE THREAD

**Issue by sauravskumar** [amir20/phantomjs-node#518]
I am trying to do a keypress with phantomjs on a page...

`page.sendEvent('keypress', page.event.key.A, null, null, 0x02000000 | 0x08000000);`

this works on phantomjs... how can we let key the keypress event to happen with this library? 

Couldn't find anything in docs related to sendEvent... Please if you can add an example...

Thank you in advance

**Comment by amir20** [comment]
Hi. This `sendEvent` is implemented. But `page.event.key.A` is not. You have to find the value for that yourself. 

```
phantomjs> page.event.key.A
65
```

Remember that this is just a wrapper around phantomjs so not everything is implemented. There is a difference between NodeJS and PhantomJS. If you need 100% features then just using PhantomJs is the better option.

**Comment by sauravskumar** [comment]
@amir20 i am new to this project... do we have to invoke `page.sendEvent` with `page.invokeMethod('sendEvent')`?

I was using this in vanilla phantom script: page.sendEvent('keypress', page.event.key.A, null, null, 0x02000000 | 0x08000000);

Can you  please guide me how to convert this for your project... will be really grateful to you for your help

**Comment by elias-winberg** [comment]
You can use `page.sendEvent` but, as @amir20 said, you'll have to find the `key` value yourself, and you can do just that [here](https://github.com/ariya/phantomjs/blob/master/src/modules/webpage.js#L468). As you can see `page.event.key.A` corresponds to the number 65, so your snippet could be rewritten as:

```js
page.sendEvent('keypress', 65, null, null, 0x02000000 | 0x08000000)
```

**Comment by sauravskumar** [comment]
@elias-winberg I am stuck with this for around 3 weeks now... i just cannot get the keypress event working... (it works when i write a script for phantomjs through cli)

My code:
```
phantom.create()
      .then(instance => {
        phInstance = instance;
        outObj = phInstance.createOutObject();
        outObj.urls = [];
        return instance.createPage();
      })
      .then(pagex => {
        page = pagex;
        page.setting('userAgent','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36');
        return page.open(`http://xyz.com`);
      })
      .then((data)=> {
        page.invokeMethod('sendEvent', 'keypress', 65, null, null, 0x02000000 | 0x08000000);
        return 1
      })
      .then(data2=> {
        page.close();
        phInstance.exit();
        res.send(data2 + ' ')
      })
      .catch(error => {
        console.log(error);
        phInstance.exit();
      });
```
Can you please tell why this is not able to fire keypress event....??? i would be very thankful for your help

**Comment by elias-winberg** [comment]
There are various issues with your code, but I tried to resolve them. Let me know if it works.

```js
phantom.create()
    .then(instance => {
        phInstance = instance;
        outObj = phInstance.createOutObject();
        outObj.urls = [];
        return instance.createPage();
    })
    .then(pagex => {
        page = pagex;
        return page.setting('userAgent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36');
    })
    .then(() => {
        return page.open(`http://xyz.com`);
    })
    .then(status => {
        return page.evaluate(function (selector) {
            document.getElementById(selector).value = '1234';
            return document.getElementById(selector).value;
        }, 'myInput');
    })
    .then(data => {
        return page.sendEvent('keypress', 65, null, null, 0x02000000 | 0x08000000);
    })
    .then(data => {
        res.send(data + ' ');
        phInstance.exit();
    })
    .catch(error => {
        console.log(error);
        phInstance.exit();
    });
```

**Comment by sauravskumar** [comment]
@elias-winberg Really Thankful to you for your kind help... it worked !! Cheers!.... Can you please help me out on more thing... is there a way to wait for 
`page.property('onResourceRequested', function (requestData,networkRequest, out) {}` function to end before sending the `res.send()`... i am using the [this way](https://github.com/amir20/phantomjs-node#pageproperty) (last part with `outObj`) to save some of the urls and the send it as response... but the res.send() is fired before `onResourceRequested` is finished.. i can see the needed  urls in console and in the outObj... Thank You again... you saved my day...

**Comment by elias-winberg** [comment]
Can you not send the data once the 'onLoadFinished' event is emitted?

**Comment by sauravskumar** [comment]
@elias-winberg let me explain... the page loads.. the keypress fires an ajax... which gives me some required urls... can `onLoadFinished` be setup for the ajax request which is fired after page has loaded and keypress event has happened ?? (I think that the `onLoadFinished` fires only for initial page load- not after that). Thank you
