### ISSUE TITLE
require('phantom') overrides global.Promise?

### ISSUE THREAD

**Issue by richardgirges** [amir20/phantomjs-node#520]
I'm using Bluebird in a node v4.x environment by overriding the global.Promise:

```javascript
// Override global Promise with bluebird
global.Promise = require('bluebird');

// Use bluebird-specific promisify
let readdir = Promise.promisify(require('fs').readdir);
```
^ this works fine

However, after importing the phantom package, it looks like the global.Promise gets reset:

```javascript
// Override global Promise with bluebird
global.Promise = require('bluebird');

// Import phantomjs-node
const phantom = require('phantom');

// Use bluebird-specific promisify
let readdir = Promise.promisify(require('fs').readdir);
```
^ this throws the following error:

```
TypeError: Promise.promisify is not a function
    at module.exports.Promise.map.readdir.then.fileNames.then.router.get.getDocs.then.router.get.absPaths
```

It looks like the Promise gets overridden by the phantomjs-node package on the global scope. Any ideas on how to get around this? Ideally we can tell phantomjs to utilize a specific Promise library (i.e. Bluebird)

### Environment

- OS: Mac OS X v10.11.6
- Node version: v4.3.`
- package version: 2.1.15

**Comment by amir20** [comment]
I actually don't have any dependencies on other `Promise` libraries. See [package.json](https://github.com/amir20/phantomjs-node/blob/master/package.json#L26). Maybe one of the dependencies is doing something. 

I wanted to make sure to not break something like this. Some people were trying to use promise with Node version < 4 and they have to include `promise-es6` manually. 

I'll do some investigation. But nothing stands out right now.

**Comment by amir20** [comment]
I ran this files

```js
global.Promise = require('bluebird');
require('phantom');
console.log(Promise.promisify)
```

And got 
```
$ node test.js
[Function]
```

**Comment by richardgirges** [comment]
I just ran the exact same test as you and got undefined:

```

**Comment by amir20** [comment]
I just tried `4.3.1` and it worked

```bash
⟩ node -v
v4.3.1
⟩ node test.js
[Function]
```

I don't know how else to reproduce it. :(

**Comment by amir20** [comment]
Since I can't reproduce with the exact same version of node, I am going to guess that it is related to your env or something else that might be changing your environment. 

Do you know docker? Could you try to reproduce somewhere besides your laptop?

**Comment by richardgirges** [comment]
I have one more interesting thing that happened.

Some of my developers were not able to reproduce the issue either. However, after deleting their node_modules directory and reinstalling bluebird and phantom from scratch, they all consistently reproduced the problem.

I will look into getting you a docker environment with this issue replicated. Thanks for the quick follow up!

**Comment by amir20** [comment]
I was able to reproduce the problem after delete `node_modules` as well. But then I was never able to get it to work again. However, it was interesting that if I ran `node` and then just pasted the contents of the test above, then it worked. 

I also noticed that removing that directory, and trying to do `require('bluebird')` still worked somehow. I don't get how that is possible since it is not installed globally. 👎 

I'll have to do more investigation. Let me know if you find something new, but I am started to think this might not be related to this module and possibly a bug with `npm` or `node`.

**Comment by amir20** [comment]
I noticed that `gulp-eslint@3.0.1` has a dependency on bluebird. I am going to try a brand new install and see where that gets me.

**Comment by amir20** [comment]
I think I found a problem. `phantomjs-prebuilt` has a dependency on `es6-promise`. It overrides `es6-promise` 👎 Not sure how to go about fixing that. 

However, when I do require phantom and then bluebird -- it works. I am going to label this as upstream dependency.

**Comment by amir20** [comment]
Possibly related to https://github.com/stefanpenner/es6-promise/issues/140#issuecomment-232202162

**Comment by amir20** [comment]
Closing due to lack of response.

**Comment by richardgirges** [comment]
@amir20  thanks for looking into this. It looks like the es6-promise issue you pointed out is what's causing the `global.Promise` override. 

As a work-around for the time-being, we're going to re-override the `global.Promise` after importing the `phantom` package. If the upstream dependency resolves the issue and you update the phantomjs-node package afterwards, we would appreciate a heads up.

Cheers

**Comment by amir20** [comment]
@richardgirges I depend on `"^2.1.4"` for phantom-prebuilt so if they update it with a later version of `es6-promise` then it should just work. If I release an update, I'll let you know.
