### ISSUE TITLE
.evaluate does not return anything good

### ISSUE THREAD

**Issue by kaytrance** [amir20/phantomjs-node#521]
I cannot understand why result of `.evaluate` equals `null` in my example.

```
whatever.queryForLink = function(url) {
    var self = this;
    return new Promise((resolve, reject) => {
        var ev = self.page.evaluate(() => {
            return "YABADABADOO";
        }).then( answer => {
            console.log("Answer", answer); // expecting here YABADABADOO, but got null instead.
        }).catch(error => {
            console.log("ERRR", error);
        });
        console.log("ev:", ev); // here I get lib$es6$promise$promise$$Promise object.. Oo
    });
};
```

I have stripped page creation and other processes and left only a problematic function. Also I tried to add `onError` for `page` object hoping that any clues will come up by this, but no such events were raised.

What really confuses me that I get `null` in console. Why null? If for some reason nothing is returned from evaluation, I would expect at least to get `undefined`..

Using phantomjs-node version 2.1.14

**Comment by elias-winberg** [comment]
It looks like `evaluate` doesn't work with arrow functions for some reason.

**Comment by amir20** [comment]
Yea. `=>` doesn't work because phantomjs doesn't understand the arrow. I am not sure if it is a bug but perhaps we can convert `=>` to `function(){}`?

**Comment by elias-winberg** [comment]
Yea, I guess it's working as intended, but it'd be nice to be able to to use arrow functions consistently. Do you think we should convert '() => {}' to 'function() {}' [here](https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L169)?

**Comment by amir20** [comment]
@elias-winberg that is where it would be. I never thought it was a bug because if you use babel then it would work without making any changes. But now this is the fourth time someone has added this as a bug. We have two options:

1. Fix it so that `=>` works
2. Throw a big huge error saying you can't use `=>`

I can do either one later next week or you can give it a try to. Happy to review whatever.

**Comment by amir20** [comment]
I didn't really fix the problem but I did add the error and warning log.

**Comment by amir20** [comment]
@kaytrance what's your status on this issue? Did you try using `function` and does it work now?

**Comment by kaytrance** [comment]
Sorry for delay. I have tried to change arrow function syntax to normal `funciton()` and it worked, so the issue can be closed.
