### ISSUE TITLE
request amouts  is limited to ten

### ISSUE THREAD

**Issue by sanrudongfeng** [amir20/phantomjs-node#522]
I'm try to splider a page that xhr amouts is more than ten,
add listener to request:
page.property('onResourceRequested', function(requestData, networkRequest) {
        //     console.log(requestData.url);
        // });
when eleventh request is just like this:
console 'info: TypeError: Attempting to configurable attribute of unconfigurable property.'I think that due to  xhr amouts. 
  is there  a way to solve this problem?
### Environment

- OS:
-os:win10 1607
- Node version (`node -v`):v6.2.2
- package version: "phantom": "^2.1.15", "phantomjs-prebuilt": "^2.1.12"

**Comment by amir20** [comment]
I don't really understand what you are saying. Perhaps try to include a minimal working example that can reproduce this bug.

**Comment by amir20** [comment]
Closing due to lack of response.

**Comment by skysilence** [comment]
I got a problem that i consume requests with ten pre seconds.

**Comment by amir20** [comment]
This is most likely an upstream dependency. 

Sent via my iPhone
