### ISSUE TITLE
Failing on instance.createPage()

### ISSUE THREAD

**Issue by joedunu** [amir20/phantomjs-node#525]
### Expected behavior

Return a promise for creating page

### Actual behavior

Failing with 'error:  TypeError: undefined is not a function' at line: /phantom/lib/phantom.js:240:56

### Steps to reproduce the behavior

1. create phantom session:  phantom.create([], undefined)
2. phantomSession.createPage() 

`function createPhantomSession() {`
`  var defer = Q.defer();`
`  if (phantomSession) {`
`    defer.resolve(phantomSession);`
`  } else {`
`    var params = undefined;`
`    // Phantom path override option`
`    if (config.phantom.path) {`
`     params = {phantomPath: config.phantom.path};`
`    }`
   ` phantom.create([], params).then(function (ph) {`
    `  console.info('New phantom session created');`
   `   phantomSession = ph;`
`      defer.resolve(phantomSession);`
`    })`
`  }`
`  return defer.promise;`
`}`

`return createPhantomSession().then(function () {`
 `   return phantomSession.createPage();`
 ` }).then(function (page) {`

### Environment

- OS: UBUNTU 14.04.5
- Node version (`node -v`): 0.12.9
- package version: 2.1.16

**Comment by amir20** [comment]
I assume this is happening because `params` is `undefined`. That would be expected results. Is it not the case for you?

**Comment by velutha** [comment]
Hey, 
I am facing the exact issue. I just tried a sample example. Here is my code.
var phInstance = null
var sitepage = null
phantom.create()
      .then(function(instance){
          phInstance = instance;
          return instance.createPage();
      })
      .then(function(page){
          sitepage = page;
          return page.open(site);
      })
      .then(function(status){
          return sitepage.property('content');
      })
      .then(function(content){
          res.send(content);
          sitepage.close();
          phInstance.exit();
      })
      .catch(function(error){
          res.send(error);
          phInstance.exit();
      });
package version: 2.1.16
node version: 0.12.7
phantomjs version: 2.1.1
os: OS X El Capitan

**Comment by amir20** [comment]
> node version: 0.12.7

That node version is not supported.

**Comment by velutha** [comment]
Hey,
So I updated my node to latest version. Works as intended now. Thank you.

**Comment by amir20** [comment]
@joedunu I will close tomorrow if I don't hear anything from you...

**Comment by joedunu** [comment]
I updated the node version and it worked for me too. So I would be happy to close this issue.
