### ISSUE TITLE
The Page#goBack() test randomly fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by elias-winberg** [amir20/phantomjs-node#528]
### Expected behaviour

The test should always be successful.

### Actual behaviour

The test randomly fails with the error:
```bash
Failures: 
1) Page #goBack()
1.1) Expected 'hi, /test2' to equal 'hi, /test1'.

68 specs, 1 failure
Finished in 7.6 seconds
[timestamp] 'test' errored after 9.07 s
[timestamp] Error in plugin 'gulp-jasmine'
Message:
    Tests failed
npm ERR! Test failed.  See above for more details.
```

### Steps to reproduce the behaviour

1. Clone the repository (`git clone https://github.com/amir20/phantomjs-node.git`)
2. Install the dependencies (`npm install`)
3. Run the tests (`npm test`)

### Environment

- OS: Ubuntu 14.04
- Node version (`node -v`): v6.3.1
- package version: 2.1.17

**Comment by elias-winberg** [comment]
[It looks like it fails for Travis CI at times too.](https://travis-ci.org/amir20/phantomjs-node/jobs/153461364)

**Comment by amir20** [comment]
I noticed that too. I wasn't sure what was going on. Any ideas?

**Comment by elias-winberg** [comment]
Oh, I think `Page#goBack` might be asynchronous.

**Comment by amir20** [comment]
You maybe right. I couldn't find any documentation on `goBack`. If that fixes it then let's have a PR and merge.

**Comment by amir20** [comment]
This is now fixed.
