### ISSUE TITLE
Clean up API documentation 

### ISSUE THREAD

**Issue by amir20** [amir20/phantomjs-node#530]
This is a placeholder for myself and others if they want to help out. But we need to remove the API from the README file and create a new page that is much cleaner. Right now the API is getting really long. The best option is to move the current API docs from README to `doc` directory or somewhere else. 

If anybody wants to help, please send me a message!

**Comment by raghudevan** [comment]
is the current api correct?

**Comment by Lizhooh** [comment]
It can be written in Wiki.

**Comment by wll8** [comment]
Can I help you?

**Comment by amir20** [comment]
Hey @wll8, I wanted to use gitbooks. I was hoping to split the current README file in to smaller sections so it's easier to follow. It would take at least a couple of hours. I would love any help. I haven't had time to clean this up.

**Comment by wll8** [comment]
@amir20 Ok, I see. I will finish it before the weekend and send `pull requests`.

**Comment by amir20** [comment]
I created a gitbook access. @wll8 let me know your email and I can send it to you. This would really help the community! Thanks again.

**Comment by wll8** [comment]
@amir20 I have used [docsify](https://docsify.js.org) and I have already done some work. If you prefer gitbook, take a look at the results of docsify.

**Comment by amir20** [comment]
Docsify is fine. Whatever is easiest. 

Sent via my iPhone

**Comment by wll8** [comment]
@amir20 Has submitted ` pull requests`.
