### ISSUE TITLE
page.evaluate does not return null correctly

### ISSUE THREAD

**Issue by gitgrimbo** [amir20/phantomjs-node#536]
### Expected behavior

`null` should be returned as the `then()` argument after `evaluate()`.

`null` is serialised to `"null"` and should be deserialised back to `null`.

````js
JSON.parse(JSON.stringify(null))
null
````

### Actual behavior

The result of `page.evaluate()` is a promise resolving to the empty string.

### Steps to reproduce the behavior

        return page.evaluate(function () {
          return document.querySelectorAll(".pageRow").length > 0 ? true : null;
        }).then(function(result) {
          // Expected: result === null
          // Actual: typeof result === "string" && result === ""
        });

### Environment

- OS: Win 7
- Node version (`node -v`): v6.3.0
- package version: 2.1.19

**Comment by amir20** [comment]
But what would happen if you return "null"? Or a string that is invalid json.

**Comment by amir20** [comment]
Hmm I guess `JSON.parse(JSON.stringify("test"))` -> `"test"`. So that does work. I can take a pull request or fix it next week. 👍

**Comment by amir20** [comment]
ugh I took a look at this and I think it should already work. Because I noticed that I parse the JSON and convert the response to object.  https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L77

**Comment by gitgrimbo** [comment]
Strange.  This is what I am seeing:

````
debug: Sending: {"id":"e87b7fe54762122b44a83f7433f45fc1","target":"page$651eb09ad9737c3b09a244f34fca9c7a","name":"invokeMethod","params":["evaluate","function () {\r\n      return null;\r\n    }"]}
debug: Parsing: {"id":"ec5f6507d0c85530cae6550e799a9e1d","target":"phantom","name":"noop","params":[]}
debug: Parsing: {"id":"e87b7fe54762122b44a83f7433f45fc1","target":"page$651eb09ad9737c3b09a244f34fca9c7a","name":"invokeMethod","params":["evaluate",null],"response":""}
debug: Sending: {"id":"b2058dd02fd884f92aeb0668f393c5d8","target":"phantom","name":"noop","params":[]}
````

Evaluate command (should return `null`):

`["evaluate","function () {\r\n      return null;\r\n    }"]`

Evaluate response (empty string):

`["evaluate",null],"response":""`

**Comment by amir20** [comment]
I did a simple test with PhantomJs because I couldn't figure out what was going on...

```js
var webPage = require('webpage');
var page = webPage.create();

page.open('http://m.bing.com', function(status) {

  var test = page.evaluate(function() {
    return null;
  });

  console.log(test === "");
  phantom.exit();

});
```

This is actually an issue with PhantomJS. So I am closing. Nice find though.
