### ISSUE TITLE
Attempting to set page.clipRect causes an error rather than printing a warning

### ISSUE THREAD

**Issue by gitgrimbo** [amir20/phantomjs-node#537]
### Expected behavior

No error, but a warning should be printed. `Phantom.this.logger` is `undefined`?

### Actual behavior

````
TypeError: Cannot read property 'warn' of undefined
    at Object.set (...\node_modules\phantom\lib\phantom.js:210:40)
````

Which is these lines:

https://github.com/amir20/phantomjs-node/blob/v2.1.19/src/phantom.js#L139..L142

````js
set: function (target, prop) {
    this.logger.warn(`Using page.${prop} = ...; is not supported. Use page.property('${prop}', ...) instead. See the README file for more examples of page#property.`);
    return false;
}
````

### Steps to reproduce the behavior

````js
    .then(() => page.clipRect = { top: 0, left: 0, width: hvWidth, height: hvHeight }; )
````

### Environment

- OS: Win 7
- Node version (`node -v`): v6.3.0
- package version: 2.1.19

**Comment by amir20** [comment]
Thanks for the find.

**Comment by gitgrimbo** [comment]
I think I used the old syntax (which I have rectified in my own code), but in case anyone else makes the same mistake ...

**Comment by amir20** [comment]
I fixed it.
