### ISSUE TITLE
Error: Cannot find module './internal/applyEach'

### ISSUE THREAD

**Issue by scopsy** [amir20/phantomjs-node#538]
When trying to install package from npm i'm receiving this error. apparently something to do with asyncjs lib deep dependency somewhere. 

### Actual behavior
> phantomjs-prebuilt@2.1.12 install /home/app/node_modules/phantom/node_modules/phantomjs-prebuilt
> node install.js

/odule.js:327
throw err;
^
Error: Cannot find module './internal/applyEach'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/home/app/node_modules/request/node_modules/form-data/node_modules/async/applyEach.js:7:18)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

### Environment

- OS: ubuntu 14.04
- Node version (`node -v`): 4.4.3
- package version:  2.1.20

**Comment by amir20** [comment]
I wasn't able to reproduce this using docker. I did

```
apt-get install curl
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install nodejs
apt-get install build-essential
npm i phantom
```

My guess is that something is messed up with `phantomjs-prebuilt`. This has happened in the past. You can try install latest version of phantomjs so that the node package just skips over it. Otherwise, I'd report this to `phantomjs-prebuilt` instead.

**Comment by missmansirao** [comment]
Hello..

While I was working with [NodeJS](https://goo.gl/SW4gfs) Developer's Install wiki page, this error "**module.js:538 Error: Cannot find module 'internal/util/types'**" encountered and got to struck here. Need help.

![nodejs-1](https://user-images.githubusercontent.com/33026737/32313241-e45e318e-bfc7-11e7-9223-f438607d9877.png)
![nodejs-2](https://user-images.githubusercontent.com/33026737/32313243-e49dc6fa-bfc7-11e7-9f6b-f50d5ff5734b.png)

Suggestions/Corrections/Help appreciated.
