### ISSUE TITLE
I cannot use CPU 100%

### ISSUE THREAD

**Issue by skysilence** [amir20/phantomjs-node#539]
hi, @amir20 
as you said, it takes a lot of CPU and memory,I had two problems as blow:
1、I tested in diff machine with limit phantom num blow 200, but in some can start 60 phantom instances and some be 80 and some be 140 and some be 200, CPU and memory of all are not overload,what's the problem can lead to this, how can i use the cpu and memory more effective?
2、base on step 1, all of them I can consume 10 requests per second,no matter 80 or 200 phantom instances, is there some settings I did not cover? 
how it works? 
Thanks in advance.

- OS: mac osx
- Node version (`node -v`): 0.12.x
- package version: 2.1.15

**Comment by amir20** [comment]
You can never have that many instances running on one machine. For starters, upgrade to latest node. You need to have multiple machines to be able to scale horizontally.  

If you set up 10 machines where each can process 10 then you can process a total of 100. 

Sorry I can't help more. Maybe try stackoverflow. 

Sent via my iPhone
