### ISSUE TITLE
Share current variable value between nodejs and phantomjs

### ISSUE THREAD

**Issue by voidmonk** [amir20/phantomjs-node#543]
### Expected behavior

When an event listener is registered to run in the phantomjs process, and a parameter variable passed from the nodejs process, the variable value should be current on subsequent event calls. The value should change if it changes in nodejs, or there should be a way to pass the updated value to the phantomjs process for event listeners.

### Actual behavior

The parameter variable value is unchanged (i.e. doesn't change in event if it changes in nodejs).

```node
let param = 1;
page.on('onResourceRequested', true, function (requestData, networkRequest, param) {
    // value of param will always remain as 1 on subsequent event calls,
    // even though it changes in the nodejs process
    console.log(param);
}, param);
param = 2;
```

### Environment

- OS: Ubuntu Server 16.04
- Node version (`node -v`): 6.4.0
- package version: 2.1.19

**Comment by amir20** [comment]
This is not a bug. It works as designed. Once the request is sent to phantom process then changes in node will not reflect in phantom. If you can think of a way to support that then let me know but otherwise it works exactly as documented.

**Comment by voidmonk** [comment]
@amir20 Thanks for clarifying. In that case, what would be the best way to send a variable from nodejs to phantomjs that's accessible during the `onResourceRequested` event but after its definition? Is there a way to set global variables or something similar that's shared between the two processes? I'll appreciate your insight on this matter.

**Comment by amir20** [comment]
You should try running it in nodejs instead with that second parameter being false. If you need to abort then I am not sure. :(

**Comment by voidmonk** [comment]
@amir20 Yeah, it looks tricky. Is there a way to have a global variable that retains its value across `onResourceRequested` event calls within the phantomjs context? I'm trying to abort all network requests after a certain request URL.

**Comment by amir20** [comment]
No. Nothing is shared. It is actually a different process. I wish it was that easy. This module is there to solve that problem. However, there are still limitations. 

If you know the url then just write if statesmen or check in the callback. That should work.  Otherwise you may need to open the page twice. 



Sent via my iPhone

**Comment by voidmonk** [comment]
@amir20 I'm not sure if an `if` statement will suffice. Here's an example of what I'm trying to do:

```node
page.on('onResourceRequested', true, function (requestData, networkRequest) {
    if (loadedAbc) // previously requested requestData.url was for abc.com; abort any further requests
        networkRequest.abort();
}
```

I'm not sure how to persist `loadedAbc` from a past `requestData.url` check.

**Comment by amir20** [comment]
I am at work so it's hard to test this out. But couldn't you 

```js
page.on('onResourceRequested', true, function (requestData, networkRequest, memory) {
  if(memory.foo === undefined){
    memory.foo = false;
  }
  // next call will have memory.foo set to false
}, {}); // <-- note empty object
```

**Comment by voidmonk** [comment]
@amir20 Hey that worked! Thanks for the workaround. Just wondering, why doesn't it work if the parameter (memory) is a boolean variable instead of an object?

**Comment by amir20** [comment]
It's the same reason why this works. 

```js
function foo(changeMe){
   chamgeMe = false;
}
let x = true;
foo(x);
x // <-- still true

function bar(changeMe){
  changeMe.something = false;
}

let y = new Object();
y.something = true;
bar(y);
y.something // <--this is now false
```

This has nothing to do with node or phantomjs or this module. It's how Javascript works. It's called passing a reference by a copy. 

You can read more here http://stackoverflow.com/questions/13104494/does-javascript-pass-by-reference

**Comment by voidmonk** [comment]
@amir20 Ah that makes sense. Didn't realise that JS objects are passed by copy of a reference. Thanks again.

**Comment by theraaz** [comment]
just a side note, we can also access outside variables and can change their value like [in this answer](http://stackoverflow.com/a/26281687/2037323)
