### ISSUE TITLE
A child page is not a WebPage object

### ISSUE THREAD

**Issue by tofik-mamishov** [amir20/phantomjs-node#545]
I have the following code:

```
page.property('pages').then(function (pages) {
    //access to pages[0]
});
```
The `pages[0]` is not a WebPage object and it doesn't has the same methods (e.g. page.render, page.evaluate), but it has the same fields like a WebPage object.

**Comment by amir20** [comment]
This works as designed because `pages` is a property that gets serialized to json and then back in to object in node. It won't work like you think it will. The functionality was never added. Pull requests are welcomed though.
