### ISSUE TITLE
Pass header "Content-Type"

### ISSUE THREAD

**Issue by loretoparisi** [amir20/phantomjs-node#546]
When in `phantomjs` I would do

```javascript
page.onResourceRequested = function(requestData, request) {
    if ((/http:\/\/.+?\.css/gi).test(requestData['url']) || requestData.headers['Content-Type'] == 'text/css') {
        console.log('The url of the request is matching. Aborting: ' + requestData['url']);
        request.abort();
    }
};
```

to filter our resources by `Content-Type` header.

When in node `phantom` I would do like

```javascript
sitepage.property('onResourceRequested', function(requestData, request) {
        console.log("onResourceRequested");
        
        var filteredRes=requestData.headers.filter(function(key,value) {
            return value['Content-Type'] == 'text/css'
        });

        if ((/http:\/\/.+?\.css/gi).test(requestData['url']) || filteredRes) {
            console.log('The url of the request is matching. Aborting: ' + requestData['url']);
            request.abort();
        }
    });
```

the problem is that I'm missing the `Content-Type` in the passed headers from `phantomjs` here.

**Comment by amir20** [comment]
I actually don't know what is going on because I am not too familiar myself with this functionality. Maybe you found a bug? Have you tried doing `console.log`

**Comment by amir20** [comment]
Oh I don't think `phantomjs` supports `filter`.

**Comment by loretoparisi** [comment]
@amir20 the `Array.filter` there is used in the `phantom` example with node. so it works.
The fact is that if I run the code in `phantomjs` I get the `Content-Type` header, while if I run the code in `phantom`I don't get this in the array of objects returned by the `requestData.headers`. Let's consider that when in `phantomjs` the `requestData.headers` is an associative array, so I can do `requestData.headers[headerName]` like

```javascript
requestData.headers['Content-Type']
```

**Comment by amir20** [comment]
Your code still runs in phantom. So I don't get what you are saying. Try doing console log on array.filter. When I did thst I got undefined object. It doest matter you're in node.

**Comment by loretoparisi** [comment]
@amir20 sorry not clear the issue is that if I use node `phantom` i.e. your module I don't get the `Content-Type` in the `headers` array. If I run `phantomjs` I get it. Forget the `Array.filter` issue.

**Comment by amir20** [comment]
When you use property method, the code actually runs in phantom. I can't imagine a difference. Can you me an example to run?

**Comment by loretoparisi** [comment]
@amir20 So I have tested out with [this](https://gist.github.com/loretoparisi/406571304ca6ac07c3bed782a259eba2) script and actually there is no bug, it was an old version of the `phantomjs` examples of the way of parsing headers. 
Thanks!

**Comment by amir20** [comment]
Nice. Close the ticket next time.

**Comment by loretoparisi** [comment]
👍
