### ISSUE TITLE
on error in childprocess all things are stuck.

### ISSUE THREAD

**Issue by ekbduffy** [amir20/phantomjs-node#548]
in phantom.js, lines near  167, in function
        this.process.stderr.on('data', function (data) 

needs to be added this line:
			_this.kill(data.toString('utf8'));
to kill errored proccess of phantom, and raise error in upper level of Promises. Otherwise - on, for example, incorrect proxy setting - it's just stucks on this error.

**Comment by amir20** [comment]
@ekbduffy can you send a pull request?

**Comment by ekbduffy** [comment]
No, i never checked out your repo:(

13 сент. 2016 г. 5:04 AM пользователь "Amir Raminfar" <
notifications@github.com> написал:
