### ISSUE TITLE
onIntialized callback is serviced after the page is loaded 

### ISSUE THREAD

**Issue by cool-Blue** [amir20/phantomjs-node#549]
### Expected behavior

script should be injected on onIntialized event
```
.^onInitialized
-> injected code running...
-> div added
-> INJECTED!!
-> page script tag is running...
-> INJECTED!!
'success'
page closed

```
### Actual behavior

onIntialized fires as expected but injectJs is delayed until after page.open
```
.^onInitialized
-> page script tag is running...
-> not injected!!
'success'
-> injected code running...
-> div added
-> INJECTED!!
page closed
```
### Steps to reproduce the behavior
```js
/**
 * run from node
 * */
var phantom = require("../lib/index");
var _ph;

  phantom.create([]).then(ph => {

    _ph = ph;
    return _ph.createPage();

}).then(page => {
    page.on('onConsoleMessage', function(message) {
      process.stdout.write('-> ' + message + '\n')
    });
    page.on('onInitialized', function() {
      page.injectJs('./test-inject.js');
      console.log('^onInitialized');  // logs out first as expected but script is not injected
    })
      .then(_ => page.open('./test-min.html'))  // page script tags run
      .then(console.dir.bind(console))  // success
      .then(_ => page.evaluate(function() {checkInjection()}))  // not injected
      .then(_ => {
        console.log('page closed');
          return page.close()
            .then(_ => _ph.exit())
        })
      }).catch(console.dir.bind(console));


/**
 * test-inject.js
 * script to be injected onInitialzed.
 */

console.log('injected code running...');
var injected = document.createElement('div');
injected.id = 'injected';
injected.setAttribute('style', 'background-color: beige; top: 100px; left: 100px; font-size: x-large;');

injected.textContent = 'INJECTED!!';
function inject(){

  if(document.body) {
    document.body.appendChild(injected);
    console.log('div added');
  }  else
    console.log('document.body is falsey, cannot add node!!');
}
inject();
```
```html
<!DOCTYPE html>
<!-- test-min.html target page -->
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>test phantomjs</title>
</head>
<body>
<script src="https://d17wj6ajhy2qee.cloudfront.net/assets/javascripts/jquery-2.1.1.min-6631a779321bc03f4a5281d3ff526254.js"></script>

<script>
    console.log("page script tag is running...");

    function checkInjection() {
        var inj = document.getElementById('injected');
        console.log(inj && inj.textContent || 'not injected!!');
    }
    void function() {
        checkInjection();
    }($)
</script>
</body>
</html>
```
Run injectJs-min from node with the other two files in the same directory. 

### Environment

- OS: windows 10
- Node version (`node -v`): v5.12.0
- package version: 2.1.21

**Comment by amir20** [comment]
I honestly don't know what is being asked. If you have a pull request then I can merge. Otherwise maybe someone else can look.

**Comment by cool-Blue** [comment]
Sorry, not well explained.  The basic issue I have is that I set
```js
page.on('onInitialized', function() {   <--- this fires before the load callback
  page.injectJs(src)   <--- but this is not completed until after the rest of the page is loaded
})
  .then(_ => return page.open(url))
  .then(_ => checkIf_src_Injected())
  .then(console.log.bind(console))  // not injected
```
When using plain phantomjs the src is injected on the initialize event as expected.  This 'normal' behaviour is useful for pre-injecting shims onto the target page.

I'm investigating still so, will update or close later.

**Comment by cool-Blue** [comment]
I think the route cause of this issue is the the asynchronous communication between phantom and node.  In native phantom, the `onInitialized` callback will be invoked as soon as the event fires and will block until it completes.  When managed asynchronously from node, `shim.js` will send a message to node via phantom's stdout and then relinquish control.  Phantom, assuming that the callback is done, continues to load the page.  It seems that phantom manages the event loops to assure the chronology of page events and maybe it would be better if this was also implemented here in phantom-node?

Anyway, the simple work-around is to run the `onInitialized` callback in the phantom, global context.  The thing stopping me from doing that was not understanding how to get a reference to the page object in that context.  After reading and finally understanding the code I can see that the callback is invoked on the WebPage object which is perfect.  You can't get this understanding from the docs however, which is not perfect, so I will submit a PR to clarify it.

```js
    page.on('onInitialized', true, function() {
      this.injectJs('./test-inject.js');
      console.log('^onInitialized');  // script is injected before any other JS on the page: happy days
    })
```
