### ISSUE TITLE
Unexpected replacement characters

### ISSUE THREAD

**Issue by inebritov** [amir20/phantomjs-node#551]
### Expected behavior

Page content is returned as utf-8 string w/o replacement characters ([wiki](https://en.wikipedia.org/wiki/Specials_%28Unicode_block%29)).
### Actual behavior

The replacement characters have appeared in random places of HTML code.
### Steps to reproduce the behavior
1. Open NodeJS console
2. Run the code:

``` javascript
var phantom = require("phantom");
function run(opts) {
    phantom.create(opts).then(function(proc) {
        proc.createPage().then(function(page) {
            page.open("http://varlamov.ru/1960870.html").then(function() {
                page.property('content').then(function (html) {
                    console.log(html.indexOf('\ufffd'));
                });
            });
        });
    });
}

run();
run();
run();
run(['--output-encoding=utf8']);
run(['--output-encoding=utf8']);
run(['--output-encoding=utf8']);
```
1. See different numbers not dependent from options
2. Open view-source:http://varlamov.ru/1960870.html in browser and see no replacement characters
### Environment
- OS: Ubuntu 14.04
- Node version (`node -v`): v6.2.2, v6.4.0
- package version: 2.1.21

**Comment by amir20** [comment]
Hmm looks like a legit bug. I'll see if I can reproduce it tonight. I don't think I'll have a fix soon.

**Comment by amir20** [comment]
I am not sure what is going on here. I have been testing this locally. But the filesize of the content is so big that it looks like it is taking forever. I stopped after the fourth attempt. Here is the output

```
> node bug.js                                                                                              29m 17s 135ms
181150
181150
181150
181150
```

It was taking a very long time but I couldn't reproduce it because locally it did what it was expected.

**Comment by inebritov** [comment]
The problem in characters. Their position doesn't matter, just open page source and you will not find '�' symbol. If you save the page content to a file ```require('fs').writeFile('/tmp/test.html', html)``` you will find this character there.

**Comment by amir20** [comment]
I was able to reproduce this. But sadly, I don't have a fix. Have you been able to debug any further?

**Comment by elias-winberg** [comment]
[Have you tried setting the encoding to utf8 in PhantomJS?](http://phantomjs.org/api/webpage/method/open.html#post-json-data-to-yourcustomapi-in-utf-8-encoding)

**Comment by inebritov** [comment]
@amir20 sorry for late answer, no I haven't able. @elias-winberg I didn't find out how to do it using this repo, but I just tried to pass this setting to ```open``` method call like this:
```
...
page.open("http://varlamov.ru/1960870.html", {encoding: 'utf8'}).then(function() {
                page.property('content').then(function (html) {
...
```
...and fter third attempt the character is not disappeared (either with ```--output-encoding=utf8`` flag or without one).

**Comment by sp90** [comment]
@amir20 the easiest way to reproduce the bug is, to make a site where the url contains fx æøå chars and then see what you get u can use this `http://tandbørsten.dk/` the problem with æ ø å and the rest of the characters is that they are url encoded.

**Comment by amir20** [comment]
I replaced `linerstream` with `split`. I'd like to use `split2` but it doesn't work. I wonder if this will fix it. Releasing a version now.

**Comment by inebritov** [comment]
The solution works great. Thanks!
