### ISSUE TITLE
Is it Windows compatible?

### ISSUE THREAD

**Issue by bitttttten** [amir20/phantomjs-node#553]
- OS: Windows 10
- Node version (`node -v`): v6.6.0
- phantomjs: 1.9.6

I'm just trying to run a simple script and I get

> error: Could not spawn [/usr/local/share/phantomjs/bin/phantomjs] executable. Pl                                                                             ease make sure phantomjs is installed correctly.
> error:  Error: spawn /usr/local/share/phantomjs/bin/phantomjs ENOENT
>     at exports._errnoException (util.js:1036:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\AppData\\Roa                                                                             ming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"

Although phantomjs is on my PATH, it is not installed in /usr/local/share which would be a directory I would install phantomjs to if I was running *nix.

What am I doing wrong?

**Comment by amir20** [comment]
> Please make sure phantomjs is installed correctly

This error happens when phantomjs can't be installed. So either make sure you can install phnatomjs from source or install latest version of it so that this module doesn't need it.

**Comment by amir20** [comment]
I don't have Windows computer, but let me know what you find.

**Comment by bitttttten** [comment]
I'm not sure what changed, I'm not getting this same error. If anyone comes across this issue, just uninstall and install via a different method (npm install prebuilt, build it, or download the binary).

**Comment by amir20** [comment]
Interesting. I am trying to use `yarn` so maybe this will be fixed.

**Comment by amir20** [comment]
Interesting. I am trying to use `yarn` so maybe this will be fixed.

**Comment by awhitehatter** [comment]
I have Windows 10. Just ran across this today, and using `yarn add phantom` fixed it. Thanks.
