### ISSUE TITLE
Cannot read string from file then put into header

### ISSUE THREAD

**Issue by akashi-dh** [amir20/phantomjs-node#554]
I'm using Ubuntu 16.04, Node version 4.3.2. and phantom latest version.
I'm trying to put content of a HTML file into header. Here is my code:

    let headerHtml = fs.readFileSync('tmp/header.html', 'utf-8');
    headerHtml = headerHtml.replace('\n', '');
    const paperSize = {
        format: 'A4',
        margin: "0.5cm",
        header: {
            height: "7cm",
            contents: phantom.callback(function(pageNum, numPages) {
              return headerHtml.replace('pageNum', pageNum);
            })
        }
    };

    await page.property('paperSize', paperSize);
    await page.open('tmp/main.html');
    await page.render('build/hello.pdf');

When I try to run the code above. I receive this error:

> info: SyntaxError: Unexpected EOF
> info:
> info:   undefined:1 in render
> info:   phantomjs://code/shim.js:126 in invokeMethod
> info:   phantomjs://code/shim.js:204 in executeCommand
> info:   phantomjs://code/shim.js:158 in read
> info: SyntaxError: Unexpected EOF

I tried put the string into a JSON then read from it (this worked with phantomjs itself), but no luck. 
What did i do wrong? Thank you in advance.

**Comment by akashi-dh** [comment]
If i put the `headerHTML` inside the callback like this:
```
    const paperSize = {
        format: 'A4',
        margin: "0.5cm",
        header: {
            height: "7cm",
            contents: phantom.callback(function(pageNum, numPages) {
              let headerHTML = "<div>A</div>";
              return headerHTML;
            })
        }
    };
```

I catch this error:

`[ReferenceError: headerHTML is not defined]`

**Comment by amir20** [comment]
`let` doesn't work in phantomjs context. Try doing this. 


```js

const paperSize = {
    format: 'A4',
    margin: "0.5cm",
    header: {
        height: "7cm",
        contents: phantom.callback(function(pageNum, numPages, headerHtml) {
          return headerHtml.replace('pageNum', pageNum);
        }, headerHtml)
    }
};
```

phantom and node are two different processes.  It won't have access to `headerHtml`. 

I haven't test the above but it should work.

**Comment by akashi-dh** [comment]
@amir20 thank you for your reply. Sadly, it doesn't work for me. :(

**Comment by akashi-dh** [comment]
```
    var createHeader = new Function('pageNum', 'numPages', 'return \'' + headerHtml +'\'.replace(\'pageNum\', pageNum).replace(\'numPages\', numPages);');
    var createFooter = new Function('pageNum', 'numPages', 'return \'' + footerHtml +'\'.replace(\'pageNum\', pageNum).replace(\'numPages\', numPages);');
    const paperSize = {
        format: config.format || "A4",
        margin: config.margin || "0cm",
        header: {
          height: config.header ? config.header.height: "0cm",
          contents: phantom.callback(createHeader)
        },
        footer: {
          height: config.footer ? config.footer.height : "0cm",
          contents: phantom.callback(createFooter)
        }
```

This is how I get it done. For anyone who need it :D
