### ISSUE TITLE
networkRequest.changeUrl doesn't work in page#on

### ISSUE THREAD

**Issue by lippea** [amir20/phantomjs-node#555]
### Expected behavior

networkRequest.changeUrl is supported under page#on
### Actual behavior

networkRequest.changeUrl is not a function
### Steps to reproduce the behavior

page.on('onResourceRequested', (requestData, networkRequest) => {
    networkRequest.changeUrl('http://localhost:8888/foo-bar-xyz');
 });
### Environment
- OS: Windows2012 R2 Standard
- Node version (`node -v`): v4.2.4
- package version: "phantom": "^2.1.14"

**Comment by amir20** [comment]
This works as documented. Using "on" runs in nodejs context. You want to run in phantomjs process instead. Read it more carefully.

**Comment by lippea** [comment]
Thanks for the quick answer.
The thing I'm trying to achieve is change url for some selected requests.
But the problem is if executing code under node, the changeurl doens't work
string.includes doesn't work if executing code under phantomjs.
Do you have any advice on how to achieve this?

**Comment by lippea** [comment]
As @amir20 said, it has to be run in phantomjs to get changeurl work, by following two ways:
page.property(...)
page.on('onResourceRequested', true, ...)
For the includes doesn't work, it's because phantomjs doesn't support it. Can use indexOf or match instead.

**Comment by pboling** [comment]
None of the methods on networkRequest are available to me when I use the `true` option.  Using property is not an option because I need to attach other events to `onResourceRequested` as well.

```
page.on('onResourceRequested', true, ...)
```

None of the specs in the test suite of this project test`on` with run within phantom runtime set to `true` either, so I am guessing that the feature advertised in the Readme just doesn't work.

**Comment by amir20** [comment]
Using `on` and `true` then it wouldn't work because you are running in Node. Methods are not passed to Node, just data. 

Why don't you use both? I think it should work. Can you also point me to which README feature? I just updated it so maybe I missed something.

**Comment by pboling** [comment]
> If you need both, then why don't you use both? I think it should work.

I have tried every combination of `property` alone, `property` with `on`, and multiple `on` event listeners, and in no combination of options have I found a way to abort the network requests.  It seems like the code is not even running.  The process overall seems to work from every way I can check, so I don't think it is blowing up - also there is no helpful `DEBUG=true` output that seems relevant.

From the Readme:

> You can return data to NodeJS by using #createOutObject(). This is a special object that let's you write data in PhantomJS and read it in NodeJS. Using the example above, data can be read by doing:

```
var outObj = phInstance.createOutObject();
outObj.urls = [];
page.property('onResourceRequested', function(requestData, networkRequest, out) {
    out.urls.push(requestData.url);
}, outObj);

// after call to page.open()
outObj.property('urls').then(function(urls){
   console.log(urls);
});
```

What this fails to show is how the call to `page.open` is actually returned as a promise, and the usage of the `outObj` values actually comes in the `then` which follows.  I can't get the outObj to ever have any data set within the event, only what I set outside the event.

**Comment by pboling** [comment]
Another part of the Readme that doesn't seem to be working for me:

> The same as in property, you can pass additional params to the function in the same way, and even use the object created by #createOutObject().

I can't get this to work, perhaps it isn't as simple as this makes it seem?

> You cannot use #property() and #on() at the same time, because it would conflict. Property just sets the function in phantomjs, while #on() manages the event in a different way.

I assume this is still true, that a `property` for `onResourceRequested` and `on` for `onResourceRequested` can't be used together.

So what I don't understand is why would `on` with `true` to run in Phantom work with additional `on` bindings to the same event?  Do they not step on each other?

I have checked out the project and will attempt to create failing specs tonight.

**Comment by amir20** [comment]
I am pretty swamped at work but sometime this or next week I'll pull down the latest and try this. I will reopen this ticket. If you find a spec that breaks then please share.

**Comment by pboling** [comment]
@amir20 I have written 9 failing specs that demonstrate behavior I expect from the Readme:
https://github.com/amir20/phantomjs-node/pull/569#pullrequestreview-7100027

**Comment by amir20** [comment]
I put a comment in the other pull request. But doing `page.property('onResourceReceived', true, function(response, out)` is not right according to README. So I am probably missing something here.

**Comment by pboling** [comment]
Updated the PR correcting the typos.  Specs still failing.

**Comment by amir20** [comment]
@pboling were you planning to send more specs? I forget what we said we will. Maybe close this if there isn't any more action items.

**Comment by pboling** [comment]
Yeah, I had the additional specs in the PR you declined because it also had failing specs for things that you decided to remove from the readme.

I'll separate the new passing specs for the proper functionality intended to be supported as soon as I can.  👍

**Comment by amir20** [comment]
@pboling What's the status of this ticket? I think you said you will send an updated PR but I haven't heard anything. Can you update? If you can't make it then it's ok. I will just close.

**Comment by amir20** [comment]
@pboling  I am closing this ticket.

**Comment by pboling** [comment]
That's fine.  I haven't had any time to work on it. 👍
