### ISSUE TITLE
evaluateJavaScript not working

### ISSUE THREAD

**Issue by kazazes** [amir20/phantomjs-node#558]
### Expected behavior

`page.evaluateJavaScript` should eval the passed function and pass the return value when resolved:

```
page.evaluateJavaScript('function() { var editor = $(\'.CodeMirror\')[0].CodeMirror; return editor.getValue(); }')
      .then(function(code) {
        console.log(code);
      });
```
### Actual behavior

Nothing is returned.

### Steps to reproduce the behavior

1. Load [a page](https://codemirror.net/1/jstest.html) with any CodeMirror project.
2. Run code above.
3. Scratch head.

### Environment

- OS: Tested on Arch and OS X
- Node version: 6.9.1
- package version: Current npm

**Comment by amir20** [comment]
Have you tried doing `catch(console.log)` to see what happens? Also with `DEBUG=true` can be helpful as suggested in the README. Providing those logs would help to debug your situation.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.
