### ISSUE TITLE
the screenshot using page.render() has not a very high quality, need help.

### ISSUE THREAD

**Issue by korbinzhao** [amir20/phantomjs-node#560]
### Expected behavior

capture a very high quality image of a webpage using page.render(), it means the screenshot has a quality just as using iphone default screenshot tool.

### Actual behavior

the screenshot I get using page.render() even I set the quality to 100 is a little bit blurry, That's disappointing.

### Steps to reproduce the behavior

page.render(screenshotPath, {format: config.format, quality: config.quality});

### Environment

- OS:

mac osx

- Node version (`node -v`):

v4.3.0

- package version: 

2.1.19

**Comment by amir20** [comment]
This sounds like a phantomjs bug. Have you tried to see what happens?

**Comment by elias-winberg** [comment]
It may be related to the following issue (as of right now you can't set the device pixel ratio): https://github.com/ariya/phantomjs/issues/10964

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.

**Comment by elecshiba** [comment]
HI, I also have the same problem with page.render(),  though I couldn't find an error reason.

**Comment by korbinzhao** [comment]
Dear, Sorry for the late response,  maybe it is not a bug @amir20. It should be related to device pixel ratio, just like @elias-winberg said. So how can I set devicePixelRatio to 2 or 3 ? If I can reset the devicePixelRatio to a higher value, I think the screenshot will has a higer quality.
