### ISSUE TITLE
page.property('clipRect') isn't working

### ISSUE THREAD

**Issue by sarahgarcin** [amir20/phantomjs-node#561]
### Expected behavior

I have tried to use the clipRect property :
```
page.property('clipRect',{
top:    0,
left:   1365,
width:  1365,
height: 1970
});
```
And it's not working. 
Does I use it in the wrong way ? 

### Environment

- OS: OSX 10.11.6
- Node version (`node -v`): v6.6.0
- package version: 2.1.21

**Comment by amir20** [comment]
This request is unclear. Providing a complete example is needed to debug these kind of issues.

**Comment by sarahgarcin** [comment]
What I'm trying to do is to render a certain part of a webpage. 
I have this phantom code: 

`phantom.create([
	  '--ignore-ssl-errors=yes',
	  '--ssl-protocol=any', 
	  '--load-images=yes',
	  '--local-to-remote-url-access=yes'
		]).then(function(ph) {
		  ph.createPage().then(function(page) {
		        page.property('clipRect', {top: 0, left: 1000, width:3000,height:890});
                        page.property('paperSize', {width: 1365, height: 1970});
		  	page.open(url)
		  	.then(function() {
			  	return page.property('content')
			    	.then(function() {
				      setTimeout(function(){
					      page.render(filePath).then(function() {
					      	page.close();
						 ph.exit();
					      });
				     	}, 2000)
				    });
			 });
		  });
		});`

Here clipRect isn't working, only the paperSize property is working. 
If I remove the paperSize property, the clipRect isn't working as well. 
I have also tried to use the viewportSize property, the same way I have used the clipRect one, but not working. 

By the way, many thanks for this module, it's great ! :)

**Comment by amir20** [comment]
Hmm. page.property actually returns a promise. So you may want to do

```js
page.property('paperSize', {width: 1365, height: 1970}).then(...)
```
But I don't know if that will solve your problem. 

I'd suggest to see if this works in vanilla phantomjs code. If that works, then it's clearly a bug with this module. I just do a pass through so I am guessing phantomjs would behave the same way?

And you are welcome. :)

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.
