### ISSUE TITLE
Replace crypto.randomBytes() with non-crypto alternative

### ISSUE THREAD

**Issue by duzun** [amir20/phantomjs-node#563]
According to docs, `crypto.randomBytes()` consumes system entropy and blocks for a considerable amount of time when system is low on entropy:

> The crypto.randomBytes() method will block until there is sufficient entropy. This should normally never take longer than a few milliseconds. The only time when generating the random bytes may conceivably block for a longer period of time is right after boot, when the whole system is still low on entropy.

There are better alternatives for generating IDs, like Math.random() which doesn't consume system entropy and is thus much faster!

**Comment by amir20** [comment]
Wow good find. Mind finding alternatives in a PR? As long as the space is big then we should be ok. The module is tested well so we should be ok to just commit it.

**Comment by duzun** [comment]
Easy #564 @amir20 :-)
