### ISSUE TITLE
Create ignores logger parameters

### ISSUE THREAD

**Issue by prashantjain68** [amir20/phantomjs-node#566]
Expect the error to be logged to the console

After debugging, I realize that es6-promise is swallowing the error despite following the recommended code.

        phantom.create(
            ['--ignore-ssl-errors=yes', '--load-images=no'],
            {
                warn: console.log,
                debug: console.log,
                error: console.log
            }
        )

As per the above code, I expect the code to be logged to the console.

- OS: MAC
- Node version (`node -v`): 4.5
- package version: 2.1.13

**Comment by amir20** [comment]
This is a bug in the documentation. It's actually 

```js
phantom.create(
  ['--ignore-ssl-errors=yes', '--load-images=no'], {
   logger: {
    warn: console.log,
    debug: console.log,
    error: console.log
   }
});
```

**Comment by amir20** [comment]
Updated the README to reflect that. Now does this work?

**Comment by prashantjain68** [comment]
Thanks Amir. I do get the best support from you and thankful for that. I havent tried it yet but I am sure it will work.

**Comment by prashantjain68** [comment]
On a side note, I have another question for which I dont want to open a bug ticket.

I am trying to download a file by clicking an element in the web page. I am also listening to the "onResponseXXXXXX" events. The response body is empty but I do see the request and the recevied events are fired. Is this your module issue or a PhantomJS issue. Looks like it is a PhantomJS issue.

**Comment by amir20** [comment]
I haven't heard of this so I am not sure. The best way is to try it in PhantomJS and see if it works there. I am guessing it because all the body's response are handled by PhantomJS.

**Comment by prashantjain68** [comment]
Thanks
