### ISSUE TITLE
console.log in evalute doesn't output to the terminal console

### ISSUE THREAD

**Issue by Nomia** [amir20/phantomjs-node#568]
### Expected behavior

I've set the onConsoleMessage, and console.log inside the evalute function, the log info should output to my teminal console.

### Actual behavior

no output for the console.log inside evaluate

### Steps to reproduce the behavior

1. make a little bit change to your simple demo code as below.
![image](https://cloud.githubusercontent.com/assets/1707818/19867213/2213b284-9fde-11e6-9354-c9d32123bb70.png)

2. webpack/babel make the code to be readable by node
3. node output.js

### Environment

- OS: MacOS
- Node version (`node -v`): 7.0.0
- package version: latest

**Comment by amir20** [comment]
Reviewing this ticket made me wonder if this https://github.com/amir20/phantomjs-node/blob/master/examples/async.js still works. I validated that it does. I'll have to test yours when I sometime.

**Comment by amir20** [comment]
When I do `page.property("onConsoleMessage", (msg) => console.log(msg));` it works. When I do `page.property("onConsoleMessage", () => console.log(arguments));` it does not. I am closing since it looks to be related to your code.

**Comment by Nomia** [comment]
Thank u for your reply.

I did a workaround(phantom callback) to make console log to the terminal when inside "page" environment.

Inside page.evaluate or js that is injected into page, rewrite the console.log method like below:

```
window.console.log = function () {
                const args = Array.prototype.slice.call(arguments);
                const message = {type: 'log', data: args};
                window.callPhantom.apply(null, [message]);
};
```

then in your node environment:
```
page.on('onCallback', (a, b, c) => {
            if (a && a.type) {
                switch (a.type) {
                case 'log':
                    console.log.apply(console, a.data);
                    break;
                default:
                    break;
                }
            }
        });
```
