### ISSUE TITLE
After javascript redirect to a new url,  "onResourceRequested" cannot get the resources requested from the new url

### ISSUE THREAD

**Issue by nne998** [amir20/phantomjs-node#570]
### Expected behavior

After javascript redirect to a new url,  "onResourceRequested" should get trigger-events of the resources requested from the new url ?

### Actual behavior

after javascript redirect to a new url,  "onResourceRequested" cannot get the resources requests on the new url

### Steps to reproduce the behavior

code:
```
phantom.create().then(instance => {
    return instance.createPage();
}).then(page => {
    page.setting('userAgent', req.config.user_agent);
    page.setting('resourceTimeout', 10 * 1000);
    page.setting('javascriptEnabled', true);
    page.on('onResourceRequested', function (requestData, networkRequest) {
        console.log(requestData);
    });
    page.open('page1 url'); 
```

#page source:
<html><head><script language="JavaScript" type="text/javascript">
window.location.href="http://newredirecturl............";
</script></head></html>

### Environment

- OS:MacOX & CentOS
- Node version (`node -v`):v6.5.0
- package version: 2.1.21

**Comment by nne998** [comment]
`phantom.create().then(instance => {
    return instance.createPage();
}).then(page => {
    page.setting('userAgent', req.config.user_agent);
    page.setting('resourceTimeout', 10 * 1000);
    page.setting('javascriptEnabled', true);
    page.on('onResourceRequested', function (requestData, networkRequest) {
        console.log(requestData);
    });
    page.open('page1 url'); 
`


#page1 source
`<html><head><script language="JavaScript" type="text/javascript"> window.location.href="http://newredirecturl............"; </script></head></html>`

**Comment by amir20** [comment]
What does this do in PhantomJS? This is most likely an upstream issue.

**Comment by amir20** [comment]
Changed state to awaiting response. If I get no response by Friday I will close.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.
