### ISSUE TITLE
Wait for an element to be visible

### ISSUE THREAD

**Issue by bertolo1988** [amir20/phantomjs-node#571]
Could someone share an example on how to wait for an element to be visible?

**Comment by amir20** [comment]
This was already discussed here https://github.com/amir20/phantomjs-node/issues/431. Closing.

**Comment by bertolo1988** [comment]
Would it be possible to reopen this issue?

**Comment by amir20** [comment]
I am not sure why we would reopen it. Did it not answer your question? Issues are for bugs and unexpected behaviors. That's why the template for submitting issues should be followed. 

If you tried it and it didn't work then that makes sense to reopen. 🍺

**Comment by bertolo1988** [comment]
I had a few thumbs up... i guess more people are looking for the same answer. Maybe post a snippet somewhere?

**Comment by amir20** [comment]
Hmm maybe I am not getting what you are saying but https://github.com/amir20/phantomjs-node/issues/431#issuecomment-207865947 already has an example. You just have to change it to your needs. I don't have code handy.
