### ISSUE TITLE
Noop's.. CPU usage, option..

### ISSUE THREAD

**Issue by KpjComp** [amir20/phantomjs-node#572]
Hi,

Been replacing my use of Phantom that uses spawning for every request,.  

And instead using your package, works well.. 

But there is one gotcha, your NOOP's are triggering every 100ms,.. On windows from task manager I can see this having a noticeable effect on CPU usage.  I've manually changed the NOOP to 10 seconds, and that works a lot better.  Could you maybe make the NOOP timeout an option..

Regards

Keith..

- OS: Windows
- Node version: 7
- package version: 3.0.2

**Comment by amir20** [comment]
Without the NOOP, phantomjs can be in a locked state. PhantomJS is a single thread process so it can only do one thing at a time. If the NOOP wasn't there, it wouldn't get the events. 

However, making it optional still makes sense. I can accept a PR you have one to make it so.

**Comment by KpjComp** [comment]
I would have though the NOOP was there to detect a failing PhantomJs.exe..   IOW: If the phantomJs.exe failed, then using a longer NOOP it would just take longer to detect this.  Increasing to 10 seconds I've had 0 issues, works like a charm, and CPU usage drops a lot.  So far, I've even increased to 30 seconds still no issues.  Response times still instant etc.

The problem I'm trying to avoid is this, say I have 20+ websites on my Server, and say I restrict to using 5 concurrent phantomjs processes per website.  In theory that could end up been 20*5, 100 Phantom JS processes running, now these 100 processes keep on running, and at 0.5% per process I'm using 50% CPU usage when phantomjs is idle.  I could of course prune them down to be 1 phantomJS per website, but even then is's 20 * 0.5,  10% CPU usage doing nothing while in waiting mode.  This could just be just a windows issues, maybe StdIn/Out pipe can get CPU hungry.

> I can accept a PR if you have one.

I'm not 100% sure how to produce a PR, but the mod's I've done are very simple.
In phantom.js unit I've just done this on the constructor..

```
var _ref$logLevel = _ref.logLevel;
let logLevel = _ref$logLevel === undefined ? defaultLogLevel : _ref$logLevel;

let noopTimeout = _ref.noopTimeout ? _ref.noopTimeout : 100; //add this line.
.
.
.
this.heartBeatId = setInterval(this._heartBeat.bind(this), noopTimeout); //change this.
```

**Comment by amir20** [comment]
The NOOP is definitely needed if there are events that later need to emit data back to node. This [code](https://github.com/amir20/phantomjs-node/blob/master/src/shim/index.js#L280) is blocking which deadlock without the NOOP. 

After thinking about this problem, it sounds like this is mostly unique to you. So you can provide a PR or you can just do 

```js
clearInterval(phantomInstance.heartBeatId)
```

`phantom.heartBeatId` is public and should work.

**Comment by KpjComp** [comment]
Ah!, right..  Yeah, I think everything I'm doing is Request / Response based.

I'm basically rendering a url and generating a PDF, I'm not attaching any events to the Phantom JS's DOM, so the clearInterval might even be a better approach..  Seems odd that PhantomJS didn't make a version of stdio that was async..

But it is worth pointing out, idle Phantom JS's using this stdio for IPC, might not just be just unique to me due to the CPU usage issue.   The CPU usage does seem strange though, but looking at your code your doing a JSON parse, and transform for the NOOP, that might be overkill for the simple NOOP command.   So I wonder if doing and early check for the NOOP command and exit early might help, I'll give it a go tomorrow and see if putting the interval back to 100 and doing this stops the CPU spike.   

eg. From NODE the NOOP could just be `this.process.stdin.write('NOOP' + os.EOL, 'utf8');`  Basically 5 bytes been sent down stdin,.  And then the early check  `if (line==='NOOP') return` should do it, and keep you message loop pumping.

**Comment by amir20** [comment]
> But it is worth pointing out, idle Phantom JS's using this stdio for IPC, might not just be just unique to me due to the CPU usage issue. The CPU usage does seem strange though, but looking at your code your doing a JSON parse, and transform for the NOOP, that might be overkill for the simple NOOP command. So I wonder if doing and early check for the NOOP command and exit early might help, I'll give it a go tomorrow and see if putting the interval back to 100 and doing this stops the CPU spike. 

That is an interesting perspective I had not thought about. I wish I had more time to play with it. Let me know what your findings are. I'd be happy to work with you to get it merged.

**Comment by KpjComp** [comment]
Ok, been doing some experiments..   And it seems to work like a charm.

In fact it seems to have made it faster, I believe this is because this solution also give the phantom process a bit of a breather, so that the GC can collect during NOOP time.

CPU usage on mine is now 0%, during idle.  And I'm also getting sub 1 second PDF renders.  Were before I was getting over 1 second.  I assume this is the GC bit.

Here is my mods ->
inside read() in shim/index.js
```
function read() {
    var line = _system2.default.stdin.readLine();
    if (line) {
        if (line === 'NOOP') {
          //if sender has done a noop,
          //it means sender is not busy
          //so lets give phantom more time
          setTimeout(function () {
            //this will reset doing_NOOP at sender,
            //so if it wants to NOOP again it can..
            _system2.default.stdout.writeLine('>NOOP');
            read();
          }, 100);
          return;
        }
        var command..............
```

And inside phantom.js constructor
```
      .............................
      this.process.stdout.pipe(new _linerstream2.default()).on('data', data => {
            const message = data.toString('utf8');
            if (message[0] === '>') {
                //Server end has finished NOOP,
                //lets allow NOOP again..
                if (message === '>NOOP') {
                  this.doing_NOOP = false;
                  return;
                }
                ................................
```

And phantom.js _heartBeat()

```
    _heartBeat() {
        if (this.commands.size === 0 && !this.doing_NOOP) {
            this.doing_NOOP = true;
            this.process.stdin.write('NOOP' + _os2.default.EOL, 'utf8');
            //this.execute('phantom', 'noop');
        }
    }
```

**Comment by amir20** [comment]
It's hard for me to understand the code because I think you are modifying the compiled JavaScript. 

Any chance you can send a pull request with the js files in src?

**Comment by KpjComp** [comment]
I modified the NPM source, it didn't look compiled.

I've just Git cloned the repository, I've never used Git for doing update,.. So I'll see if I can do a new branch and do a pull request.  Really need to learn to do this anyway.. :)

**Comment by KpjComp** [comment]
Ok, tried to push a new branch -> noop_cpu_update

But get error -> remote: Permission to amir20/phantomjs-node.git denied to KpjComp.

**Comment by KpjComp** [comment]
Ok, I've found a way to do a diff, if that helps..

```
commit e47f38b8228e4472e28ea32be292927263c4fa6b
Author: keith <keith@saxon>
Date:   Tue Nov 15 15:07:38 2016 +0000

    Update NOOP to be more CPU friendly.

diff --git a/src/phantom.js b/src/phantom.js
index 1fd3b68..f5718ea 100644
--- a/src/phantom.js
+++ b/src/phantom.js
@@ -94,6 +94,12 @@ export default class Phantom {
         this.process.stdout.pipe(new Linerstream()).on('data', data => {
             const message = data.toString('utf8');
             if (message[0] === '>') {
+                //Server end has finished NOOP,
+                //lets allow NOOP again..
+                if (message === '>NOOP') {
+                  this.doing_NOOP = false;
+                  return;
+                }
                 const json = message.substr(1);
                 this.logger.debug('Parsing: %s', json);
 
@@ -315,9 +321,11 @@ export default class Phantom {
     }
 
     _heartBeat(): void {
-        if (this.commands.size === 0) {
-            this.execute('phantom', 'noop');
-        }
+      if (this.commands.size === 0 && !this.doing_NOOP) {
+        this.doing_NOOP = true;
+        this.process.stdin.write('NOOP' + _os2.default.EOL, 'utf8');
+        //this.execute('phantom', 'noop');
+      }
     }
 
     /**
diff --git a/src/shim/index.js b/src/shim/index.js
index 709c865..6d9986f 100644
--- a/src/shim/index.js
+++ b/src/shim/index.js
@@ -122,6 +122,18 @@ const commands = {
 function read() {
     let line = system.stdin.readLine();
     if (line) {
+        if (line === 'NOOP') {
+            //if sender has done a noop,
+            //it means sender is not busy
+            //so lets give phantom more time
+            setTimeout(function () {
+                //this will reset doing_NOOP at sender,
+                //so if it wants to NOOP again it can..
+                _system2.default.stdout.writeLine('>NOOP');
+                read();
+            }, 100);
+            return;
+        }
         let command = JSON.parse(line, function(key, value) {
             if (value
                 && typeof value === 'string'

```

**Comment by amir20** [comment]
You have to fork the project first. Then push your branch. And then create a pull request.

**Comment by KpjComp** [comment]
Oh, I think I've done it..  But the Pull Requests is saying something about Travis -> All checks have failed.

So I might still have done something wrong :(

Only ever used GIT to grab stuff, not update.. So this is all new to me..
