### ISSUE TITLE
When phantomjs crashes, this module never exits and just locks up.

### ISSUE THREAD

**Issue by TechnologySolutionsGroup** [amir20/phantomjs-node#573]
Using the simple.js example within this module, try this URL: http://www.architecturaldigest.com/story/benjamin-moore-2017-color-of-the-year-shadow

phantomjs crashes, but the simple.js script never exits, causing node to simple lock and halt processing.

**Comment by amir20** [comment]
Hmm good find.

**Comment by amir20** [comment]
@TechnologySolutionsGroup should be fixed with latest commit.

**Comment by TechnologySolutionsGroup** [comment]
Thanks for the quick fix!
