### ISSUE TITLE
XSLTProcessor somehow available on macOS X

### ISSUE THREAD

**Issue by kentnek** [amir20/phantomjs-node#578]
I've been scratching my head over an unexpected behavior.

I'm trying to read a webpage that requires XSLTProcessor using `phantomjs-node`, and although I'm well aware that QtWebkit does not support XSLT, for some reason my crawling code works perfectly on a macOS X machine. Here's a snippet that proves the existence of XSLTProcessor:

```js
var phantom = require("phantom");

var phInstance = null;
phantom.create()
    .then(instance => {
        phInstance = instance;
        return instance.createPage();
    })
    .then(page => {
        page.evaluate(function() {
            // this gives [object XSLTProcessorConstructor] on macOS X
            console.log(XSLTProcessor); 
        });
    })
    .catch(error => {
        console.log(error);
        phInstance.exit();
    });
```

On Windows/Linux, this would give `ReferenceError: Can't find variable: XSLTProcessor`, as expected.

Does anyone know why this happens, and how to make XSLTProcessor available on Windows/Linux as well?

**Comment by amir20** [comment]
This is more of a phantomjs question and not this module.

**Comment by kentnek** [comment]
On second thought, I actually suspect it has something to do with the `phantomjs-prebuilt` package, as the provided phantomjs binaries for macOS X might have been built differently (with XSLT on?)

But still, I'd love to receive insights from others and see if this is replicable.

**Comment by amir20** [comment]
I don't think so. I tried it with my brew install of phantom js on mac and it does work. I didn't have a windows machine to confirm though. 

Sent via my iPhone

**Comment by amir20** [comment]
Closing since it doesn't seem related to this repo.
