### ISSUE TITLE
page.open() not resolving

### ISSUE THREAD

**Issue by TonySchu** [amir20/phantomjs-node#579]
When I use page.open for a url which is doing a lot of javascript for a long time, the promise is not resolving. Is there any way to set a timeout to force phantom to render the page after xy seconds?

Thanks a lot!

- OS:
- Node version (`node -v`):6.9.1
- package version: *

**Comment by TonySchu** [comment]
Sorry, I got it from the comments of some other "issues.

This can be closed. 👍

**Comment by yourfavorite** [comment]
@TonySchu I think I may be running into the same issue. Can you share a link to the other issues that helped you?

**Comment by TonySchu** [comment]
Hi, I just used this before page.open()
`page.setting("resourceTimeout", 5000);`
