### ISSUE TITLE
View SSL certificate

### ISSUE THREAD

**Issue by akshatster** [amir20/phantomjs-node#580]
Hi guys,

is there a way of inspecting the SSL certificate the site is using, under phantomjs-node, or viewing its fingerprint?

### Environment

Phantom Version 2.1.1 on OS X Sierra 10.12 16A323

**Comment by amir20** [comment]
This doesn't seem to be related to this module. If phantomjs can do it then most likely this can too. Have you looked at the documentation for phantomjs?

**Comment by amir20** [comment]
Please close if resolved.

**Comment by akshatster** [comment]
Oh ok, ill have a look there. Thanks
