### ISSUE TITLE
Error when using multiple instances in parallel

### ISSUE THREAD

**Issue by TonySchu** [amir20/phantomjs-node#583]
Hi,

at first, thanks a lot for the awesome work and the great modul. I am using it to make screenshot of many webpages. To save CPU I use one Phantom instance per process. In this instance I am opening a page, render it, close it and go on.

This works really great except when I am starting another process. In this case I get this error, when one process is done:
_Error: undefined is not an object (evaluating 'target[command.params[0]]')
    at Liner.Phantom.process.stdout.pipe.on.data (/Users/cassini/Node/webshot/node_modules/phantom/lib/phantom.js:147:45)_

This only occurs when on process is finished and another is still running on another phantom instance.

Creating the instance:

`
    function initPhantom(todos) {
        phantom.create(['--ignore-ssl-errors=no'], {logLevel: 'error'})
            .then(function (instance) {
                var processId = instance.process.pid;
                console.log("===================> instance: ", processId);
                phInstance = instance;
                webshot(0, todos);
            }).catch(function(e) {
            console.log(e);
        });
    }

        function webshot(id, shots) {
            phInstance.createPage().then(function (_page, error) {
                if(error){
                    console.log("first", error);
                }
                    sitepage = _page;
                    sitepage.property('viewportSize', {width: 1024, height: 768});
                    //sitepage.property('clipRect', {width: 1024, height: 768});
                    //sitepage.property('userAgent', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36');
                    sitepage.setting("resourceTimeout", 4000);
                    return sitepage.open(shots[id].url);
                }).catch(function(e) {
                    console.log(e);
                }).then(function (status, error) {
                    if(error){
                        console.log(error)
                    }
                    console.log("render %s / %s", id + 1, shots.length);
                    setTimeout(function () {
                        var image = 'temp_img/' + shots[id]._id + '.png';
                        sitepage.render(image, {format: 'png', quality: '30'})
                            .then(function (finished, error) {
                            if(error){
                                console.log(error)
                            }
                            sitepage.close();
                            chekcImageinDb(shots[id], image);
                            if (id < shots.length-1) {
                                console.log("test",shots.length)
                                id += 1;
                                webshot(id, shots);
                            } else {
                                console.log("===================> all done: %s files has been written", shots.length);
                                 phInstances.shift();
                                if(phInstances.length < 1){
                                     console.log("kill phantom ", phInstances);
                                }
                            }
                        }).catch(function(e) {
                            console.log("last before",e);
                        });
                    }, 2000);
                }).catch(function(e) {
                console.log("last one", e);
            })
        }`

- OS:
- Node version (`node -v`): 6.9.1
- package version: *

**Comment by TonySchu** [comment]
I found the problem. When the second instance is created, all open functions will be executed on the new instance. Is there a way to bind it to a specific phantom instance?

**Comment by amir20** [comment]
That's weird. I think you might be something wrong. How are you running multiple instances? I have a couple cluster and pm2 examples in the example directory and I have stress tested it with 10 clients running in parallel. It worked just fine. The reason I actually rewrote this module was so that multiple instances work. 

I am traveling for the holidays but I'll try to look this weekend. 

Sent via my iPhone

**Comment by amir20** [comment]
I don't see you doing exit(). That could be the culprit as you probably have a bunch of processes running. 

Also, on my iPhone I can't tell how you spawn multiple instances. That could help me see what's wrong.

**Comment by TonySchu** [comment]
Thank you for you response, especially while your on holidays.
Not doing exit, was just for testing, normally I kill the phantom instance, after the process is done.

<img width="461" alt="bildschirmfoto 2016-11-23 um 17 58 54" src="https://cloud.githubusercontent.com/assets/19664656/20571244/f6e4a8d6-b1a6-11e6-98b0-2836b955cc9e.png">

Please have a look at this log. When the second instance is created (pID: 8697) all processes will be executed on the new instance. This will interrupt the process and mess around with the pictures. So URL1 is rendered as Image 2 etc.

Is there a better way of creating an instance and looping through urls?

Thanks again.

**Comment by KpjComp** [comment]
Your using the same phInstance for all of them..

Do this -> call like -> `webshot(0, todos, instance);`

And modify you webshot to -> `function webshot(id, shots, phInstance) {`

The above will create a closure for the phInstance = instance in your webshot function.  Your problem isn't using phantom, but understanding how asynchronous methods are handled.

**Comment by TonySchu** [comment]
Thank you a lot! I will try this in a minute. But you are totally right, I used Node.js for the first time 3 month ago. Sorry for the noob-mistake.

Best,
Tony

**Comment by KpjComp** [comment]
> Sorry for the noob-mistake.

No need to be sorry, the asynchronous nature of node.js is probably the hardest part to master.  The good news is it's going to get a lot easier,  `async` & `await` are coming, in fact if you don't mind running node in `--harmony-async-await` you can use them now.  Also the `let` keyboard also helps with asynchronous confusion's :) .

**Comment by amir20** [comment]
When I was reading your code on my iPhone I noticed you set globally the phantom instance as well. That could behave incorrectly. 

Hopefully that fixes it. 

Thanks KpjComp for help!

Sent via my iPhone

**Comment by TonySchu** [comment]
Thank to both of you for your time. I followed the recommendation and changed my code to the following:

`    function initPhantom(todos) {
        var phantom = require('phantom');
        phantom.create(['--ignore-ssl-errors=no'], {logLevel: 'error'})
            .then(function (instance) {
                var processId = instance.process.pid;
                console.log("===================> instance: ", processId);
                webshot(0, todos, processId, instance);
            }).catch(function(e) {
            console.log(e);
        });
    }


        function webshot(id, shots, processId, phInstance)  {
            phInstance.createPage().then(function (_page, error) {
                if(error){
                    console.log("first", error);
                }
                    sitepage = _page;
                    sitepage.property('viewportSize', {width: 1024, height: 768});
                    //sitepage.property('clipRect', {width: 1024, height: 768});
                    //sitepage.property('userAgent', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36');
                    sitepage.setting("resourceTimeout", 4000);
                    return sitepage.open(shots[id].url);
                }).catch(function(e) {
                    console.log(e);
                }).then(function (status, error) {
                    if(error){
                        console.log(error)
                    }
                    console.log("render %s / %s", id + 1, shots.length, "processId: ", processId);
                    setTimeout(function () {
                        var image = 'temp_img/' + shots[id]._id + '.png';
                        sitepage.render(image, {format: 'png', quality: '30'})
                            .then(function (finished, error) {
                            if(error){
                                console.log(error)
                            }
                            sitepage.close();
                            chekcImageinDb(shots[id], image);
                            if (id < shots.length-1) {
                                id += 1;
                                webshot(id, shots, processId, phInstance);
                            } else {
                                //process.kill(processId);
                                console.log("===================> all done: %s files has been written", shots.length, "processId: ", processId);
                                 phInstances.shift();
                                /*if(phInstances.length < 1){
                                     console.log("kill phantom ", phInstances);
                                }*/
                            }
                        }).catch(function(e) {
                            console.log("last before - processID: ", processId ,e);
                        });
                    }, 2000);
                }).catch(function(e) {
                console.log("last one", e);
            })
        }`


Still the same error, when doing multiple instances:
<img width="722" alt="bildschirmfoto 2016-11-24 um 17 50 12" src="https://cloud.githubusercontent.com/assets/19664656/20605999/89cadda6-b26e-11e6-9337-656efee87414.png">
](url)

**Comment by TonySchu** [comment]
Thank god, it is working now. 
My problem was that page was still globally set. 
No it is working perfectly.

Thanks again!
