### ISSUE TITLE
Example hangs with no error

### ISSUE THREAD

**Issue by yourfavorite** [amir20/phantomjs-node#586]
```
var phantom = require('phantom');
console.log('0');
phantom.create().then(function(ph) {
  console.log('1');
  return ph.createPage(function(page) {
    console.log('2');
    return page.open("http://www.google.com", function(status) {
      console.log("opened google? ", status);
      return page.evaluate((function() {
        return document.title;
      }), function(result) {
        console.log('Page title is ' + result);
        return ph.exit();
      });
    });
  });
}).catch(error => {
  console.log(error);
});
```

Using the above code, I get a log of 0 and a log of 1 and then the terminal window just hangs with no other output. Not sure how to troubleshoot this further.

Node: 6.9.1 and 7.2.0 (tried both)
Phantomjs: 2.1.1
Phantom: 3.1.0

**Comment by amir20** [comment]
Createpage and open return a promise. You are not using .then() the right way. See the documentation for correct usage.

**Comment by yourfavorite** [comment]
Ah, I see. I think I was following an old tutorial from another site. Thanks!
