### ISSUE TITLE
Phantom pool

### ISSUE THREAD

**Issue by olalonde** [amir20/phantomjs-node#590]
I just wrote a resource pool for phantomjs-node: https://github.com/blockai/phantom-pool

I wrote it to speed up the creation of phantom instances (made a big difference in my benchmarks). Posting here in case it's useful to anyone else.

**Comment by amir20** [comment]
Hey that's pretty cool! I recommend adding a link to readme file at the bottom. How much faster was it?

**Comment by amir20** [comment]
Also you should call page close. Otherwise it's a memory leak.

**Comment by amir20** [comment]
@olalonde I will probably close this issues this week as it is not really an issue. Feel free to send a pull request to add your pool to a section at the bottom of the README.

**Comment by olalonde** [comment]
Ok, I'll add something to README.

I had a script which generated web screenshots. Here, I was creating a phantom instance for each screenshot and then destroying it:

```
info: Migrating 5eVMdE
info: Migrated 5eVMdE in 8.70s
info: Migrating mep2bM
info: Migrated mep2bM in 8.60s
info: Migrating 7ax9by
info: Migrated 7ax9by in 8.47s
info: Migrating YaOpbx
info: Migrated YaOpbx in 7.52s
info: Migrating RdG7dD
info: Migrated RdG7dD in 8.56s
info: Migrating QdJ2dO
info: Migrated QdJ2dO in 8.94s
info: Migrating 1aKReQ
```

After, with phantom-pool (re-uses instances instead of creating/destroying each time):

```
info: Migrating RdG7dD
info: Migrated RdG7dD in 5.94s
info: Migrating QdJ2dO
info: Migrated QdJ2dO in 1.19s
info: Migrating mbk5ez
info: Migrated mbk5ez in 1.21s
info: Migrating 7ax9by
info: Migrated 7ax9by in 1.13s
info: Migrating 1aKReQ
info: Migrated 1aKReQ in 1.19s
info: Migrating wdLwbj
info: Migrated wdLwbj in 1.20s
info: Migrating 1aMAaW
```

I don't have that benchmark anymore but if you are often creating/destroying phantom instances, using a pool is almost certainly a good idea.

**Comment by amir20** [comment]
Nice. That's almost an 8x improvement.
