### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by delmotte** [amir20/phantomjs-node#592]
### Expected behavior

Something that just works like on my OSX desktop

### Actual behavior

info: ReferenceError: Can't find variable: require
info: ReferenceError: Can't find variable: requireLazy
info: ReferenceError: Can't find variable: requireLazy
info: ReferenceError: Can't find variable: JSCC

### Steps to reproduce the behavior

```
let _instance = null;
phantom
        .create()
        .then(instance => {
            _instance = instance;
            return instance.createPage();
        })
        .then(page => {
            return page.open('https://facebook.com/search/people/?q=Hello+World');
        })
        .then(() => {
            return _instance.exit();
        })
```

### Environment

- OS: Debian 8
- Node version (`node -v`): v6.9.1
- package version: 3.2.0

**Comment by amir20** [comment]
I have no idea what this ticket means? 

This prints `done` for me. 

```js
var phantom = require("phantom");
let _instance = null;
phantom
        .create()
        .then(instance => {
            _instance = instance;
            return instance.createPage();
        })
        .then(page => {
            return page.open('https://facebook.com/search/people/?q=Hello+World');
        })
        .then(() => {
                console.log('done')
            return _instance.exit();
        })
```

**Comment by amir20** [comment]
I don't have debian by the way. So I don't know if this is an env issue.

**Comment by amir20** [comment]
Tested with Debian using Docker. It worked.

**Comment by delmotte** [comment]
Still got the error ...

**Comment by amir20** [comment]
Your issue is unclear. I am not sure how to reproduce. Sorry I can't help.

**Comment by delmotte** [comment]
I tested with a Docker, one more time, it failed from my Debian 8 VPS ! WTF I can't understand what happen...

**Comment by amir20** [comment]
It doesn't really help that you keep saying it doesn't work but don't actually show any code or steps to reproduce. Maybe it is a language barrier. If you want help, you should provide all detail for me to know how you are running it, what is the environment and what does the dockerfile look like.  Here is what I run

```
FROM debian:8
MAINTAINER Amir Raminfar <findamir@gmail.com>

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y nodejs build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev

RUN npm install phantom
```

And run the test command above with 

```
⨉⪧ ~/Desktop/phantomjs-debian ⟩ docker run -it phantomjs-debian:latest
root@92bd6f09dedf:/# cat >> test.js
var phantom = require("phantom");
let _instance = null;
phantom
        .create()
        .then(instance => {
            _instance = instance;
            return instance.createPage();
        })
        .then(page => {
            return page.open('https://facebook.com/search/people/?q=Hello+World');
        })
        .then(() => {
                console.log('done')
            return _instance.exit();
        })
root@92bd6f09dedf:/# node test.js 
done
```

If you want help, then provide exact files and steps to reproduce this issues.

**Comment by delmotte** [comment]
The problem is when the HOST is Debian 8, I tested to run a docker on my macOS desktop : it works, I tried to run a docker from Debian 8 VPS : it failed.
So, the problem is the _**Debian 8 host**_ !
