### ISSUE TITLE
how can I set the value of 'content'?

### ISSUE THREAD

**Issue by zhzehong** [amir20/phantomjs-node#601]
I set content value like this, 
return page.property('content', body).then(function() {
    return page.property('content').then(function(content){
        console.log(content)
        return null
    })
})
I get the log is
\<html\>\<head\>\</head\>\<body\>\</body\>\</html\>

seems that the page is empty

**Comment by amir20** [comment]
Look at https://github.com/amir20/phantomjs-node/search?utf8=%E2%9C%93&q=setContent&type=Code for example on how to use `setContent`

**Comment by zhzehong** [comment]
ok,thanks
