### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by drchikoze** [amir20/phantomjs-node#604]
Hello,
i'm trying to generate pdf using your module. Charset was setted to UTF8, but report looks agly(with question symbols). Have you  any idea what can be wrong.

### Environment

- OS: ubuntu 12
- Node version (`node -v`): 6.3.0
- package version: 3.2.1

**Comment by amir20** [comment]
Could be related to #551. But that was fixed. I don't know what could be wrong. Can you provide a working example when I can run locally and reproduce?

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.
