### ISSUE TITLE
Crawling over a list of URLs

### ISSUE THREAD

**Issue by isteven** [amir20/phantomjs-node#606]
Hi, first of all, thanks for the excellent library. 

Unfortunately I need to ask a question which seems to have been asked quite a few times here.

I'm a newbie in both nodeJS and PhantomJS, and have been, without success, trying to find the error-free way to loop over and crawl from a list of URLs. 

### Expected behavior

Looping over a list of URLs to crawl. Some of these URLs might generate errors, would be great if somehow I can just grab whatever result I can (ignoring or catching the errors), and then proceed with the next URL in the list.

I also want to put the crawl result into MySQL DB. Most likely I'll be using MySQLJs or something similar.

I'm not looking for the 100% resource efficient method if it's too complicated to understand. For now, anything decent & fast enough is OK.

### Actual behavior

Encountered errors:

Error: undefined is not an object (evaluating 'objectSpace[command.target][command.params[0]]')
    at Stream.Phantom.process.stdout.pipe.on.data (E:\Webroot\nuvisus\crawler\node_modules\phantom\lib\phantom.js:137:45)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (E:\Webroot\nuvisus\crawler\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (E:\Webroot\nuvisus\crawler\node_modules\through\index.js:45:5)
    at emit (E:\Webroot\nuvisus\crawler\node_modules\split\index.js:37:14)
    at next (E:\Webroot\nuvisus\crawler\node_modules\split\index.js:49:7)
    at Stream.<anonymous> (E:\Webroot\nuvisus\crawler\node_modules\split\index.js:54:5)
    at Stream.stream.write (E:\Webroot\nuvisus\crawler\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:555:20)

### Steps to reproduce the behavior

``` javascript
var phantom = require("phantom");
var fs = require('fs');

// siteList.json contains the list of URLs
fs.readFile('siteList.json', 'utf8', function(err, data) {
    if (err) {
        return console.log(err);
    }

    var siteList = JSON.parse(data);

    siteList.forEach(function(website) {

        // The main phantom logic below is taken from the simple.js in the example folder.
        // My simple brain told me just to loop over the thing.
        phantom.create().then(ph => {
            _ph = ph;
            return _ph.createPage();
        }).then(page => {
            _page = page;
            return _page.open( website.url );
        }).then(status => {
            console.log(status);
            return _page.property('content')
        }).then(content => {
            console.log(content);
            _page.close();
            _ph.exit(); // I tried not using exit(), but also encountered error
        }).catch(e => console.log(e));
    });
});
```

### Environment

- OS: Win 7 Ultimate 64 bit
- Node version (`node -v`):  6.9.4
- package version: 4.0.0

**Comment by amir20** [comment]
Not knowing the full context, I am guessing your issue is with `_ph = ph`. `_ph` is never defined and the scope will probably be global by default. I assume this always works over one URL. But over multiple URLs, then `_ph` will be overridden every time and you may actually close another process by accident. This could cause the errors you are seeing. 

This is probably something you are doing, so I'll leave this issue open and help you if I can. But you need to start rethinking about a better way to do this. The loop over the JSON URLs will run really fast and as a result, will have N phantom processes open. You probably should rethink this by introducing a pool or/and process only a few URLs at any given time.

**Comment by amir20** [comment]
Ps. Even though this is a question,  I do appreciate that you followed the template for issues and actually shared some code. That shows you tried something. I hope to figure out what is going on.

**Comment by amir20** [comment]
Possibly related to https://github.com/amir20/phantomjs-node/issues/583. Look for the global scope that caused the error.

**Comment by isteven** [comment]
Hi @amir20 , 

Thanks for the reply.

> Not knowing the full context, I am guessing your issue is with _ph = ph. _ph is never defined and the scope will probably be global by default. I assume this always works over one URL. But over multiple URLs, then _ph will be overridden every time and you may actually close another process by accident. This could cause the errors you are seeing.

At the moment, the full context is just those code. Additionally, siteList.json is just this:

```json
[
    { "url": "http://www.stackoverflow.com" },
    { "url": "https://news.ycombinator.com/" },
    { "url": "http://edition.cnn.com/" }
]
```
Following your advice, can give me a pointer on my code to make the _ph scope local? 

> Possibly related to #583. Look for the global scope that caused the error.

I tried following #583 (and other similar issues), but I couldn't really understand the way it resolves the promises.

Any other more simple JS example to crawl that list of URL and save the result to, say, DB or at least txt file?

> Ps. Even though this is a question, I do appreciate that you followed the template for issues and actually shared some code. That shows you tried something. I hope to figure out what is going on.

If you check my github profile, you'll see that I'm a front-end library developer as well. I understand how hectic things can be, so I try my best to follow whatever bug/issue reporting convention asked by the dev.

**Comment by amir20** [comment]
I haven't test it but I think this would work

```js
 siteList.forEach(function(website) {
        let _ph; // <---- this is scoping _ph
        phantom.create().then(ph => {
            _ph = ph;
            return _ph.createPage();
        }).then(page => {
            _page = page;
            return _page.open( website.url );
        }).then(status => {
            console.log(status);
            return _page.property('content')
        }).then(content => {
            console.log(content);
            _page.close();
            _ph.exit(); // I tried not using exit(), but also encountered error
        }).catch(e => console.log(e));
    });
```

**Comment by isteven** [comment]
@amir20 , 

Thanks a lot, your example works. I now realize my stupidity.. I should have include <code>_ph</code> and <code>_page</code> declarations in the loop as well. Both <code>var</code> and <code>let</code> work.

It's just that I have this error, even on success (I managed to grab the contents)

```
(node:6704) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
TypeError: Cannot read property 'catch' of undefined
```

Any idea why?

**Comment by protspace** [comment]
I am also struggling with the same kind of crawler for a list of urls

```
    (node:26686) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 29):     Error: Phantom process stopped with exit code null
error: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
(node:26686) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): Error: Error reading from stdin: Error: This socket has been ended by the other party
error: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

```
