### ISSUE TITLE
!!!ERROR AFTER NEW COMMIT

### ISSUE THREAD

**Issue by TonySchu** [amir20/phantomjs-node#608]
Hi, 

I did a new deployment on my server and I get this error:
[
<img width="818" alt="bildschirmfoto 2017-01-21 um 18 43 13" src="https://cloud.githubusercontent.com/assets/19664656/22176397/ae51b19a-e009-11e6-80ca-e5034118ff0c.png">
](url)

It is working on my local machine(mac), but is crashing after starting the server on the ec2 AWS linux machine.

**Comment by amir20** [comment]
@TonySchu this is most likely caused by an older version of node. < 6 is no longer supported.

**Comment by TonySchu** [comment]
Hi amir,

thanks for the fast response! Sorry for not checking the Node-Version!
