### ISSUE TITLE
page.clearMemoryCache not available

### ISSUE THREAD

**Issue by rafaelmaiolla** [amir20/phantomjs-node#609]
I saw that there are other issues closed regarding the `clearMemoryCache`, but none of them resolved the issue itself.

Is there a workaround for it? Will `clearMemoryCache` be available in the near future?

**Comment by amir20** [comment]
You should be able to use `invokeMethod` as document in README. Something like `page.invokeMethod('clearMemoryCache'). I haven't tried this myself. Pull requests are welcomed.

**Comment by rafaelmaiolla** [comment]
That worked.  Thank you!
