### ISSUE TITLE
 Parsing function in params

### ISSUE THREAD

**Issue by n30n0v** [amir20/phantomjs-node#610]
Hi!

I'm trying to paste markup in page through `evaluate` method and pass parameters into it.  It works perfectly until that parameter is not string like this: `'function () { ...}'`.

In file `src/shim/index.js`, method `read` try  parse function:

```js
let command = JSON.parse(line, function(key, value) {
    if (value
        && typeof value === 'string'
        && value.substr(0, 8) === 'function'
        && value.indexOf('[native code]') === -1) {
        const startBody = value.indexOf('{') + 1;
        const endBody = value.lastIndexOf('}');
        const startArgs = value.indexOf('(') + 1;
        const endArgs = value.indexOf(')');

        // eslint-disable-next-line no-new-func
        return new Function(value.substring(startArgs, endArgs), value.substring(startBody, endBody));
    }
    return value;
});
```

Why is it necessary and which ways of solving this?

### Steps to reproduce the behavior

1. create file `index.js` such as:

```js
const phantom = require('phantom');

(async function() {
    const instance = await phantom.create();
    const page = await instance.createPage();

    await page.invokeMethod('evaluate', function (code) {
      document.body.innerHTML = code
    }, 'function hi{ return invalid js for example}');

    const content = await page.property('content');
    await instance.exit();
}());
```

2. run `node --harmony-async-await index.js`

### Expected behavior

Paste markup in page

### Actual behavior

Error:
```bash
info: SyntaxError: Expected an identifier but found 'js' instead
```

### Environment

- OS: Mac
- Node version: v7.4.0
- package version: 4.0.0

**Comment by amir20** [comment]
This is necessary because _everything_ is serialized as json between node and phantomjs. This also include functions. So something like `page.evaluate(function(){...})` will actually convert `function(){...}` to `"function(){...}"`. On the phantomjs side, it checks to see if it finds function decelrations and tries to parse it by creating `new Function(...)`. 

I don't know how to go about fixing it. I am not sure what you are trying to do. If you want to update the content, then why aren't you using `setContent`?

**Comment by amir20** [comment]
Also, I am guessing if you did `<code>function hi{ return invalid js for example}</code>` that it wouldn't break.

**Comment by n30n0v** [comment]
I saw command format, it's looks something like this `{"id":2,"target":"page$1","name":"invokeMethod","params":["evaluate","function (code) {\n      document.body.innerHTML = code\n    }","string"],"deferred":null}`. But I suppose that parsing function unnecessary and ONLY in phantom side string will be parse. 

I'm try delete part of parsing and my example perfectly works. 

But it may breaks other cases, I don't know, but tests passed. I prepare PR anyway

By the way, in native phantom also may pass parameters looks like ''function () {...}"
