### ISSUE TITLE
High CPU usage even when not processing anything

### ISSUE THREAD

**Issue by UKNC** [amir20/phantomjs-node#612]
### Expected behavior

%CPU should be around zero.

### Actual behavior

CPU is high, sometimes 70% when no work is requested from phantom.
http://pix.toile-libre.org/upload/original/1485956272.png

### Steps to reproduce the behavior

I have not tried to isolate the problem. The module is a part of a complicated program. 

The program is NodeJS server which accepts HTTP GET requests and while processing them uses phantom module to build a web page, parse it, retrieve info from it and use the info in the response to the requests.

After several requests and phantom usage, phantom module continues to consume CPU even when no requests are performed to the server, as it can be seen from the attached image.

Any conclusions which can be made from _top_ output provided in the link above are highly appreciable.

### Environment

- OS: CentsOS7
- Node version (`node -v`): 7.2.1
- package version: 3.2.1

**Comment by amir20** [comment]
This is either something going on with upstream phantomjs which I can't control or the heartbeat is causing this. This was fixed in https://github.com/amir20/phantomjs-node/pull/577 so I am not sure if something else is new.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.
