### ISSUE TITLE
How to access child pages?

### ISSUE THREAD

**Issue by stanisfun** [amir20/phantomjs-node#614]
Is there a way to access child page? (if a page was opened in new tab from current page)

**Comment by amir20** [comment]
There is not. This was also asked in #545. I never added the functionality. :(

**Comment by UKNC** [comment]
A new window (tab) is opened through window.open( url, target="_blank"). Is there a way to know what url is? Tracking onNavigationRequest does not help. 

Using 
```
page.property('onPageCreated', function(newPage) {
})

```

does not help as `newPage`  is not real page object.

What can I do?

**Comment by amir20** [comment]
@UKNC is this question related to child pages?

**Comment by UKNC** [comment]
@amir20 I think yes. If I could access child page that is opened through `window.open` I could determine the `url`. I cannot and I don't see any way to do that.

**Comment by safvanak** [comment]
var newPage =  require('webpage').create();
newPage=page.pages[0];
newPage.render("Child.jpg");

**Comment by amir20** [comment]
@safvanak  I don't think you understand the problem. You wrote phantomjs code, not node. 

@UKNC The only way to get this supported is to add the feature. I won't have time for the next few weeks. Feel free to send me a PR if you can. I can merge asap.

**Comment by Vinayk93** [comment]
we got a sample problem here
we opened multiple page but how to get the reference of each page

**Comment by Vinayk93** [comment]
i create a issue please look forward to it.
https://github.com/amir20/phantomjs-node/issues/633

**Comment by calvinl** [comment]
@amir20 I'm up for creating a PR for this, but I want to make sure this is related to the problem I'm having first: 

I have this code: 

```
let results = { urls: [] };

phantom.create([], {
  phantomPath: '/usr/local/bin/phantomjs',
  logLevel: 'info'
}).then(function(instance) {
  return instance.createPage();
}).then(function(page) {
  page.on('onPageCreated', function(newPage) {
    // `results` object is accessible in this closure
    newPage.onLoadFinished = function() {
      // however, it's not available in here (this is in PhantomJS context?)
      results.urls.push(newPage.url);
    };
  });
})
```

Essentially, I need to capture the URLs of popup windows, but I can't push the URL to the node context. Feels like we should be able to do something like this:

```
page.on('onPageCreated', function(newPage) {
  newPage.on('onLoadFinished', function() {
    results.urls.push(newPage.url);
  };
});

I can work on the PR if you can point me in the right direction.

**Comment by amir20** [comment]
Hmm, this one is a little tricky. You are trying to do a callback inside another callback! Trouble ensues. 

Here is what I think is happening....

```js
page.on('onPageCreated', function(newPage) {
  // this is node. I believe newPage is serialized. so you can't call methods on. 
});
```

Why can't you just push to `results` on `onPageCreated`. Why do you have to wait for it finish?

**Comment by calvinl** [comment]
@amir20 Thanks for getting back to me. `newPage.url` isn't available until it finishes loading, for some reason -- see here: http://phantomjs.org/api/webpage/handler/on-page-created.html

**Comment by amir20** [comment]
OK, then to answer your orginal question. This is not related to new child pages. I believe the point of this issue was to add `page.pages[0]` support. Insteaed, you want to be able to open a new page and access that page via node in a callback. 

I am trying to figure out the easiest way to do that. The logic for creating a new page is [here](https://github.com/amir20/phantomjs-node/blob/master/src/shim/index.js#L20) in phantomjs. This is where the page object is saved and an ID is returned to node. When a page is created via `onPageCreated`, node has no idea. Unfortunately, I don't have an easy solution for you. But I am hoping I gave you some ideas on what is going on.

**Comment by amir20** [comment]
The more I think about your use case @calvinl, I think you should use vanilla phantomjs. Your use case is too specific so you might struggle to get node/phantom to talk to each other correctly. All calls are async and that's why it is hard to have multiple callbacks.

**Comment by calvinl** [comment]
@amir20 thanks. I was starting to lean toward that too, I was just hesitant at first because the rest of the script I'm writing is in node, so it'd be nice to have an integrated option. I'm thinking I'll just set up PhantomJS as a service to be called via node or something. Thanks for your help!

**Comment by amir20** [comment]
I think I am going to close this since there isn't much activity and I don't have plans to add this feature.
