### ISSUE TITLE
onResourceRequested not pass networkRequest object

### ISSUE THREAD

**Issue by eyalcohen4** [amir20/phantomjs-node#617]
### Expected behavior

When I open a page, I want to be able to check if phantom will redirect from the URL I asked for.
If so, I want to abort the redirect request.
I was trying to do it with:
```
page.on('onResourceRequested`, function (requestData, networkRequest) {
    if (....) {
       networkRequest.abort();
   } 
 });`
```

### Actual behavior

I get an error: 
```
 if (redirectURLs.indexOf(requestData.url) !== -1) {
                             ^
ReferenceError: redirectURLs is not defined
```

### Steps to reproduce the behavior

1. Open a page
2. Catch the onResourceRequested event
3. Do networkRequest.abort();

### Environment

- OS: Ubuntu 16.10
- Node version (`node -v`): 7.4.0
- package version: 2.1.21

**Comment by amir20** [comment]
I would first upgrade to the latest version. Then make sure you read [this part](https://github.com/amir20/phantomjs-node#pageon) of the README. You can't call `abort()` in node, it has to be in phantom.

**Comment by eyalcohen4** [comment]
tnx for the quick answer!
