### ISSUE TITLE
close a page except quite the instance

### ISSUE THREAD

**Issue by h2y** [amir20/phantomjs-node#618]
```
const phantom = require('phantom'),
    co = require('co');

phantom.create(['--load-images=no'])
.then(instance => {
    co(function* () {
        for(let i = 0; i < 20; i++) {
            const page = yield instance.createPage();

            const status = yield page.open('http://www.diaox2.com');
            console.log(status);

            const content = yield page.property('content');

            yield page.stop();
            yield page.close();
        }
    });
});
```

### Expected behavior

I dont want to create a instance for every link, so I just create one instance. And use `page.stop()`, `page.close()` to close a link after get contents.

### Actual behavior

Memory can't be recycled by `.close`

<https://github.com/ariya/phantomjs/issues/13923> There is another issue same to me.

### Environment

- OS:Win10 x64
- Node version (`node -v`): 7.4.0
- package version: 4.0.0

**Comment by amir20** [comment]
So this is an upstream issue with phantomjs then? The fix would need to be done in phantomjs. https://github.com/ariya/phantomjs/issues/11390

**Comment by h2y** [comment]
I need to restart the instance in a interval.
(｡•́︿•̀｡)
