### ISSUE TITLE
phantom's installation of phantomjs won't start on Docker/Linux container

### ISSUE THREAD

**Issue by ckundo** [amir20/phantomjs-node#619]
### Expected behavior

When I include `phantom` as a dependency, and I require it to invoke `phantomjs` command, then `phantomjs` should load from the correct file path and run.

### Actual behavior

When I include `phantom` in my project as a dependency and then use it to invoke a `phantomjs` action, I get an error:

```
error: Could not spawn [/usr/app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.
```

### Steps to reproduce the behavior

1. `npm install -g accesslint-cli` on a linux environment
1. `accesslint https://www.accesslint.com`

```
error: Could not spawn [/usr/lib/node_modules/accesslint-cli/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.
```

### Environment

- OS: Alpine Linux 3.5 running in a Docker container (Docker 1.13.1 on Ubuntu 16.04)
- Node version (`node -v`): v6.9.2
- package version: [2.1.2](https://github.com/accesslint/accesslint-cli.js/blob/master/package.json#L35)

## Notes

This may be related to https://github.com/amir20/phantomjs-node/issues/514, and might be resolved by updating `phantomjs-prebuilt` to `2.1.9`.

**Comment by ckundo** [comment]
Not 100% sure, but this issue may be due to being on a 64 bit environment trying to run `phantomjs` compiled for 32 bit architecture. Investigating more.

**Comment by ckundo** [comment]
This turned out to be an issue with phantomjs not compiling correctly in Alpine Linux (see https://github.com/sgerrand/alpine-pkg-glibc/issues/13). Solution was to install an Alpine specific package: https://github.com/Overbryd/docker-phantomjs-alpine/releases/tag/2.11

**Comment by beeman** [comment]
Got here via Google, the command linked above does not seem to work with the node-alpine images because there is no `curl` installed.

This command works for me:

```
RUN apk update && apk add --no-cache fontconfig curl && \
  mkdir -p /usr/share && \
  cd /usr/share \
  && curl -L https://github.com/Overbryd/docker-phantomjs-alpine/releases/download/${PHANTOM_VERSION}/phantomjs-alpine-x86_64.tar.bz2 | tar xj \
  && ln -s /usr/share/phantomjs/phantomjs /usr/bin/phantomjs \
  && phantomjs --version
```

**Comment by daaain** [comment]
Same as @beeman, but I also had a problem with a weird `curl` error message ("curl: (48) An unknown option was passed in to libcurl"), so had to add `curl-dev` 🙄 

```
RUN apk update && apk add --no-cache fontconfig curl curl-dev && \
  mkdir -p /usr/share && \
  cd /usr/share \
  && curl -L https://github.com/Overbryd/docker-phantomjs-alpine/releases/download/2.11/phantomjs-alpine-x86_64.tar.bz2 | tar xj \
  && ln -s /usr/share/phantomjs/phantomjs /usr/bin/phantomjs \
  && phantomjs --version
```

**Comment by wader** [comment]
I had problem with phantomjs hanging on all script. This versions worked better for me https://github.com/ariya/phantomjs/issues/14186#issuecomment-381924432

**Comment by sudeepdk** [comment]
This will work 100 % -- follow this it worked for me ... 

https://www.vultr.com/docs/how-to-install-phantomjs-on-ubuntu-16-04

**Comment by amir20** [comment]
For all those who end up here, there is an example Dockerfile at https://github.com/amir20/phantomjs-node/blob/master/examples/Dockerfile. It's a little old but still works.

**Comment by beeman** [comment]
Thanks for sharing Amir! 🙏

**Comment by redaxmedia** [comment]
Solved the issue on Alpine image using:

```
npm install phantomjs-prebuilt --global --unsafe-perm
```
