### ISSUE TITLE
await instance.exit();

### ISSUE THREAD

**Issue by shirmin** [amir20/phantomjs-node#621]
await instance.exit();
console.log('pass');

### Expected behavior

do show 'pass'

### Actual behavior

Sometimes it can't pass the exit() and show nothing. Even added try()catch{}

### Steps to reproduce the behavior

I don't know how to reproduce, but it occur every some hours in our system.

### Environment

- OS: Windows Server 2008
- Node version (`node -v`):  7.5.0
- package version: 3.2.0

**Comment by protspace** [comment]
I'm developing a crawler which parses a list of sites in a loop with throttle.
I think I also have the same problem which appear randomly time to time.  
For example this first "zombie" instance if hanging for a long time and uses CPU time
http://prntscr.com/eeotcr

**Comment by amir20** [comment]
@shirmin any update? I am not sure what is the action item here. Also pease update to version `4.0.0`

**Comment by shirmin** [comment]
We changed code to:
try{
 await instance.kill();
 await instance.exit();
} catch ...

and updated to 4.0.0

Our system runs as we expected. 
thanks.

**Comment by amir20** [comment]
WOOHOO!
