### ISSUE TITLE
Support of customized environment variables to phantomjs

### ISSUE THREAD

**Issue by ZizhangAi** [amir20/phantomjs-node#622]
In my application I need to set the timezone for phantomjs, and from my understanding currently we cannot pass environment variables to the child process, something like `this.process = spawn(phantomPath, args.concat([pathToShim]), {env: env});`. What's your thoughts on this? Thanks.

**Comment by amir20** [comment]
Well this is an interesting one. I think a good solution would be to forward all env cars from the node process to phantom. Ideally this should be transparent to the user. 

Can you send a pull request?

**Comment by amir20** [comment]
Ping @ZizhangAi

**Comment by ZizhangAi** [comment]
@amir20 Hi I'm busy with work but will send a PR as soon as I can. Thx.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.
