### ISSUE TITLE
gzipp'ed pages are not decompressed

### ISSUE THREAD

**Issue by UKNC** [amir20/phantomjs-node#623]
### Expected behavior

Compressed pages to be decompressed automatically.

### Actual behavior

Pages are not decompressed.

### Steps to reproduce the behavior

Here is the demo:
https://gist.github.com/UKNC/887059b4bf6359ced5d1d982399dd32e

When you run it as
`> node server.js 0`

it sets custom headers: 
` { "Accept-Encoding": "identity;q=1.0, gzip;q=0"}`

and google sends plain htmls.

When you run as 
`> node server.js 1`

the header is 
` { "Accept-Encoding": "identity;q=1.0, gzip;q=1"}`

and google sends gzipped html. 

On the console you can see gibberish.

### Environment

- OS:
- Node version (`node -v`): 7.2.1
- package version: 4.0.0.

**Comment by amir20** [comment]
This looks to be related to a bug in phantomjs. See https://github.com/ariya/phantomjs/issues/13621.
