### ISSUE TITLE
Re-use page object

### ISSUE THREAD

**Issue by branpar** [amir20/phantomjs-node#624]
### Expected behavior

Once I initialize page.createPage() I can do multiple actions with it. Right now if I create it I can then do .open() but if later I want to take a screenshot of the page I opened, say in a different function, I am unable to do so because it requires a promise. 

### Actual behavior

I create the page object and use .open() to open the page. Later on in the code I call a function that takes a screenshot of the page. I get back a blank screenshot. However, if I chain .open().then( .render() ) I get back a screenshot. I require abstraction of this functionality for my project. 

### Environment

- OS: Windows 7
- Node version (`node -v`): v6.6.0
- package version: v4.0.0

**Comment by amir20** [comment]
I don't think I understand your problem. You have to use a promise. There is no way around it since it is an async execution. Can you clarify?

**Comment by branpar** [comment]
Hi,

Thanks for the quick response. I am trying to use es6 modules to abstract out functionality so that I can build a test automation suite. By doing this we can have a stepped-approach to testing. As an example, say I want an end-to-end test for an ecommerce website. So I would have steps, I want to open the homepage, then take a screenshot, then click on log on, take a screenshot, then I want to add in a username and password and click on the "Log on" button. Then I branch and test what happens if the username/password is correct or incorrect, because the expectation is they will take me to different places.

By doing this I can test flows on the website using a step logic. The problem with the promise returns is that I can't break these into steps. Instead of having a function to open a URL, then another to take a screenshot, I can only open the URL -or- I can open the URL and then take the screenshot in one step.

The way the compiled Phantom executable works is this method of steps. I can create a page variable in JS and then later on take a screenshot of the page using that same created page. I cannot do that with this module as-is.

So really if I want to navigate to a page and take a screenshot always it will work. But if I want to navigate around, interact with the page, and then only certain times take a screenshot I can't do that, unless I wrote a function for this specific scenario, which means a ton of repetitive code (imagine all the .open()'s chained to everything else.  It's just not scale-able. 

Do you understand my use-case and why I can't accomplish this with a promise being returned always?

**Comment by amir20** [comment]
I don't think your question is related to phantom node module. I'll try my best to answer. 

> By doing this I can test flows on the website using a step logic. The problem with the promise returns is that I can't break these into steps. Instead of having a function to open a URL, then another to take a screenshot, I can only open the URL -or- I can open the URL and then take the screenshot in one step.

I am not sure what you mean by this. You can do something like 

```js
const page = await phantom.open(...);
await page.evaluate(funtion(){...});
// do some other stuff 

if(someCondition){
   await page.render();
}
```
I am using `await` but there is not difference if I was to use promises and chain `then`. I think the idea of promises is just confusing you. 

> The way the compiled Phantom executable works is this method of steps. I can create a page variable in JS and then later on take a screenshot of the page using that same created page. I cannot do that with this module as-is.

You can do the same thing as I showed above. Your code can be linear and based on a condition do something else. 

> So really if I want to navigate to a page and take a screenshot always it will work. But if I want to navigate around, interact with the page, and then only certain times take a screenshot I can't do that, unless I wrote a function for this specific scenario, which means a ton of repetitive code (imagine all the .open()'s chained to everything else. It's just not scale-able.

I don't know what this means. 

> Do you understand my use-case and why I can't accomplish this with a promise being returned always?

I guess I don't. I think if I saw code it would be easier to help out. 

Again, it feels like you are confused on using promises. Promises are not going away any time soon. Phantom communication is async. Did you have something else in mind that I am not understanding?

**Comment by branpar** [comment]
> I am using await but there is not difference if I was to use promises and chain then. I think the idea of promises is just confusing you.

I understand how to use promises. I also attempted to use async / await and that didn't work either. Here's an example:

**Test Case 1**
```
function openSite() {
    const status = await page.open('https://stackoverflow.com/');
    console.log(`Page opened with status [${status}].`);
}

(async function() {
    const instance = await phantom.create();
    const page = await instance.createPage();

    await openPage();
}());
```

This will work, it will return "Page opened with status success"

**Test Case 2**
```
function screenshot() {
    await page.render('stackoverflow.png');
    console.log(`File created at [./stackoverflow.png]`);
}

function openSite() {
    const status = await page.open('https://stackoverflow.com/');
    console.log(`Page opened with status [${status}].`);
}

(async function() {
    const instance = await phantom.create();
    const page = await instance.createPage();

    await openPage();
    await screenshot();
}());
```
This will open the page and return "Page opened with status success" and then print out "File created at ./stackoverflow.png" but the screenshot is blank. 

Since the test cases need to be generic to be written I can't have the screenshot function also open the page. Because if I click on a button to add a product to a cart, I can't open the page, I need to screenshot the resulting page. This works with the phantom executable broken into functions. it does **not** work with this package using promises or async.

**Comment by amir20** [comment]
I am not sure where is `openPage`. I see `openSite` but not page. If I fix it to 

```js
const phantom = require('phantom');

let page;
let instance;

async function screenshot() {
    await page.render('stackoverflow.png');
    console.log(`File created at [./stackoverflow.png]`);
}

async function openPage() {
    const status = await page.open('https://stackoverflow.com/');
    console.log(`Page opened with status [${status}].`);
}

(async function() {
    instance = await phantom.create();
    page = await instance.createPage();

    await openPage();
    await screenshot();
}());

```

Then I see a screenshot and it works for me. I can't reproduce your results.

**Comment by amir20** [comment]
ping @branpar

**Comment by branpar** [comment]
Hi @amir20, I think I'm going to try to take my project in a different direction. Making Phantom work in Node isn't working and it works with the stand-alone Phantom executable file. Thanks for your assistance.

**Comment by amir20** [comment]
I still don't understand the problem. I wasn't able to reproduce the bug.  

Good luck.
