### ISSUE TITLE
How can i do if i want to use window object?

### ISSUE THREAD

**Issue by DawnLck** [amir20/phantomjs-node#627]
### How can i do if i want to use window object?
Phantom can use the window object like below:
`console.log(window === this);
window.scrollTo(0,10000);
phantom.exit();?`
But is there a window object in phantomjs-node?
The docs in npm is too short, and it just confuse me.
Waiting for your answer.

**Comment by amir20** [comment]
You can use window to get values. Here is the [example](https://github.com/amir20/phantomjs-node/blob/a0e550b1c61f87bc854697a75b7ee2f2a0c87186/src/__test__/page.spec.js#L246). But you can't use it to call methods.
