### ISSUE TITLE
Missing API clearMemoryCache()

### ISSUE THREAD

**Issue by IAMtheIAM** [amir20/phantomjs-node#628]
### Environment

- OS: Windows 10 x64
- Node version (`node -v`): 4.4.7
- package version:  ^2.2.21

According to [this commit ](https://github.com/ariya/phantomjs/commit/5768b705a019da719fa356fdbf370f3ea72b4c93) there should be a method available to clear the page cache called clearMemoryCache().

 But when I call page.clearMemoryCache() - it says `
[TypeError: page.clearMemoryCache is not a function]`

Is this method implemented in phantomjs-node and if so, how do we use it? If not, how do we clear the page cache?

**Comment by amir20** [comment]
It's not implemented. It's really easy to add it. You could use [invokeMethod](page#invokeMethod) or add a PR to add it [here](https://github.com/amir20/phantomjs-node/blob/master/src/page.js#L95).
