### ISSUE TITLE
PhantomJS cutting/splitting words in half across page breaks

### ISSUE THREAD

**Issue by IAMtheIAM** [amir20/phantomjs-node#629]
### Environment

- OS: Windows 10 x64
- Node version (`node -v`): 4.4.7
- package version:  ^2.2.21

What steps will reproduce the problem?
  1. Create multi page website
  2. Render as pdf

I am using the phantomjs-node api to render a PDF. The problem is that words that appear near the end of a page are split across 2 pages, half the word on page 1, other half on page 2. I cannot understand why this is happening. What can I do to fix this?

![phantomjs_cutting_words_in_half_across_page_breaks](https://cloud.githubusercontent.com/assets/13709948/23868424/92e59e26-07dc-11e7-8fa2-817a0f0bb1e9.png)

**Comment by amir20** [comment]
This is most definitely a phantomjs issue. Setting it as an upstream label.

**Comment by IAMtheIAM** [comment]
Ok, thank you, I opened an [issue](https://github.com/ariya/phantomjs/issues/14892) at phantomjs directly.
