### ISSUE TITLE
How to pass variable to function within page.evaluate?

### ISSUE THREAD

**Issue by Darker** [amir20/phantomjs-node#630]
I have defined a function that sets value to reactJS element:

```
function reactJSSetValue(elm, value) {
    elm.value = value;
    elm.defaultValue = value;
    elm.dispatchEvent(new Event("input", {bubbles: true, target: username, data: value}));
}
```

I want to use it to login to my page:
```
    let result = await page.evaluate(function(){
        reactJSSetValue(document.querySelector("#id-username"), LOGIN_DETAILS.name);
        reactJSSetValue(document.querySelector("#id-password"), LOGIN_DETAILS.password);
        document.querySelector("fieldset div.wrap button").click();
        return true;
    });
```
But that won't work:
```
info: ReferenceError: Can't find variable: reactJSSetValue
info:   undefined:2 in anonymous
info:   :7
null
```

I figured the variable context is lost for the callback, so I tried to `bind({reactJSSetValue: reactJSSetValue})` on the callback, but got this error:
```
warn: Arrow functions such as () => {} are not supported in PhantomJS. Please use function(){} or compile to ES5.
(node:13256) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Arrow functions such as () => {} are not supported in PhantomJS.
(node:13256) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-z
ero exit code.
```

How do I pass that function to page scope?

**Comment by amir20** [comment]
So phantom-node and phantomjs are two different processes. You can't pass variable or functions. This question has been asked a few times and I haven't been able to solve it. One way would be to do something like

```
page.defineMethod('reactJSSetValue', function(){...});
```

But that would only work if `reactJSSetValue` doesn't call any other methods. This quickly gets complicated so I never implemented it. I am open to ideas.

**Comment by elias-winberg** [comment]
@amir20 you can actually pass arguments:

```js
page.evaluate(function(message) {
    console.log(message);
}, 'Hello, world!');
```

**Comment by amir20** [comment]
Yea @elias-winberg but I don't think you can pass functions. :/ @Darker was trying to figure out how to pass `reactJSSetValue`. If the function is isolated then it might work but it won't work if that function depends on other functions.

**Comment by elias-winberg** [comment]
Oh, my mistake, sorry! Maybe we could add something like `defineGlobalFunction` that adds the function to the global scope rather than to the page?

**Comment by amir20** [comment]
@elias-winberg that's genius! haha. I didn't think of that. The one gotcha is to make sure inside `evaluate` no other global methods are used. That's mostly why I didn't implement this because then it would be misused and probably filed as a bug. For example, if `foo()` calls `bar()`. Both `foo` and `bar` need to be in phantomjs. 

Anyway, looks like there is a solution! So I think we can close this.

**Comment by tiger6201** [comment]
ty elias-winberg your answer helped me, i was stuck for hours.
