### ISSUE TITLE
How to post an event from page to nodeJS?

### ISSUE THREAD

**Issue by Darker** [amir20/phantomjs-node#631]
In case this question isn't clear, here's full description: http://stackoverflow.com/q/42836875/607407

**Comment by amir20** [comment]
Hello, 

Have you been able to get this to work in vanilla phantomjs? When using `page.on`, I am pretty sure it only works for phantom events. Not custom events inside the dom. I don't think that would work as you expected. Perhaps if you can get it to work in phantomjs then I can figure out why it's not working.

**Comment by Darker** [comment]
Yes, `page.on` does not receive custom DOM events. The question therefore is how to trigger `page.on` event from DOM. If I knew how to do that in phantomjs, problem would be solved.

**Comment by amir20** [comment]
Yea, I don't know of such way. This module is just a wrapper. No new functionality is possible.
