### ISSUE TITLE
If I hava a async operating in 'script' tag, how could I do to make sure rendering page after get full data.

### ISSUE THREAD

**Issue by lastIndexOf** [amir20/phantomjs-node#632]
Hello, when I get a page from phantom I can't get data from ajax

Such as 
```
<script>
request.get('/ajax')
  .end((err, res) => {
     dom1.innerHTMl = res.text
  }


</script>


```

In this code, dom1 can't be rerender for 'res.text'

How could I do to resolve it??

Thank u

**Comment by amir20** [comment]
This is not an issue for this module and probably an upstream issue instead. Closing as I don't think I can help.
