### ISSUE TITLE
Window object

### ISSUE THREAD

**Issue by UltraDosaaf** [amir20/phantomjs-node#638]
There is this function: `window.callPhantom()` that could be used as callback Page -> Phantom, but how to call opened page Phantom -> Page??? If inside webpage exist `window.pageIsCalled()` function, so how can I access global `window` object from phantom side?

**Comment by amir20** [comment]
I don't know what you are asking.

**Comment by UKNC** [comment]
I will try to answer. 

There is no window.pageIsCalled().  You should send to the callback handler outObject and then poll on state change of some property.

```

// get window location when window is loaded
let outObj = page.createOutObject();
outObj.objFromPage = {};
await page.property('onCallback', function(objFromPage, outObj) {
   outObj.objFromPage = objFromPage;
}, outObj);

let objFromPage = await new Promise( (resolve, reject)=>{
  let iid = setInterval(async function() {
     let obj = await page.outObj.property('objFromPage');
    if (Object.keys(obj).length !== 0) {
      clearInterval(iid);
      return resolve(obj);
   }
 })
});

page.evaluate( function() {
   window.onload = function() {
      window.callPhantom({ loc: window.location});
   }
});
```

**Comment by UltraDosaaf** [comment]
There is method called `callPhantom()`. I can call it whenever I want to phantom make me a screenshot.
```html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8">
      <title>animation</title>
      <script type="text/javascript">
         function init(){
            setTimeout(function(){
               window.callPhantom({time: Date.now()});
            }, Math.random() * 1000)
         }
         window.playPageAnimation = function(){
            // play canvas animation
         }
      </script>
   </head>
   <body onload="init();" style="background-color:#ff9900;margin:0px;">
      <canvas id="canvas" width="500" height="400"></canvas>
   </body>
</html>
```

But what if I want to run some animation on that page and only then take a screenshot?
```javascript
page.on('onCallback', data => {
   window.playPageAnimation();
   page.render(path.join(screenshot_folder, Date.now() + '.png'));
}
```

**Comment by amir20** [comment]
I don't think this is a bug. Issues are for bugs or broken functionalities. I honestly don't know how the inner workings of phantomjs in regards to callPhantom so I cannot help.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
