### ISSUE TITLE
setting resourceTimeout causes disabling images and javascript 

### ISSUE THREAD

**Issue by intergleam** [amir20/phantomjs-node#639]
### Expected behavior

to follow [phantomJS docs](http://phantomjs.org/api/webpage/property/settings.html)

### Actual behavior

when i set `await page.property('settings', { 'resourceTimeout': 50000 });` the page snapshot doesn't contain images and a warning that JS is disabled

### Steps to reproduce the behavior

1. run this code
```
const phantom = require('phantom');

(async function () {
    const instance = await phantom.create();
    const page = await instance.createPage();

    await page.property('viewportSize', { width: 1024, height: 600 });
    await page.property('settings', { resourceTimeout: 50000 });
//or await page.property('settings', { 'resourceTimeout': 50000 });
    const status = await page.open('http://stackoverflow.com/');
    console.log(`Page opened with status [${status}].`);

    await page.render('image.jpg', { format: 'jpeg', quality: '50' });
    console.log(`File created`);

    await instance.exit();
}());
```
2. Check the `image.jpg` file

### Environment

- OS: Linux Ubuntu 16.10 
- Node version (`node -v`): 7.8.0
- package version: 4.0.1

**Comment by amir20** [comment]
@intergleam did you read the [docs](https://github.com/amir20/phantomjs-node#pagesetting)?

**Comment by intergleam** [comment]
of course. mind saying what is wrong with my code?

**Comment by amir20** [comment]
> page.settings can be accessed via page.setting(key) or set via page.setting(key, value). Here is an example to read javascriptEnabled property.

You should be using `page.setting` _not_ `page.property('settings', ...)`
