### ISSUE TITLE
Render page before page is fully loaded

### ISSUE THREAD

**Issue by motleycrew** [amir20/phantomjs-node#644]
Hi Amir

I am trying to take screenshot of a page. However page is rendered only when all of the resources are loaded. How can I render page after a time interval?
Thanks for your help.

Example url: http://bit.ly/2nrdwkQ

      co(function*() {
      var instance = yield phantom.create();
      try {
        var page = yield instance.createPage();
        yield page.setting('userAgent', phantomOptions.userAgent);
        yield page.setting('resourceTimeout ', 500);
        yield page.property('viewportSize', {width: screenshotWidth, height: screenshotHeight});
        yield page.property('clipRect', {width: screenshotWidth, height: screenshotHeight});
        var status = yield page.open(url);

        yield page.on("onLoadStarted", function() {
          var currentUrl = page.evaluate(function() {
            return window.location.href;
          });
          console.log('Current page ' + currentUrl + ' will be gone...');
          console.log('Now loading a new page...');
        });

        console.log("taking screenshot");
        yield page.render(imageDetails.absolutePath, {quality: options.quality});
        console.log("screenshot taken");
        var dstUrl = yield page.property('url');
        var title = yield page.property('title');

        console.log("dst_url:" + dstUrl);
        console.log("title:" + title);
        } catch (e) {
        console.log('Error found: ' + e.message);
       } finally {
        instance.exit();
      }
      }).catch(console.error);

**Comment by amir20** [comment]
hey @motleycrew, I don't I understand your question. If you want to render after an interval then why couldn't you just use `setInterval`?

**Comment by motleycrew** [comment]
Thanks for the prompt response Amir. Sorry I wasn't clear.
http://bit.ly/2nrdwkQ

For the above url it takes roughly 10-18 seconds before it could even reach setTimeout function.

 How do stop/interrupt page.open at specific interval?

        console.time('page-open');
        yield page.open(url);
        console.timeEnd('page-open');
        setTimeout(function () {
          page.render(imageDetails.absolutePath, {quality: options.quality});
        }, 1000);

**Comment by amir20** [comment]
Hello, I am out of the country for the next two weeks. My internet access is limited. However, looking at your question while away, I don't think this is a `phantomjs-node` issue. All calls are proxied to phantomjs. When you do `yield page.open(url);`, it waits until phantomjs completes the request. I would try to do it with vanilla phantomjs and see how that works for you.

**Comment by amir20** [comment]
Any update on this @motleycrew? I will close if I don't hear back.
