### ISSUE TITLE
How to catch the rejection when call `phantom.kill()`?

### ISSUE THREAD

**Issue by huzidaha** [amir20/phantomjs-node#645]
When use `phantom.kill()`, the command line complains:

```
(node:10388) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Phantom process was killed
```

- OS: macOS Sierra 10.12.5 Beta
- Node version:  v6.10.0
- package version: 4.0.2

**Comment by amir20** [comment]
Can you explain how you are running it? Are you using `await` or promise? With `await` you need to wrap with `try-catch`.

**Comment by huzidaha** [comment]
I think it's Node.js's warning, every unhandled promise rejection will print this message. And according to `phantomjs-node/src/phantom.js`

https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L340-L349

```javascript
...
    _rejectAllCommands(errmsg: string = 'Phantom exited prematurely'): void {
        // prevent heartbeat from preventing this from terminating
        clearInterval(this.heartBeatId);
        for (const command of this.commands.values()) {
            if (command.deferred != null) {
                command.deferred.reject(new Error(errmsg));
            }
        }
    }
}
...
```
`command.deferred.reject(new Error(errmsg));` seems to no way to be handled from user's code.

**Comment by amir20** [comment]
That should be handled if you have all the correct promise.catch methods defined. How do you call it?
