### ISSUE TITLE
TypeError: page.evaluateJavascript is not a function

### ISSUE THREAD

**Issue by appfeel** [amir20/phantomjs-node#646]
### Expected behavior
Javascript is injected

### Actual behavior
Error: TypeError: page.evaluateJavascript is not a function

### Steps to reproduce the behavior

```js
const jsPDF = fs.readFileSync(`${global.projectPath}/bower_components/jsPDF/dist/jspdf.min.js`);
const pdfHtml = handlebars.compile(`${fs.readFileSync(`${global.projectPath}/public/pdf/pdf.html`)}`);
const pdfData = { test: 'Hello' };
const html = pdfHtml(pdfData);
await page.setContent(html, '');
await page.evaluateJavascript(jsPDF); // <-- ERROR
const output = await page.evaluate(() => {
    var pdfContent = document.getElementById('pdf-content');
    var doc = new jsPDF();
    doc.fromHTML(pdfContent, 20, 35);
    // var event = new CustomEvent("pdfGenerated", { data: 'Hello' }); // doc.output() });
    // document.dispatchEvent(event);
    return doc.output();
});
```

### Environment

- OS: OSX 10.11.6
- Node version (`node -v`): v6.10.1
- package version: phantom@4.0.2

**Comment by appfeel** [comment]
I've achieved the behavior with:

```js
        const pdfFunctionStr = new Function(`(function () { ${jsPDF}})()`);
        await page.evaluate(pdfFunctionStr);
        const output = await page.evaluate(() => {
            var pdfContent = document.getElementById('pdf-content');
            var doc = new jspdf();
            doc.fromHTML(pdfContent, 20, 35);
            return doc.output();
        });
```

But I'm not sure if not understanding documentation or it is an error: https://github.com/amir20/phantomjs-node#pageevaluatejavascript

**Comment by amir20** [comment]
I can confirm this is a bug :( Thanks for finding it! I'll look in to it today.

**Comment by amir20** [comment]
Well the [tests](https://github.com/amir20/phantomjs-node/blob/a0e550b1c61f87bc854697a75b7ee2f2a0c87186/src/__test__/page.evaluate.spec.js#L80) were written incorrectly! Oops.

**Comment by amir20** [comment]
Hmm. I found your problem. You have a typo. `page.evaluateJavascript` should be `page.evaluateJavaScript`. It is case sensitive.
