### ISSUE TITLE
page.evaluate changes value of string parameter sent to it

### ISSUE THREAD

**Issue by UKNC** [amir20/phantomjs-node#647]
### Expected behavior

```
myPrintText Node:
function myPrint() {
  console.log("Hello, World!");
}
```

### Actual behavior
```
info: myPrintText inside phantom page:
info: myName: John
info: myPrintText:
info: function anonymous() { 
info:   console.log("Hello, World!");
info: }
```

[Describe observed behavior here]

I convert function `myPrint()` into string and assign to myPrintText var: 
`var myPrintText = myPrint.toString()`

Then I send the variable containing function text into page evaluate() function and print contents of the text:

```
await page.evaluate( function( myPrintText, myName ) {
    console.log("myPrintText inside phantom page:\n");
    console.log('myName: '+ myName );
    console.log("myPrintText:\n" + myPrintText );
  }, myPrintText, myName );
```

Somehow, the name of function inside the sent text is changed from `myPrint()` into `anonymous()`

How evaluate() changes text variables sent to it?

### Steps to reproduce the behavior

The case study code:

```
const phantom = require('phantom');
const Promise = require('bluebird');

function myPrint() {
  console.log("Hello, World!");
}

(async function() {
  let ph = await phantom.create();
  let page = await ph.createPage();
 
  await page.property('onConsoleMessage', function(msg) {
    console.log(msg);
  });

  var myName = "John";
  var myPrintText = myPrint.toString();

  console.log("myPrintText Node:\n" + myPrintText);

  await page.evaluate( function( myPrintText, myName ) {
    console.log("myPrintText inside phantom page:\n");
    console.log('myName: '+ myName );
    console.log("myPrintText:\n" + myPrintText );
  }, myPrintText, myName );


})();

```

### Environment

- OS: ubuntu, centos
- Node version (`node -v`): 7.6.0
- package version: 4.0.1

**Comment by amir20** [comment]
I think I know what's going on. The way phantom communicates with node is by doing exactly what you have done (call `toString()` and then parse the string using `Function`). In the [shim.js](https://github.com/amir20/phantomjs-node/blob/master/src/shim/index.js#L136), I look for function and try to deserialize back to a function. The name doesn't really matter so I strip it. 

There isn't a good fix as the parsing is done all the same way. If you do 

```js
await page.evaluate( function( myPrintText, myName ) {
    console.log("myPrintText inside phantom page:\n");
    console.log('myName: '+ myName );
    console.log("myPrintText:\n" + myPrintText );
  }, '  ' + myPrintText, myName );
```

it will work. It's a hack, I am not proud of it so hopefully it works.

**Comment by UKNC** [comment]
I solved that by 

`myPrintText = myPrintText.replace('function', '_function') `

before sending to `page.evaluate()` and performing 

`myPrintText = myPrintText.replace('_function', 'function') `

inside `page.evaluate()`

I think this condition should be mentioned in **documentation** of `page.evaluate()` as _function_ word inside string parameter to it is kinda control sequence and should be escaped.

Thanks for your solution.
