### ISSUE TITLE
Module not found: Error: Cannot resolve module 'child_process'

### ISSUE THREAD

**Issue by linwalker** [amir20/phantomjs-node#648]
I want to render a pdf by the code:
```
var phantom = require('phantom');   

phantom.create().then(function(ph) {
    ph.createPage().then(function(page) {
        page.open("http://www.google.com").then(function(status) {
            page.render('google.pdf').then(function() {
                console.log('Page Rendered');
                ph.exit();
            });
        });
    });
});
```
it went wrong ：
```
ERROR in ./~/._phantom@4.0.2@phantom/lib/phantom.js 
Module` not found: Error: Cannot resolve module 'child_process' in /workcode/octopus-oper-web/node_modules/._phantom@4.0.2@phantom/lib
     @ ./~/._phantom@4.0.2@phantom/lib/phantom.js 11:21-45
    
    ERROR in ./~/._phantomjs-prebuilt@2.1.14@phantomjs-prebuilt/lib/phantomjs.js
    Module not found: Error: Cannot resolve module 'child_process' in /workcode/octopus-oper-web/node_modules/._phantomjs-prebuilt@2.1.14@phantomjs-prebuilt/lib
     @ ./~/._phantomjs-prebuilt@2.1.14@phantomjs-prebuilt/lib/phantomjs.js 10:12-36
```

**Comment by amir20** [comment]
This looks to be a bad installation of `phantom`. `child_process` is a node module and either you have bad install or the version of node is so old that it is not compatible. You didn't list the version number so I don't know.

**Comment by linwalker** [comment]
@amir20 my node version is 6.10.0

**Comment by amir20** [comment]
Then I don't know what the problem is. Sounds like a bad install.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.

**Comment by esteban-quijada** [comment]
I have the same error. Do you think it has to do with phantomjs module that should only run on nodejs and not from the client side?

**Comment by amir20** [comment]
Can you give me a way to reproduce it? Maybe in a docker file? Otherwise, I don't think there is much I can do to debug.

**Comment by DevCubeHD** [comment]
@amir20 its as simple as taking a create-react-app and trying to use it inside any
