### ISSUE TITLE
phantom.addCookie or page.addCookie

### ISSUE THREAD

**Issue by stuk88** [amir20/phantomjs-node#650]
### Expected behavior

I'm trying to set the cookies of a page and there is no addCookie on phantom object.

### Actual behavior

```javascript

const phantom = require('phantom');

const base_cookies = [
    {name: 'cookie_1', value: '1'},
    {name: 'cookie_2', value: '2'},
    ];

function getUrlHtml(url) {
    return new Promise(function (resolve, reject) {
        var _ph = null;

        for(var i in base_cookies) {        
            phantom.addCookie(base_cookies[i]);
        }
        phantom.create().then(ph => {
            _ph = ph;

            return _ph.createPage();
        }).then(page => {
            page.setting('userAgent','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36');
            page.invokeAsyncMethod('open',url).then(function (status) {
                page.property('content').then(function (html) {
                    _ph.exit();
                    page.close()
                    resolve(html);
                })
            }).catch(reject)
        })
    })
}
```
That did not work.
Trying to run addCookie on the ph instance create resulted in the same error.

### Steps to reproduce the behavior

just run in node

### Environment

- OS: windows
- Node version (`node -v`): v7.3.0
- package version: 4.0.1

**Comment by amir20** [comment]
Add cookie is defined on the page object. https://github.com/amir20/phantomjs-node/search?utf8=%E2%9C%93&q=addcookie+&type=  Can you show me the code with page object?

**Comment by elias-winberg** [comment]
You are calling `addCookie` on the module, not the instance. You should do `_ph.addCookie(...)` not `phantom.addCookie(...)`.

**Comment by stuk88** [comment]
Worked for me:
```javascript
 for(var i in base_cookies) {        
                     page.invokeMethod('addCookie',base_cookies[i]);
                 }
```

**Comment by amir20** [comment]
`page. addCookie` should work as it is tested. Closing.
