### ISSUE TITLE
Not rendering full image when inside docker

### ISSUE THREAD

**Issue by ilijamt** [amir20/phantomjs-node#652]
### Expected behavior

Create a render of the full page, and the page should be fully loaded

### Actual behavior

Creates a partial image, image at the bottom of the page

#### Create a file **async.js**

```
const phantom = require('phantom');
(async function() {
    const instance = await phantom.create();
    const page = await instance.createPage();
    const url = process.argv[2];
    await page.property('viewportSize', {width: 1280, height: 1024});
    const status = await page.open(url);
    console.log(`Page opened with status [${status}].`);
    await page.render("/tmp/render.jpg");
    await instance.exit();
}());

// node --harmony-async-await render.js

```
#### Create a file **Dockerfile**

```
FROM debian:8
MAINTAINER Amir Raminfar <findamir@gmail.com>

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y nodejs build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev

RUN npm install phantom

ADD async.js /async.js

ENTRYPOINT ["node", "--harmony-async-await", "/async.js"]
CMD ["http://stackoverflow.com"]
```
#### Run the commands

```
docker build . -t phantomjs-test
docker run phantomjs-test "https://detail.tmall.hk/hk/item.htm?toSite=main&id=542813567399&id=542813567399&amp;skuId=3428181282407&amp;user_id=3040241921&amp;cat_id=52792006&amp;is_b=1&amp;rn=39c12f026e91ce71cc320346f435cfc7/"
```
### Environment

- OS: Debian
- Node version (`node -v`): v7.9.0
- package version: master
- Docker version 17.04.0-ce, build 4845c56

# Extra information

Rendering directly with phantomjs works

```
var page = require('webpage').create();
var url = "https://detail.tmall.hk/hk/item.htm?toSite=main&id=542813567399&id=542813567399&amp;skuId=3428181282407&amp;user_id=3040241921&amp;cat_id=52792006&amp;is_b=1&amp;rn=39c12f026e91ce71cc320346f435cfc7/";

page.open(url, function() {
  setTimeout(function() {
  	page.render('/tmp/phantom_render.jpg');
  	phantom.exit();
  }, 10000);
});
```

Attached picture of render

### Resources

![render](https://cloud.githubusercontent.com/assets/1139427/25363768/7d282d0e-295d-11e7-8c77-62a1760202ac.jpg)

![phantom_render](https://cloud.githubusercontent.com/assets/1139427/25364038/ba7e7c9c-295f-11e7-8383-6157bf6e3d48.jpg)

**Comment by amir20** [comment]
I don't have docker on my new laptop yet. But I don't think this is related to this module. If it works in one env and not another then it's most likely an env issue. I can't look right now. I'll leave this open in  case anybody else can find a solution.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.

**Comment by malinich** [comment]
I experience the same issue
