### ISSUE TITLE
PDF getting generated without any text

### ISSUE THREAD

**Issue by kushal813** [amir20/phantomjs-node#654]
Can anybody point me to a direction to rectify the issue where all PDFs are generated without any text.

I tried creating www.google.com page PDF and here's the result.

[https://drive.google.com/file/d/0Bwc4SyF6vi4IdVVxN0JHMkZtREE/view?usp=drivesdk](url)

- os Ubuntu
- Node version (`node -v`): 4.5.0
- package version: latest

**Comment by amir20** [comment]
Check to see phantomjs is [properly installed](http://phantomjs.org/build.html). 
You need to make sure all fonts are installed correctly.
