### ISSUE TITLE
How would you log the customHeaders?

### ISSUE THREAD

**Issue by julianguyen** [amir20/phantomjs-node#656]
### Expected behavior

I tried `console.log(this.page.customHeader)` where `this.page` is `this.browser.createPage()` returned. But it didn't work.

I tried to use the promise returned for `self.page.property('customHeaders', {})`, but it was undefined as well.

### Actual behavior

I just get undefined.

**Comment by amir20** [comment]
I am away for work so I can't paste an example. But if you search issues you should be able find an example. You need to use the property method. It's in the readme. 

Sent via my iPhone

**Comment by julianguyen** [comment]
I've looked in both areas, I haven't found anything that works @amir20 :/

**Comment by danilopartalj** [comment]
You can do like this:

phantom.create()
  .then(instance => {
    return instance.createPage();
  })
.then(page => {
    return page.property('customHeaders');
  })
  .then(result => {
    console.log(result);
  })

**Comment by julianguyen** [comment]
Omg awesome @danilopartalj! That worked thank you!
