### ISSUE TITLE
How to recieve data from page back to node via callback?

### ISSUE THREAD

**Issue by Lisennk** [amir20/phantomjs-node#657]

**Comment by amir20** [comment]
Why don't you write a description? Instead, I have to guess as to what you are saying. It doesn't help me help you. Please update the description and follow the guidelines to create new issues. 

Before creating new issues search first. I promise answers are easier to find than ask.  

If it is just using callback then [search](https://github.com/amir20/phantomjs-node/search?utf8=%E2%9C%93&q=callback&type=) for `callback` to find [this](https://github.com/amir20/phantomjs-node/blob/856256b8f6f3d9b100b954339b5bb14f822f0733/src/__test__/page.evaluate.spec.js#L59).
