### ISSUE TITLE
renderBase64 returns empty string for pdf

### ISSUE THREAD

**Issue by manuschiller** [amir20/phantomjs-node#659]
### Expected behavior

it should return a base64 representation of the pdf content.

### Actual behavior
an empty string with length 0.

### Steps to reproduce the behavior

```
const phantom = require('phantom');

(async function() {
    const instance = await phantom.create();
    const page = await instance.createPage();

    await page.property('viewportSize', {width: 1024, height: 600});
    await page.property('content', '<html><head><title>Test</title></head><body><p>Test</p></body></html>');
    const b64 = await page.renderBase64('pdf');
    console.log('base64', b64);
    console.log(typeof b64);
    console.log(b64.length);
    
    await instance.exit();
}());
```

### Environment

- OS: MAC OSX Sierra
- Node version (`node -v`):  v 7.8.0
- package version: 4.0.3

**Comment by amir20** [comment]
I was able to reproduce this. Not sure what's going on but I'll take a look later.

**Comment by amir20** [comment]
I think I found your problem @manuschiller. I tried `PNG` and it worked. Then I [read](http://phantomjs.org/api/webpage/method/render-base64.html) the documentation and realized PDF is not a supported type.

**Comment by manuschiller** [comment]
@amir20
That is actually not correct:
https://github.com/ariya/phantomjs/blob/master/src/webpage.cpp#L1084

It does render PDFs to base64. It will only return an empty string, if the rendering fails

**Comment by amir20** [comment]
Then I am not sure how I can help :( I would suggest trying with PhantomJS and see if that works. If that works but it doesn't work in this node module then it's a bug. I don't add any new functionality and proxy everything to phantomjs process.

**Comment by wangmerry** [comment]
Hi.  I tried PNG , but it did not work.  JPEG worked
