### ISSUE TITLE
clearMemoryCache not available on page object

### ISSUE THREAD

**Issue by 88media** [amir20/phantomjs-node#662]
page.clearMemoryCache() should be available so the cached resources could be emptied. Please add 'clearMemoryCache' to the page methods.

**Comment by amir20** [comment]
Read https://github.com/amir20/phantomjs-node/search?q=clearMemoryCache&type=Issues&utf8=%E2%9C%93

**Comment by amir20** [comment]
PR would be appreciated!

**Comment by clintmod** [comment]
Why was this closed?
