### ISSUE TITLE
How to render a large number of page in a resource effective way ?

### ISSUE THREAD

**Issue by George3d6** [amir20/phantomjs-node#669]
If I wanted to use this package for viewing a lot of pages (e.g. open 1000 pages/sec) in an efficient way, how should I go about it ? I assume there is some way to re-use a  phantom instance or even a page, right ?

**Comment by amir20** [comment]
The best way that I can think of is using a resource pool. There is a project linked in readme file https://github.com/amir20/phantomjs-node#pooling that you might want to check out. Obviously, 1000p/s requires memory and resources to it. Hope this helps.

**Comment by George3d6** [comment]
Sorry, for some reason that part of the doc completely escaped me, I will close this now :.
Yes, I do have the resources (most likely) to do this, so that shouldn't be a problem.
