### ISSUE TITLE
Error on debian

### ISSUE THREAD

**Issue by singlewind** [amir20/phantomjs-node#670]
First of all, thank you for making the module for us easily interact with PhantomJs

### Expected behavior

I wrote the code on windows which works perfectly. However, when I try to dockerize the application I got following error. I don't think the error belongs your code. It looks like node fail to spawn the child process. I found node community discuss about the permission which I don't think related either. Did you run any issue like this before?

```
 Call to Node module failed with error: Error: spawn EINVAL
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at new Phantom (/app/node_modules/phantom/lib/phantom.js:109:49)
    at resolve (/app/node_modules/phantom/lib/index.js:23:41)
    at Object.create (/app/node_modules/phantom/lib/index.js:23:10)
```

- OS: debian-jessie
- Node version (`node -v`):6.11.0
- package version: 4.0.4

**Comment by amir20** [comment]
Did you check out this Dockerfile https://github.com/amir20/phantomjs-node/blob/master/examples/Dockerfile? 

Sounds like phantom isn't insalled.

**Comment by singlewind** [comment]
I will try. Thanks. This may related network. PhantomJS need access url which serves by the same container. The port binding on the external ip may not bind to the local IP.
