### ISSUE TITLE
Call page#invokeMethod  with arguments

### ISSUE THREAD

**Issue by mickeyjohn** [amir20/phantomjs-node#673]
Hi,
I  am tried calling page#invokeMethod with an argument then getting error:
"(node:14671) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: undefined is not an object (evalu
ating 'method.apply')"

According to the readme doc:
page#invokeMethod
A method can be invoked using the #invokeMethod(method, arg1, arg2, arg3...) method.

My code:
```
sitePage.invokeMethod('injectJS', './sample-geojson.js')..then(function (status) {
    console.log('Inject status: ', status);
});
sitePage.open('myPage.html').then(callback);
```

What I am trying to do is to call phantom page's injectJS() method to set data for a local html file before doing a screen capture.

Please anyone with any idea? Thanks.

**Comment by mickeyjohn** [comment]
Just type error. It must be 'injectJs' instead of 'injectJS'. No issue

**Comment by amir20** [comment]
Why do you use `invovkeMethod` and not `page#injectJs` at https://github.com/amir20/phantomjs-node/blob/ce1d1107218bacc154a8c6d36999baced4a61ae4/src/page.js#L107

**Comment by mickeyjohn** [comment]
@amir20: Awesome. Thanks for pointing out that.
