### ISSUE TITLE
Chaining render to onLoadFinished

### ISSUE THREAD

**Issue by harsh-a1** [amir20/phantomjs-node#675]
QUESTION

### Expected behavior

I am trying to get a pdf of a report from a website which needs login. So I am first logging in to the website which then redirects to the page I want access to. I need to hook the onLoadFinished function to the     page.render function. Here is the code I am using:

    page.open(BASE_URL + Report_URL).then(function(status) {
            console.log(status);
            try{
                page.evaluate(function(){      
                    setTimeout(function(){
                    document.getElementById("username").value = "admin";
                    document.getElementById("password").value = "admin";
                    document.getElementById("submit").click();
                    },100)                  
                })
                         
            page.property('onLoadFinished', function(status,page) {
                console.log('==== onLoadFinished()');
                try{
                    console.log('  status: ' + status );
                    page.render("report.pdf")
                }catch(ex){
                    var fullMessage = "\nJAVASCRIPT EXCEPTION";           
                    console.log(fullMessage);
                }
            },page);
            }catch(ex){
                var fullMessage = "\nJAVASCRIPT EXCEPTION";
            
                console.log(fullMessage);
            }
            
        });
### Actual behavior

Nothing happens, even exception does not come. 
How can this be achieved? I want to chain the onloadFinished function to another function which can render the page as pdf...pls help!!

### Environment

- OS: Ubuntu 14
- Node version (`node -v`): v6.2.2
- package version: npm - 3.9.5

**Comment by amir20** [comment]
Did you try using `page.on(...)` instead of `property`? I really should just remove `property` as it confuses people.

**Comment by harsh-a1** [comment]
Thanks for replying Amir, I solved it by using **this.render** instead of **page.render.** Updated code :-

    page.open(BASE_URL + Report_URL).then(function(status) {
        console.log(status);
        try{
            page.evaluate(function(){      
                setTimeout(function(){
                document.getElementById("username").value = "admin";
                document.getElementById("password").value = "admin";
                document.getElementById("submit").click();
                },100)                  
            })
                     
        page.property('onLoadFinished', function(status,page) {
            console.log('==== onLoadFinished()');
            try{
                console.log('  status: ' + status );
                this.render("report.pdf")
            }catch(ex){
                var fullMessage = "\nJAVASCRIPT EXCEPTION";           
                console.log(fullMessage);
            }
        },page);
        }catch(ex){
            var fullMessage = "\nJAVASCRIPT EXCEPTION";
        
            console.log(fullMessage);
        }
        
    });
