### ISSUE TITLE
How to save cookies between pages.

### ISSUE THREAD

**Issue by MKiselev** [amir20/phantomjs-node#676]
### Expected behavior
When a go to next page session and cookie will be saved.

### Actual behavior
Cookie and session not saved.

### Steps to reproduce the behavior
```js
const phantom = require('phantom');
const config = require('./config');

let phantomInstance, page;

(async function () {

    phantomInstance = await phantom.create();
    page = await phantomInstance.createPage();
    await page.setting('userAgent', config.userAgent);
    await page.property('viewportSize', {width: 800, height: 600});


    await page.open('some_url');

    // Do some action, login on site
    
    await page.open('next_url'); // <- here I expected logged in state on site, but session not saved ((

    await phantomInstance.exit();
}());

```

### Environment

- OS: Ubuntu 16.10 
- Node version: v8.1.3
- package version: 4.0.4

When use phantomjs we can set cli param https://stackoverflow.com/questions/30957723/phantomjs-isnt-saving-cookies but how do it when I use module?

**Comment by amir20** [comment]
I did some research and I don't think phantomjs supports sessions out of the box. You have to provide a cookie file as suggested [here](https://stackoverflow.com/questions/14824798/phantomjs-and-sessions).  Which you can do with this module using `phantom.create(['--cookies-file=/path/to/cookies.txt']);`

I haven't personally used this feature myself so you might need to make sure it works in phantomjs before trying to use this module.

**Comment by MKiselev** [comment]
@amir20
Thank you very much for your help.

But real reason because I lost session between pages was be phantomjs protection.

Excuse for troubling.
