### ISSUE TITLE
Page constructor problem

### ISSUE THREAD

**Issue by Auxolust** [amir20/phantomjs-node#679]
### Expected behavior

Creating a page object

### Actual behavior

Getting : TypeError: _page2.default is not a constructor

### Steps to reproduce the behavior

1. Try use a createPage

Seems like the offending problem is this
```js
var _page2 = _interopRequireDefault(_page);
```
causing an exported object which is like this from _page
```js

var exports =
{
default: //...
}
```

to be wrapped again causing a nested default default object

### Environment

- OS: Windows 8.1 x64
- Node version (`node -v`): v8.1.0
- package version:  v4.0.4

**Comment by amir20** [comment]
There has be to something going on with your installation. All the tests pass. I tested this morning and it all works. And travis runs with node 6, 7, and 8. So something is else is up. Can you share the smallest code that reproduces this?

**Comment by Auxolust** [comment]
```js
phantom.create([]).
	.then(function(phantasm )
		{
                    //Fails here
		    return phantasm.createPage();
		}).then(function(page)
               {
                      //...
              });
```

**Comment by amir20** [comment]
I did that exactly and it works...

```js
const phantom = require('phantom');


phantom.create().then(function (phantasm) {
    return phantasm.createPage();
}).then(function (page) {
    console.log(page)
});
```

I don't know how to reproduce it.
