### ISSUE TITLE
flexbox not supported

### ISSUE THREAD

**Issue by jjeejj** [amir20/phantomjs-node#680]
### Expected behavior

[Describe expected behavior here]

### Actual behavior
[Describe observed behavior here]
this module not supported flexbox,but the native phantonjs (2.1.1) is supported.

Can I configure it ?

Or not updated ？ 
### Steps to reproduce the behavior

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Environment

- OS: window 10 x64
- Node version (`node -v`): node version 7.10.0
- package version: 4.0.4

**Comment by amir20** [comment]
I don't know if flexbox is supported. Currently, phantom `v2.1.x` is being used so if you say it is supported then it is. This is a wrapper around phantomjs so please follow through with the documentation.
