### ISSUE TITLE
No screenshot or blank screenshot rendered for certain sites

### ISSUE THREAD

**Issue by abhishekdubey1** [amir20/phantomjs-node#682]
For certain sites no screenshot is rendered or blank screenshot is rendered even after a wait. See code below:

sample url: hxxp://cigessa.com/ser/impot.gouv/clientID/d13de6e670938c25adcc4f3ba402acff 

FYI: it is a phishing site.

You can test it with
`node screenshot.js http://cigessa.com/ser/impot.gouv/clientID/d13de6e670938c25adcc4f3ba402acff test1.png`

```
const phantom = require('phantom');
const sleep = require('sleep');

let args = process.argv.slice(2);

(async function () {
  const instance = await phantom.create();
  const page = await instance.createPage();

  const status = await page.open(
   args[0]
  );

  console.log('page loaded successfully: ', args[0]);
  sleep.msleep(3000);
  await page.evaluate(function () {
    var style = document.createElement('style'),
      text = document.createTextNode('body { background-color: #fff }');
    style.setAttribute('type', 'text/css');
    style.appendChild(text);
    document.head.appendChild(style);
  });

  await page.render(args[1],
    {quality: 100});

  console.log('done');
  await instance.exit();
})();

```

**Comment by amir20** [comment]
This would be an issue with phantomjs and not related to this module. If you can't reproduce it with plain phantomjs then you can create an issue.

**Comment by tanujaSigmoid** [comment]
I am trying blow code for creating screenshot using phantomJS 2.1.1 but getting blank screenshot.
Please help me to identify the issue. It is really helpful.
Thanks in advance

![sigview](https://user-images.githubusercontent.com/53603824/62359189-ec10e300-b533-11e9-9690-8ba317bcdc1e.png)

var page = require('webpage').create();
page.open('https://sigview.sigmoid.io/app/#/signIn', function() {
  setTimeout(function() {
     page.render('sigview.png');
     phantom.exit();
  }, 1000);
});
