### ISSUE TITLE
How can I became a contributor?

### ISSUE THREAD

**Issue by thEpisode** [amir20/phantomjs-node#687]
Hey team, I'm using your library and specifically needs to use tome functions not listed on documentation and I want to contribute with documentation and more functionality.  This is my first time contributing in Open Source project and I want to know how can I became a contributor?

Ps: I love this project.

**Comment by amir20** [comment]
Hi @thEpisode. Thanks for the support! ❤️ I am the maintainer of the project and we have about a dozen contributors. You don't need to do anything to contribute :) You just need to send a pull request, then I will review and provide feedback. After that, I can merge and deploy a new version. Right now all of the code is in ES6 with flow style type checking. I think that actually makes it confusing so the number of PRs have declined. The code to add new methods is located [here](https://github.com/amir20/phantomjs-node/blob/master/src/page.js#L100). Really easy to add. I recommended to add tests and of course update documentation. Make sure that `npm test` works locally before creating the pull request. 

That's about it! Let me know if you need help. I am traveling for another week but will try to respond.

**Comment by thEpisode** [comment]
Thank you so much 😄
