### ISSUE TITLE
networkRequest incorrect

### ISSUE THREAD

**Issue by red010182** [amir20/phantomjs-node#691]
```
await page.on("onResourceRequested",  (requestData, networkRequest) => {
  console.log(networkRequest);
});
```

the result always to be
```
networkRequest { objectName: '' }
```

which is quite different from original [doc](http://phantomjs.org/api/webpage/handler/on-resource-requested.html)

**Comment by amir20** [comment]
This is clearly documented https://github.com/amir20/phantomjs-node#pageon and why it doesn't work. Closing. Next time please read the docs and follow the template for creating issues.
