### ISSUE TITLE
Install on FreeBSD/x64 failing

### ISSUE THREAD

**Issue by backstube** [amir20/phantomjs-node#694]
Hi,
I'd like to install phantomJS on FreeBSD in order to get HackMD up & running. This seems to be harder than expected. 

This is what I did:

`#> npm i phantom --save`

will not install phantomJS 4.0.5 (latest), instead it falls back to `phantomjs-prebuilt@2.1.15` which apparently happens to be the wrong arch:

<pre>
PhantomJS not found on PATH
Unexpected platform or architecture: freebsd/x64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-17T17_03_22_182Z-debug.log
</pre>

Wrong arch AND wrong version. 

So I went ahead and tried to build it myself; FreeBSD comes with a fine source code repo called Ports. PhantomJS is there, right where one would expect it to be. My compile-run started off by pulling `ariya-phantomjs-2.1.1_GH0.tar.gz`, an even older version than the binary package before.<br />
I let it run to see what happens. It didn't go well, spit errors after a while which aren't meaningful b/c it's the wrong version by a lot.

That let me to a `git clone` to build it from this repo here @v4.0.5. Next obstacle: how would one build it from scratch?  No makefile, no other (known) structure to build a binary. Full stop.

So, my question is: How do I build or install phantomJS successfully on FreeBSD (11.0)?  Thanks for any hint.

Cheers!

=====

### Expected behavior

PhantomJS would install w/o errors on Step 3 (s. below).

### Actual behavior

It doesn't install (s. above).

### Steps to reproduce the behavior

1. Install node & npm, which went fine on FreeBSD 11.0-p12
2. install a bunch of modules, which also went fine
3. install phantomjs, which didn't work in any way or shape or form

### Environment

- OS: FreeBSD 11.0 
- Node version (`node -v`): v8.1.4
- npm version: 5.3.0
- package version: source version 4.0.5

**Comment by amir20** [comment]
Looks like this a problem with `phantomjs-prebuilt`. I did some googling which led me to https://stackoverflow.com/questions/35228267/freebsd-phantomjs-installation-issue and https://github.com/ariya/phantomjs/issues/12963 which points to resolution. I think your best bet is to figure out how to get phantomjs working on freebsd first.
