### ISSUE TITLE
phantom.exit is not a function

### ISSUE THREAD

**Issue by tridungle** [amir20/phantomjs-node#697]
I'm having trouble getting this to run on docker.  I was test on local and It work well
### Expected behavior
phantom.exit is not a function
### Steps to reproduce the behavior
Run on docker, ec2 instance
### Environment

- OS: Debian
- Node version (`node -v`): 6
- package version: 4.0.5

**Comment by amir20** [comment]
Can you provide code example? I am closing for now until example code is provided.
