### ISSUE TITLE
Node 8 Alpine Phantom

### ISSUE THREAD

**Issue by talyuk** [amir20/phantomjs-node#702]
I have Node 8 Alpine image at Docker, I installed Alpine specific package (from [this issue](https://github.com/amir20/phantomjs-node/issues/619)), but when I tried to run simple.js from examples, createPage() didn't work. Phantom instance was created, but then creating page didn't anything. No exception, no executing. What can be wrong? 

I added comments to simple.js: 
```javascript
phantom
  .create()
  .then(ph => {
    console.log('PHANTOM');
    _ph = ph;
    return _ph.createPage();
  })
  .then(page => {
    console.log('PAGE');
    _page = page;
    return _page.open('https://stackoverflow.com/');
  })
  .then(status => {
    console.log(status);
    return _page.property('content');
  })
  .then(content => {
    console.log(content);
    _page.close();
    _ph.exit();
  })
  .catch(e => console.log(e));
```
And I see only 'PHANTOM'.

- OS: Alpine Node 8
- Node version (`node -v`): 8.6.0
- package version: 4.0.5

**Comment by amir20** [comment]
It sounds like you don't have phantomjs installed correctly. What does your dockerfile look like? I have a dockerfile in the [example folder](https://github.com/amir20/phantomjs-node/blob/master/examples/Dockerfile) that doesn't use alpine. So you have to make sure you install 
```nodejs build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev
```

**Comment by amir20** [comment]
Also try running `docker run -it <image> sh` and then run `phantomjs`. If that fails then you should fix it first.

**Comment by talyuk** [comment]
I had node:alpine image, but I didn't have enough time to resolve this issue, so I installed node:8 image without Alpine specific phantomjs package, and got working phantom
