### ISSUE TITLE
Intermediate value is not a function?

### ISSUE THREAD

**Issue by knoxcard** [amir20/phantomjs-node#705]
Here is the source code I am running on Windows...

```
(async function() {
  const instance = await phantom.create();
  const page = await instance.createPage();
  await page.on('onResourceRequested', function(requestData) {
    console.info('Requesting', requestData.url);
  });

  const status = await page.open('https://stackoverflow.com/');
  const content = await page.property('content');
  console.log(content);

  await instance.exit();
})();
```

### Expected behavior

Just want the output to display source code

### Actual behavior

(async function() {
^
TypeError: {(intermediate value)(intermediate value)(intermediate value)(intermediate value)} is not a function
    at Object.<anonymous> (C:\indospace.io\proxybot\proxybot.js:54:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

### Environment

- OS: Windows 10
- Node version (`node -v`): 8.7.0
- package version:

**Comment by amir20** [comment]
I think this is something you are doing as it is complaining about `async` not being a valid keyword. Check your node or try running another `async` example first.

**Comment by knoxcard** [comment]
Yup! I ended up taking the code and putting it an individual file and it works.  Probably some semicolon or weird character encoding.
