### ISSUE TITLE
Occasionally, the access request timeout program has been pending pending

### ISSUE THREAD

**Issue by zouwei** [amir20/phantomjs-node#706]
### Expected behavior
Timeout pending
[Describe expected behavior here]
Waiting all the time
### Actual behavior

[Describe observed behavior here]

### Steps to reproduce the behavior

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Environment

- OS:Windows
- Node version (`node -v`):v8.6.0
- package version: The latest version

**Comment by amir20** [comment]
I have no idea what you are asking.
