### ISSUE TITLE
Deprecate page.property(event, function) in favor of page.on(event, function)

### ISSUE THREAD

**Issue by amir20** [amir20/phantomjs-node#709]
Just a place holder for myself to deprecate `page.property`.

**Comment by amir20** [comment]
This is now deprecated on `v4.0.0.7`

**Comment by epdev** [comment]
@amir20 What should I use instead of `page.property('content')`?

**Comment by amir20** [comment]
`page.property('content')` is still fine. It's just for events'

**Comment by epdev** [comment]
Btw I'm confused because I have v4.0.7 installed through the npm and on the page.js file in the method "property" I have line `console.log(args.length == 2 && typeof args[1] === 'function');`. This logs `true` or `false` everytime I use method "property". On GitHub this line doesn't exist.

**Comment by amir20** [comment]
Oh wow. Nice find @epdev. I don't know what happened. I didn't have that either locally. But because travis deploy is broken right now, something must have happened when i tried to `npm publish` locally. 

I fixed this in `4.0.8`. Can you check?

**Comment by epdev** [comment]
4.0.8 works well. Thanks.
