### ISSUE TITLE
Page.open() cannot open a win os path

### ISSUE THREAD

**Issue by popo1221** [amir20/phantomjs-node#712]
### Expected behavior
The method page.open() should open a win os path like:
`
Z:\Codes\phantom-highcharts-win\node_modules\@en\highcharts-render-job\exporter.html
`
### Actual behavior
An error happens when openning a win os pah:
(node:6520) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot open exporter.html
(node:6520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
### Steps to reproduce the behavior
Reproduce the problem by the codes:
```js
const instance = await phantom.create();
const page = await instance.createPage()
const status = await page.open(require.resolve('./exporter.html'))
```

### Environment

- OS: Windows 10
- Node version (`node -v`): 8.9.1
- package version: 3.2.1

**Comment by popo1221** [comment]
It also cannot open a path like:
Z:/Codes/phantom-highcharts-win/node_modules/@en/highcharts-render-job/exporter.html

But it is ok if I pass a path like: 
node_modules/@en/highcharts-render-job/exporter.html
(the relative path)

**Comment by amir20** [comment]
I don’t think phantomjs supports file paths.

**Comment by amir20** [comment]
According to this you should prepend `file://` 

https://stackoverflow.com/questions/19939046/phantomjs-fails-to-open-local-file
