### ISSUE TITLE
Running in lambda breaks finding '/shim/index.js'. It would be nice to be able to pass path to shim.

### ISSUE THREAD

**Issue by zachschultz** [amir20/phantomjs-node#713]
### Expected behavior

When running `phantom.create([],{phantomPath:<MYPATH>})...` in a lamda function I expect to have a running instance of phantom.

I would like to pass the path to the `/shim/index.js` file through the `.create()` config.

### Actual behavior

When trying to run `.create(...)` in a AWS Lambda context, I get the error `error: Can't open '/shim/index.js'`.

### Steps to reproduce the behavior

1. Create a lambda function, import `phantom`, and try to run `phantom.create(...)`
2. [Second Step]
3. [Other Steps...]

### Environment

- OS: Mac OS
- Node version (`node -v`): 8.6.0
- package version: 4.0.11

**Comment by amir20** [comment]
Hey  @zachschultz I haven't used lambda + phantom yet. So I am not sure what do here to test. It sounds like you want a way to pass the path to the shim. 

If you want, you can provide a pull request and change this [line](https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L74) to make it configurable. Pull requests are welcomed. :) 

Hope this helps.

**Comment by amir20** [comment]
No response so I am going to close and we can reopen if necessary.

**Comment by zachschultz** [comment]
@amir20 sorry about my lack of response, I'll gladly submit a PR when I get the chance!
