### ISSUE TITLE
How to use --cookie-file in order to spoof cookies being loaded

### ISSUE THREAD

**Issue by SivanMehta** [amir20/phantomjs-node#714]
### Expected behavior

I am attempting to read a given `.txt` file as a cookie file and print out the contents as they are present in the phantom browser. The basis for this code was the seemingly unresolved issue resolution [here](https://github.com/amir20/phantomjs-node/issues/676#issuecomment-312734568). Here is the relevant snippet of code:

```js
    const phantom = require('phantom');

    const instance = await phantom.create(['--cookies-file=' + path.join(tempDir, 'oc-cookie.txt')])
    const page = await instance.createPage();
    const cookies = await page.evaluate(function() {
      return document.cookie;
    })
    console.log("#### cookies START ####");
    console.log(await cookies);
    console.log("#### cookies END ####");
```

For reference, `index.html` is the following:

```html
<html>
</html>
```

And `cookies.txt` is just

```
a=123
```

All of these files are in the same directory, so file paths *_shouldn't_* be an issue. I *_expect_* that running this will simply print out the contents of `cookies.txt`:

```
#### cookie START ####
a=123
#### cookie END ####
```

### Actual behavior

However, I actually get the following output

```
#### cookie START ####
null
#### cookie END ####
```

### Environment

- OS: Mac OSX 10.12.6 (Sierra)
- Node version (`node -v`): `v8.9.1`
- package version: `4.0.2`

**Comment by SivanMehta** [comment]
I was just using the module wrong.

**Comment by amir20** [comment]
Also your version is a couple minor versions behind.
