### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by pociej** [amir20/phantomjs-node#719]
Once tryign to use, just when i call 

``` const phantom = require('phantom');``` 

i get 
![screen shot 2017-12-27 at 14 37 39](https://user-images.githubusercontent.com/3854675/34383164-a8516f0e-eb13-11e7-8d4a-159f00142c5e.png)

- OS: macOs high sierra 10.13.2
- Node version : 8.0.0 
- package version: 4.0.12

**Comment by amir20** [comment]
Try using node 9. I think you need at least 8.9.x for the latest version.

**Comment by amir20** [comment]
I actually tried this with node version `8.0.0` and t worked. So something is up with your env. 

<img width="871" alt="screen shot 2017-12-29 at 9 07 35 am" src="https://user-images.githubusercontent.com/260667/34442553-b8dec0fa-ec77-11e7-99d4-6d4ddd122421.png">
