### ISSUE TITLE
There are some serrations when  turn PDF.

### ISSUE THREAD

**Issue by chenfeifei-e** [amir20/phantomjs-node#724]
### Expected behavior

[Describe expected behavior here]

### Actual behavior

[Describe observed behavior here]
I want to convert an HTML file to PDF, but this HTML has SVG, and PNG, which causes the PDF to be turned out to be serrate. Is there any way to solve this problem?
### Steps to reproduce the behavior
[922.pdf](https://github.com/amir20/phantomjs-node/files/1621177/922.pdf)

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Environment
node 8.1.0
- OS:
- Node version (`node -v`):
- package version: 
4.0.5

**Comment by amir20** [comment]
This is a phantomjs issue so I would suggest looking there instead.
