### ISSUE TITLE
HTML to PDF has a lot of jaggies.

### ISSUE THREAD

**Issue by chenfeifei-e** [amir20/phantomjs-node#725]
### Expected behavior

[Describe expected behavior here]

### Actual behavior

[Describe observed behavior here]
There are some SVG and PNG files in HTML files, and these SVG should be PNG when you go to PDF, so there are a lot of jagged edges, is there any way to solve this problem?
### Steps to reproduce the behavior

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Environment
node -v8.1
- OS:
- Node version (`node -v`):
- package version: 
4
[928.pdf](https://github.com/amir20/phantomjs-node/files/1631346/928.pdf)
[test3.pdf](https://github.com/amir20/phantomjs-node/files/1631360/test3.pdf)

.0.5

**Comment by amir20** [comment]
I don't think I can help you here. This is a phantomjs issue. I don't know the inner working of phantomjs that well to know why it would be causing this.
