### ISSUE TITLE
npm install phantom on raspberry pi fails - no binary available for your platform/architecture

### ISSUE THREAD

**Issue by nospam2k** [amir20/phantomjs-node#728]
### Expected behavior

Install no problem

### Actual behavior

PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally

### Steps to reproduce the behavior

1. npm install phantom

### Environment

- OS: Linux raspberrypi 4.9.76-v7+ #1076 SMP Wed Jan 10 17:34:49 GMT 2018 armv7l GNU/Linux
- Node version (`node -v`): v8.9.4
- package version: phantomjs-prebuilt@2.1.16

**Comment by nospam2k** [comment]
I think I've resolved it. Needed to follow directions here:

https://www.bitpi.co/2015/02/10/installing-phantomjs-on-the-raspberry-pi/

**Comment by amir20** [comment]
I think this is meant for phantomjs-prebuilt. That's a different project. So I am closing.
