### ISSUE TITLE
Render pdf as blank page without error

### ISSUE THREAD

**Issue by mickeyjohn** [amir20/phantomjs-node#729]
### Expected behavior
page.render would create a capture of the page and save as an pdf file.

### Actual behavior
It can only render successfully once. Subsequent renders end up with blank pdf file without any error.

### Steps to reproduce the behavior
My codes:

```
var log = console.log;
var nolog = function () { };

var sitepage = null;
var phInstance = null;

phantom.create(['--ssl-protocol=any'], {
    phantomPath: '/home/user/.npm-global/bin/phantomjs',
    logger: { warn: log, debug: log, error: log }
})
    .then(instance => {
        phInstance = instance;
        return instance.createPage();
    })
    .then(page => {
        sitepage = page;
        return sitepage.on('viewportSize', { width: 800, height: 600 });
    })
    .then(() => {
        return sitepage.open('https://www.google.ca');
    })
    .then(() => {
        return sitepage.render(__dirname + '/test.pdf', { format: 'pdf' })
            .then(() => {
                console.log('DONE');                
            });
    })
    .catch(error => {
        console.timeEnd('test');
        console.log('Center Error: ', error);
    })
    .then(() => {
        phInstance.exit();
        // process.exit();
    });;

```
It is driving me crazy now. Could anyone please help showing me why or the best way to troubleshot the issue? I have another testing site still running well using phantomjs and phantom-node the same way to render.

### Environment

- OS: Ubuntu destop 14.04
- Node version (`node -v`): v8.9.4
- package version: 4.0.12

**Comment by amir20** [comment]
What do you mean subsequent calls? Do you mean when you call the same script again it’s blank? 



Sent via my iPhone

**Comment by mickeyjohn** [comment]
yes, that's right. I can only have a random rarely render success. What do you recomend me to check?

**Comment by mickeyjohn** [comment]
```
    .then(() => {
        return sitepage.open('https://www.google.ca');
    })
    .then((status) => {
        console.log("Status:", status);
        return sitepage.render(__dirname + '/test.pdf', { format: 'pdf' })
            .then(() => {
                console.log('DONE');                
            });
    })
```
I have the status log as: "Status: fail " now.

**Comment by amir20** [comment]
I am on my iPhone so it’s harder to debug. Usually I say this is a phantomjs issue but the fact that it works sometimes makes me doubt that. It sounds like it’s a race issue. 

Page.open returns a status. Can you print that out? 

Once I get home I can try to run your example as well.

**Comment by amir20** [comment]
Oh wait I just saw your comment. So status failing means something is wrong with the call. Are you behind a vpn?

**Comment by mickeyjohn** [comment]
I am not under a VPN network. I tried the url in chrome, it works normally. Now, I try a local page in my node app, it output status as true but still a blank page. This issue happened once before and now it is com back again.

**Comment by amir20** [comment]
Random idea, delete node modules directory and do reinstall. I also noticed you are passing your own path to phantom. Can you try with the version that’s shipped in node modules?

Sent via my iPhone

**Comment by mickeyjohn** [comment]
I did remove node_modules folder then npm install again. It's still blank. I also re-installed phantomjs-prebuilt. Can you show me the steps to install needed packaged?

The custom path (/home/user/.npm-global/bin/phantomjs -v) pointing to a symlink file. I can run a command to show its version as 2.1.1.

**Comment by amir20** [comment]
I think I found your problem. I don't think you were using promises correctly. You create a pdf but then immediately kill the process. That's why it's blank. 

Try changing to

```js
phantom.create(['--ssl-protocol=any'], {    
    logger: { warn: log, debug: log, error: log }
})
    .then(instance => {
        phInstance = instance;
        return instance.createPage();
    })
    .then(page => {
        sitepage = page;
        return sitepage.on('viewportSize', { width: 800, height: 600 });
    })
    .then(() => {
        return sitepage.open('https://www.google.ca');
    })
    .then((status) => {
        console.log("Status:", status);
        return sitepage.render(__dirname + '/test.pdf', { format: 'pdf' })
    })
    .catch(error => {
        console.timeEnd('test');
        console.log('Center Error: ', error);
    })
    .then(() => {
        console.log('DONE');
        phInstance.exit();
        // process.exit();
    });;
```

Why aren't you using async and await? This would not have happened.

**Comment by amir20** [comment]
This is the file I get by the way. 
[test.pdf](https://github.com/amir20/phantomjs-node/files/1712792/test.pdf)

**Comment by mickeyjohn** [comment]
Thanks a lot for your help. It is still blank. I have tried like you test before. May be It's about something else. Can you share me on how you setup phantomjs?
I tried async and await and still blank:

```
(async function() {
  const instance = await phantom.create();
  const page = await instance.createPage();
  await page.on('onResourceRequested', function(requestData) {
    console.info('Requesting', requestData.url);
  });

  const status = await page.open('https://stackoverflow.com/');
  await page.render(__dirname + '/test.pdf', { format: 'pdf' });

  await instance.exit();
})()
```;

**Comment by amir20** [comment]
I didn't setup phantomjs. It's already included as a dependency. See https://github.com/amir20/phantomjs-node/blob/master/package.json#L28.

**Comment by amir20** [comment]
I have reponed until we figure out what's going on.

**Comment by mickeyjohn** [comment]
You are right. Only need to npm install phantomjs-prebuilt within the project then It works like a charm. I highly appreciate your help. Thanks a lot and have a great weekend.

**Comment by mickeyjohn** [comment]
Hi amir20,
The resolution above worked at home in my laptop. Today, I went back to my dev PC, I removed the global installation of phantomjs-prebuilt, install it locally for each project. Now, the online project is working but the dev one still has blank problem. Does it work for multiple projects ?

Best Regards,
John.
