### ISSUE TITLE
getElementsByTagName() and getElementsByClassName() returns an array with null values

### ISSUE THREAD

**Issue by MakroBox** [amir20/phantomjs-node#730]
### Expected behavior
The 'elements' array should contain all the `<p>` tags.

### Actual behavior
**The first object in array 'elements' is OK, and the others' value are `null`.** 
(But! The length of the array is equal with the number of `<p>` tags on my site!)
The problem occurs with `getElementsByTagName()`, and `getElementsByClassName()` too. (and maybe other functions)

### Code
```node
const phantom = require('phantom');

(async function() {
  console.log('Creating Phantom instance...');
  const instance = await phantom.create();
  const page = await instance.createPage();

  const status = await page.open('https://www.makrovps.tk');
  if (!status)
    return console.log('Cannot open www.makrovps.tk');
  const pageContent = await page.property('content');

  const elements = await page.evaluate(function() {
    const elementsByTag = document.getElementsByTagName('p');
    return elementsByTag;
  });
  console.dir(elements);

  await instance.exit();
})();
```
### Console result
It's too long because of the first element, so I uploaded it:
[Pastebin](https://pastebin.com/3tMRiExy)

### Environment
- OS: Windows 10
- Node version: v9.5.0
- package version: 4.0.12

**Comment by amir20** [comment]
I don't see anything wrong in your code. Have you tried this with Vanilla PhantomJS code without node? This could be a bug with Phantomjs.

**Comment by amir20** [comment]
Actually, I have an idea. I think `getElementsByTagName` might return a special object which is not serializable. I suggest you don't return DOM objects and instead return what you want to node. Like if you want all the classes then loop over each `p` and return `p.clashName`.

**Comment by MakroBox** [comment]
```node
const myElement = await page.evaluate(function() {
  const elementsByTag = document.getElementsByTagName('p');
  for (i = 0; i < elementsByTag.length; i++)
    if (elementsByTag[i].innerHTML == 'MakroBox')
      return elementsByTag[i];
});
console.dir(myElement);
```
This works like a charm.
I can return one element, but I cannot return the whole result of `getElementsByTagName()`.
**I think that could be a bug with PhantomJS.** (but I haven't tried it with vanilla PhantomJS yet)

Thanks for help,
_Makro_

**Comment by amir20** [comment]
I think it's because `document.getElementsByTagName('p')` is a special object. Can you see if you can just return a regular good 'ol array. Like `['aaa', 1, true]`

**Comment by MakroBox** [comment]
**Yeah, you're right.** 😄 

This code works perfectly:
```node
const myArray = await page.evaluate(function() {
  return ['string', 100, true, false, 'Hello, Phantom!'];
});
console.dir(myArray);
```
