### ISSUE TITLE
How to get body of the response in onResourceReceived

### ISSUE THREAD

**Issue by HTKT** [amir20/phantomjs-node#732]
### Expected behavior

I would like to get the body of the Post Method after submit form.
### Actual behavior

The body is empty in onResourceReceived for that POST request.
Any help on this issue? Thanks

### Environment

- OS: MacOS
- Node version (`node -v`): v8.9.4
- package version:

**Comment by amir20** [comment]
It would be great if you show some code.

**Comment by HTKT** [comment]
Hi Amir,

I've tried another solution to detect new page is loaded instead of get the "body" in response. 
But now i'm stuck at the submit form (ASP.NET), i called the submit form but can not received the expected result, The website is using "multipart/form-data" to POST data.

There is no button submit, it only have <input type = "image"...> to submit form.
Here is the HTML code:

`<form name="aspnetForm" method="post" action="ApplicationForm.aspx" onsubmit="javascript:return WebForm_OnSubmit();" id="aspnetForm" enctype="multipart/form-data">
...
      <input type="image" name="PlaceHolderMain$imgOk" id="PlaceHolderMain_imgOk" src="/images/ok-button-25px.png" onclick="hideMyParent();WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions("PlaceHolderMain$imgOk", "", true, "", "", false, false))" style="border-width:0px;border:none !important;" />
`

I tried these steps:
1. call `click()` of PlaceHolderMain$imgOk but it only send the form Request not multipart/form-data.
2. call submit form `$("#aspnetForm").submit();` but the result is not correct because it's missing 2 parameter: `PlaceHolderMain$imgOk.x` and `PlaceHolderMain$imgOk.y`.

This is my code:

`await page.evaluate(function() {
        $("#aspnetForm").submit();
     });

console.log ('submit Form trigger')

                 setTimeout(
                     async function() {
                         const pageContent = await page.property('content');
                             console.log('load new html');
             
                             //render only Form rectangle
                             var formClipRect = await page.evaluate(function(element) {
                                 return document.getElementById(element).getBoundingClientRect();
                             }, 'Div1');
                             console.log('formClipRect = ' + formClipRect);
     
                             // generate PDF    
                            // page.property('clipRect', {left: formClipRect.left, top: formClipRect.top,  width: formClipRect.width, height: formClipRect.height}).then(async function() {                        
                             var pic = await page.render('/Users/admin/Desktop/Captcha/form.pdf');
                             console.log('pic Frm = ' + pic);
 
                             //await instance.exit()
                         // });
                     },
                20000);
`


Please help me. I tried many solution but still not work. Maybe i have a mistake somewhere.
Thanks for your help.

**Comment by amir20** [comment]
It's going to be really hard for me to help you since I don't have any context. I am not sure how to help unless you ask a more specific question. Something I can reproduce.

**Comment by HTKT** [comment]
Sorry for bad explaination.
My context is auto populate the data into the form then submit.
I can populate data to element successfully, but when i call submit, it's not work.

On the website, after fill in the data, the site show the popup and  i must to click on the OK button then the site redirect to another page. As the flow, when clicking on the OK button, it will trigger the submit form action, but i found the page source and can not see any form submit on that, so i have to call form.submit() manual to submit but not success. I think it it related to the embedded script on the site which i did not inject them to phantom. That is why i open another issue to ask about the injectJs.

**Comment by amir20** [comment]
I think you are asking for some help that is out of my scope. I recommend looking at stackoverflow for help.
