### ISSUE TITLE
How to inject the scripts from page

### ISSUE THREAD

**Issue by HTKT** [amir20/phantomjs-node#733]
The HTML page has the script as below:

```
<script src="/_res/js/jquery.js" type="text/javascript"></script>
<script src="/WebResource.axd?d=5At4BVuSsWGYDY9lb87tCvy" type="text/javascript"></script>

```

On `onResourceRecevied` function, i can see above script downloaded successful.
Then i inject them to `page` :

```
page.injectJs('/_res/js/jquery.js').then(async function(res) {
          console.log("injectJs")
        page.injectJs('/WebResource.axd?d=5At4BVuSsWGYDY9lb87tCvy').then(async function(res) {
            console.log("injectJs")
        })
})
```

The console logged "injectJs" but i can not call the any function on that script files.
I inject wrong path file or i have to use `includeJs` instead?

Thanks

**Comment by amir20** [comment]
`injectJs` runs inside phantomjs process. So you should probably do

```
page.injectJs('/_res/js/jquery.js').then(async function(res) {
          console.log("injectJs")       
})

 page.injectJs('/WebResource.axd?d=5At4BVuSsWGYDY9lb87tCvy').then(async function(res) {
            console.log("injectJs")
        })
```

Also your use of `async` seems to be incorrect.  `page.injectJs` returns a promise. You'll have to figure out the correct syntax.

**Comment by HTKT** [comment]
Because i want to inject all scripts before working on the page e.g: fill data or submit.

The issue i got is the path for these scripts seem to not correct, i'm not sure i should use relative or absoluate url for these scripts. Can you help to explain more? Thanks

**Comment by amir20** [comment]
This is well documented so I am going to close.
