### ISSUE TITLE
Simple use case with jQuery and parsing DOM

### ISSUE THREAD

**Issue by atais** [amir20/phantomjs-node#735]
### Expected behavior

I would like to create a simple website parser, but the given examples are way too complex for me to understand.

### Actual behavior

I can not parse the DOM.

### Steps to reproduce the behavior

With the "normal" phantom I was able to achieve the behaviour with a script like:

```
var page = require('webpage').create();

page.open(url, function (status) {
    console.log('opened ' + status);
    page.includeJs("https://code.jquery.com/jquery-1.10.2.min.js", function () {
        console.log('included');
        setTimeout(function () {
            var result = page.evaluate(function () {
                var a = $('#myDiv').text();
                return a;
            });
            console.log(result);
            phantom.exit()
        }, 5000);
    });
});
```

I tried copying your "simple" example, but I am failing to get it working:

```
phantom
    .create()
    .then(ph => {
        _ph = ph;
        return _ph.createPage();
    })
    .then(page => {
        _page = page;
        return _page.open(url)
    })
    .then(() => {
        return _page.includeJs('https://code.jquery.com/jquery-3.1.1.min.js');
    })
    .then(status => {
        console.log(status);
        var a = $('#myDiv').text(); ///????
        return a; /// ????
        // return _page.property('content');
        return a; // does not work!
    })
    .then(content => {
        console.log(content);
        _page.close();
        _ph.exit();
    })
    .catch(e => console.log(e));
```

I struggle here for a couple of hours and I would really appreciate some assistance.
Thanks!

**Comment by amir20** [comment]
Closing due to no response.

**Comment by atais** [comment]
Sorry for lack of response.
Thanks for advice, but what is worse, I did a quick debug, and noticed that
```return _page.includeJs('https://code.jquery.com/jquery-3.1.1.min.js');```
causes my script to hang.

How could I solve this?

**Comment by amir20** [comment]
That's great. Looks like problem solved itself. I always recommend async/await. NodeJs callback hell is too complicated.
