### ISSUE TITLE
the error make my program crashed.

### ISSUE THREAD

**Issue by zhy1** [amir20/phantomjs-node#736]
```
error: Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

```

crash and i cannot catch error in catch or process.on('exit', ()=>

why???

**Comment by amir20** [comment]
This is not related to this project. It's probably a phantomjs error.

**Comment by zhy1** [comment]
but why the catch code disabled?
```
try{
}catch(e
```
or 
```
process.on('exit'  , 
```
the problems can cause programs to crash.

**Comment by zhy1** [comment]
const page = await instance.createPage().catch(e => e);

**Comment by zhy1** [comment]
is babel-flow compile leads to error?

**Comment by amir20** [comment]
`await instance.createPage().catch(e => e);` isn't right. You need to use `try-catch`. Sorry I can't help more. I am very busy with other stuff.
