### ISSUE TITLE
The same function why [phantomjs] is faster, how should I write? Is it related to [promise]?

### ISSUE THREAD

**Issue by wll8** [amir20/phantomjs-node#738]
### Expected behavior

There are two code examples below. When you run `test 1`, the result immediately appears with the callback.

![image](https://user-images.githubusercontent.com/28223260/40874314-4c66c4f6-66a0-11e8-9fe1-fb7aff9d198c.png)

![image](https://user-images.githubusercontent.com/28223260/40874312-405aa3d0-66a0-11e8-9728-5d7ce03279bf.png)

### Actual behavior
`test 2`
`test 2` is not. It seems to be waiting for something to be completed. But this makes the result very slow.
How can I write faster? Like `phantomjs`.

![image](https://user-images.githubusercontent.com/28223260/40874306-3522c68c-66a0-11e8-8e78-fad1a3cd2bac.png)

### Steps to reproduce the behavior

``` js
    function waitFor(testFx, onReady, timeOutMillis) {
        var maxtimeOutMillis = timeOutMillis ? timeOutMillis : 3000,
            start = new Date().getTime(),
            condition = false,
            interval = setInterval(function() {
                if ( (new Date().getTime() - start < maxtimeOutMillis) && !condition ) {
                    condition = (typeof(testFx) === "string" ? eval(testFx) : testFx())
                } else {
                    if(!condition) {
                        console.log("'()' timeout")
                        phantom.exit(1)
                    } else {
                        console.log("'()' finished in " + (new Date().getTime() - start) + "ms.")
                        typeof(onReady) === "string" ? eval(onReady) : onReady()
                        clearInterval(interval)
                    }
                }
            }, 250)
    }
```

**[First Step] test 1**
``` js
    // test 1
    // node_modules/phantomjs/bin/phantomjs [file]

    var page = require('webpage').create()
    var url = 'http://www.google.com'
    page.open(url, function (status) {
        waitFor(function() {
            return page.evaluate(function() {
                return document.querySelector('title')
            })
        }, function() {
            var p = page.evaluate(function(tag){
              return document.querySelector(tag).innerText
            }, 'title')
            console.log('p', p)
            phantom.exit()
        }, 10 * 1000)
    })

```

**[Second Step] test 2**

``` js
    // test 2
    // node [file]

    const phantom = require('phantom')
    ;(async function () {
      const instance = await phantom.create()
      const page = await instance.createPage()

      const status = await page.open('http://www.google.com')

      waitFor(function() {
          return page.evaluate(function() {
              return document.querySelector('title')
          })
      }, function() {
          var p = page.evaluate(function(tag){
            return document.querySelector(tag).innerText
          }, 'title')

          p.then(res => {
            console.log('p', res)
            instance.exit()
          })
      }, 10 * 1000)
    })()

```

### Environment

- OS: `Mac OS X 10.13.1`
- Node version (`node -v`): `v8.9.4`
- package version: `4.0.12`

**Comment by amir20** [comment]
This module does a considerable amount of extra work to communicate to the `phantomjs` process. So having some sort of extra overhead is expected. I don't think 2x is right though. I noticed you had `250ms` in your `waitFor` in the `setInterval` function. Can you decrease that to 10ms? From your tests above, it's going to be multiples of 250ms. 

Finally, your test1 says `2302ms`. Am I missing something?

**Comment by wll8** [comment]
@amir20 
Maybe you didn't test the code. Well, I modified it to 10ms and uploaded two test results. They are gif images.

The left is `phantom` and the right is `phantomjs`. Looking at the gif map will take a long time, but you will see the running process.

### gif 1
![image](https://user-images.githubusercontent.com/28223260/40882279-0cf7ad20-670f-11e8-8f86-31d5110eba3b.png)

### gif 2
![image](https://user-images.githubusercontent.com/28223260/40882281-28491398-670f-11e8-8245-d7355a202107.png)

![image](https://user-images.githubusercontent.com/28223260/40882289-7526f716-670f-11e8-8dac-18451466dc39.png)
`phantom` It seems to only use `23ms`, but it will appear `google` after a long time.

**Comment by amir20** [comment]
@wll8 the text is so small, I can't read it. Can you try https://asciinema.org/? It's super easy. I have too many projects inflight to run the code.

**Comment by amir20** [comment]
I believe I solved your problem. You are returning a whole dom object to Node. That's going to be very slow. 

For example

```js
return page.evaluate(function() {
        return document.querySelector("title"); // This will return a whole new object which will need to get serialized
      })
```

You can debug this your self doing `DEBUG=true node test.js`. 

I changed it to 

```js
return page.evaluate(function() {
        return document.querySelector("title") !== null;
      })
```

And now it is A LOT faster.
