### ISSUE TITLE
Can't resolve 'child_process' in node_modules/phantom/lib/phantom.js   

### ISSUE THREAD

**Issue by lebronding** [amir20/phantomjs-node#739]
### Expected behavior

[Describe expected behavior here]

### Actual behavior

[Describe observed behavior here]

### Steps to reproduce the behavior

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Environment

- OS: mac
- Node version (`node -v`): 8.6.0
- package version: 4.0.12

**Comment by amir20** [comment]
?
