### ISSUE TITLE
Using a backtick ` inside of a rendered html file's javascript seems to break all javascript

### ISSUE THREAD

**Issue by TheJimFactor** [amir20/phantomjs-node#747]
### Expected behavior
Use it like I do in node.js or client side javascript as a quotation with interpolation.

### Actual behavior
No javascript works in rendered pdf.

### Steps to reproduce the behavior

1. Open a local file with `page.open(filename)`

2. Have the following javascript code in the `.html`  you are trying to render as PDF. The `url` attribute has the \`
```
      const options = {
        type:'POST',
        url:`https://example.com`,
        data:{userID:'stuffhere'}
      }
```
3. Run it and render to PDF

### Environment

- OS: Ubuntu 16.04 LTS
- Node version (`node -v`): v8.11.1
- package version: 6.0.0

When I replace \` with `'` javascript worked again. (I was setting the `.textContent` via javascript)

**Comment by amir20** [comment]
This is not related to this module. Phantomjs hasn't been updated for a while and it doesn't support ` yet.
