### ISSUE TITLE
How to inject core.js to Page during page initialization? 

### ISSUE THREAD

**Issue by Gunner17** [amir20/phantomjs-node#749]
I am trying to inject core.js to phantom page, since phantom does not support es6. This is how I am doing it :

```
page.property('onInitialized', function() {
	if(page.injectJs('core.js')){
	    console.log("Polyfill loaded");
				return page;
	} else {
		console.log("Polyfill Failed");
	}
});
```

But it always causes an exception. Could you please tell me the right way to do it?

**Comment by amir20** [comment]
Your code has a lot of problems. `property` no longer accepts functions. `page` return a promise.  Your knowledge of `Promise`s needs to be understood before using this package. Try looking at examples at https://github.com/amir20/phantomjs-node/blob/master/src/__tests__/page.test.js#L116-L122. Hopefully, that will help you.
