### ISSUE TITLE
Object.defineProperty not work

### ISSUE THREAD

**Issue by tdzard94** [amir20/phantomjs-node#750]
i tried to evaluate javascript like this:
await page.evaluateJavaScript("function(){ Object.defineProperty(navigator, 'userAgent', { get: function () { return 'iPhone'; },configurable: true});}");
but it not work and i got an error:
ERROR: TypeError: Attempting to configurable attribute of unconfigurable property.
index.js:38
TRACE:
 -> undefined: 1 (in function "defineProperty")
 -> : 1 (in function "anonymous")

How to fix it??

**Comment by amir20** [comment]
This a probably an issue with phantomjs and not this module. Try it with phantomjs first to make sure that this is possible.

**Comment by tdzard94** [comment]
Thanks for reply!
