### ISSUE TITLE
How to reconstruct the phantom itself that was removed?

### ISSUE THREAD

**Issue by trucntht93** [amir20/phantomjs-node#751]
I using the Phantom NodeJS to open the page. The process of my server as below:
        Step 1: Client send request to /a endpoint to open the page. At this time, i created 1 instance phantomInstance and page variable. After finished, Server return the result (here is the captcha image) to Client.
        Step 2: Client need to reply the data (captcha text) to /b endpoint to verify the captcha with the page which open in the last request /a, if success then close and exit phantom.
The issue is:
       After completing step 1, I wanted to close this phantom to reduce the amount of memory used for the phantom, avoiding the 'phantom-pool' phenomenon.
       Then, when the client performs step 2, I want to reconstruct the phantom itself that was removed to authenticate the capcha.
May i know there're any solution for this problem?
Thanks for helping.

**Comment by amir20** [comment]
Hi @trucntht93, this is a pretty advanced topic! :) When working sessions, you need to be able to recreate the session in the second session. This depends on how the website works. If the website is based off using cookies then you can copy the cookies between phantom instances and that should work. 

That all sounds complicated, I would recommend just using the same instance and not worrying about memory. If your use case is to have a lot of these instances then having multiple computers might be your best option. 

So really, you have two options: 

1. Figure out what is the easiest way to share session. In some cases that's just a cookie. 
2. Don't do premature optimization and stick to have a single instance for two pages.
