### ISSUE TITLE
Use phantom on a badly signed https website --> error

### ISSUE THREAD

**Issue by blured75** [amir20/phantomjs-node#754]
### Expected behavior

[Describe expected behavior here]
Should open the page even if there is a ssl or https error

### Actual behavior

[Describe observed behavior here]
if there is a https it only give an empty page with a status failed

Normaly with phantomjs you can pass --ignore-ssl-errors parameters. Is there a way to do that with pahntomjs-node ? Or could it be done ?

### Steps to reproduce the behavior

const instance = await phantom.create();
    const page = await instance.createPage();
    page.on("onResourceRequested", function(requestData) {});

    const status = await page.open(
        "https://www....."
    );

    console.log("status of page", status)
    
    let  content = await page.property('content');
    
    
    console.log("content of generated page : ", content)

### Environment

- OS: FreeBSD
- Node version (`node -v`): 6.14.3
- package version: 6.0.3

**Comment by amir20** [comment]
Have you tried passing that to `create()`? http://amirraminfar.com/phantomjs-node/#/phantom_obj?id=create

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.

**Comment by blured75** [comment]
thanks it works perfectly !!!
