### ISSUE TITLE
onResourceRequested : Support of networkRequest argument needed

### ISSUE THREAD

**Issue by nicolaspro14** [amir20/phantomjs-node#755]
Hello ! I'm getting some trouble trying to block some url requests through your page.on('onResourceRequested') method.

### Expected behavior

Suppose you want to block request at facebook.net sdk.js to speed up your phantom bot

```
// Listen for all requests that are to be loaded by page
        page.on('onResourceRequested', function(requestData, networkRequest) {
            // Detect if request goes to facebook
            if (requestData.url.indexOf('facebook.net') !== -1) {
                // Block the request
                networkRequest.abort()
            }
        })
```

This works if using directly phantomJs [onResourceRequested API](http://phantomjs.org/api/webpage/handler/on-resource-requested.html)

### Actual behavior

networkRequest.abort() is not working :
TypeError: request.abort is not a function
    at Proxy.anonymous 
    at EventEmitter.emitter.on.eArgs 
    at EventEmitter.emit (events.js:182:13)
    at Stream.Phantom.process.stdout.pipe.on.data 

Looks like you don't support a second argument for page.on('whatever') callback.

Is there a way to fix it please ?
Thanks in advance !

**Comment by nicolaspro14** [comment]
I have forgotten to mention how I initialize the page object first : 

 ```
const phantom = require('phantom');

async function crawlPage(url, params) {

    const instance = await phantom.create();
    var page = await instance.createPage();
    await page.property('viewportSize', { width: 1024, height: 1000 });

    // Listen for all requests that are to be loaded by page
    page.on('onResourceRequested', function(requestData, networkRequest) {
        // Detect if request goes to facebook
        if (requestData.url.indexOf('facebook.net') !== -1) {
            // Block the request
            networkRequest.abort();
        }
    })

    const status = await page.open(url);

    // Stuff when page opened here

}
```

**Comment by amir20** [comment]
Hello! Have you read the `page#on` documentation? http://amirraminfar.com/phantomjs-node/#/page_obj?id=on By default, events are executed in node process. If you want to be able to abort or call methods in phantom then you need to pass `true` to second parameter. 

```
page.on('onResourceRequested', true, function (requestData, networkRequest) {
    networkRequest.abort(); // This would work, because you are accessing to the non serialized networkRequest.
});
```

**Comment by nicolaspro14** [comment]
Thanks for the reply.

You're right, I misunderstood the runOnPhantom argument.
Before I did that, nothing was working with the "true" arg because I was trying to access a variable outside this function.

Now everything is ok ! Thanks again.
