### ISSUE TITLE
viewportSize  without effect

### ISSUE THREAD

**Issue by 312xiaoguai** [amir20/phantomjs-node#758]
yield page.property('viewportSize', { width: 100, height: 100 }); 
 yield page.property('viewportSize', { width: 1024, height: 768 });

The exported pdf looks the same，How do I set it up to change the width and height of the pdf?

**Comment by amir20** [comment]
This should work. I am not sure what is causing it to not. Might be worth showing the whole code as I have no idea what else you are doing.
