### ISSUE TITLE
Page breaking while generating PDF report

### ISSUE THREAD

**Issue by ramizkasid** [amir20/phantomjs-node#761]
![pdf break](https://user-images.githubusercontent.com/31642039/46190916-1772e200-c313-11e8-8b3d-4feffb19e670.png)
Here is the image of pdf in which page is breaking along with data.
### Environment

- OS: Ubuntu
- Node version (`node -v`): v8.10.0
- package version:  2.0.0

**Comment by amir20** [comment]
Are you really using version `2.0.0`? That's really old.

**Comment by amir20** [comment]
This is probably a bug with phantomjs and not this module.

**Comment by ramizkasid** [comment]
Is there any page break property available for phantomjs or any other solution

**Comment by ramizkasid** [comment]
Is there any update on this issue? We need to rectify this issue as soon as possible.

**Comment by amir20** [comment]
@ramizkasid You have to do the research yourself with phantomjs. This module is just a wrapper around phantomjs to make it easier to use it. It doesn't add any new functionality.
