### ISSUE TITLE
could not spawn ['myProjectDir/node_modules.phantomjs-prebuilt/lib/phantom.bin/phantomjs.exe'], please make sure phantomjs is installed correctly

### ISSUE THREAD

**Issue by linYeeTracy** [amir20/phantomjs-node#766]
when i require 'phantom' module on windows, it works well
but when i deploy my project on linux, throw an error `could not spawn ['myProjectDir/node_modules.phantomjs-prebuilt/lib/phantom.bin/phantomjs.exe'], please make sure phantomjs is installed correctly`

how can i deal with that ?
please

### Environment

- linux && node v8.11.3

**Comment by amir20** [comment]
I couldn't reproduce this. Are you sure you have all dependencies installed? Check out https://github.com/amir20/phantomjs-node/blob/master/examples/Dockerfile for an example using Dockerfile and Linux.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.

**Comment by roysG** [comment]
I get also this bug
