### ISSUE TITLE
 EvalError: Refused to evaluate,  'unsafe-eval' is not allowed,  "default-src 'self' 'unsafe-inline'

### ISSUE THREAD

**Issue by Crackiii** [amir20/phantomjs-node#786]
My Instances : 

`        ph_instance          =      await phantom.create();
        ph_page              =      await ph_instance.createPage();`

My Code : 
`jobs = await ph_page.evaluate(function(){ 
                                var fn = new Function(' document.getElementById("loadbutton").textContent.match(/\d+/g)[2]');
                                return fn();
                            },);`

I am evaluating the above code in [this](https://www.ferchau.com/de/de/karriere/jobs-bewerbung/jobangebote/search/) site. And it returns this error.   EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'

**Comment by amir20** [comment]
@Crackiii are you familiar with Content-Security-Policy? That website restrict eval function. You can see in the header 

```
Content-Security-Policy: default-src 'self' 'unsafe-inline' https: data: *.able-group.de *.ferchau.com *.mapbox.com *.pubmatic.com *.criteo.net *.criteo.com *.doubleclick.net www.google-analytics.com www.googletagmanager.com *.youtube.com *.facebook.com *.fbcdn.net *.googleusercontent.com *.twitter.com *.twimg.com wss://www.ferchau.com wss://ferchau-test.able-plattform.de;
```

Not related to phantom.

**Comment by Crackiii** [comment]
So we can't open scrap that site now ? Or any alternative way ?

**Comment by amir20** [comment]
I am not sure what you are trying to do. But I won't be able to help you as it is beyond the scope of this project. I'd try stackoverflow.

**Comment by Crackiii** [comment]
Its related to the SSL issue, where you turn off the webSecurity on pure phantom JS

**Comment by amir20** [comment]
If it's just SSL then try disabling SSL http://amirraminfar.com/phantomjs-node/#/phantom_obj?id=create
