### ISSUE TITLE
is there any way to get the cookie string

### ISSUE THREAD

**Issue by joneldiablo** [amir20/phantomjs-node#789]
I have this code:

```
(async function () {
      const instance = await phantom.create();
      const page = await instance.createPage();
      const status = await page.open(`${codaDomain}/login`, 'POST', body);
      const content = await page.property('cookies');
      const cookies = await page.cookies();
      const cookieString = await page.evaluate(function() {
        return document.cookie;
      });

      console.log(cookies, cookieString);
      console.log(status, content);
      console.log(page.settings);
      con
      await instance.exit();
    })();
```
but the cookieString is empty

how can I get the cookie as string?

**Comment by amir20** [comment]
Have you tried the cookie() method? https://github.com/amir20/phantomjs-node/blob/f9249bb447619d9dba78c4e84329e29f6a42f181/src/__tests__/page.test.js#L160

**Comment by joneldiablo** [comment]
yes man, is in my example 
![image](https://user-images.githubusercontent.com/13206502/49884418-71575400-fdfa-11e8-9b2f-1eb43a8fa233.png)

But `await page.cookies();` its returning an object which describe the cookie
```
{
  page:'',
  httponly: true,
  name: '....',
  value: '........',
  //....... etc
}
```
My question is if I can get the cookie string without do the convertion manually:
```
cookies.map(cookie=>`${cookie.name}=${cookie.value}`).join('; ')
```

**Comment by amir20** [comment]
No, I don't think you can do that. `page.evaluate` wouldn't work either since the cookies are stored outside the of javascript. You would have to http://phantomjs.org/api/phantom/property/cookies.html as your best option and do what you did.
