### ISSUE TITLE
Command Prompt is Showing when start processing

### ISSUE THREAD

**Issue by neevannv** [amir20/phantomjs-node#810]
Command prompt is popping up every time when application started, is there any way to fix.
I have used PM2 npm package to serve my application as service

**Comment by neevannv** [comment]
I have attached screenshot can you please take look at it.
![git-cmd](https://user-images.githubusercontent.com/43032763/52067167-07f4f580-25a0-11e9-8d97-98f4c42abb54.png)

**Comment by amir20** [comment]
@neevannv I am not sure what that is because I don't use Windows. I think the problem might be something not related to phantom. Phantom is just a simple wrapper around phantomjs. I won't be able to help you because I can't reproduce it.

**Comment by neevannv** [comment]
@amir20 Actually i built application in Node.js and with phantomjs-node which accepts URL as parameter and when phantom JS starts loading page this command prompt is appearing.
