### ISSUE TITLE
page.setProxy() is not a function

### ISSUE THREAD

**Issue by lukakostic** [amir20/phantomjs-node#827]
### Expected behavior

From page.test.js:

    const page = await phantom.createPage();
    await page.setProxy(`http://localhost:${port}/`);
    await page.open('http://phantomjs.org/');

### Actual behavior

    this._ph = await phantom.create();
	let page = this._ph.createPage();
    await page.setProxy(`http://${this.proxy}/`); //TypeError: page.setProxy is not a function
    await page.open(url);

### Environment

- OS: Windows 10
- Node version (`node -v`): v11.9.0
- package version: "phantom": "^2.1.21", "phantomjs-prebuilt": "^2.1.16"

**Comment by amir20** [comment]
I can't reproduce it. Can you give me some code to run on my side?

**Comment by amir20** [comment]
Oh don't you need `await`?  Like `let page = await this._ph.createPage()`

**Comment by lukakostic** [comment]
await works gets an error on the line below:

> await page.open(url);
> page.onLoadFinished = async function(status) { //error


With this error:
> TypeError: 'set' on proxy: trap returned falsish for property 'onLoadFinished'

**Comment by amir20** [comment]
That’s because onLoadFinished doesn’t support async. Look at the docs to see how to do it. 

Sent via my iPhone
