### ISSUE TITLE
runOnPhantom request.abort() Expected an identifier but found 'url' instead

### ISSUE THREAD

**Issue by khanhankkhan** [amir20/phantomjs-node#855]
### Expected behavior

request.abort() prevents phantom from downloading some urls within the webpage
### Actual behavior

Error output is

```
info: SyntaxError: Expected an identifier but found 'url' instead
info:   undefined:4 in Function
info:   phantomjs://code/index.js:315
info:   :0 in parse
info:   phantomjs://code/index.js:307 in read
```

### Steps to reproduce the behavior

node startme.js in the command line, where 'startme.js' is below

```
const phantom = require('phantom');

async function get_page_content(url, done)
{
  const instance = await phantom.create();
  let page = await instance.createPage();

  page.on('onResourceTimeout', function(e)
  {
    console.log('page timeout ',e);
    page.exit(1);
    done('');
  });


  await page.on('onResourceRequested', true, function(requestData, request)
  {
console.log('reqd ', requestData);
console.log('req ', request);
    let url = requestData['url'];
    //abort style sheets
    if (url.indexOf("css") != -1)
    {
      console.log('Skipping', url);
      request.abort(); //crash without 'true'
    }
    else
    {
      console.info('Requesting', requestData.url);
    }
  });

console.log('openurl ', url);
  const status = await page.open(url);
  const content = await page.property('content');
  await instance.exit();

  done(content);
};


get_page_content('https://google.com', function(r)
{
  console.log("i'm done");
});
```

### Environment

- OS: Mac OSX and Ubuntu 18.04 LTS
- Node version (`node -v`): v10.15.3
- package version: 6.2.0

**Comment by amir20** [comment]
This is to be expected. `request.abort(); //crash without 'true'` needs `true` to run in phantom. Without true, the callback is executed in Node which won't have access to `abort()`. 

This is documented already on http://amirraminfar.com/phantomjs-node/#/page_obj?id=on

**Comment by khanhankkhan** [comment]
i thought i did have 'true' though? (true is the input as the second parameter as in the example)

```await page.on('onResourceRequested', true, function(requestData, request)```

**Comment by khanhankkhan** [comment]
that line is not responsible for the crash because there is no crash it was just a note to myself.

what happens is phantom hangs, and then prints out to the screen 

```
MacBook-Air-5:node iansharp$ node idk.js 
openurl  https://google.com
info: SyntaxError: Expected an identifier but found 'url' instead
info:   undefined:2 in Function
info:   phantomjs://code/index.js:315
info:   :0 in parse
info:   phantomjs://code/index.js:307 in read
```

**Comment by amir20** [comment]
Oh sorry. Let's try again. 

Have you tried `requestData.url` instead of `['url']`? Remember that this is running in phantomjs process. So a lot of the es6 styles won't work. I would remove `let` and anything else that might not be es6. 

Do you what line is throwing the error? I can't tell from the exception. I am guessing it's

**Comment by amir20** [comment]
I'll try to run this in a little time. And see if I can see what's wrong.

**Comment by khanhankkhan** [comment]
thank you amir! yes, that fixed it for me, i used *.url*  and just to be safe I used 'var u = ...', in case it might name-conflict with the other 'url' declared in the same function, so for me it works great doing the following 

```
const phantom = require('phantom');

async function get_page_content(url)
{
  const instance = await phantom.create();
  let page = await instance.createPage();

  page.on('onResourceTimeout', function(e)
  {
    console.log('page timeout ',e);
    page.exit(1);
    done('');
  });


  page.on('onResourceRequested', true, function(requestData, request)
  {
    var u = requestData.url;
    //abort style sheets
    if (u.indexOf("css") != -1)
    {
      console.log('Skipping', u);
      request.abort();
    }
    else
    {
      console.info('Requesting', u);
    }
  });

console.log('openurl ', url);
  const status = await page.open("https://google.com");
  const content = await page.property('content');
  await instance.exit();

  return content;
};

(async () => {
let content = await get_page_content('https://google.com');

console.log("i'm done", content);
})();
```

**Comment by amir20** [comment]
OK just as suspected. Changed `let` to `var` and it worked for me.

**Comment by amir20** [comment]
Nice! We both found the same thing at same time. I wish phantom would update but it seems like the project is maintenance mode.  For me it's still awesome to test my shims on websites.

**Comment by khanhankkhan** [comment]
yeah, it's really great. thanks for your helping me.
