### ISSUE TITLE
Possible to remove the phantomjs-prebuilt dependency?

### ISSUE THREAD

**Issue by Kveitemjol** [amir20/phantomjs-node#863]
Hello.

Is it possible to remove the dependency of phantomjs-prebuilt? As it is now its causing some issues with buildservers and packaging.

In a nutshell the issue is that when you do a NPM install on the buildserver it will run the install script from phantomjs-prebuilt there and add the location.js file to node_modules. If you decide to package your project and include the node_modules as a part of your deployment process (to avoid getting other versions etc. on the server you are deploying to) you end up bringing location.js with you.

In our case we are deploying to linux, but building the package on windows and naturally this causes some issues since the phantomjs.path is pointing to a windows executable in the node_modules folder, while it should be using the phantomjs that is pre-installed on the server.

As of now we can override the path with the config, but it will still cause a lot of unnessesary downloads on the build server and increase the package size. Wouldnt it be better to install phantomjs-prebuilt seperatly and use phantom.create ([], { phantomPath: phantomjs.path }) ?

**Comment by amir20** [comment]
Hi @Kveitemjol,

It is possible to remove this dependency but I would have to do it for all who use this library. Unfortunately, that is not ideal for the average user. A while back (3 years ago), phantomjs was not included. I received a lot of bugs with version incompatibility. Many were using older versions that phantomjs-node didn't support. And I didn't want to be in the backward compatibility business. Some were also asking me where or how to install phantomjs. 

For that reason, I included phantomjs binaries. This is a common practice and the reocmmended way if you are familiar with [12-factor architecture](https://12factor.net/dependencies). 

> Twelve-factor apps also do not rely on the implicit existence of any system tools. Examples include shelling out to ImageMagick or curl. While these tools may exist on many or even most systems, there is no guarantee that they will exist on all systems where the app may run in the future, or whether the version found on a future system will be compatible with the app. If the app needs to shell out to a system tool, that tool should be vendored into the app.

Your use case is unique. Building on one OS but running on another will probably yield unexpected results. For example, in Rails a lot of the Gems are built for the OS that is targeted. 

For most of our projects, we use Docker and the problems of shipping code with OS dependencies has just gone away. I know this isn't probably the solution you were hoping for as it is a complete different set of tools. But I am optimizing for 90% use case which isn't building on Windows and deploying on Linux. 

I hope this explanation helps. 

Ps. I have tried looking at `optional` dependencies with NPM but it just doesn't seem to work. If you know of a way to make `phantomjs-prebuilt` skipped then I can add that to `package.json`.
