### ISSUE TITLE
No response from request to  some websites

### ISSUE THREAD

**Issue by r3dwc** [amir20/phantomjs-node#888]
This code does work well on most websites but doesn't work on some websites.
For example, https://www.kroger.com/
I used this in express app.

```js
(async function() {
  const instance = await phantom.create();
  const page = await instance.createPage();
  await page.on('onResourceRequested', function(requestData) {
    console.info('Requesting', requestData.url);
  });

  const status = await page.open('https://www.kroger.com/');
  const content = await page.property('content');
  console.log(content);

  await instance.exit();
})();
```

Console:
Requesting https://www.kroger.com/
GET / - - ms - -
Requesting https://www.kroger.com/
GET / - - ms - -

package.json
{
  "scripts": {
    "start": "nodemon ./bin/www"
  },
  "dependencies": {
    "cookie-parser": "~1.4.4",
    "cors": "^2.8.5",
    "debug": "~2.6.9",
    "express": "~4.16.1",
    "http-errors": "~1.6.3",
    "morgan": "~1.9.1",
    "nodemon": "^1.19.1",
    "phantom": "^6.2.0",
    "pug": "2.0.0-beta11"
  }
}

**Comment by amir20** [comment]
Looks like `kroger.com` blocks certain user agents. It doesn't work with `curl` or `phantom`. 

<img width="1322" alt="Screen Shot 2019-06-30 at 12 13 59 PM" src="https://user-images.githubusercontent.com/260667/60401029-a75aec00-9b30-11e9-8bcb-f719bd21dc8f.png">


With `npx phantom@latest https://www.kroger.com/` it throws the same error which explains why it never finishes...

<img width="1322" alt="Screen Shot 2019-06-30 at 12 15 16 PM" src="https://user-images.githubusercontent.com/260667/60401039-be99d980-9b30-11e9-9b14-9672b4db4758.png">

There isn't anything that can be done unless you change the user agent which you can do with `  page.setting('userAgent', 'foo app')`. I haven't tested if it works.

**Comment by r3dwc** [comment]
It works! Thank you very much.

**Comment by r3dwc** [comment]
I made an api to return the content with express and uploaded to firebase. But it doesn't work in firebase app. Still no response. Would you let me know the solution? Thanks.

**Comment by amir20** [comment]
That kind of question is not suited for issues. You should ask stackoverflow.com or other places. This is only for issues. Closing.
