### ISSUE TITLE
can phantomjs play mp3?

### ISSUE THREAD

**Issue by huge818** [amir20/phantomjs-node#891]
### Expected behavior

[Describe expected behavior here]

### Actual behavior

[Describe observed behavior here]

### Steps to reproduce the behavior

1. [First Step]
`
var page = require('webpage').create();
phantom.outputEncoding="utf8";
page.open("http://127.0.0.1:3000/player.html", function(status) {
	if (status === "success" ) {
		console.log(page.title); 
	} else {
		console.log("Page failed to load."); 
	}
});
`

2. [Second Step]   player.html
main content

`
<audio id="music-player" src="media/music.mp3" autoplay></audio>
`

3. [Other Steps...] 
phantomjs player.js

### Environment

- OS: window10

- Node version (`node -v`):
- package version: 
music.mp3 is exsist and it is ok ！

but,It can not play it

**Comment by amir20** [comment]
I have no idea.
