### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by LeeHyungGeun** [amir20/phantomjs-node#894]
### Expected behavior

Install can be done

### Actual behavior

Install error
![image](https://user-images.githubusercontent.com/2471651/61427158-bb378800-a94f-11e9-98b9-08844a195bf0.png)

### Steps to reproduce the behavior

1. `npm i --save phantom`

### Environment

- OS: macOS Mojave (10.14.4)
- Node version (`node -v`): 10.0.0
- package version: 6.2.0

**Comment by amir20** [comment]
I can't reproduce @LeeHyungGeun. 

<img width="1322" alt="Screen Shot 2019-07-18 at 8 46 08 AM" src="https://user-images.githubusercontent.com/260667/61472065-908e0500-a938-11e9-9a27-5015fdb95627.png">


Maybe try updating your node or make sure there are not VPN issues.

**Comment by LeeHyungGeun** [comment]
Let me try check my network. Thanks. @amir20
