### ISSUE TITLE
PhantomJS ScreenShot for my login page is Blank

### ISSUE THREAD

**Issue by tanujaSigmoid** [amir20/phantomjs-node#901]
### Expected behavior

It will capture whole page of screenshot.

### Actual behavior

I am trying blow code for creating screenshot using phantomJS 2.1.1 but getting blank screenshot. Can please tell me what i did wrong?

### Steps to reproduce the behavior

 var page = require('webpage').create();
    page.open('https://sigview.sigmoid.io/app/#/signIn',function(){
        setTimeout(function() {
        page.render('sigview.png');
        phantom.exit();
        }, 1000);
    });

When i added
 page.onConsoleMessage = function(msg, lineNum, sourceId) {
  console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};

CONSOLE: Google Analytics Initialized (from line # in "")
CONSOLE: jQuery.Deferred exception: undefined is not a function (evaluating 'Object.assign({},d,o)') t@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:8081643
o@https://sigview.sigmoid.io/app/scripts/scripts.e53141f8.js:1:8772726
invoke@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:464073
https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:458160
invoke@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:464073
https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:462631
getService@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:460540
injectionArgs@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:463648
instantiate@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:464197
https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:518515
createDetachedTour@https://sigview.sigmoid.io/app/scripts/scripts.e53141f8.js:1:11736460
https://sigview.sigmoid.io/app/scripts/scripts.e53141f8.js:1:3025948
invoke@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:464073
https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:462993
forEach@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:427302
createInjector@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:462942
doBootstrap@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:438797
bootstrap@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:439323
angularInit@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:438068
https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:722817
mightThrow@https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:237532
https://sigview.sigmoid.io/app/scripts/vendor.00e53c4a.js:1:238173 undefined (from line # in "")

I think undefined errors make PhantomJs choke. 
What can be the probable cause for such undefined error? As i am not sure why it is coming.

Can please help me out to fix this issue? It is very helpful.

Thanks in advance

**Comment by amir20** [comment]
I am not 100% sure but I am guessing you don't have all the polyfills required. Phantomjs browser is old and it doesn't have `Object.assign` so that might be causing this to break. Of course, I haven't tested it so you'll have to investigate. It's not a bug with phantom though.
