### ISSUE TITLE
Unable to set paperSize property with dimensions of the page

### ISSUE THREAD

**Issue by prithwirajbose** [amir20/phantomjs-node#919]
### Expected behavior

If the following works:
`page.property('paperSize', { format: 'A4', orientation: 'portrait' })`

Then I am expecting the following to work as well:
`page.property('paperSize', { width: '8.5in', height: '11in', margin: '1in' })`

### Actual behavior

But seems like Rendering PDF from a page, when paperSize is set using height and width properties, doesn't work. The PDF fails to render.

### Environment

- OS: Openshift (Redhat PaaS)
- Node version (`node -v`): 8.0
- package version: 6.2.0

**Comment by prithwirajbose** [comment]
Just wanted to add that it is really difficult to toggle around with the page dimension on the aforesaid environment. Although it worked well on Windows 2010 Server + NodeJS 8 environment. When no paperSize property is specified, the rendered PDF contains a extremely long (horizontally) pages. Page break takes place, but at a long weird height. Please can you check the code and help me get the page size corrected.

**Comment by amir20** [comment]
There is a test case at https://github.com/amir20/phantomjs-node/blob/f9249bb447619d9dba78c4e84329e29f6a42f181/src/__tests__/page.test.js#L79 that shows width and height should work. This is passed directly to phantomjs so I am not sure what the problem could be. Perhaps somethings has changed.
