### ISSUE TITLE
Unable to set proxy settings when working behind a Proxy Server for Internet Access

### ISSUE THREAD

**Issue by prithwirajbose** [amir20/phantomjs-node#922]
### Expected Behavior

Phantom JS seems to accept Proxy Settings now. So, it should be a common feature to include. I've tried adding environment variables in Unix (HTTPS_PROXY/HTTP_PROXY) before running the node program. However, the Phantom Library doesn't seem to obey the OS Proxy Settings. So there should be an option to supply the settings to the library while initializing.

### Actual behavior

One of my example webpage has a Google Chart in it. The chart rendered well when the code is executed from a system with open internet access. However, when the code runs from a Unix Box which is behind a Proxy server, the Google Chart JS file fails to load. Subsequently the chart fails to render and error thrown due to missing JS Variables. 

_If there is a feature already available in the library to specify Proxy, it should be clearly mentioned in the Documentation. In that case, please update the Documentation._

### Environment

- OS: Unix (Redhat)
- Node version (`node -v`): 8.11.4
- package version: 6.3.3

**Comment by amir20** [comment]
https://github.com/amir20/phantomjs-node/blob/f9249bb447619d9dba78c4e84329e29f6a42f181/src/__tests__/page.test.js#L366

You can send pull request to update docs.
